export function createInput({ canvas, joystick, knob, lookZone, actionButton }) {
  const state={moveX:0,moveY:0,lookX:0,lookY:0,action:false,sprint:false},pointers=new Map(),keys=new Set(); let joyId=null,lookId=null,joyOrigin={x:0,y:0},lookLast={x:0,y:0};
  const setKnob=(x,y)=>{const r=42,l=Math.hypot(x,y)||1,s=Math.min(1,r/l);knob.style.transform=`translate(${x*s}px, ${y*s}px)`;};
  const clearJoy=()=>{joyId=null;state.moveX=0;state.moveY=0;setKnob(0,0);joystick.classList.remove('active');}; const clearLook=()=>{lookId=null;state.lookX=0;state.lookY=0;lookZone.classList.remove('active');};
  const down=(e)=>{if(e.target===actionButton||actionButton.contains(e.target))return;canvas.setPointerCapture?.(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(e.clientX<innerWidth*.46&&joyId===null){joyId=e.pointerId;joyOrigin={x:e.clientX,y:e.clientY};joystick.classList.add('active');}else if(lookId===null){lookId=e.pointerId;lookLast={x:e.clientX,y:e.clientY};lookZone.classList.add('active');}};
  const move=(e)=>{if(!pointers.has(e.pointerId))return;if(e.pointerId===joyId){const dx=e.clientX-joyOrigin.x,dy=e.clientY-joyOrigin.y,r=58;state.moveX=Math.max(-1,Math.min(1,dx/r));state.moveY=Math.max(-1,Math.min(1,-dy/r));state.sprint=Math.hypot(state.moveX,state.moveY)>.86;setKnob(dx,dy);}else if(e.pointerId===lookId){state.lookX+=e.clientX-lookLast.x;state.lookY+=e.clientY-lookLast.y;lookLast={x:e.clientX,y:e.clientY};}pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});};
  const up=(e)=>{pointers.delete(e.pointerId);if(e.pointerId===joyId)clearJoy();if(e.pointerId===lookId)clearLook();};
  canvas.addEventListener('pointerdown',down,{passive:true});canvas.addEventListener('pointermove',move,{passive:true});canvas.addEventListener('pointerup',up,{passive:true});canvas.addEventListener('pointercancel',up,{passive:true});actionButton.addEventListener('pointerdown',(e)=>{e.preventDefault();state.action=true;});window.addEventListener('keydown',(e)=>{keys.add(e.code);if(e.code==='KeyE'||e.code==='Space')state.action=true;});window.addEventListener('keyup',(e)=>keys.delete(e.code));
  return {sample(){let x=state.moveX,y=state.moveY;if(keys.has('KeyA')||keys.has('ArrowLeft'))x-=1;if(keys.has('KeyD')||keys.has('ArrowRight'))x+=1;if(keys.has('KeyW')||keys.has('ArrowUp'))y+=1;if(keys.has('KeyS')||keys.has('ArrowDown'))y-=1;const l=Math.hypot(x,y);if(l>1){x/=l;y/=l;}const out={moveX:x,moveY:y,lookX:state.lookX,lookY:state.lookY,action:state.action,sprint:state.sprint||keys.has('ShiftLeft')||keys.has('ShiftRight')};state.lookX=0;state.lookY=0;state.action=false;return out;},destroy(){clearJoy();clearLook();pointers.clear();keys.clear();}};
}
