import { installMobileRuntime } from '../../shared/mobile-runtime.js';
installMobileRuntime();

const STORE='pocket-works:witness-of-era';
const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));
const pick=a=>a[Math.floor(Math.random()*a.length)];
const state={round:0,total:0,choice:{author:0,quote:0,year:1453,source:0},archive:[],history:[]};

const authors=[
 {name:'Владимир Ленин',years:[1870,1924],gravitas:94,portrait:'lenin',tags:['revolution','state']},
 {name:'Юлий Цезарь',years:[-100,-44],gravitas:96,portrait:'caesar',tags:['war','state']},
 {name:'Наполеон Бонапарт',years:[1769,1821],gravitas:92,portrait:'napoleon',tags:['war','state']},
 {name:'Сократ',years:[-470,-399],gravitas:90,portrait:'socrates',tags:['philosophy']},
 {name:'Клеопатра VII',years:[-69,-30],gravitas:90,portrait:'cleopatra',tags:['state']},
 {name:'Исаак Ньютон',years:[1643,1727],gravitas:91,portrait:'newton',tags:['science']},
 {name:'Княгиня Ольга',years:[890,969],gravitas:88,portrait:'olga',tags:['state','war']},
 {name:'Уинстон Черчилль',years:[1874,1965],gravitas:93,portrait:'churchill',tags:['war','state']}
];
const quotes=[
 {text:'Проблема цитат в интернете в том, что люди сразу верят в их подлинность.',modern:100,tags:['media','philosophy']},
 {text:'Историю пишут победители. Посты редактируют админы.',modern:96,tags:['war','media']},
 {text:'Никогда не спорь с человеком, у которого есть скриншот без контекста.',modern:100,tags:['media','philosophy']},
 {text:'Если план не сработал, назовите его первым этапом реформы.',modern:74,tags:['state']},
 {text:'Всякая империя вечна примерно до следующего вторника.',modern:62,tags:['state','philosophy']},
 {text:'Кто контролирует мемы, тот контролирует трактовку источника.',modern:99,tags:['state','media']},
 {text:'Не всё, что написано курсивом, является первоисточником.',modern:69,tags:['science','philosophy']},
 {text:'Главное преимущество дедлайна в том, что после него всё становится историей.',modern:88,tags:['state','philosophy']}
];
const sources=[
 {name:'Протокол заседания, стр. 4',born:1500,serious:96,tags:['official']},
 {name:'Архив Telegram, т. II',born:2013,serious:92,tags:['digital']},
 {name:'Берестяная грамота без номера',born:1000,serious:78,tags:['archive']},
 {name:'Запись со слов очевидца',born:-3000,serious:72,tags:['oral']},
 {name:'Подпись под чёрно-белой фотографией',born:1826,serious:84,tags:['photo']},
 {name:'Сборник «Цитаты великих людей», 2009',born:2009,serious:68,tags:['book']},
 {name:'Полевая телеграмма, фонд 17',born:1840,serious:94,tags:['official']},
 {name:'Надпись на обороте иконы',born:500,serious:86,tags:['archive']}
];
const briefs=[
 {title:'Сделай так, чтобы переслали в семейный чат',hint:'Нужен ясный анахронизм, но максимально серьёзная подача.',bias:'balanced'},
 {title:'Нужен анахронизм минимум на пять веков',hint:'Дата должна конфликтовать с биографией. Чем точнее — тем лучше.',bias:'chrono'},
 {title:'Подкрепи чушь документом',hint:'Технология источника должна появиться заметно позже самой цитаты.',bias:'source'},
 {title:'Финал: почти правдоподобно, но физически невозможно',hint:'Лучший пост — тот, над которым сначала не смеются.',bias:'master'}
];
const comments=['«Сразу после этого, кстати, и пал Константинополь.»','«Редко кто знает этот ранний период его творчества.»','«Источник утерян, но цитата слишком точная, чтобы быть выдумкой.»','«Я это ещё в школе слышал, значит правда.»','«Прадед рассказывал почти дословно.»','«Ну фотография же чёрно-белая. Какие ещё нужны доказательства?»'];
const $=s=>document.querySelector(s);
const screens=['intro','game','result','finale'];
function showScreen(name){screens.forEach(id=>$('#'+id+'-screen').classList.toggle('is-active',id===name));}
function save(){localStorage.setItem(STORE,JSON.stringify({best:Number(localStorage.getItem(STORE+':best')||0),archive:state.archive.slice(0,20)}));}
function load(){try{const data=JSON.parse(localStorage.getItem(STORE)||'{}');if(Array.isArray(data.archive))state.archive=data.archive;}catch{}const best=Number(localStorage.getItem(STORE+':best')||0);$('#best-line').textContent=best?`Лучший архив: ${best} / 400`:'Лучший архив: —';}
function haptic(pattern=12){if(navigator.vibrate)navigator.vibrate(pattern);}
function portrait(kind){const common='viewBox="0 0 180 220" aria-hidden="true"',bg='<rect width="180" height="220" fill="#20201d"/>',fills='fill="#e9e5da" stroke="#20201d" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"';const art={lenin:`<path ${fills} d="M39 207c4-49 24-77 55-90-20-14-31-36-27-61 4-31 29-50 58-48 35 2 56 29 52 60-2 21-13 38-30 49 30 13 50 42 54 90Z"/><path d="M89 61c14 8 32 8 48 0M96 89c14 8 30 8 44 0M105 113c11 7 22 7 33 0" ${fills} fill="none"/>`,caesar:`<path ${fills} d="M33 208c7-48 30-78 66-92-18-13-28-34-27-58 1-32 25-54 56-54 31 0 55 24 54 57-1 23-11 42-30 55 33 14 55 45 60 92Z"/><path d="M72 35c-15-8-25-19-29-31m40 23C72 15 68 8 67 1m31 23C90 12 89 5 90 0m24 24c-2-12 1-20 7-28" ${fills} fill="none"/>`,napoleon:`<path d="M22 54h136l-27 22H49Z" fill="#e9e5da"/><path ${fills} d="M44 209c7-47 28-76 61-91-18-13-27-34-25-57 3-31 26-51 55-51 30 0 53 22 53 53 0 23-10 42-28 55 31 15 52 45 57 91Z"/>`,socrates:`<path ${fills} d="M34 210c6-43 24-68 54-84-13-13-20-30-19-49 1-33 25-58 57-58 34 0 57 27 56 60-1 19-8 35-22 47 28 15 47 42 53 84Z"/><path d="M82 108c18 10 43 10 60 0-4 36-54 36-60 0Z" fill="#e9e5da"/><path d="M91 118c13 8 29 8 42 0" ${fills} fill="none"/>`,cleopatra:`<path ${fills} d="M40 209c7-46 27-74 59-89-16-13-25-31-25-52 0-33 23-57 55-57 32 0 54 24 54 57 0 21-9 39-25 52 31 15 51 44 58 89Z"/><path d="M73 45 34 62l39 9m111-30 27 20-27 10" ${fills} fill="none"/>`,newton:`<path ${fills} d="M28 210c7-45 27-72 57-87-15-13-23-31-22-52 1-35 27-60 61-60 34 0 59 26 58 61-1 20-9 38-24 51 30 16 49 43 55 87Z"/><path d="M63 59C45 43 50 18 73 15c-7-17 21-25 31-8 10-17 38-9 31 8 25 2 31 29 12 45" fill="#e9e5da"/>`,olga:`<path ${fills} d="M31 210c8-46 28-74 60-90-15-13-23-32-21-53 2-34 26-57 58-57 33 0 56 25 55 59-1 21-10 39-25 51 31 16 51 45 57 90Z"/><path d="M68 36 92 4l17 26 20-27 25 33" fill="#e9e5da"/>`,churchill:`<path ${fills} d="M31 210c6-42 24-70 56-86-17-14-26-33-25-55 1-33 25-56 58-56 34 0 58 24 57 58-1 22-10 40-27 53 32 15 53 43 59 86Z"/><path d="M83 83c24 14 49 14 72 0M96 112c15 7 29 7 43 0" ${fills} fill="none"/>`};return `<svg ${common}>${bg}${art[kind]||art.lenin}</svg>`;}
function render(){const a=authors[state.choice.author],q=quotes[state.choice.quote],s=sources[state.choice.source],y=state.choice.year;$('#portrait-cell').innerHTML=portrait(a.portrait);$('#quote-preview').textContent=q.text;$('#author-preview').textContent=a.name;$('#year-preview').textContent=formatYear(y);$('#source-preview').textContent='ИСТОЧНИК: '+s.name;$('#author-slot').textContent=a.name;$('#quote-slot').textContent=q.text;$('#source-slot').textContent=s.name;$('#year-value').textContent=formatYear(y);}
function formatYear(y){return y<0?`${Math.abs(y)} до н. э.`:`${y}`}
function randomizeRound(){state.choice.author=Math.floor(Math.random()*authors.length);state.choice.quote=Math.floor(Math.random()*quotes.length);state.choice.source=Math.floor(Math.random()*sources.length);const pools=[[1453,1917,2024,476,1204],[800,1066,1492,1812,1991],[-44,988,1600,1848,2007],[1453,1969,2001,2026,753]];state.choice.year=pick(pools[state.round]);render();}
function startGame(){state.round=0;state.total=0;state.history=[];$('#total-score').textContent='000';randomizeRound();prepareRound();showScreen('game');}
function prepareRound(){const b=briefs[state.round];$('#round-label').textContent=`ДЕЛО ${state.round+1}/4`;$('#brief-title').textContent=b.title;$('#brief-hint').textContent=b.hint;render();}
function yearDistance(a,y){if(y<a.years[0])return a.years[0]-y;if(y>a.years[1])return y-a.years[1];return 0;}
function tagAffinity(a,q){return q.tags.some(t=>a.tags.includes(t))?1:0;}
function scoreCurrent(){const a=authors[state.choice.author],q=quotes[state.choice.quote],s=sources[state.choice.source],y=state.choice.year,b=briefs[state.round];const dist=yearDistance(a,y);const chrono=clamp(dist/10+(q.modern*Math.max(0,1900-y))/2500+(s.born>y?Math.min(45,(s.born-y)/18):0));const sourceImpossible=s.born>y?clamp((s.born-y)/12):0;const affinity=tagAffinity(a,q);const deadpan=clamp(s.serious*.64+a.gravitas*.36);const incoherence=clamp((affinity?0:22)+(dist>1600?18:0)+(sourceImpossible>90?15:0)+(q.modern>95&&y<0?17:0));const target=b.bias==='master'?74:b.bias==='chrono'?82:b.bias==='source'?78:70;const relevant=b.bias==='source'?chrono*.55+sourceImpossible*.45:chrono;const sweet=clamp(100-Math.abs(relevant-target)*1.25);let score=clamp(sweet*.56+deadpan*.38-incoherence*.28+(affinity?8:0));if(b.bias==='chrono'&&dist<500)score-=22;if(b.bias==='source'&&s.born<=y)score-=26;if(b.bias==='master'&&(chrono<55||deadpan<82))score-=18;score=Math.round(clamp(score));return{score,chrono:Math.round(chrono),deadpan:Math.round(deadpan),chaos:Math.round(incoherence),dist,sourceImpossible};}
function publish(){const result=scoreCurrent(),a=authors[state.choice.author],q=quotes[state.choice.quote],s=sources[state.choice.source],y=state.choice.year;state.total+=result.score;state.history.push(result);state.archive.unshift({author:a.name,quote:q.text,year:formatYear(y),source:s.name,score:result.score,ts:Date.now()});state.archive=state.archive.slice(0,20);save();$('#total-score').textContent=String(state.total).padStart(3,'0');$('#result-score').textContent=String(result.score).padStart(2,'0');$('#meter-chrono').style.width=result.chrono+'%';$('#meter-deadpan').style.width=result.deadpan+'%';$('#meter-chaos').style.width=result.chaos+'%';let title='СЛИШКОМ НОРМАЛЬНО',verdict='Редакция просила историческую ложь, а вы почти начали проверять источники.';if(result.score>=88){title='ИДЕАЛЬНО НЕПРАВДА';verdict='Форма безупречна, факт невозможен, сомнение появляется только через полторы секунды. Редакционный стандарт.'}else if(result.score>=70){title='МОЖНО РАССЫЛАТЬ';verdict='Хорошая уверенная чушь. Кто-то обязательно спросит «а точно?», но уже после пересылки.'}else if(result.score>=48){title='ВИДЕН МОНТАЖ';verdict='Шутка понятна слишком быстро. Добавьте серьёзности или сделайте анахронизм менее лобовым.'}else if(result.chaos>45){title='ПРОСТО БРЕД';verdict='Элементы не складываются в одну убедительную ложь. Абсурд должен выглядеть как ошибка архива, а не генератор слов.'}$('#result-title').textContent=title;$('#verdict-line').textContent=verdict;$('#comment-line').textContent=pick(comments);$('#next-button').textContent=state.round===3?'ЗАКРЫТЬ АРХИВ':'СЛЕДУЮЩЕЕ ДЕЛО';showScreen('result');haptic(result.score>=70?[18,35,18]:25);}
function nextRound(){if(state.round>=3){finish();return;}state.round++;randomizeRound();prepareRound();showScreen('game');}
function finish(){const best=Number(localStorage.getItem(STORE+':best')||0);if(state.total>best)localStorage.setItem(STORE+':best',String(state.total));let title='АРХИВ НЕ ПРИНЯЛ',copy='Слишком много случайности. Историческая дезинформация требует ремесла.',stamp='НЕ СОШЛОСЬ';if(state.total>=330){title='ВЫ ТАМ БЫЛИ';copy='Четыре публикации, ни одной проверки, и всё выглядит так, будто под ними есть сноска. Опасно хороший результат.';stamp='ПОДЛИННО'}else if(state.total>=260){title='ПОЧТИ ПЕРВОИСТОЧНИК';copy='Редакция довольна. Несколько веков исчезли без следа, а комментарии уже спорят о контексте.';stamp='ПРИНЯТО'}else if(state.total>=190){title='РАБОЧАЯ ВЕРСИЯ ИСТОРИИ';copy='Часть цитат проживёт хотя бы до первого человека с Википедией. Уже неплохо.';stamp='В АРХИВ'}$('#finale-title').textContent=title;$('#final-copy').textContent=copy;$('#final-score').textContent=`${state.total} / 400`;$('#final-stamp').textContent=stamp;showScreen('finale');load();}
function openChoice(type){const map={author:['Кто это якобы сказал',authors],quote:['Что он якобы сказал',quotes],source:['Где это якобы нашли',sources],year:['Выбери год',[]]};if(type==='year'){openYearSheet();return;}const[title,data]=map[type];$('#sheet-title').textContent=title;const list=$('#choice-list');list.innerHTML='';data.forEach((item,i)=>{const btn=document.createElement('button');btn.className='choice-option'+(state.choice[type]===i?' is-selected':'');btn.type='button';btn.dataset.index=i;btn.innerHTML=`<b>${item.name||item.text}</b><span>${type==='author'?`${formatYear(item.years[0])} — ${formatYear(item.years[1])}`:type==='source'?`Технология: с ${formatYear(item.born)}`:`Индекс современности: ${item.modern}/100`}</span>`;btn.addEventListener('click',()=>{state.choice[type]=i;render();closeSheet();haptic(8)});list.append(btn)});$('#sheet-backdrop').hidden=false;$('#choice-sheet').hidden=false;}
function openYearSheet(){$('#sheet-title').textContent='Когда это якобы произошло';const list=$('#choice-list');list.innerHTML='';const years=[-44,476,800,988,1204,1453,1492,1648,1812,1917,1969,1991,2007,2026];years.forEach(y=>{const btn=document.createElement('button');btn.className='choice-option'+(state.choice.year===y?' is-selected':'');btn.type='button';btn.innerHTML=`<b>${formatYear(y)}</b><span>${y===1453?'особенно убедительный год':''}</span>`;btn.addEventListener('click',()=>{state.choice.year=y;render();closeSheet();haptic(8)});list.append(btn)});$('#sheet-backdrop').hidden=false;$('#choice-sheet').hidden=false;}
function closeSheet(){$('#sheet-backdrop').hidden=true;$('#choice-sheet').hidden=true;}
function changeYear(delta){const y=state.choice.year;const step=Math.abs(y)>=1000?50:Math.abs(y)>=100?10:1;state.choice.year=clamp(y+delta*step,-1000,2026);render();}
function openArchive(){const list=$('#archive-list');list.innerHTML='';if(!state.archive.length)list.innerHTML='<div class="empty-archive">Пока пусто.<br>Ни одного сомнительного источника.</div>';state.archive.forEach(x=>{const e=document.createElement('article');e.className='archive-entry';e.innerHTML=`<b>${x.author} · ${x.year} · ${x.score}/100</b><p>“${x.quote}”</p><span>${x.source}</span>`;list.append(e)});$('#archive-panel').hidden=false;}
function closeArchive(){$('#archive-panel').hidden=true;}
function clearArchive(){state.archive=[];save();openArchive();haptic(16)}
$('#start-button').addEventListener('click',startGame);$('#replay-button').addEventListener('click',startGame);$('#publish-button').addEventListener('click',publish);$('#next-button').addEventListener('click',nextRound);document.querySelectorAll('[data-slot]').forEach(btn=>btn.addEventListener('click',()=>openChoice(btn.dataset.slot)));$('#year-down').addEventListener('click',()=>changeYear(-1));$('#year-up').addEventListener('click',()=>changeYear(1));$('#sheet-close').addEventListener('click',closeSheet);$('#sheet-backdrop').addEventListener('click',closeSheet);$('#archive-button').addEventListener('click',openArchive);$('#final-archive-button').addEventListener('click',openArchive);$('#archive-close').addEventListener('click',closeArchive);$('#archive-clear').addEventListener('click',clearArchive);$('#pause-button').addEventListener('click',()=>{$('#pause-panel').hidden=false});$('#resume-button').addEventListener('click',()=>{$('#pause-panel').hidden=true});document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeSheet();closeArchive();$('#pause-panel').hidden=true}});window.addEventListener('pagehide',save);document.addEventListener('visibilitychange',()=>{if(document.hidden)save()});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));load();render();
