'use strict';
function loop(now){try{const dt=Math.min(.033,(now-last)/1000||0);last=now;update(dt);draw();requestAnimationFrame(loop)}catch(err){$('fatalText').textContent=err.message||String(err);$('fatal').classList.add('show');console.error(err)}}
function start(){resetRun();mode='play';paused=false;show(null);syncHud()}
$('playBtn').onclick=start;$('rulesPlay').onclick=start;$('rulesBtn').onclick=()=>show('rules');$('rulesBack').onclick=()=>show('menu');$('againBtn').onclick=start;$('menuBtn').onclick=()=>{mode='menu';show('menu');updateMenu()};$('pauseBtn').onclick=()=>{if(mode!=='play')return;paused=true;mode='pause';show('pause')};$('resumeBtn').onclick=()=>{paused=false;mode='play';show(null)};$('quitBtn').onclick=()=>{paused=false;mode='menu';show('menu');updateMenu()};
$('attackBtn').addEventListener('pointerdown',e=>{e.preventDefault();attack()});$('dashBtn').addEventListener('pointerdown',e=>{e.preventDefault();dash()});
document.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>{const k=b.dataset.up,cost={vital:12+save.up.vital*14,edge:16+save.up.edge*18,step:20+save.up.step*20}[k];if(save.up[k]>=5)return toast('МАКСИМУМ');if(save.embers<cost)return toast('НЕ ХВАТАЕТ УГЛЯ');save.embers-=cost;save.up[k]++;store();tone(300,.1,'square',.04);toast('УЛУЧШЕНО')});
const stick=$('stick');function stickMove(e){const r=stick.getBoundingClientRect(),x=e.clientX-(r.left+r.width/2),y=e.clientY-(r.top+r.height/2),l=Math.hypot(x,y),m=Math.min(34,l),nx=l?x/l:0,ny=l?y/l:0;input.x=nx*(l>8);input.y=ny*(l>8);stick.style.setProperty('--sx',(nx*m)+'px');stick.style.setProperty('--sy',(ny*m)+'px')}
stick.addEventListener('pointerdown',e=>{input.pointer=e.pointerId;stick.setPointerCapture(e.pointerId);stickMove(e)});stick.addEventListener('pointermove',e=>{if(input.pointer===e.pointerId)stickMove(e)});function stickEnd(e){if(input.pointer!==e.pointerId)return;input.pointer=null;input.x=input.y=0;stick.style.setProperty('--sx','0px');stick.style.setProperty('--sy','0px')}stick.addEventListener('pointerup',stickEnd);stick.addEventListener('pointercancel',stickEnd);
addEventListener('keydown',e=>{const k=e.key.toLowerCase();input.keys.add(k);if(['j','enter'].includes(k)){e.preventDefault();attack()}if(['k',' '].includes(k)){e.preventDefault();dash()}if(k==='escape'){if(mode==='play')$('pauseBtn').click();else if(mode==='pause')$('resumeBtn').click()}});addEventListener('keyup',e=>input.keys.delete(e.key.toLowerCase()));
for(let i=0;i<52;i++)ashes.push({x:rnd(0,W),y:rnd(0,H),v:rnd(5,18),s:rnd(0,99),z:Math.random()<.8?1:2,c:Math.random()<.18?'#8f5b35':'#5d4b3e'});
updateMenu();show('menu');requestAnimationFrame(loop);
