'use strict';
function attack(){if(mode!=='play'||player.attackT>0||player.dashT>0)return;player.combo=player.comboT>0?(player.combo%3)+1:1;player.comboT=.44;player.attackT=.16;player.hits++;const wide=player.combo===3;const range=(wide?32:25)*(has('range')?1.22:1);const arc=wide?1.55:1.15;let hit=0;
 for(const e of enemies){if(e.dead)continue;const d=dist(player,e),da=Math.abs(norm(ang(player,e)-player.face));if(d<range+e.r&&da<arc){let dmg=player.power*(has('power')?1.25:1)*(wide?(has('heavy')?2.0:1.55):1);if(has('dashCrit')&&player.dashCd>.72)dmg*=1.8;if(has('crown'))dmg*=1+kills*.02;if(has('pierce')&&player.hits%5===0)dmg*=1.6;if(e.hp/e.maxHp<.22&&player.will>=30){dmg=999;player.will-=30;if(has('executeHeal'))player.hp=Math.min(player.maxHp,player.hp+8);text(e.x,e.y-12,'КАЗНЬ', '#f1b45f');tone(62,.18,'sawtooth',.08);vibe(35)}damageEnemy(e,dmg);hit++}}
 if(player.combo===3&&has('hook'))for(const e of enemies){if(!e.dead&&dist(player,e)<70){const a=ang(e,player);e.x+=Math.cos(a)*10;e.y+=Math.sin(a)*10}}
 if(player.will>=100&&has('willSpark'))for(let i=-1;i<=1;i++)shots.push({x:player.x,y:player.y,vx:Math.cos(player.face+i*.3)*150,vy:Math.sin(player.face+i*.3)*150,r:2,life:.7,friendly:true,dmg:7});
 tone(wide?115:180,.055,wide?'sawtooth':'square',.05);vibe(wide?18:8);if(!hit)player.will=Math.max(0,player.will-1)}
function damageEnemy(e,dmg){e.hp-=dmg;e.hurt=.12;player.will=clamp(player.will+(6*(has('will')?1.35:1)),0,100);const a=ang(player,e);e.x+=Math.cos(a)*5;e.y+=Math.sin(a)*5;if(has('slow'))e.slow=1.2;burst(e.x,e.y,'#d47835',5);text(e.x,e.y-9,Math.round(dmg),'#e8c996');if(e.hp<=0)killEnemy(e)}
function killEnemy(e){if(e.dead)return;e.dead=true;kills++;runCoal+=e.type==='boss'?40:e.type==='brute'?4:2;if(has('killDash'))player.dashCd=Math.max(0,player.dashCd-.28);burst(e.x,e.y,e.type==='boss'?'#f0a24f':'#7f5e47',18);tone(e.type==='boss'?48:82,.16,'square',.06);vibe(e.type==='boss'?60:22)}
function dash(){if(mode!=='play'||player.dashCd>0||player.dashes<=0)return;let x=input.x,y=input.y;if(Math.hypot(x,y)<.2){x=Math.cos(player.face);y=Math.sin(player.face)}const l=Math.hypot(x,y)||1;player.dx=x/l;player.dy=y/l;player.dashT=.19;player.inv=.27;player.dashes--;player.dashCd=.9*(1-save.up.step*.07)*(has('dash')?.8:1);burst(player.x,player.y,'#b29a7b',8);tone(260,.08,'sawtooth',.04);vibe(12)}
function hurtPlayer(dmg,source){if(player.inv>0||mode!=='play')return;dmg*=has('armor')?.82:1;if(player.hp-dmg<=0&&has('halo')&&player.halo){player.halo=false;player.hp=1;player.inv=1;toast('НИМБ ТРЕСНУЛ');burst(player.x,player.y,'#e6d2a7',20);return}player.hp-=dmg;player.hurt=.25;player.inv=.65;shake=5;flash=.12;const a=ang(source||{x:120,y:100},player);player.x+=Math.cos(a)*8;player.y+=Math.sin(a)*8;tone(52,.18,'sawtooth',.08);vibe(40);if(player.hp<=0)finish(false)}
function perfect(){player.will=clamp(player.will+24*(has('will')?1.35:1),0,100);text(player.x,player.y-14,'ИДЕАЛЬНО','#f1b45f');if(has('parryWave'))for(const e of enemies)if(!e.dead&&dist(player,e)<48)damageEnemy(e,8);tone(520,.09,'square',.04);vibe(15)}
