'use strict';
function update(dt){frame+=dt;for(let i=0;i<ashes.length;i++){const a=ashes[i];a.y+=a.v*dt;a.x+=Math.sin(frame+a.s)*dt*4;if(a.y>H){a.y=-4;a.x=rnd(0,W)}}if(mode!=='play'||paused)return;
 player.inv=Math.max(0,player.inv-dt);player.hurt=Math.max(0,player.hurt-dt);player.attackT=Math.max(0,player.attackT-dt);player.comboT=Math.max(0,player.comboT-dt);if(!player.comboT)player.combo=0;player.dashCd=Math.max(0,player.dashCd-dt);if(player.dashCd===0&&player.dashes<2)player.dashes++;
 let mx=input.x,my=input.y;if(input.keys.has('arrowleft')||input.keys.has('a'))mx=-1;if(input.keys.has('arrowright')||input.keys.has('d'))mx=1;if(input.keys.has('arrowup')||input.keys.has('w'))my=-1;if(input.keys.has('arrowdown')||input.keys.has('s'))my=1;const ml=Math.hypot(mx,my);if(ml>.1){mx/=ml;my/=ml;player.face=Math.atan2(my,mx)}
 if(player.dashT>0){player.dashT-=dt;player.x+=player.dx*220*dt;player.y+=player.dy*220*dt}else{player.x+=mx*player.speed*dt;player.y+=my*player.speed*dt}player.x=clamp(player.x,16,W-16);player.y=clamp(player.y,68,H-68);
 for(const e of enemies){if(e.dead)continue;e.hurt=Math.max(0,e.hurt-dt);e.cd-=dt;e.slow=Math.max(0,e.slow-dt);const a=ang(e,player),d=dist(e,player),slow=e.slow>0?.55:1;
  if(e.type==='husk'){if(d>16){e.x+=Math.cos(a)*e.speed*slow*dt;e.y+=Math.sin(a)*e.speed*slow*dt}if(e.cd<0&&d<19){e.tele=.22;e.cd=1.0}}
  if(e.type==='brute'){if(e.tele>0){}else if(d>24){e.x+=Math.cos(a)*e.speed*slow*dt;e.y+=Math.sin(a)*e.speed*slow*dt}if(e.cd<0&&d<34){e.tele=.48;e.cd=1.8}}
  if(e.type==='archer'){if(d<78){e.x-=Math.cos(a)*e.speed*slow*dt;e.y-=Math.sin(a)*e.speed*slow*dt}else if(d>120){e.x+=Math.cos(a)*e.speed*slow*dt;e.y+=Math.sin(a)*e.speed*slow*dt}if(e.cd<0){e.tele=.38;e.cd=1.65}}
  if(e.type==='wisp'){e.x+=Math.cos(a+Math.sin(frame*2+e.seed)*.7)*e.speed*slow*dt;e.y+=Math.sin(a+Math.sin(frame*2+e.seed)*.7)*e.speed*slow*dt;if(e.cd<0&&d<70){e.tele=.28;e.cd=1.2}}
  if(e.type==='boss')updateBoss(e,dt,a,d);
  if(e.tele>0){e.tele-=dt;if(e.tele<=0)enemyStrike(e,a,d)}
 }
 for(let i=shots.length-1;i>=0;i--){const s=shots[i];s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;if(s.friendly){for(const e of enemies)if(!e.dead&&dist(s,e)<s.r+e.r){damageEnemy(e,s.dmg);s.life=0;break}}else if(dist(s,player)<s.r+player.r){if(player.dashT>0&&player.inv>.12)perfect();else hurtPlayer(s.dmg,s);s.life=0}if(s.life<=0||s.x<-10||s.x>W+10||s.y<50||s.y>H-40)shots.splice(i,1)}
 enemies=enemies.filter(e=>!e.dead);for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=20*dt;p.life-=dt;if(p.life<=0)particles.splice(i,1)}for(let i=texts.length-1;i>=0;i--){texts[i].y-=16*dt;texts[i].life-=dt;if(texts[i].life<=0)texts.splice(i,1)}
 if(enemies.length===0){roomDelay+=dt;if(roomDelay>.85){if(room===7)finish(true);else chooseRelic()}}
 syncHud()}
function updateBoss(e,dt,a,d){if(e.hp<e.maxHp*.5&&e.phase===1){e.phase=2;e.speed=25;e.phaseFlash=1;toast('ФАЗА II');burst(e.x,e.y,'#d04b2e',30);tone(44,.35,'sawtooth',.08)}if(e.tele<=0){if(d>50){e.x+=Math.cos(a)*e.speed*dt;e.y+=Math.sin(a)*e.speed*dt}if(e.cd<0){const roll=Math.random();e.tele=e.phase===2?.42:.58;e.pattern=roll<.42?'fan':roll<.75?'slam':'ring';e.cd=e.phase===2?1.05:1.45}}}
function enemyStrike(e,a,d){if(e.type==='archer'){shots.push({x:e.x,y:e.y,vx:Math.cos(a)*78,vy:Math.sin(a)*78,r:3,life:2.2,dmg:9})}else if(e.type==='wisp'){for(let i=-1;i<=1;i++)shots.push({x:e.x,y:e.y,vx:Math.cos(a+i*.24)*70,vy:Math.sin(a+i*.24)*70,r:2,life:1.8,dmg:7})}else if(e.type==='boss'){if(e.pattern==='fan')for(let i=-2;i<=2;i++)shots.push({x:e.x,y:e.y,vx:Math.cos(a+i*.22)*90,vy:Math.sin(a+i*.22)*90,r:3,life:2.3,dmg:11});if(e.pattern==='ring')for(let i=0;i<10+(e.phase*2);i++){const q=i/(10+e.phase*2)*TAU;shots.push({x:e.x,y:e.y,vx:Math.cos(q)*68,vy:Math.sin(q)*68,r:3,life:2.8,dmg:10})}if(e.pattern==='slam'&&d<58)hurtPlayer(18,e);shake=7}else{const range=e.type==='brute'?37:22;if(d<range){if(player.dashT>0&&player.inv>.12)perfect();else hurtPlayer(e.type==='brute'?17:10,e)}}}
function chooseRelic(){mode='choice';show('relic');const pool=baseRelics.filter(r=>!relicsOwned.includes(r[3])).sort(()=>Math.random()-.5).slice(0,3);$('relicKicker').textContent='ЗАЛ '+roman(room)+' ОЧИЩЕН';$('relicGrid').innerHTML='';for(const r of pool){const b=document.createElement('button');b.className='relic';b.innerHTML='<span class="sigil">'+r[1]+'</span><b>'+r[0]+'</b><p>'+r[2]+'</p>';b.onclick=()=>{relicsOwned.push(r[3]);if(r[3]==='hp'){player.maxHp+=24;player.hp+=24}room++;mode='play';show(null);spawnRoom()};$('relicGrid').appendChild(b)}}
function finish(win){mode='end';paused=false;const coal=runCoal+Math.max(0,room-1)*3+(win?35:0);save.embers+=coal;save.bestRoom=Math.max(save.bestRoom,room);if(win)save.wins++;store();show('end');$('endKicker').textContent=win?'ПЕПЕЛЬНИК ОТКРЫЛСЯ':'ЗАБЕГ ОКОНЧЕН';$('endTitle').textContent=win?'Хранитель стал пеплом':'Тебя развеяли';$('endCopy').textContent=win?'Семь залов позади. Но чаша снова тёплая — значит, внутри осталось ещё что-то мерзкое.':'Ты оставил после себя уголь. Купи постоянное улучшение и вернись менее хрупким.';$('endRoom').textContent=room;$('endKills').textContent=kills;$('endCoal').textContent=coal;ui.boss.classList.remove('show');tone(win?330:55,win?.4:.25,win?'square':'sawtooth',.07)}
function syncHud(){$('hpText').textContent=Math.ceil(player.hp)+'/'+player.maxHp;$('hpBar').style.width=clamp(player.hp/player.maxHp*100,0,100)+'%';$('willText').textContent=Math.floor(player.will);$('willBar').style.width=player.will+'%';$('dashText').textContent='●'.repeat(player.dashes)+'○'.repeat(2-player.dashes);if(boss){$('bossBar').style.width=clamp(boss.hp/boss.maxHp*100,0,100)+'%';$('bossPhase').textContent=boss.phase===1?'I':'II'}}
function burst(x,y,color,n){for(let i=0;i<n;i++)particles.push({x,y,vx:rnd(-45,45),vy:rnd(-48,16),life:rnd(.2,.65),color,size:rnd(1,3)})}function text(x,y,t,color){texts.push({x,y,t,color,life:.7})}function norm(a){while(a>Math.PI)a-=TAU;while(a<-Math.PI)a+=TAU;return a}
