import {createRequire} from 'node:module';import {mkdir,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';
const require=createRequire(import.meta.url);const {chromium,webkit}=require(process.env.INKBREAK_PLAYWRIGHT || (process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'@playwright/test'));
await mkdir('apps/inkbreak/qa',{recursive:true});const server=spawn(process.execPath,['scripts/serve-site.mjs'],{stdio:'ignore'});await new Promise(r=>setTimeout(r,500));const summaries=[];
try{for(const engine of (process.env.INKBREAK_WEBKIT==='only'?[webkit]:process.env.INKBREAK_WEBKIT==='1'?[chromium,webkit]:[chromium])){const isChrome=engine===chromium;const browser=await engine.launch(isChrome&&process.env.INKBREAK_CHROMIUM?{executablePath:process.env.INKBREAK_CHROMIUM,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']}:{headless:true});
for(const size of [{width:393,height:852},{width:852,height:393}]){const name=`${isChrome?'chromium':'webkit'}-${size.width}`,errors=[];const context=await browser.newContext({viewport:size,deviceScaleFactor:1,isMobile:true,hasTouch:true,recordVideo:process.env.INKBREAK_VIDEO==='1'?{dir:'apps/inkbreak/qa',size}:undefined});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`)});
await page.goto('http://127.0.0.1:4173/apps/inkbreak/');await page.waitForFunction(()=>window.__AI_TEST_STATE__?.ready);await page.screenshot({path:`apps/inkbreak/qa/${name}-first.png`});assert.equal(await page.locator('#menu a').getAttribute('href'),'../../');await page.locator('#sound').click();assert.equal(await page.locator('#sound').innerText(),'Звук: выкл');await page.locator('#start').click();await page.screenshot({path:`apps/inkbreak/qa/${name}-action.png`});
// Exercise actual pointer capture and cancellation on the thumb stick.
const box=await page.locator('#stick').boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width*.8,box.y+box.height/2);await page.waitForTimeout(180);await page.mouse.up();let state=await page.evaluate(()=>window.__AI_TEST_STATE__);assert.ok(state.player.x>0);await page.locator('#pause').click();await page.waitForFunction(()=>window.__AI_TEST_STATE__.mode==='pause');assert.equal((await page.evaluate(()=>window.__AI_TEST_STATE__)).mode,'pause');await page.screenshot({path:`apps/inkbreak/qa/${name}-pause.png`});const before=await page.evaluate(()=>window.__AI_TEST_STATE__.player);await page.waitForTimeout(150);assert.deepEqual(await page.evaluate(()=>window.__AI_TEST_STATE__.player),before);await page.locator('#continue').click();await page.waitForFunction(()=>window.__AI_TEST_STATE__.mode==='play');
// A player bot reads published state and uses only real keyboard inputs.
// It never edits game state, health, clock, enemies or progression.
let held=new Set(),completed=0,retries=0,firstDash=false;const deadline=Date.now()+190000;
while(Date.now()<deadline&&completed<3){state=await page.evaluate(()=>window.__AI_TEST_STATE__);if(state.mode==='dead'){retries++;if(retries>4)throw new Error(`${name}: combat bot repeatedly died`);for(const k of held)await page.keyboard.up(k);held.clear();await page.locator('#continue').click();await page.waitForFunction(()=>window.__AI_TEST_STATE__.mode==='play');continue;}
if(state.mode==='complete'){completed++;await page.screenshot({path:`apps/inkbreak/qa/${name}-chapter${state.chapter+1}-complete.png`});assert.ok(state.score>0);for(const k of held)await page.keyboard.up(k);held.clear();if(completed<3){await page.locator('#continue').click();await page.waitForFunction(()=>window.__AI_TEST_STATE__.mode==='play');}continue;}
if(state.mode!=='play')throw new Error(`Unexpected mode ${state.mode}`);
let near=state.enemies.slice().sort((a,b)=>Math.hypot(a.x-state.player.x,a.z-state.player.z)-Math.hypot(b.x-state.player.x,b.z-state.player.z))[0],target=new Set();if(near){const dx=near.x-state.player.x,dz=near.z-state.player.z,d=Math.hypot(dx,dz);if(d>2.2){if(dx>.35)target.add('d');if(dx<-.35)target.add('a');if(dz>.35)target.add('s');if(dz<-.35)target.add('w');}if(near.boss&&near.windup>0&&d<4.5){target=new Set();if(dx>0)target.add('a');else target.add('d');if(dz>0)target.add('w');else target.add('s');if(state.dashCooldown===0)await page.keyboard.press('Shift');}}
for(const k of held)if(!target.has(k))await page.keyboard.up(k);for(const k of target)if(!held.has(k))await page.keyboard.down(k);held=target;await page.keyboard.press('j');if(!firstDash&&state.kills>0){await page.keyboard.press('k');firstDash=true;}await page.waitForTimeout(110);
}
assert.equal(completed,3,`${name}: did not complete all chapters`);assert.ok(firstDash);assert.equal((await page.evaluate(()=>window.__AI_TEST_STATE__)).savedChapter,2);await page.reload();await page.waitForFunction(()=>window.__AI_TEST_STATE__?.ready);assert.equal((await page.evaluate(()=>window.__AI_TEST_STATE__)).savedChapter,2);assert.ok((await page.locator('#record').innerText()).includes('ОЧКОВ'));
if(isChrome){await page.evaluate(()=>Promise.race([navigator.serviceWorker.ready,new Promise((_,reject)=>setTimeout(()=>reject(new Error('SW readiness timeout')),15000))]));await page.reload();await page.waitForFunction(()=>window.__AI_TEST_STATE__?.ready);await context.setOffline(true);await page.reload();await page.waitForFunction(()=>window.__AI_TEST_STATE__?.ready);assert.equal((await page.evaluate(()=>window.__AI_TEST_STATE__)).mode,'menu');await context.setOffline(false);}
await page.emulateMedia({reducedMotion:'reduce'});await page.locator('#start').click();await page.keyboard.press('j');await page.keyboard.press('k');await page.screenshot({path:`apps/inkbreak/qa/${name}-reduced.png`});assert.deepEqual(errors,[]);summaries.push({name,completed,retries,errors});console.log(JSON.stringify(summaries.at(-1)));await context.close();}
await browser.close();}await writeFile(`apps/inkbreak/qa/results-${process.env.INKBREAK_WEBKIT==='only'?'webkit':'chromium'}.json`,JSON.stringify(summaries,null,2));}finally{server.kill();}
