import { installMobileRuntime } from '../../shared/mobile-runtime.js';
import { createVersionedStore } from '../../shared/capabilities/storage.js';
import { watchOrientation, lockOrientation, unlockOrientation } from '../../shared/capabilities/device.js';
import { createWorkshopMode } from '../../shared/workshop-mode.js';
import { watchConnectivity } from '../../shared/pwa-utils.js';

installMobileRuntime();
const $ = (s) => document.querySelector(s);
const clamp = (v, a, b) => Math.max(a, Math.min(b, v));
const lerp = (a, b, t) => a + (b - a) * t;
const TAU = Math.PI * 2;
const NS = 'pocket-works:petlya-17';
const VERSION = '1.0.0';
const LAPS = 3;
const SEG = 20;
const COUNT = 280;
const TRACK_LENGTH = SEG * COUNT;
const DRAW = 92;
const MAX_SPEED = 306;

const store = createVersionedStore({namespace:NS,version:1,defaults:{settings:{sensitivity:22,sound:true,haptics:true},records:{bestFinish:null,bestLapMs:null}}});
const saved = store.getAll();
const settings = {sensitivity:clamp(Number(saved.settings?.sensitivity)||22,10,35),sound:saved.settings?.sound!==false,haptics:saved.settings?.haptics!==false};
let records = {bestFinish:Number.isFinite(saved.records?.bestFinish)?saved.records.bestFinish:null,bestLapMs:Number.isFinite(saved.records?.bestLapMs)?saved.records.bestLapMs:null};

const canvas=$('#race'),ctx=canvas.getContext('2d',{alpha:false,desynchronized:true});
const menu=$('#menu'),settingsScreen=$('#settings'),pauseScreen=$('#pause'),resultsScreen=$('#results'),controls=$('#controls'),steerPad=$('#steerPad'),draft=$('#draft'),message=$('#message'),pauseButton=$('#pauseButton'),gasButton=$('#gas'),brakeButton=$('#brake');
let width=1,height=1,dpr=1,lastFrame=performance.now(),mode='menu',settingsReturn='menu',countdown=0,countMark=4,sensorStop=null,sensorBaseline=null,sensorActive=false,steerTarget=0,steer=0,throttle=false,braking=false,raceTime=0,lapStart=0,bestLap=Infinity,passes=0,previousPosition=6,shake=0,collisionCooldown=0,lastGear=1;
const player={distance:0,speed:0,x:0,lap:1};

const track=Array.from({length:COUNT},(_,i)=>{const t=i/COUNT;return{curve:Math.sin(t*TAU*2)*.48+Math.sin(t*TAU*5+.8)*.27+Math.sin(t*TAU*9-.4)*.12,elevation:Math.sin(t*TAU*3+1.1)*.42+Math.sin(t*TAU*7)*.13}});
const botTemplates=[
{name:'ЯКОРЬ',color:'#e0b84d',stripe:'#1d2521',pace:.925,aggression:.35,lane:-.62},
{name:'НОЖ',color:'#c5482e',stripe:'#eee3c9',pace:.992,aggression:.92,lane:.28},
{name:'ТЕНЬ',color:'#2d4d46',stripe:'#d6d1bd',pace:.967,aggression:.2,lane:-.18},
{name:'ГОНЧАЯ',color:'#ded8c4',stripe:'#a62f1b',pace:.978,aggression:.72,lane:.68},
{name:'ИСКРА',color:'#4b78a1',stripe:'#f2c557',pace:.945,aggression:.58,lane:.05}
];
let bots=[];
const makeBots=()=>botTemplates.map((t,i)=>({...t,id:i+11,distance:16+i*14,speed:0,x:t.lane,targetX:t.lane,decisionAt:1.2+i*.35,wobble:Math.random()*TAU}));

class EngineAudio{
 constructor(){this.c=null;this.master=null;this.engine=null;this.harmonic=null;this.noise=null}
 async unlock(){if(!settings.sound)return;if(!this.c){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;this.c=new AC;this.master=this.c.createGain();this.master.gain.value=.0001;this.master.connect(this.c.destination);this.engine=this.c.createOscillator();this.engine.type='sawtooth';this.harmonic=this.c.createOscillator();this.harmonic.type='square';const filter=this.c.createBiquadFilter(),hg=this.c.createGain();filter.type='lowpass';filter.frequency.value=540;hg.gain.value=.08;this.engine.connect(filter);this.harmonic.connect(hg).connect(filter);filter.connect(this.master);this.engine.start();this.harmonic.start();const n=this.c.sampleRate*.2;this.noise=this.c.createBuffer(1,n,this.c.sampleRate);const ch=this.noise.getChannelData(0);for(let i=0;i<n;i++)ch[i]=Math.random()*2-1}if(this.c.state==='suspended')await this.c.resume()}
 update(speed,active){if(!this.c||!this.master||!settings.sound)return;const n=this.c.currentTime,rpm=42+speed*1.34;this.engine.frequency.setTargetAtTime(rpm,n,.035);this.harmonic.frequency.setTargetAtTime(rpm*2.02,n,.035);this.master.gain.setTargetAtTime(active?.075+speed/MAX_SPEED*.055:.0001,n,.07)}
 beep(freq=520,dur=.09,g=.12){if(!this.c||!settings.sound)return;const o=this.c.createOscillator(),gain=this.c.createGain();o.type='square';o.frequency.value=freq;gain.gain.setValueAtTime(g,this.c.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,this.c.currentTime+dur);o.connect(gain).connect(this.c.destination);o.start();o.stop(this.c.currentTime+dur)}
 crash(k=1){if(!this.c||!settings.sound||!this.noise)return;const s=this.c.createBufferSource(),f=this.c.createBiquadFilter(),g=this.c.createGain();s.buffer=this.noise;f.type='bandpass';f.frequency.value=120+k*180;g.gain.setValueAtTime(.16*k,this.c.currentTime);g.gain.exponentialRampToValueAtTime(.0001,this.c.currentTime+.18);s.connect(f).connect(g).connect(this.c.destination);s.start()}
 mute(){if(this.c&&this.master)this.master.gain.setTargetAtTime(.0001,this.c.currentTime,.03)}
}
const audio=new EngineAudio();
const haptic=p=>{if(settings.haptics&&navigator.vibrate)navigator.vibrate(p)};
const segmentAt=d=>track[Math.floor((((d%TRACK_LENGTH)+TRACK_LENGTH)%TRACK_LENGTH)/SEG)%COUNT];
const formatTime=ms=>{if(!Number.isFinite(ms))return'—';const t=Math.max(0,Math.floor(ms)),m=Math.floor(t/60000),s=Math.floor(t%60000/1000);return`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}.${String(t%1000).padStart(3,'0')}`};
const saveSettings=()=>store.set('settings',{...settings});
const saveRecords=()=>{store.set('records',{...records});updateRecords()};
function updateRecords(){$('#bestFinish').textContent=records.bestFinish?`${records.bestFinish}/6`:'—';$('#bestLap').textContent=formatTime(records.bestLapMs)}
function updateSettings(){$('#sensitivity').value=settings.sensitivity;$('#sensitivityValue').textContent=`${settings.sensitivity}°`;for(const [id,on] of [['sound',settings.sound],['haptics',settings.haptics]]){const b=$(`#${id}`);b.textContent=on?'ВКЛ':'ВЫКЛ';b.classList.toggle('off',!on);b.setAttribute('aria-pressed',String(on))}}
function resize(){const r=canvas.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);width=Math.max(1,Math.floor(r.width));height=Math.max(1,Math.floor(r.height));canvas.width=Math.floor(width*dpr);canvas.height=Math.floor(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}
function axis(e){const a=Number(screen.orientation?.angle??window.orientation??0);if(a===90)return Number(e.beta)||0;if(a===270||a===-90)return-(Number(e.beta)||0);return Number(e.gamma)||0}
async function enableTilt(){sensorBaseline=null;sensorStop?.();sensorStop=await watchOrientation(e=>{const v=axis(e);if(sensorBaseline===null)sensorBaseline=v;const n=clamp((v-sensorBaseline)/settings.sensitivity,-1,1);steerTarget=Math.abs(n)<.035?0:n});sensorActive=Boolean(sensorStop);return sensorActive}
function stopTilt(){sensorStop?.();sensorStop=null;sensorBaseline=null;sensorActive=false}
function say(text,duration=900){message.textContent=text;clearTimeout(say.timer);if(duration)say.timer=setTimeout(()=>message.textContent='',duration)}
function position(){let p=1;for(const b of bots)if(b.distance>player.distance)p++;return p}
function updateHud(){const p=position();$('#position').textContent=p;$('#lap').textContent=`${Math.min(player.lap,LAPS)}/${LAPS}`;const ahead=bots.map(b=>b.distance-player.distance).filter(d=>d>0).sort((a,b)=>a-b)[0];$('#gap').textContent=Number.isFinite(ahead)?`+${(ahead/Math.max(player.speed/3.6,1)).toFixed(1)}с`:'ЛИДЕР'}
function resetRace(){Object.assign(player,{distance:0,speed:0,x:0,lap:1});bots=makeBots();raceTime=0;lapStart=0;bestLap=Infinity;passes=0;previousPosition=6;shake=0;collisionCooldown=0;lastGear=1;steer=0;steerTarget=0;throttle=false;braking=false;updateHud()}
async function startRace(useTilt){$('#start').disabled=true;$('#practice').disabled=true;await audio.unlock();let tilt=false;if(useTilt)tilt=await enableTilt();if(!tilt){stopTilt();steerPad.hidden=false}else steerPad.hidden=true;try{await lockOrientation('landscape')}catch{}resetRace();menu.classList.add('hidden');settingsScreen.classList.add('hidden');pauseScreen.classList.add('hidden');resultsScreen.classList.add('hidden');controls.hidden=false;pauseButton.hidden=false;draft.hidden=true;mode='countdown';countdown=3.7;countMark=4;lastFrame=performance.now();say(tilt?'ДЕРЖИ РОВНО':'РУЛЬ — ПОЛОСА ВНИЗУ',900);$('#start').disabled=false;$('#practice').disabled=false}
function draftStrength(){let k=0;for(const b of bots){const d=b.distance-player.distance,l=Math.abs(b.x-player.x);if(d>9&&d<175&&l<.29)k=Math.max(k,(1-d/175)*(1-l/.29))}return clamp(k,0,1)}
function updateBots(dt){bots.forEach((b,i)=>{const c=Math.abs(segmentAt(b.distance+80).curve),target=clamp(249+b.pace*48-c*31+clamp((player.distance-b.distance)/1300,-1,1)*4+Math.sin(raceTime*.0007+b.wobble)*(2+b.aggression*2.5),218,300);b.speed+=clamp(target-b.speed,-62*dt,38*dt);b.distance+=b.speed/3.6*dt;if(raceTime/1000>b.decisionAt){const cd=Math.sign(segmentAt(b.distance+150).curve),tactical=-cd*(.18+b.aggression*.18),random=Math.sin(b.wobble+raceTime*.00031+i)*.55;b.targetX=clamp(tactical+random,-.78,.78);b.decisionAt=raceTime/1000+1.4+Math.random()*2.2}b.x+=clamp(b.targetX-b.x,-dt*(.28+b.aggression*.25),dt*(.28+b.aggression*.25))})}
function collide(){if(collisionCooldown>0)return;for(const b of bots){const d=b.distance-player.distance,l=Math.abs(b.x-player.x);if(d>-8&&d<17&&l<.2){collisionCooldown=.48;player.speed*=.82;b.speed*=.91;player.x+=(player.x<=b.x?-1:1)*.11;shake=Math.max(shake,9);audio.crash(.85);haptic([18,22,26]);say('КОНТАКТ',500);return}}}
function updateRace(dt){if(mode==='countdown'){countdown-=dt;const mark=Math.ceil(countdown);if(mark!==countMark&&mark>0&&mark<=3){countMark=mark;say(String(mark),760);audio.beep(360+(3-mark)*70,.11,.14);haptic(18)}if(countdown<=0){mode='racing';say('СТАРТ',800);audio.beep(760,.18,.18);haptic([25,30,35])}return}if(mode!=='racing')return;raceTime+=dt*1000;collisionCooldown=Math.max(0,collisionCooldown-dt);steer+=(steerTarget-steer)*Math.min(1,dt*9);const curve=segmentAt(player.distance+45).curve,k=draftStrength(),limit=MAX_SPEED+k*20,force=throttle?74*(1-player.speed/(limit+45)):0;player.speed=clamp(player.speed+(force-(braking?137:0)-8-player.speed*.026)*dt,0,limit);player.x+=steer*(.3+player.speed/MAX_SPEED*.83)*dt;player.x-=curve*(player.speed/MAX_SPEED)**2*.2*dt;if(Math.abs(player.x)>.93){player.speed=Math.max(0,player.speed-83*dt);shake=Math.max(shake,2.2+player.speed/100)}if(Math.abs(player.x)>1.16){player.x=Math.sign(player.x)*1.16;player.speed*=.76;shake=Math.max(shake,8);audio.crash(.7);haptic([24,18,22])}const before=player.distance;player.distance+=player.speed/3.6*dt;updateBots(dt);collide();const oldLap=Math.floor(before/TRACK_LENGTH),newLap=Math.floor(player.distance/TRACK_LENGTH);if(newLap>oldLap&&newLap<LAPS){const lt=raceTime-lapStart;lapStart=raceTime;bestLap=Math.min(bestLap,lt);player.lap=newLap+1;say(player.lap===LAPS?'ПОСЛЕДНИЙ КРУГ':`КРУГ ${player.lap}`,1200);audio.beep(650,.16,.13);haptic([20,20,20])}const p=position();if(p<previousPosition)passes+=previousPosition-p;previousPosition=p;const gear=clamp(Math.floor(player.speed/48)+1,1,6);if(gear!==lastGear&&player.speed>20){lastGear=gear;audio.beep(90+gear*18,.035,.035);haptic(8)}draft.hidden=k<.12;if(!draft.hidden)draft.querySelector('b').textContent=`+${Math.round(k*20)}`;if(player.distance>=LAPS*TRACK_LENGTH)finish();updateHud()}
function finish(){if(mode==='finished')return;mode='finished';controls.hidden=true;pauseButton.hidden=true;draft.hidden=true;audio.update(0,false);audio.beep(820,.32,.16);haptic([35,35,70]);const p=position();if(!records.bestFinish||p<records.bestFinish)records.bestFinish=p;if(Number.isFinite(bestLap)&&(!records.bestLapMs||bestLap<records.bestLapMs))records.bestLapMs=Math.round(bestLap);saveRecords();const names=['Первое','Второе','Третье','Четвёртое','Пятое','Шестое'],texts=['Чисто. Быстро. Остальные могут оформить письменную жалобу.','До победы не хватило одного злого торможения.','Подиум есть. Переднее крыло тоже почти есть.','Средний результат. Зато стены теперь знают твоё имя.','Соперники уехали. Самоуважение осталось на пит-лейне.','Финишировал последним, но технически всё ещё финишировал.'];$('#resultTitle').textContent=`${names[p-1]} место`;$('#resultText').textContent=texts[p-1];$('#resultPosition').textContent=`${p}/6`;$('#resultTime').textContent=formatTime(raceTime);$('#resultLap').textContent=formatTime(bestLap);$('#resultPasses').textContent=passes;resultsScreen.classList.remove('hidden')}
function goMenu(){mode='menu';stopTilt();unlockOrientation();controls.hidden=true;pauseButton.hidden=true;draft.hidden=true;pauseScreen.classList.add('hidden');resultsScreen.classList.add('hidden');settingsScreen.classList.add('hidden');menu.classList.remove('hidden');audio.mute();message.textContent='';throttle=false;braking=false;updateRecords()}
function pauseRace(){if(!['racing','countdown'].includes(mode))return;mode='paused';throttle=false;braking=false;controls.hidden=true;pauseButton.hidden=true;pauseScreen.classList.remove('hidden');audio.update(player.speed,false)}
function resumeRace(){if(mode!=='paused')return;mode='racing';pauseScreen.classList.add('hidden');controls.hidden=false;pauseButton.hidden=false;lastFrame=performance.now()}
function openSettings(from='menu'){settingsReturn=from;menu.classList.add('hidden');pauseScreen.classList.add('hidden');settingsScreen.classList.remove('hidden');updateSettings()}
function closeSettings(){settingsScreen.classList.add('hidden');(settingsReturn==='pause'?pauseScreen:menu).classList.remove('hidden')}

function projectRoad(){const horizon=height*.31,bottom=height*.91,nearHalf=Math.max(width*.42,290),farHalf=Math.max(width*.018,13),pts=[];let heading=0,lateral=0;for(let i=0;i<=DRAW;i++){const p=i/DRAW,n=1-p,s=segmentAt(player.distance+i*SEG);heading+=s.curve*.00155;lateral+=heading;const half=farHalf+(nearHalf-farHalf)*n**1.32,y=horizon+(bottom-horizon)*n**1.53-s.elevation*height*.025*p*(1-p),x=width*.5-player.x*half+lateral*half*.21;pts.push({x,y,half,segment:Math.floor((player.distance+i*SEG)/SEG)})}return pts}
function quad(a,b,c,d,fill){ctx.fillStyle=fill;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.lineTo(c.x,c.y);ctx.lineTo(d.x,d.y);ctx.fill()}
function background(curve){const g=ctx.createLinearGradient(0,0,0,height*.62);g.addColorStop(0,'#91a7a0');g.addColorStop(.62,'#d7cdaf');g.addColorStop(1,'#e7d7b5');ctx.fillStyle=g;ctx.fillRect(0,0,width,height);const par=-steer*12-curve*18;ctx.fillStyle='#61756e';ctx.beginPath();ctx.moveTo(0,height*.33);for(let x=0;x<=width;x+=40)ctx.lineTo(x,height*.29+Math.sin((x+par)*.018)*12+Math.sin(x*.006)*8);ctx.lineTo(width,height*.47);ctx.lineTo(0,height*.47);ctx.fill();ctx.save();ctx.translate(par*1.7,0);for(let i=-2;i<13;i++){const x=i*width/10,base=height*.325;ctx.fillStyle=i%3?'#8e8067':'#7c6c55';ctx.fillRect(x,base-24-(i%2)*12,width/14,30+(i%2)*12);if(i%4===0){ctx.strokeStyle='#46534d';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x+8,base-25);ctx.lineTo(x+8,base-92);ctx.lineTo(x+62,base-78);ctx.stroke()}}ctx.restore()}
function road(pts){for(let i=DRAW-1;i>=0;i--){const n=pts[i],f=pts[i+1],sn=n.half*1.15,sf=f.half*1.15,alt=n.segment%2===0;quad({x:n.x-sn,y:n.y},{x:n.x+sn,y:n.y},{x:f.x+sf,y:f.y},{x:f.x-sf,y:f.y},alt?'#d7c7a3':'#b94925');quad({x:n.x-n.half,y:n.y},{x:n.x+n.half,y:n.y},{x:f.x+f.half,y:f.y},{x:f.x-f.half,y:f.y},alt?'#383b36':'#343732');if(n.segment%4<2){const ln=Math.max(1,n.half*.014),lf=Math.max(.5,f.half*.014);quad({x:n.x-ln,y:n.y},{x:n.x+ln,y:n.y},{x:f.x+lf,y:f.y},{x:f.x-lf,y:f.y},'#d9d0b9')}}}
function pointAt(pts,d){const raw=d/SEG,i=clamp(Math.floor(raw),0,DRAW-1),t=clamp(raw-i,0,1),a=pts[i],b=pts[i+1];return{x:lerp(a.x,b.x,t),y:lerp(a.y,b.y,t),half:lerp(a.half,b.half,t)}}
function drawCar(b,p){const s=clamp(p.half/(width*.42),.025,1),w=92*s,h=52*s,x=p.x+b.x*p.half,y=p.y-h*.8;ctx.save();ctx.translate(x,y);ctx.fillStyle='#0005';ctx.fillRect(-w*.58,h*.72,w*1.16,h*.18);ctx.fillStyle='#161916';ctx.fillRect(-w*.64,h*.25,w*.2,h*.5);ctx.fillRect(w*.44,h*.25,w*.2,h*.5);ctx.fillStyle=b.color;ctx.beginPath();ctx.moveTo(-w*.5,h*.72);ctx.lineTo(-w*.38,0);ctx.lineTo(0,-h*.18);ctx.lineTo(w*.38,0);ctx.lineTo(w*.5,h*.72);ctx.fill();ctx.fillStyle=b.stripe;ctx.fillRect(-w*.08,-h*.08,w*.16,h*.78);ctx.fillStyle='#1b211e';ctx.fillRect(-w*.22,h*.13,w*.44,h*.24);if(s>.16){ctx.fillStyle='#eee1c5';ctx.font=`900 ${Math.max(7,11*s)}px ui-monospace`;ctx.textAlign='center';ctx.fillText(b.id,0,h*.62)}ctx.restore()}
function drawBots(pts){bots.map(b=>({b,d:b.distance-player.distance})).filter(o=>o.d>4&&o.d<DRAW*SEG).sort((a,b)=>b.d-a.d).forEach(o=>drawCar(o.b,pointAt(pts,o.d)))}
function furniture(pts){for(let i=10;i<DRAW;i+=13){const p=pts[i],side=p.segment%3===0?-1:1,x=p.x+side*p.half*1.36,s=clamp(p.half/(width*.42),.02,1);ctx.fillStyle='#222822';ctx.fillRect(x-2*s,p.y-55*s,4*s,55*s);ctx.fillStyle=p.segment%2?'#d4b64c':'#b94725';ctx.fillRect(x-18*s,p.y-58*s,36*s,13*s)}}
function mirrors(){const y=height*.19,w=Math.min(width*.16,170),h=Math.min(height*.105,58);[width*.12,width*.88-w].forEach((x,index)=>{ctx.save();ctx.fillStyle='#161917';ctx.fillRect(x-5,y-5,w+10,h+10);ctx.beginPath();ctx.rect(x,y,w,h);ctx.clip();ctx.fillStyle='#879b95';ctx.fillRect(x,y,w,h*.46);ctx.fillStyle='#3c403b';ctx.beginPath();ctx.moveTo(x+w*.32,y+h);ctx.lineTo(x+w*.45,y+h*.46);ctx.lineTo(x+w*.55,y+h*.46);ctx.lineTo(x+w*.68,y+h);ctx.fill();const behind=bots.map(b=>({b,d:player.distance-b.distance})).filter(o=>o.d>0&&o.d<210).filter(o=>index===0?o.b.x<player.x+.1:o.b.x>=player.x-.1).sort((a,b)=>a.d-b.d)[0];if(behind){const s=clamp(1-behind.d/230,.18,.72);ctx.fillStyle=behind.b.color;ctx.fillRect(x+w*.5-17*s,y+h*.72-12*s,34*s,18*s);ctx.fillStyle='#151817';ctx.fillRect(x+w*.5-12*s,y+h*.72-8*s,24*s,7*s)}ctx.restore()})}
function cockpit(){const top=height*.73;ctx.fillStyle='#121512';ctx.beginPath();ctx.moveTo(0,height*.57);ctx.lineTo(width*.15,top);ctx.lineTo(width*.34,top+height*.04);ctx.lineTo(width*.66,top+height*.04);ctx.lineTo(width*.85,top);ctx.lineTo(width,height*.57);ctx.lineTo(width,height);ctx.lineTo(0,height);ctx.fill();ctx.fillStyle='#292c27';ctx.beginPath();ctx.moveTo(0,height*.54);ctx.lineTo(width*.035,height*.55);ctx.lineTo(width*.18,height);ctx.lineTo(0,height);ctx.fill();ctx.beginPath();ctx.moveTo(width,height*.54);ctx.lineTo(width*.965,height*.55);ctx.lineTo(width*.82,height);ctx.lineTo(width,height);ctx.fill();mirrors();const x=width*.5,y=height*.87,r=Math.min(width,height)*.155;ctx.save();ctx.translate(x,y);ctx.rotate(steer*.58);ctx.strokeStyle='#262a25';ctx.lineWidth=Math.max(12,r*.18);ctx.beginPath();ctx.arc(0,0,r,Math.PI*.1,Math.PI*.9,true);ctx.stroke();ctx.strokeStyle='#6f7267';ctx.lineWidth=Math.max(2,r*.025);ctx.stroke();ctx.fillStyle='#242722';ctx.beginPath();ctx.moveTo(-r*.68,-r*.16);ctx.lineTo(-r*.2,r*.18);ctx.lineTo(r*.2,r*.18);ctx.lineTo(r*.68,-r*.16);ctx.lineTo(r*.46,r*.54);ctx.lineTo(-r*.46,r*.54);ctx.fill();ctx.restore();const gw=Math.min(width*.17,180),gh=Math.min(height*.14,78),gx=x-gw/2,gy=y-gh*.63;ctx.fillStyle='#0a0d0b';ctx.fillRect(gx,gy,gw,gh);ctx.strokeStyle='#70766c';ctx.strokeRect(gx,gy,gw,gh);ctx.fillStyle='#e5d8b8';ctx.textAlign='center';ctx.font=`900 ${Math.max(19,gh*.43)}px ui-monospace`;ctx.fillText(String(Math.round(player.speed)).padStart(3,'0'),x,gy+gh*.48);ctx.font=`800 ${Math.max(7,gh*.12)}px ui-monospace`;ctx.fillText('КМ/Ч',x,gy+gh*.66);const gear=clamp(Math.floor(player.speed/48)+1,1,6);ctx.fillStyle='#d75b2a';ctx.font=`1000 ${Math.max(13,gh*.25)}px ui-monospace`;ctx.fillText(gear,x,gy+gh*.91);for(let i=0;i<12;i++){ctx.fillStyle=i/12<clamp(player.speed/MAX_SPEED,0,1)?(i>9?'#d34325':'#d7bd5b'):'#3b3e38';ctx.fillRect(gx+i*gw/12,gy-7,gw/12-2,4)}}
function render(){const c=segmentAt(player.distance+60).curve,s=shake>.1?shake:0,sx=s?(Math.random()-.5)*s:0,sy=s?(Math.random()-.5)*s*.45:0;shake*=.88;ctx.save();ctx.translate(sx,sy);background(c);const pts=projectRoad();road(pts);furniture(pts);drawBots(pts);cockpit();ctx.restore()}
function frame(now){const dt=clamp((now-lastFrame)/1000,0,.05);lastFrame=now;updateRace(dt);audio.update(player.speed,mode==='racing'||mode==='countdown');render();requestAnimationFrame(frame)}
function hold(button,setter){const end=e=>{setter(false);button.classList.remove('active');if(e?.pointerId!=null&&button.hasPointerCapture?.(e.pointerId))button.releasePointerCapture(e.pointerId)};button.addEventListener('pointerdown',e=>{e.preventDefault();button.setPointerCapture?.(e.pointerId);setter(true);button.classList.add('active')});button.addEventListener('pointerup',end);button.addEventListener('pointercancel',end);button.addEventListener('lostpointercapture',end)}
hold(gasButton,v=>throttle=v);hold(brakeButton,v=>braking=v);
let steerPointer=null;function steerFrom(e){const r=steerPad.getBoundingClientRect();steerTarget=clamp((e.clientX-r.left)/r.width*2-1,-1,1);steerPad.querySelector('i').style.left=`${(steerTarget+1)*50}%`}
steerPad.addEventListener('pointerdown',e=>{e.preventDefault();steerPointer=e.pointerId;steerPad.setPointerCapture?.(e.pointerId);steerFrom(e)});steerPad.addEventListener('pointermove',e=>{if(e.pointerId===steerPointer)steerFrom(e)});const releaseSteer=e=>{if(e.pointerId!==steerPointer)return;steerPointer=null;steerTarget=0;steerPad.querySelector('i').style.left='50%'};steerPad.addEventListener('pointerup',releaseSteer);steerPad.addEventListener('pointercancel',releaseSteer);steerPad.addEventListener('lostpointercapture',releaseSteer);
const keys=new Set();window.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','KeyA','KeyD','KeyW','KeyS','Space','Escape'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.code==='Escape'){if(['racing','countdown'].includes(mode))pauseRace();else if(mode==='paused')resumeRace()}if(['ArrowUp','KeyW','Space'].includes(e.code))throttle=true;if(['ArrowDown','KeyS'].includes(e.code))braking=true;if(!sensorActive){if(['ArrowLeft','KeyA'].includes(e.code))steerTarget=-1;if(['ArrowRight','KeyD'].includes(e.code))steerTarget=1}});window.addEventListener('keyup',e=>{keys.delete(e.code);if(['ArrowUp','KeyW','Space'].includes(e.code))throttle=false;if(['ArrowDown','KeyS'].includes(e.code))braking=false;if(!sensorActive&&!['ArrowLeft','KeyA','ArrowRight','KeyD'].some(k=>keys.has(k)))steerTarget=0});
$('#start').addEventListener('click',()=>startRace(true));$('#practice').addEventListener('click',()=>startRace(false));$('#settingsButton').addEventListener('click',()=>openSettings('menu'));$('#pauseSettings').addEventListener('click',()=>openSettings('pause'));pauseButton.addEventListener('click',pauseRace);$('#resume').addEventListener('click',resumeRace);$('#restart').addEventListener('click',()=>startRace(sensorActive));$('#quit').addEventListener('click',goMenu);$('#again').addEventListener('click',()=>startRace(sensorActive));$('#resultsMenu').addEventListener('click',goMenu);$('#closeSettings').addEventListener('click',closeSettings);
$('#sensitivity').addEventListener('input',e=>{settings.sensitivity=Number(e.target.value);$('#sensitivityValue').textContent=`${settings.sensitivity}°`;sensorBaseline=null;saveSettings()});$('#sound').addEventListener('click',async()=>{settings.sound=!settings.sound;saveSettings();updateSettings();if(settings.sound)await audio.unlock();else audio.mute()});$('#haptics').addEventListener('click',()=>{settings.haptics=!settings.haptics;saveSettings();updateSettings();if(settings.haptics)haptic(18)});
let resetArmed=false,resetTimer=0;$('#reset').addEventListener('click',e=>{const b=e.currentTarget;if(!resetArmed){resetArmed=true;b.textContent='НАЖМИ ЕЩЁ РАЗ ДЛЯ СБРОСА';clearTimeout(resetTimer);resetTimer=setTimeout(()=>{resetArmed=false;b.textContent='СБРОСИТЬ РЕКОРДЫ'},3500);return}resetArmed=false;records={bestFinish:null,bestLapMs:null};saveRecords();b.textContent='РЕКОРДЫ СБРОШЕНЫ';setTimeout(()=>b.textContent='СБРОСИТЬ РЕКОРДЫ',1200)});
window.addEventListener('resize',resize);window.addEventListener('orientationchange',()=>{sensorBaseline=null;setTimeout(resize,120)});document.addEventListener('visibilitychange',()=>{if(document.hidden&&['racing','countdown'].includes(mode))pauseRace()});window.addEventListener('pagehide',()=>{saveSettings();saveRecords();audio.mute()});window.addEventListener('appdatareset',()=>{records={bestFinish:null,bestLapMs:null};Object.assign(settings,{sensitivity:22,sound:true,haptics:true});updateRecords();updateSettings();goMenu()});
createWorkshopMode({appName:'ПЕТЛЯ 17',version:VERSION,cachePrefix:'petlya-17-',storageNamespace:NS,onReset(){store.reset();window.dispatchEvent(new CustomEvent('appdatareset'))}});watchConnectivity(online=>document.documentElement.dataset.network=online?'online':'offline');
updateRecords();updateSettings();resize();bots=makeBots();requestAnimationFrame(frame);
