import * as T from './vendor/three.js';
import { installMobileRuntime } from '../../shared/mobile-runtime.js';
installMobileRuntime();
const $=s=>document.querySelector(s),canvas=$('#world'),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const KEY='pocket-works:inkbreak:progress';let saved={chapter:0,best:0,sound:true};
try{const p=JSON.parse(localStorage.getItem(KEY));if(p&&typeof p==='object'){saved.chapter=Math.max(0,Math.min(2,Number.isInteger(p.chapter)?p.chapter:0));saved.best=Math.max(0,Math.min(999999,Number(p.best)||0));saved.sound=p.sound!==false;}}catch{}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(saved));}catch{}}
let renderer,scene,camera,hero,meshData,world,roof,clock=new T.Clock(),soundContext;
let mode='menu',chapter=saved.chapter,wave=0,hp=5,score=0,kills=0,combo=0,comboTime=0,invulnerable=0,attackCD=0,dashCD=0,dashTime=0,freeze=0,trauma=0,elapsed=0,callTimer=0,advanceTimer=0;
let enemies=[],effects=[],bullets=[],marks=[],stick={x:0,z:0,id:null},keys=new Set(),facing=new T.Vector3(0,0,1),dashVector=new T.Vector3(),player=new T.Vector3(0,0,4),lastHud='';
const chapters=[{name:'НОЧНОЙ ТИРАЖ',caption:'Крыши типографии. Твои страницы у них.',color:0x758d87},{name:'ПОЛОСА ПРЕПЯТСТВИЙ',caption:'Наборщики вышли с дальнобойными перьями.',color:0x788795},{name:'ПОСЛЕДНЕЕ СЛОВО',caption:'Главный редактор ждёт тебя на крыше.',color:0x9b7f6c}];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const ink=0x202f32,paper=0xeee4cc,red=0xcb4535;
function material(color,vertices=false){const gradient=new T.DataTexture(new Uint8Array([72,160,238]),3,1,T.RedFormat);gradient.needsUpdate=true;gradient.minFilter=T.NearestFilter;gradient.magFilter=T.NearestFilter;const m=new T.MeshToonMaterial({color,gradientMap:gradient,vertexColors:vertices});m.onBeforeCompile=s=>{s.fragmentShader=s.fragmentShader.replace('#include <dithering_fragment>',`#include <dithering_fragment>
float d = length(mod(gl_FragCoord.xy, 5.0)-2.5);
float shade = dot(outgoingLight, vec3(.299,.587,.114));
if (d < .65 && shade < .72) gl_FragColor.rgb *= .72;`);};return m;}
const outlines=new T.MeshBasicMaterial({color:ink,side:T.BackSide});outlines.onBeforeCompile=s=>{s.vertexShader=s.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\n transformed += normal * .035;');};
function outlined(geometry,m){const g=new T.Group(),body=new T.Mesh(geometry,m),edge=new T.Mesh(geometry,outlines);g.add(edge,body);return g;}
const mats={paper:material(paper),ink:material(ink),red:material(red),roof:material(0xb4b6a1),wall:material(0xd0cab3),blue:material(0x768d8b),dark:material(0x425153)};
function block(x,y,z,w,h,d,m,parent=world){const g=outlined(new T.BoxGeometry(w,h,d),m);g.position.set(x,y,z);parent.add(g);return g;}
function label(text,w=4,h=1.1,color='#202f32',bg='#eee4cc'){const c=document.createElement('canvas');c.width=512;c.height=128;const ctx=c.getContext('2d');ctx.fillStyle=bg;ctx.fillRect(0,0,512,128);ctx.strokeStyle='#202f32';ctx.lineWidth=12;ctx.strokeRect(4,4,504,120);ctx.fillStyle=color;ctx.font='900 56px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,256,67);const tex=new T.CanvasTexture(c);const o=new T.Mesh(new T.PlaneGeometry(w,h),new T.MeshBasicMaterial({map:tex,side:T.DoubleSide}));return o;}
function city(){world=new T.Group();scene.add(world);roof=new T.Group();scene.add(roof);block(0,-.5,0,19,1,21,mats.wall,roof);block(0,.03,0,18.4,.12,20.4,mats.roof,roof);
// Roof seam marks and an oversized painted printing registration cross.
for(let x=-8;x<=8;x+=2)block(x,.103,0,.018,.015,20,mats.dark,roof);
for(let z=-9;z<=9;z+=2)block(0,.104,z,18,.015,.018,mats.dark,roof);
for(const x of [-9.2,9.2]){block(x,.3,0,.25,.6,21,mats.paper,roof);for(let z=-9;z<=9;z+=3)block(x,.68,z,.1,.76,.13,mats.ink,roof);block(x,1.04,0,.08,.08,20,mats.ink,roof);}
block(0,.25,-10.2,18.5,.5,.3,mats.paper,roof);block(0,.25,10.2,18.5,.5,.3,mats.paper,roof);
// Authored grouped rooftop props stay outside collision-free fighting floor.
for(let x of [-7.5,7.5])for(let z of [-7.5,7.5]){block(x,.4,z,1.1,.7,1.6,mats.dark,roof);block(x,.85,z,1.3,.16,1.8,mats.paper,roof);for(let a=-.5;a<=.5;a+=.22)block(x+a,.55,z+.81,.035,.37,.015,mats.ink,roof);}
block(-6.8,1.05,-9,2.6,2.1,1.8,mats.wall,roof);block(-6.8,2.13,-9,2.85,.14,2,mats.paper,roof);block(-6.8,.9,-8.08,.8,1.6,.04,mats.ink,roof);const sign=label('ТИПОГРАФИЯ',6,1.25);sign.position.set(0,.0,10.53);sign.rotation.x=-.1;roof.add(sign);
const registration=label('01 / ТУШЬ',3.7,.9);registration.rotation.x=-Math.PI/2;registration.position.set(0,.13,0);roof.add(registration);
let randomSeed=61;const rand=()=>{randomSeed=(randomSeed*1664525+1013904223)>>>0;return randomSeed/4294967296;};
for(let i=0;i<68;i++){let x=(rand()-.5)*90,z=(rand()-.5)*85;if(Math.abs(x)<13&&Math.abs(z)<14){x+=x<0?-21:21;}const w=3+rand()*5,d=3+rand()*4,h=5+rand()*15,y=-12+h/2;const m=[mats.paper,mats.wall,mats.blue][i%3];block(x,y,z,w,h,d,m);block(x,-12+h+.1,z,w+.3,.3,d+.3,mats.ink);for(let a=-w/2+.5;a<w/2;a+=1.25)for(let b=1;b<h-1;b+=2){block(x+a,-12+b,z+d/2+.025,.45,.72,.05,mats.dark);}for(let a=-d/2+.5;a<d/2;a+=1.5)for(let b=1;b<h-1;b+=2)block(x+w/2+.025,-12+b,z+a,.04,.72,.4,mats.dark);if(i%5===0){block(x,-12+h+1.2,z,.4,2.5,.4,mats.ink);}}
const billboard=label('НЕ МОЛЧИ',9,2.8,'#cb4535');billboard.position.set(17,3,-13);world.add(billboard);for(let x of [14,20])block(x,.8,-13,.12,4.4,.12,mats.ink);
}
// Batch the fixed architecture into a small material set: phone GPU cost scales
// with visible materials instead of thousands of individual window draw calls.
function batchStatic(group){
 group.updateMatrixWorld(true);const buckets=new Map(),remove=[];
 group.traverse(o=>{if(!o.isMesh||o.geometry.type!=='BoxGeometry')return;const id=o.material.uuid;if(!buckets.has(id))buckets.set(id,{material:o.material,positions:[],normals:[],uvs:[]});const b=buckets.get(id),geo=o.geometry.clone().applyMatrix4(o.matrixWorld).toNonIndexed();b.positions.push(...geo.attributes.position.array);b.normals.push(...geo.attributes.normal.array);b.uvs.push(...geo.attributes.uv.array);geo.dispose();remove.push(o);});
 for(const o of remove){o.parent.remove(o);o.geometry.dispose();}
 for(const b of buckets.values()){const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(b.positions,3));geo.setAttribute('normal',new T.Float32BufferAttribute(b.normals,3));geo.setAttribute('uv',new T.Float32BufferAttribute(b.uvs,2));scene.add(new T.Mesh(geo,b.material));}
}
function makeActor(enemy=false,boss=false){const geometry=new T.BufferGeometry();geometry.setAttribute('position',new T.Float32BufferAttribute(meshData.positions,3));geometry.setAttribute('normal',new T.Float32BufferAttribute(meshData.normals,3));let cols=meshData.colors;if(enemy){const transformed=[];for(let i=0;i<cols.length;i+=3){const c=cols[i]>.9?[.74,.73,.62]:cols[i]>.7?[.13,.23,.25]:[.065,.095,.10];transformed.push(...c);}cols=transformed;}geometry.setAttribute('color',new T.Float32BufferAttribute(cols,3));geometry.setAttribute('skinIndex',new T.Uint16BufferAttribute(meshData.skinIndices,4));geometry.setAttribute('skinWeight',new T.Float32BufferAttribute(meshData.skinWeights,4));const g=new T.Group(),skin=new T.SkinnedMesh(geometry,material(0xffffff,true)),bones=meshData.bones.map(b=>{const o=new T.Bone();o.name=b[0];o.position.fromArray(b[2]);return o;});bones.forEach((b,i)=>{const parent=meshData.bones[i][1];if(parent<0)skin.add(b);else bones[parent].add(b);});skin.bind(new T.Skeleton(bones));const edge=new T.SkinnedMesh(geometry,outlines);edge.bind(skin.skeleton,skin.bindMatrix);edge.frustumCulled=false;skin.frustumCulled=false;g.add(edge,skin);if(boss)g.scale.setScalar(1.7);else if(enemy)g.scale.setScalar(1.12);scene.add(g);
const mixer=new T.AnimationMixer(skin);const tracks=(data,times)=>Object.entries(data).map(([name,values])=>new T.NumberKeyframeTrack(`.bones[${name.split(':')[0]}].rotation[${name.split(':')[1]}]`,times,values));const clips={Idle:new T.AnimationClip('Idle',1.6,tracks({'chest:z':[0,.018,0],'head:y':[-.08,.08,-.08]},[0,.8,1.6])),Run:new T.AnimationClip('Run',.55,tracks({'armL:x':[-.6,.6,-.6],'armR:x':[.6,-.6,.6],'legL:x':[.6,-.6,.6],'legR:x':[-.6,.6,-.6],'cape:x':[-.2,-.42,-.2]},[0,.275,.55])),Attack:new T.AnimationClip('Attack',.38,tracks({'armR:x':[.3,-1.65,-1.1,0],'chest:y':[-.3,.6,.2,0],'cape:y':[.25,-.35,-.1,0]},[0,.07,.18,.38])),Hit:new T.AnimationClip('Hit',.25,tracks({'chest:x':[0,-.35,0]},[0,.07,.25]))};let current=null;const actions={};for(const [n,c]of Object.entries(clips)){actions[n]=mixer.clipAction(c);if(n==='Attack'||n==='Hit'){actions[n].setLoop(T.LoopOnce,1);actions[n].clampWhenFinished=true;}}const play=(name)=>{if(current===name&&actions[name].isRunning())return;const previous=actions[current];current=name;actions[name].reset().fadeIn(.06).play();previous?.fadeOut(.06);};play('Idle');const shadow=new T.Mesh(new T.CircleGeometry(boss?1.2:.65,20),new T.MeshBasicMaterial({color:ink,transparent:true,opacity:.20,depthWrite:false}));shadow.rotation.x=-Math.PI/2;shadow.position.y=.14;scene.add(shadow);return{g,skin,bones,mixer,play,shadow,animTime:0};}
function audio(kind){if(!saved.sound)return;try{soundContext??=new(window.AudioContext||window.webkitAudioContext)();soundContext.resume();const o=soundContext.createOscillator(),v=soundContext.createGain();o.type=kind==='hit'?'sawtooth':'triangle';o.frequency.setValueAtTime((kind==='hit'?110:kind==='dash'?310:520)*(0.88+Math.random()*.22),soundContext.currentTime);o.frequency.exponentialRampToValueAtTime(45,soundContext.currentTime+.11);v.gain.setValueAtTime(.055,soundContext.currentTime);v.gain.exponentialRampToValueAtTime(.001,soundContext.currentTime+.14);o.connect(v).connect(soundContext.destination);o.start();o.stop(soundContext.currentTime+.15);}catch{}}
function call(text,time=1){$('#callout').textContent=text;callTimer=time;}
function ripple(pos,color=red,size=1){const o=new T.Mesh(new T.RingGeometry(.8,1,36),new T.MeshBasicMaterial({color,transparent:true,opacity:.9,side:T.DoubleSide,depthWrite:false}));o.rotation.x=-Math.PI/2;o.position.copy(pos);o.position.y=.2;scene.add(o);effects.push({o,t:0,d:.35,size});}
function burst(pos){ripple(pos,red,2.5);for(let i=0;i<9;i++){const o=new T.Mesh(new T.PlaneGeometry(.13,.5),new T.MeshBasicMaterial({color:i%2?ink:red,side:T.DoubleSide}));o.position.copy(pos);o.position.y=1;const a=i/9*Math.PI*2;o.rotation.x=-Math.PI/2;o.rotation.z=a;scene.add(o);effects.push({o,t:0,d:.4,velocity:new T.Vector3(Math.sin(a)*5,2,Math.cos(a)*5)});}}
function clearObject(o){scene.remove(o);o.traverse?.(n=>{if(n.geometry)n.geometry.dispose();});}
function cleanFight(){enemies.forEach(e=>{clearObject(e.g);clearObject(e.shadow);clearObject(e.ring);});effects.forEach(e=>clearObject(e.o));bullets.forEach(b=>clearObject(b.o));marks.forEach(clearObject);enemies=[];effects=[];bullets=[];marks=[];}
function spawnWave(){wave++;advanceTimer=0;const count=chapter===2&&wave===3?1:3+chapter+wave;for(let i=0;i<count;i++){const boss=chapter===2&&wave===3,actor=makeActor(true,boss),angle=i/count*Math.PI*2+wave*.55;actor.g.position.set(Math.sin(angle)*6,.12,Math.cos(angle)*7-1);actor.shadow.position.set(actor.g.position.x,.14,actor.g.position.z);const ring=new T.Mesh(new T.RingGeometry(.88,1,48),new T.MeshBasicMaterial({color:red,transparent:true,opacity:0,side:T.DoubleSide,depthWrite:false}));ring.rotation.x=-Math.PI/2;scene.add(ring);enemies.push({...actor,hp:boss?14:chapter+2,boss,ranged:chapter>0&&i%3===0&&!boss,cooldown:1.3+i*.3,windup:0,stun:0,ring,attackTarget:new T.Vector3(),speed:boss?1.15:1.65+chapter*.18});}call(chapter===2&&wave===3?'ГЛАВНЫЙ РЕДАКТОР':`ПОЛОСА ${wave} / 3`,1.4);audio('start');}
function begin(){cleanFight();mode='play';hp=5;player.set(0,.12,4);facing.set(0,0,1);wave=0;kills=0;score=0;combo=0;comboTime=0;dashCD=0;attackCD=0;dashTime=0;invulnerable=1;freeze=0;trauma=0;advanceTimer=0;$('#menu').classList.add('hidden');$('#dialog').classList.add('hidden');$('#controls').classList.remove('hidden');$('#hud').classList.remove('hidden');scene.background=new T.Color(paper);spawnWave();hud();}
function hud(){const s=`${hp}:${chapter}:${wave}:${enemies.length}:${score}:${combo}:${mode}:${enemies.find(e=>e.boss)?.hp}`;if(s===lastHud)return;lastHud=s;$('#issue').textContent=`ВЫПУСК 0${chapter+1}`;$('#chapter').textContent=chapters[chapter].name;$('.health').setAttribute('aria-label',`Здоровье ${hp} из 5`);$('.health').querySelectorAll('i').forEach((e,i)=>e.classList.toggle('empty',i>=hp));$('#objective').textContent=enemies.some(e=>e.boss)?`Главный редактор: ${enemies[0].hp} ударов`:`Полоса ${wave} / 3 · Банда: ${enemies.length} · ${score} очков`;$('#combo').textContent=combo>1?`×${combo} КОМБО`:'';}
function dialog(kind){mode=kind;stick.x=stick.z=0;keys.clear();$('#controls').classList.add('hidden');$('#dialog').classList.remove('hidden');const copy={pause:['ТИРАЖ ПРИОСТАНОВЛЕН','Пауза.','Чернила подождут.','ПРОДОЛЖИТЬ ↗'],dead:['НЕ УШЛО В ПЕЧАТЬ','Зачёркнут.','Твоя история ещё не закончена. Попробуй другой ритм: замах, рывок, удар.','ПЕРЕПИСАТЬ ВЫПУСК ↗'],complete:['СТРАНИЦЫ ВЕРНУЛИСЬ',chapter===2?'Точка.': 'Продолжение следует.',chapter===2?`Тираж твой. Главный редактор уволен. ${score} очков.`:`${chapters[chapter].name}: ${score} очков. Следующая крыша уже ждёт.`,chapter===2?'НОВЫЙ ТИРАЖ ↗':'СЛЕДУЮЩИЙ ВЫПУСК ↗']}[kind];['#dialog-kicker','#dialog-title','#dialog-copy','#continue'].forEach((s,i)=>$(s).textContent=copy[i]);$('#restart').classList.toggle('hidden',kind!=='pause');}
function damage(){if(invulnerable>0||mode!=='play')return;hp--;combo=0;comboTime=0;invulnerable=1.15;trauma=.3;hero.play('Hit');hero.animTime=.25;burst(player);call('КЛЯКСА!',.5);audio('hit');hud();if(hp<=0)dialog('dead');}
function hit(e,power=1){if(e.hp<=0)return;e.hp-=power;e.stun=.4;e.windup=0;e.ring.material.opacity=0;e.g.position.addScaledVector(facing,.7);e.g.position.x=clamp(e.g.position.x,-8,8);e.g.position.z=clamp(e.g.position.z,-9,9);e.play('Hit');e.animTime=.25;burst(e.g.position);freeze=reduced?0:.045;trauma=reduced?0:.15;audio('hit');if(e.hp<=0){combo=comboTime>0?combo+1:1;comboTime=4;score+=100*combo;kills++;const mark=new T.Mesh(new T.CircleGeometry(.75,7),new T.MeshBasicMaterial({color:ink,transparent:true,opacity:.8}));mark.rotation.x=-Math.PI/2;mark.position.set(e.g.position.x,.15,e.g.position.z);scene.add(mark);marks.push(mark);clearObject(e.g);clearObject(e.shadow);clearObject(e.ring);enemies=enemies.filter(x=>x!==e);call(combo>1?`×${combo} — В ПЕЧАТЬ!`:'БАХ!',.7);if(!enemies.length)advanceTimer=1.1;}hud();}
function aim(){let near=null,dist=Infinity;for(const e of enemies){const d=player.distanceToSquared(e.g.position);if(d<dist){dist=d;near=e;}}if(near){facing.copy(near.g.position).sub(player);facing.y=0;facing.normalize();}return near;}
function attack(){if(mode!=='play'||attackCD>0)return;attackCD=.34;aim();hero.play('Attack');hero.animTime=.38;audio('attack');ripple(player,ink,1.6);let any=false;for(const e of [...enemies]){const delta=e.g.position.clone().sub(player);delta.y=0;const dist=delta.length();if(dist<(e.boss?3.5:3.05)&&delta.normalize().dot(facing)>-.15){hit(e);any=true;}}if(!any)call('SWISH',.25);}
function dash(){if(mode!=='play'||dashCD>0)return;let m=new T.Vector3(stick.x,0,stick.z);if(m.length()<.2){aim();m.copy(facing);}dashVector.copy(m).normalize();facing.copy(dashVector);dashTime=.22;dashCD=1.15;invulnerable=.38;hero.play('Attack');hero.animTime=.35;audio('dash');call('ШР-Р-Р!',.35);for(const e of enemies)e.dashHit=false;}
function shoot(e){const d=e.attackTarget.clone().sub(e.g.position);d.y=0;d.normalize();const o=outlined(new T.ConeGeometry(.16,.85,4),mats.ink);o.rotation.x=Math.PI/2;o.rotation.z=-Math.atan2(d.x,d.z);o.position.copy(e.g.position);o.position.y=.7;scene.add(o);bullets.push({o,d,t:0});}
function simulation(dt){elapsed+=dt;attackCD=Math.max(0,attackCD-dt);dashCD=Math.max(0,dashCD-dt);invulnerable=Math.max(0,invulnerable-dt);comboTime=Math.max(0,comboTime-dt);if(!comboTime)combo=0;$('#dash').disabled=dashCD>0;$('#dash').firstChild.textContent=dashCD>0?`${dashCD.toFixed(1)} c`:'РЫВОК';let mx=stick.x,mz=stick.z;if(keys.has('a')||keys.has('arrowleft'))mx--;if(keys.has('d')||keys.has('arrowright'))mx++;if(keys.has('w')||keys.has('arrowup'))mz--;if(keys.has('s')||keys.has('arrowdown'))mz++;const movement=new T.Vector3(mx,0,mz);if(movement.length()>1)movement.normalize();if(dashTime>0){dashTime-=dt;player.addScaledVector(dashVector,20*dt);ripple(player,red,.55);for(const e of [...enemies])if(!e.dashHit&&e.g.position.distanceTo(player)<(e.boss?2.6:1.65)){e.dashHit=true;hit(e,2);}}else{player.addScaledVector(movement,5.2*dt);if(movement.length()>.08)facing.copy(movement).normalize();}player.x=clamp(player.x,-8.1,8.1);player.z=clamp(player.z,-9.0,9.0);
hero.g.position.copy(player);hero.g.rotation.y=Math.atan2(facing.x,facing.z);hero.shadow.position.set(player.x,.14,player.z);hero.animTime=Math.max(0,hero.animTime-dt);if(hero.animTime===0)hero.play(movement.length()>.08?'Run':'Idle');hero.mixer.update(dt);hero.g.visible=invulnerable<=0||Math.floor(elapsed*14)%2===0||dashTime>0;
for(const e of [...enemies]){e.cooldown=Math.max(0,e.cooldown-dt);e.stun=Math.max(0,e.stun-dt);e.animTime=Math.max(0,e.animTime-dt);const delta=player.clone().sub(e.g.position);delta.y=0;const dist=delta.length(),dir=delta.normalize();e.g.rotation.y=Math.atan2(dir.x,dir.z);e.ring.position.set(e.g.position.x,.18,e.g.position.z);e.shadow.position.set(e.g.position.x,.14,e.g.position.z);
if(e.windup>0){e.windup-=dt;const radius=e.boss?4:e.ranged?1.2:2.2;e.ring.scale.setScalar(radius);e.ring.material.opacity=.65+Math.sin(elapsed*10)*.2;if(e.windup<=0){e.ring.material.opacity=0;e.cooldown=e.boss?1.8:e.ranged?2.4:1.4;e.play('Attack');e.animTime=.38;if(e.ranged)shoot(e);else{ripple(e.g.position,red,e.boss?5:2.4);if(dist<(e.boss?4.1:2.35))damage();}}}
else if(e.stun<=0){const range=e.boss?4:e.ranged?9:1.7;if(dist>range){e.g.position.addScaledVector(dir,e.speed*dt);if(!e.animTime)e.play('Run');}else if(e.cooldown===0){e.windup=e.boss?1:e.ranged?.9:.7;e.attackTarget.copy(player);e.play('Idle');}else if(!e.animTime)e.play('Idle');}
e.mixer.update(dt);}
// Prevent stacked enemies while preserving telegraphed stationary attacks.
for(let i=0;i<enemies.length;i++)for(let j=i+1;j<enemies.length;j++){const a=enemies[i],b=enemies[j],v=a.g.position.clone().sub(b.g.position);v.y=0;const n=v.length();if(n>0&&n<1.2){v.multiplyScalar((1.2-n)*.5/n);if(a.windup<=0)a.g.position.add(v);if(b.windup<=0)b.g.position.sub(v);}}
for(const b of [...bullets]){b.t+=dt;b.o.position.addScaledVector(b.d,7*dt);if(b.o.position.distanceTo(player)<.9){damage();b.t=5;}if(b.t>4){clearObject(b.o);bullets=bullets.filter(x=>x!==b);}}
if(advanceTimer>0){advanceTimer-=dt;if(advanceTimer<=0){if(wave<3)spawnWave();else{saved.best=Math.max(saved.best,score);saved.chapter=Math.max(saved.chapter,Math.min(2,chapter+1));persist();dialog('complete');}}}hud();}
function updateEffects(dt){for(const e of [...effects]){e.t+=dt;const p=e.t/e.d;if(e.velocity){e.o.position.addScaledVector(e.velocity,dt);e.velocity.y-=15*dt;e.o.rotation.z+=dt*4;}else{e.o.scale.setScalar(.3+p*(e.size||2));e.o.material.opacity=1-p;}if(e.t>=e.d){clearObject(e.o);effects=effects.filter(x=>x!==e);}}callTimer-=dt;if(callTimer<=0)$('#callout').textContent='';}
function publish(){window.__AI_TEST_STATE__={app:'inkbreak',ready:!!hero,mode,chapter,wave,hp,score,kills,enemies:enemies.map(e=>({x:e.g.position.x,z:e.g.position.z,hp:e.hp,boss:e.boss,windup:e.windup})),player:{x:player.x,z:player.z},dashCooldown:dashCD,attackCooldown:attackCD,savedChapter:saved.chapter};}
function frame(){requestAnimationFrame(frame);const dt=Math.min(.04,clock.getDelta());if(document.hidden||!renderer)return;freeze=Math.max(0,freeze-dt);if(mode==='play'&&freeze===0)simulation(dt);if(mode==='menu'){hero.g.visible=true;hero.g.position.set(0,.12,2);hero.g.rotation.y=-.4;hero.mixer.update(dt);}if(mode==='play'||mode==='menu')updateEffects(dt);trauma=Math.max(0,trauma-dt);const portrait=innerWidth<innerHeight,follow=mode==='menu'?new T.Vector3(portrait?0:-5,0,1):player.clone().multiplyScalar(.34);const desired=follow.clone().add(new T.Vector3(12,21,24));camera.position.lerp(desired,1-Math.exp(-dt*6));if(!reduced&&trauma>0){camera.position.x+=Math.sin(elapsed*91)*trauma;camera.position.y+=Math.cos(elapsed*77)*trauma;}camera.lookAt(follow);renderer.render(scene,camera);publish();}
function resize(){if(!renderer)return;const w=canvas.clientWidth,h=canvas.clientHeight;renderer.setSize(w,h,false);const a=w/h,span=a<1?12.2/a:19;camera.left=-span*a/2;camera.right=span*a/2;camera.top=span/2;camera.bottom=-span/2;camera.updateProjectionMatrix();stick.x=stick.z=0;}
function bind(){const nub=$('#stick i'),control=$('#stick');function reset(){stick.x=stick.z=0;stick.id=null;nub.style.transform='';}control.addEventListener('pointerdown',e=>{if(mode!=='play'||stick.id!==null)return;stick.id=e.pointerId;control.setPointerCapture(e.pointerId);update(e);});function update(e){if(stick.id!==e.pointerId)return;const r=control.getBoundingClientRect();let x=(e.clientX-r.left-r.width/2)/42,z=(e.clientY-r.top-r.height/2)/42;const n=Math.hypot(x,z);if(n>1){x/=n;z/=n;}stick.x=x;stick.z=z;nub.style.transform=`translate(${x*31}px,${z*31}px)`;}control.addEventListener('pointermove',update);for(const event of ['pointerup','pointercancel','lostpointercapture'])control.addEventListener(event,reset);$('#attack').addEventListener('pointerdown',e=>{e.preventDefault();attack();});$('#dash').addEventListener('pointerdown',e=>{e.preventDefault();dash();});addEventListener('keydown',e=>{if(e.target.closest('button,a,input'))return;const k=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();keys.add(k);if(k==='j'||k===' ')attack();if(k==='k'||k==='shift')dash();if(k==='escape'&&mode==='play')dialog('pause');});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));addEventListener('blur',()=>{reset();keys.clear();if(mode==='play')dialog('pause');});document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='play'){dialog('pause');soundContext?.suspend();}});$('#start').onclick=()=>{chapter=saved.chapter;begin();$('#start').blur();};$('#pause').onclick=()=>{if(mode==='play')dialog('pause');};$('#continue').onclick=()=>{if(mode==='pause'){mode='play';$('#dialog').classList.add('hidden');$('#controls').classList.remove('hidden');}else if(mode==='complete'){chapter=chapter===2?0:chapter+1;begin();}else begin();$('#continue').blur();};$('#restart').onclick=()=>begin();function toggle(){saved.sound=!saved.sound;persist();soundLabels();}$('#sound').onclick=toggle;$('#dialog-sound').onclick=toggle;soundLabels();if(saved.chapter>0){$('#start').innerHTML=`ПРОДОЛЖИТЬ — ВЫПУСК 0${saved.chapter+1} <b>↗</b>`;$('#menu-note').textContent='Тираж ещё не спасён. Вернись на следующую крышу.';}$('#record').textContent=saved.best?`ЛУЧШИЙ ТИРАЖ: ${saved.best} ОЧКОВ`:'';}
function soundLabels(){for(const s of ['#sound','#dialog-sound'])$(s).textContent=`Звук: ${saved.sound?'вкл':'выкл'}`;}
async function init(){try{renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.outputColorSpace=T.SRGBColorSpace;scene=new T.Scene();scene.background=new T.Color(paper);scene.fog=new T.Fog(paper,42,100);camera=new T.OrthographicCamera(-10,10,10,-10,.1,160);camera.position.set(12,21,24);scene.add(new T.HemisphereLight(0xfff3d9,0x596c72,2.4));const sun=new T.DirectionalLight(0xfff7dc,2.5);sun.position.set(-10,20,10);scene.add(sun);const response=await fetch('./assets/courier.json');if(!response.ok)throw new Error('Не удалось загрузить курьера.');meshData=await response.json();city();batchStatic(world);batchStatic(roof);hero=makeActor();hero.g.position.set(0,.12,2);bind();resize();addEventListener('resize',resize);canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();if(mode==='play')dialog('pause');$('#error-copy').textContent='Графический контекст прерван. Перезапуск вернёт тебя к сохранённому выпуску.';$('#error').classList.remove('hidden');});$('#loading').classList.add('hidden');$('#hud').classList.add('hidden');publish();frame();}catch(e){$('#loading').classList.add('hidden');$('#error-copy').textContent='Для этой истории нужен WebGL 2. '+e.message;$('#error').classList.remove('hidden');console.error(e);}}
init();
