import test from 'node:test';
import assert from 'node:assert/strict';
import {createState,step,clone,factions,SCENARIOS,POLICIES,METRICS,SHOCKS,shockAt,validState} from './model.js';
test('identical policies and shocks produce identical counterfactuals without mutation',()=>{let a=createState(),b=clone(a);const original=clone(a);step(a,'war');assert.deepEqual(a,original);for(let i=0;i<50;i++){const sh=shockAt(71342,i+1);a=step(a,sh);b=step(b,sh);}assert.deepEqual(a,b);});
test('education has delayed benefit and immediate cost',()=>{let a=createState(),b=clone(a);b.p.education=100;const aa=step(a),bb=step(b);assert.ok(bb.m.knowledge>aa.m.knowledge);assert.ok(bb.m.treasury<aa.m.treasury);assert.equal(bb.m.prosperity,aa.m.prosperity);assert.ok(bb.last.backlash>0);assert.equal(step(bb).last.backlash,0);});
test('reforming B does not alter A, results diverge under common shocks',()=>{let a=createState(),b=clone(a);b.p.education=80;b.p.liberty=75;for(let i=1;i<=20;i++){const sh=shockAt(71342,i);a=step(a,sh);b=step(b,sh);assert.equal(a.last.shock,b.last.shock);}assert.equal(a.p.education,20);assert.notDeepEqual(a.m,b.m);assert.ok(b.m.knowledge>a.m.knowledge);});
test('military spending mitigates invasion and welfare mitigates harvest loss',()=>{for(const [p,event] of [['army','war'],['welfare','harvest']]){const a=createState(),b=clone(a);a.p[p]=0;b.p[p]=100;const lossA=step(a,event).m.prosperity-step(a).m.prosperity,lossB=step(b,event).m.prosperity-step(b).m.prosperity;assert.ok(lossB>lossA);}});
test('every scenario and extreme policy remains finite, normalized and bounded over 250 years',()=>{for(const sc of SCENARIOS)for(const extreme of [0,100]){let s=createState(sc.id);for(const k of Object.keys(POLICIES))s.p[k]=extreme;for(let i=1;i<=250;i++){s=step(s,Object.keys(SHOCKS)[i%5]);assert.ok(validState(s));assert.ok(Math.abs(factions(s).reduce((n,f)=>n+f.power,0)-100)<1e-8);for(const k of Object.keys(METRICS)){assert.ok(Number.isFinite(s.m[k]));assert.ok(s.m[k]>=(k==='treasury'?-100:0)&&s.m[k]<=100);}}assert.equal(s.history.length,201);assert.equal(s.log.length,60);}});
test('corrupt state is rejected before rendering',()=>{for(const edit of [s=>s.p.tax='bad',s=>s.m.stability=null,s=>s.history=[],s=>s.last={before:{},terms:{}},s=>s.log=[{year:1,headline:'x',shock:'invalid',delta:0}]]){const s=createState();edit(s);assert.equal(validState(s),false);}assert.ok(validState(JSON.parse(JSON.stringify(step(createState(),'war')))));});
