// Deliberately fictional model. All coefficients are exposed here and in the model panel.
export const clamp=(x,a=0,b=100)=>Math.max(a,Math.min(b,x));
export const clone=x=>JSON.parse(JSON.stringify(x));
export const POLICIES={tax:['Налоговая нагрузка','Низкая','Высокая','Доход растёт до предела; чрезмерные налоги сжимают экономику.'],education:['Образование','Привилегия','Для всех','Дорого сейчас. Знания копятся годами и усиливают запрос на свободу.'],liberty:['Гражданские свободы','Цензура','Открытость','Поддержка горожан и учёных, недовольство старых элит.'],welfare:['Социальная защита','Каждый сам','Общий фонд','Снижает неравенство и напряжение, требует средств.'],army:['Военный бюджет','Минимум','Мобилизация','Защита от вторжения, влияние генералов и постоянные расходы.'],secular:['Светскость','Вера и трон','Светское право','Усиливает науку, ослабляет церковь и её поддержку.'],land:['Земельная реформа','Поместья','Распределение','Снижает неравенство и влияние знати; элиты сопротивляются.']};
export const METRICS={prosperity:['Достаток','#27786c','Условный индекс выпуска и благосостояния.'],knowledge:['Знания','#61799a','Накопленный запас образования и технологий.'],inequality:['Неравенство','#b57848','Чем выше, тем сильнее концентрация богатства.'],stability:['Устойчивость','#4f7652','Поддержка влиятельных групп и способность выдерживать кризисы.'],treasury:['Казна','#8d6d35','Резерв бюджета. Ниже нуля — долг, нижний предел −100.']};
export const SCENARIOS=[
{id:'crown',name:'Старый порядок',era:'Королевство на пороге перемен',desc:'Земля у знати, школы у церкви. У государства есть деньги, но мало причин меняться.',p:{tax:35,education:20,liberty:20,welfare:15,army:45,secular:15,land:10},m:{prosperity:46,knowledge:22,inequality:72,stability:64,treasury:65}},
{id:'port',name:'Республика купцов',era:'Богатство без равенства',desc:'Торговля процветает. Вопрос в том, сколько ещё большинство согласится обслуживать чужое процветание.',p:{tax:25,education:50,liberty:65,welfare:20,army:25,secular:70,land:35},m:{prosperity:72,knowledge:53,inequality:78,stability:54,treasury:45}},
{id:'barracks',name:'Государство-крепость',era:'Порядок под охраной',desc:'Генералы гарантируют стабильность. Они же выставляют счёт за её обслуживание.',p:{tax:55,education:30,liberty:10,welfare:30,army:85,secular:50,land:25},m:{prosperity:40,knowledge:35,inequality:55,stability:65,treasury:30}},
{id:'dawn',name:'Новая республика',era:'Свобода с пустой казной',desc:'Старый режим пал. Обещаний много, институты хрупкие, а бюджет не читает манифесты.',p:{tax:40,education:65,liberty:85,welfare:65,army:20,secular:80,land:70},m:{prosperity:40,knowledge:45,inequality:45,stability:40,treasury:10}}
];
export const SHOCKS={none:{name:'Спокойный год',desc:'Внешних потрясений нет.'},harvest:{name:'Неурожай',desc:'Падение достатка; социальная защита смягчает удар.'},war:{name:'Вторжение',desc:'Проверка армии, падение достатка и расходы на оборону.'},discovery:{name:'Научный прорыв',desc:'Рост знаний и достатка; эффект сильнее в образованной стране.'},panic:{name:'Торговый кризис',desc:'Падает достаток, казна теряет часть резервов.'}};
export function factions(s){const p=s.p,m=s.m;const raw=[
['nobles','Знать','Земля и наследство',28-.21*p.land+.08*m.inequality,85-.48*p.land-.23*p.liberty-.12*p.tax],
['clergy','Духовенство','Вера и авторитет',25-.20*p.secular,85-.58*p.secular-.12*p.liberty],
['merchants','Купцы','Прибыль и правила',12+.18*m.prosperity,43+.25*m.prosperity+.20*p.liberty-.40*p.tax],
['people','Общины','Хлеб и достоинство',14+.12*p.liberty+.09*p.land,40+.30*m.prosperity-.42*m.inequality+.25*p.welfare+.13*p.liberty-.14*p.tax],
['army','Офицеры','Бюджет и порядок',8+.23*p.army,35+.64*p.army-.16*p.liberty-(m.treasury<0?12:0)],
['scholars','Учёные','Знания и свобода',4+.16*m.knowledge,22+.38*p.liberty+.25*p.secular+.22*p.education]
];const total=raw.reduce((t,r)=>t+Math.max(3,r[3]),0);return raw.map(([id,name,motive,w,loyalty])=>({id,name,motive,power:Math.max(3,w)/total*100,loyalty:clamp(loyalty)}));}
export function createState(id='crown'){const scenario=SCENARIOS.find(x=>x.id===id)||SCENARIOS[0];const s={scenario:scenario.id,year:0,p:clone(scenario.p),enacted:clone(scenario.p),m:clone(scenario.m),history:[],log:[],last:null};s.history.push({year:0,...s.m});return s;}
export function shockAt(seed,year){let n=(seed^Math.imul(year,2654435761))>>>0;n^=n>>>16;n=Math.imul(n,2246822507)>>>0;const v=n%100;return v<55?'none':v<70?'harvest':v<82?'panic':v<92?'discovery':'war';}
export function step(state,shock='none'){
const s=clone(state),p=s.p,m=s.m,f=factions(s);const support=f.reduce((t,g)=>t+g.power*g.loyalty/100,0);const backlash=Object.keys(p).reduce((t,k)=>t+Math.abs(p[k]-s.enacted[k]),0)/70;
const terms={prosperity:[['Знания',m.knowledge*.045],['Свободный обмен',p.liberty*.012],['Износ экономики',-1.5],['Чрезмерные налоги',-Math.max(0,p.tax-40)*.06],['Военная нагрузка',-p.army*.018],['Нестабильность',-Math.max(0,50-m.stability)*.075],['Долг',-Math.max(0,-m.treasury)*.025]],knowledge:[['Школы',p.education*.042],['Светская наука',p.secular*.008],['Утрата знаний',-m.knowledge*.032]],inequality:[['Концентрация капитала',1.1+m.prosperity*.008],['Социальная защита',-p.welfare*.019],['Доступ к земле',-p.land*.018]],stability:[['Поддержка групп',(support-m.stability)*.13],['Социальный разрыв',-Math.max(0,m.inequality-55)*.032],['Запрос на свободу',-Math.max(0,m.knowledge-p.liberty-10)*.06],['Скорость реформ',-backlash],['Бюджетный кризис',-Math.max(0,-m.treasury)*.022]],treasury:[['Налоги',p.tax*.19*(.5+m.prosperity/100)*(1-p.tax/180)],['Администрация',-1.6],['Школы',-p.education*.023],['Социальный фонд',-p.welfare*.024],['Армия',-p.army*.024],['Проценты по долгу',-Math.max(0,-m.treasury)*.035]]};
if(shock==='harvest'){terms.prosperity.push(['Неурожай',-7+p.welfare*.04]);terms.stability.push(['Голод',-4+p.welfare*.025]);}
if(shock==='war'){terms.prosperity.push(['Вторжение',-Math.max(1,13-p.army*.12)]);terms.treasury.push(['Оборона',-8]);terms.stability.push(['Внешняя угроза',-Math.max(0,8-p.army*.09)]);}
if(shock==='discovery'){terms.knowledge.push(['Прорыв',3+p.education*.03]);terms.prosperity.push(['Новые технологии',2+m.knowledge*.035]);}
if(shock==='panic'){terms.prosperity.push(['Торговый кризис',-6]);terms.treasury.push(['Спасение торговли',-5]);}
const before=clone(m);for(const k of Object.keys(METRICS)){m[k]=clamp(m[k]+terms[k].reduce((t,x)=>t+x[1],0),k==='treasury'?-100:0,100);}
s.year++;s.enacted=clone(p);s.last={terms,before,shock,support,backlash};s.history.push({year:s.year,...m});if(s.history.length>201)s.history.shift();
const strongest=f.filter(g=>g.loyalty<40).sort((a,b)=>b.power-a.power)[0];let headline=m.stability<25?'Институты трещат':m.treasury<0?'Государство живёт в долг':strongest?`${strongest.name}: растёт сопротивление`:m.prosperity>70?'Полоса процветания':'Хрупкое равновесие';s.log.unshift({year:s.year,headline,shock,delta:m.prosperity-before.prosperity});s.log=s.log.slice(0,60);return s;
}
export function validState(s){return s&&SCENARIOS.some(x=>x.id===s.scenario)&&Number.isInteger(s.year)&&s.year>=0&&s.year<=10000&&['p','enacted'].every(obj=>s[obj]&&Object.keys(POLICIES).every(k=>Number.isFinite(s[obj][k])&&s[obj][k]>=0&&s[obj][k]<=100))&&s.m&&Object.keys(METRICS).every(k=>Number.isFinite(s.m[k])&&s.m[k]>=(k==='treasury'?-100:0)&&s.m[k]<=100)&&(!s.last||(s.last.before&&Object.keys(METRICS).every(k=>Number.isFinite(s.last.before[k]))&&s.last.terms&&Object.keys(METRICS).every(k=>Array.isArray(s.last.terms[k])&&s.last.terms[k].every(t=>Array.isArray(t)&&typeof t[0]==='string'&&Number.isFinite(t[1])))&&Object.hasOwn(SHOCKS,s.last.shock)))&&Array.isArray(s.history)&&s.history.length>0&&s.history.length<=201&&s.history.every(r=>Number.isInteger(r.year)&&Object.keys(METRICS).every(k=>Number.isFinite(r[k])))&&Array.isArray(s.log)&&s.log.length<=60&&s.log.every(r=>Number.isInteger(r.year)&&typeof r.headline==='string'&&Object.hasOwn(SHOCKS,r.shock)&&Number.isFinite(r.delta));}
