import { installMobileRuntime } from '../../shared/mobile-runtime.js';
installMobileRuntime();

const $ = (id) => document.getElementById(id);
const canvas = $('battle'), ctx = canvas.getContext('2d', { alpha:false });
const COLS=8, ROWS=10, KEY='horugvi-campaign-v1:save', SAVE_VERSION=1;
const P={ink:'#3f3c2c',gold:'#d3b36f',red:'#a3493a',blue:'#486d79',paper:'#e4d0a4',grass:'#93a476'};
const SCENES=[
  {title:'У БРОДА',book:'КНИГА ПЕРВАЯ',eyebrow:'I · ПЕРЕПРАВА',name:'На рассвете у брода',description:'За рекой показались чужие стяги. Удержите оба брода до седьмого хода. Не дайте разбить знамя воеводы.',objective:'Удерживайте брод · 7 ходов',limit:7,goal:'survive',theme:0,woods:[[1,1],[6,2],[0,6],[6,7]],hills:[[4,6],[5,6]],village:[[7,8]],road:[[3,0],[3,1],[3,2],[3,3],[3,4],[3,5],[3,6],[3,7],[3,8],[3,9]],
   allies:[['general',3,8],['spears',3,6],['archers',1,7],['cavalry',6,7]],enemies:[['spears',3,1],['cavalry',6,1],['archers',2,2],['spears',5,2]]},
  {title:'ЛЕСНОЙ ОБОЗ',book:'КНИГА ВТОРАЯ',eyebrow:'II · ЗАСАДА',name:'Случай на лесной дороге',description:'В обозе врага — жалованье его наёмников. Доберитесь до повозки с чёрной печатью прежде девятого хода.',objective:'Захватите обоз · до IX хода',limit:9,goal:'cart',theme:1,woods:[[1,1],[2,1],[1,3],[3,3],[5,4],[1,6],[6,6],[4,8]],hills:[[4,2],[7,5]],village:[[6,1]],cart:[6,2],road:[[0,8],[1,7],[2,6],[3,5],[4,4],[5,3],[6,2],[7,1]],
   allies:[['general',1,8],['spears',2,7],['archers',0,6],['cavalry',3,8]],enemies:[['spears',5,2],['spears',6,3],['archers',5,1],['cavalry',7,4]]},
  {title:'КОРОННЫЙ ХОЛМ',book:'КНИГА ТРЕТЬЯ',eyebrow:'III · РАЗВЯЗКА',name:'Поле коронного холма',description:'На холме возвышается последняя вражеская хоругвь. Возьмите высоту и удержите её два хода подряд — или обратите неприятеля в бегство.',objective:'Держите холм · 2 хода',limit:11,goal:'hill',theme:2,woods:[[1,2],[6,3],[0,5],[6,7]],hills:[[3,4],[4,4],[3,5],[4,5],[2,4]],village:[[7,1]],road:[[3,9],[3,8],[3,7],[3,6],[3,5],[3,4],[3,3],[3,2],[3,1],[3,0]],
   allies:[['general',3,8],['spears',2,7],['spears',5,8],['archers',1,8],['cavalry',6,7]],enemies:[['general',4,1],['spears',3,3],['spears',5,3],['archers',2,2],['cavalry',6,2]]}
];
const UNIT={general:{name:'Хоругвь воеводы',men:82,morale:96,speed:1,range:1,power:12},spears:{name:'Копейщики',men:90,morale:85,speed:1,range:1,power:14},archers:{name:'Лучники',men:62,morale:76,speed:1,range:3,power:13},cavalry:{name:'Конные дружинники',men:68,morale:90,speed:2,range:1,power:17}};
const NAMES={ally:{general:'Воевода Мирослав',spears:'Дружина копейщиков',archers:'Земские лучники',cavalry:'Конная сотня'},enemy:{general:'Чёрная хоругвь',spears:'Вражеские копья',archers:'Наёмные стрелки',cavalry:'Вражеская конница'}};
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const distance=(a,b)=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y);
const seedRandom=(seed)=>()=>{seed=(Math.imul(seed,1664525)+1013904223)|0;return (seed>>>0)/4294967296};
let state, screen='intro', mode=null, panelMode='intro', sound=false, suspended=false, selected=null, anim=null, fieldCache=null, w=320,h=440,dpr=1,lastFrame=0,toastTimeout=0,audio=null;
const safeRead=()=>{try{const x=JSON.parse(localStorage.getItem(KEY));if(x&&x.v===SAVE_VERSION&&Number.isInteger(x.scene)&&x.scene>=0&&x.scene<SCENES.length&&Array.isArray(x.units)&&x.units.every(u=>Number.isInteger(u.x)&&u.x>=0&&u.x<8&&Number.isInteger(u.y)&&u.y>=0&&u.y<10)&&x.units.length<=20&&['play','interlude','complete','defeat'].includes(x.screen))return x;}catch{}return null};
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify({v:SAVE_VERSION,screen,stateMarker:screen,scene:state.scene,round:state.round,units:state.units,ordersLeft:state.ordersLeft,hillTurns:state.hillTurns||0,wounds:state.wounds||0,sound,screen:['menu','confirm','intro'].includes(screen)?'play':screen}))}catch{}};
function makeScene(i,wounds=0){const sc=SCENES[i],rand=seedRandom(671+i*109),units=[];for(const side of ['ally','enemy']){const arr=side==='ally'?sc.allies:sc.enemies;arr.forEach(([type,x,y],j)=>{const base=UNIT[type],isAlly=side==='ally';units.push({id:`${side[0]}${j}`,side,type,x,y,px:x,py:y,facing:isAlly?-1:1,men:base.men-(isAlly?Math.min(14,wounds*2):0),maxMen:base.men,morale:base.morale-(isAlly?Math.min(10,wounds):8+Math.floor(rand()*10)),order:{type:'hold'},pending:null,rout:0,flash:0});});}return {scene:i,round:1,units,ordersLeft:2,hillTurns:0,wounds,log:'Коснитесь синего знамени.'}}
function enterPlay(i,wounds=0){state=makeScene(i,wounds);screen='play';selected=state.units.find(u=>u.side==='ally')?.id||null;mode=null;anim=null;fieldCache=null;hidePanel();save();updateUI();}
function showPanel(kind,eyebrow,title,copy,buttons){panelMode=kind;const ov=$('overlay');ov.classList.remove('hidden');$('panelEyebrow').textContent=eyebrow;$('panelTitle').textContent=title;$('panelCopy').textContent=copy;const area=$('panelActions');area.replaceChildren();for(const b of buttons){const el=document.createElement('button');el.type='button';el.textContent=b.label;el.className=b.secondary?'secondary':'';el.addEventListener('click',()=>{tone(392,.04);b.fn()});area.append(el);}screen=kind==='pause'||kind==='confirm'?'menu':kind;save();updateUI()}
function hidePanel(){screen='play';$('overlay').classList.add('hidden');save();updateUI()}
function intro(){const prior=safeRead();if(prior){sound=!!prior.sound;state={scene:prior.scene,round:prior.round,units:prior.units,ordersLeft:prior.ordersLeft,hillTurns:prior.hillTurns||0,wounds:prior.wounds||0,log:'Летопись сохранила ваши приказы.'};screen=prior.screen==='play'?'intro':prior.screen;selected=state.units.find(u=>u.side==='ally'&&u.men>0)?.id||null;fieldCache=null;if(prior.screen==='interlude'){
 showPanel('interlude','ПОБЕДА · КНИГА ЗАКРЫТА','Сражение выиграно','Победа уже записана в летопись. Впереди следующая книга.',[{label:'Следующая книга →',fn:()=>enterPlay(state.scene+1,state.wounds)},{label:'Новая летопись',secondary:true,fn:askRestart}]);
 }else if(prior.screen==='complete'){
 showPanel('complete','III · ПОСЛЕДНЯЯ ЗАПИСЬ','Знамёна стоят','Все три книги завершены. Следующая летопись может быть иной.',[{label:'Начать новую летопись →',fn:()=>enterPlay(0)}]);
 }else if(prior.screen==='defeat'){
 showPanel('defeat','ЛЕТОПИСЬ ПРЕРВАНА','Хоругвь пала','Поле битвы осталось за врагом. Вы можете переписать этот исход.',[{label:'Повторить битву →',fn:()=>enterPlay(state.scene,state.wounds)},{label:'Новая летопись',secondary:true,fn:askRestart}]);
 }else showPanel('intro','ЛЕТОПИСЬ О ВОЙНЕ','Хоругви',`Книга ${state.scene+1}. Ваши отряды всё ещё ждут приказов.`,[{label:'Продолжить битву →',fn:()=>hidePanel()},{label:'Новая летопись',secondary:true,fn:()=>askRestart()}]);}else{state=makeScene(0);selected=null;screen='intro';showPanel('intro','ЛЕТОПИСЬ О ВОЙНЕ','Хоругви','Гонец прибыл на рассвете. Четыре хоругви ждут приказов. На исход битвы влияют не только мечи, но и страх.',[{label:'Открыть первую книгу →',fn:()=>enterPlay(0)}]);}updateUI()}
function askRestart(){showPanel('confirm','НАЧАТЬ ЗАНОВО','Зачеркнуть летопись?','Новый поход сотрёт сохранённые битвы. Это действие нельзя отменить.',[{label:'Да, новая летопись',fn:()=>enterPlay(0)},{label:'Оставить как есть',secondary:true,fn:()=>pause()}])}
function pause(){showPanel('pause','КНИГА ПРИКАЗОВ','Передышка',`Книга ${state.scene+1}, ход ${state.round}. Два новых приказа за ход; старые действуют, пока их не заменят.`,[{label:'Вернуться на поле →',fn:()=>hidePanel()},{label:sound?'Звук: включён':'Звук: выключен',secondary:true,fn:()=>{sound=!sound;save();pause()}},{label:'Начать заново',secondary:true,fn:askRestart}])}
function getUnit(id){return state.units.find(u=>u.id===id&&u.men>0&&u.rout===0)}
function alive(side){return state.units.filter(u=>u.side===side&&u.men>0&&u.rout===0)}
function toRoman(n){return ['','I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII'][n]||String(n)}
function updateUI(){const sc=SCENES[state.scene];$('scenarioName').textContent=sc.title;$('chapter').textContent=sc.book;$('roundLabel').textContent=`ХОД ${toRoman(state.round)} / ${toRoman(sc.limit)}`;$('objective').textContent=sc.objective;$('ordersCount').textContent=`${state.ordersLeft}/2`;const u=getUnit(selected);$('unitName').textContent=u?NAMES[u.side][u.type]:'Выберите хоругвь';$('unitDetail').textContent=u?`${u.men} воинов · дух ${u.morale}% · ${describeOrder(u)}`:'Коснитесь синего знамени';const playable=screen==='play'&&!anim;for(const btn of document.querySelectorAll('.orders button')){btn.disabled=!playable||!u||u.side!=='ally'||state.ordersLeft<=0;btn.classList.toggle('active',mode===btn.dataset.command)}$('endTurn').disabled=!playable;$('hint').textContent=state.log||'Выберите войско, чтобы отдать приказ.'}
function describeOrder(u){if(u.pending)return 'гонец в пути';const type=u.order?.type;return ({hold:'держит строй',move:'в походе',attack:'наступает',rally:'перестраивается'})[type]||'ожидает'}
function toast(message){clearTimeout(toastTimeout);const el=$('fieldToast');el.textContent=message;el.classList.add('show');toastTimeout=setTimeout(()=>el.classList.remove('show'),1800)}
function feedback(message){state.log=message;toast(message);updateUI()}
function playTone(freq,dur=.12){if(!sound)return;try{audio=audio||new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),gain=audio.createGain();o.type='triangle';o.frequency.value=freq;gain.gain.setValueAtTime(.025,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+dur);o.connect(gain).connect(audio.destination);o.start();o.stop(audio.currentTime+dur)}catch{}}
function tone(freq,dur){playTone(freq,dur)}
function issue(order){const u=getUnit(selected);if(!u||u.side!=='ally'||state.ordersLeft<=0||screen!=='play'||anim)return;const general=alive('ally').find(x=>x.type==='general');if(general&&distance(u,general)>3&&u.id!==general.id){u.pending={order,turns:1};feedback('Гонец несёт приказ. Прибудет через ход.')}else{u.order=order;u.pending=null;feedback(order.type==='hold'?'Знамя останется на месте.':order.type==='rally'?'Отряд перестроится в конце хода.':order.type==='attack'?'Приказ наступать передан.':'Отряд выступит в поход.')}state.ordersLeft--;mode=null;save();updateUI();tone(270,.07)}
function selectCommand(type){const u=getUnit(selected);if(!u||u.side!=='ally'||state.ordersLeft<=0)return;if(type==='hold'||type==='rally'){issue({type});return}mode=mode===type?null:type;feedback(mode==='move'?'Коснитесь места на поле.':mode==='attack'?'Коснитесь неприятельского отряда.':'Выберите действие.');updateUI()}
function onBoardTap(evt){if(screen!=='play'||anim)return;const r=canvas.getBoundingClientRect();const x=(evt.clientX-r.left)*w/r.width, y=(evt.clientY-r.top)*h/r.height;const tile=coordinates(x,y);const tapped=state.units.filter(u=>u.men>0&&u.rout===0).sort((a,b)=>distPixel(a,x,y)-distPixel(b,x,y)).find(u=>distPixel(u,x,y)<Math.max(24,Math.min(cellSize().x,cellSize().y)*.58));if(mode&&getUnit(selected)&&state.ordersLeft>0){if(mode==='attack'){if(tapped?.side!=='enemy'){feedback('Укажите вражескую хоругвь.');return}issue({type:'attack',target:tapped.id});return}if(mode==='move'){if(!tile||!passable(tile.x,tile.y)){feedback('Сюда войско не пройдёт.');return}issue({type:'move',x:tile.x,y:tile.y});return}}
if(tapped?.side==='ally'){selected=tapped.id;mode=null;state.log=describeOrder(tapped);updateUI();tone(480,.025)}else if(tapped?.side==='enemy'){selected=tapped.id;mode=null;state.log=`Неприятель: ${tapped.men} бойцов, дух ${tapped.morale}%.`;updateUI()}else{selected=null;mode=null;state.log='Выберите своё знамя.';updateUI()}}
function cellSize(){return{x:(w-30)/COLS,y:(h-32)/ROWS}}
function pixel(x,y){const c=cellSize();return{x:15+(x+.5)*c.x,y:16+(y+.5)*c.y}}
function coordinates(x,y){const c=cellSize();const tx=Math.floor((x-15)/c.x),ty=Math.floor((y-16)/c.y);return tx>=0&&tx<COLS&&ty>=0&&ty<ROWS?{x:tx,y:ty}:null}
function distPixel(u,x,y){const p=pixel(u.x,u.y);return Math.hypot(p.x-x,p.y-y)}
function terrain(x,y){const sc=SCENES[state.scene];if(x<0||y<0||x>=COLS||y>=ROWS)return 'void';if(sc.theme===0&&y===4)return x===3||x===6?'bridge':'river';if(sc.hills.some(v=>v[0]===x&&v[1]===y))return 'hill';if(sc.woods.some(v=>v[0]===x&&v[1]===y))return 'wood';if(sc.village.some(v=>v[0]===x&&v[1]===y))return 'village';if(sc.road.some(v=>v[0]===x&&v[1]===y))return 'road';return 'field'}
function passable(x,y){const t=terrain(x,y);return t!=='void'&&t!=='river'}
function paths(from,to,type){if(!to||!passable(to.x,to.y))return[];const start=`${from.x},${from.y}`,goal=`${to.x},${to.y}`;let frontier=[{x:from.x,y:from.y}],dist={[start]:0},prev={};const key=(p)=>`${p.x},${p.y}`;while(frontier.length){frontier.sort((a,b)=>dist[key(a)]-dist[key(b)]+(Math.abs(a.x-to.x)+Math.abs(a.y-to.y))*.65-(Math.abs(b.x-to.x)+Math.abs(b.y-to.y))*.65);const p=frontier.shift(),pk=key(p);if(pk===goal)break;for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const n={x:p.x+dx,y:p.y+dy};if(!passable(n.x,n.y))continue;let cost=terrain(n.x,n.y)==='wood'?(type==='cavalry'?3:1.65):1;cost+=terrain(n.x,n.y)==='hill'?.25:0;const nk=key(n),g=dist[pk]+cost;if(dist[nk]===undefined||g<dist[nk]){dist[nk]=g;prev[nk]=p;frontier.push(n)}}}if(!prev[goal])return[];const a=[];let k=goal;while(k!==start&&prev[k]){const [x,y]=k.split(',').map(Number);a.unshift({x,y});k=key(prev[k])}return a}
function nearestTarget(u,side){let goals=alive(side);if(!goals.length)return null;goals.sort((a,b)=>distance(a,u)-distance(b,u)+(a.type==='archers'?-1:0)-(b.type==='archers'?-1:0));return goals[0]}
function enemyOrders(){for(const e of alive('enemy')){let t=nearestTarget(e,'ally');if(!t)continue;if(e.type==='archers'){const targets=alive('ally').filter(u=>distance(u,e)<=3);if(targets.length){targets.sort((a,b)=>distance(a,e)-distance(b,e));t=targets[0]}}
 e.order={type:'attack',target:t.id};if(e.morale<38&&e.type!=='general')e.order={type:'hold'}}}
function resolve(){if(screen!=='play'||anim)return;mode=null;const previous=Object.fromEntries(state.units.map(u=>[u.id,{x:u.x,y:u.y,men:u.men,morale:u.morale}]));state.round++;enemyOrders();const occupied=()=>new Set(state.units.filter(u=>u.men>0&&u.rout===0).map(u=>`${u.x},${u.y}`));
 // Delayed messengers arrive at the start of resolution; the old order still governed movement this turn.
 for(const u of alive('ally')){if(u.pending){u.pending.turns--;if(u.pending.turns<=0){u.nextOrder=u.pending.order;u.pending=null}}}
 const orderUnits=[...alive('ally'),...alive('enemy')].sort((a,b)=>((a.type==='cavalry'?0:1)-(b.type==='cavalry'?0:1))||(a.id<b.id?-1:1));
 for(const u of orderUnits){u.px=u.x;u.py=u.y;u.flash=0;if(u.order?.type==='rally'||u.order?.type==='hold')continue;let goal=null;const order=u.order||{type:'hold'};if(order.type==='move')goal={x:order.x,y:order.y};if(order.type==='attack'){const t=getUnit(order.target)||nearestTarget(u,u.side==='ally'?'enemy':'ally');if(t){if(distance(u,t)>UNIT[u.type].range)goal={x:t.x,y:t.y};else continue}}
 if(!goal)continue;let steps=paths(u,goal,u.type);let left=UNIT[u.type].speed;while(steps.length&&left-->0){let next=steps.shift();if(!passable(next.x,next.y))break;if(occupied().has(`${next.x},${next.y}`))break;u.facing=next.x>u.x?1:next.x<u.x?-1:next.y>u.y?1:-1;u.x=next.x;u.y=next.y;u.flash=-1;if(terrain(next.x,next.y)==='wood'&&u.type==='cavalry')break}
 if(order.type==='move'&&u.x===goal.x&&u.y===goal.y)u.order={type:'hold'} }
 // Resolve engagements after movement. One unit strikes once per turn. Defender may answer during its own attack.
 const attacks=[];for(const u of [...alive('ally'),...alive('enemy')]){const foes=alive(u.side==='ally'?'enemy':'ally');const range=UNIT[u.type].range;let options=foes.filter(e=>Math.abs(e.x-u.x)+Math.abs(e.y-u.y)<=range);if(!options.length)continue;const intended=getUnit(u.order?.target);options.sort((a,b)=>Number(b.id===intended?.id)-Number(a.id===intended?.id)||distance(a,u)-distance(b,u)||a.morale-b.morale);let target=options[0];if(!target)continue;
 // Holders retaliate in melee, archers shoot at range, all orders can collide into combat.
 const melee=distance(u,target)===1;let power=UNIT[u.type].power*(u.men/u.maxMen*.5+.5);const flank=(target.facing!==0&&Math.sign(u.x-target.x)===-target.facing&&Math.abs(u.x-target.x)>0);if(flank)power*=1.32;if(terrain(u.x,u.y)==='hill')power*=1.18;if(terrain(target.x,target.y)==='hill')power*=.8;if(u.type==='spears'&&target.type==='cavalry'&&melee)power*=1.42;if(u.type==='cavalry'&&u.flash===-1&&melee&&terrain(u.x,u.y)!=='wood')power*=1.5;if(u.type==='archers'&&melee)power*=.58;if(u.order?.type==='hold'&&u.type==='spears')power*=1.13;
 const variability=.87+((state.round*7+u.x*3+target.y+u.id.charCodeAt(1))%7)*.04;const harm=Math.max(3,Math.round(power*variability));attacks.push({from:u.id,to:target.id,harm,morale:Math.round(harm*(flank?1.5:.85)+(u.type==='cavalry'&&u.flash===-1?7:0)),flank});}
 let moraleShocks=0;for(const a of attacks){const t=state.units.find(u=>u.id===a.to);if(!t||t.men<=0)continue;t.men=Math.max(0,t.men-a.harm);t.morale=clamp(t.morale-a.morale,0,100);t.flash=1;if(a.flank)moraleShocks++}
 for(const u of state.units){if(u.men<=0||u.morale<=18){u.rout++;if(u.rout>=1){u.men=0;for(const friend of state.units.filter(v=>v.side===u.side&&v.id!==u.id&&v.men>0&&distance(v,u)<=2))friend.morale=Math.max(0,friend.morale-9)}}else if(u.order?.type==='rally'){u.morale=Math.min(100,u.morale+21);u.order={type:'hold'}}else if(u.order?.type==='hold'&&u.flash!==1)u.morale=Math.min(100,u.morale+5);if(u.nextOrder){u.order=u.nextOrder;delete u.nextOrder}}
 state.ordersLeft=2;state.log=moraleShocks?'Фланговый удар поколебал ряды.':attacks.length?'Войска сошлись в схватке.':'Знамёна двинулись по полю.';
 const end=battleResult();const after=()=>{if(end)finish(end);else{save();updateUI()}};anim={start:performance.now(),duration:window.matchMedia('(prefers-reduced-motion: reduce)').matches?80:800,previous,after};save();updateUI();tone(attacks.length?180:310,.13)}
function battleResult(){const sc=SCENES[state.scene],a=alive('ally'),e=alive('enemy');if(!a.some(u=>u.type==='general')||!a.length)return 'defeat';if(!e.length)return 'victory';if(sc.goal==='survive'&&state.round>sc.limit)return 'victory';if(sc.goal==='cart'&&a.some(u=>distance(u,{x:sc.cart[0],y:sc.cart[1]})<=1))return 'victory';if(sc.goal==='hill'){const allies=a.filter(u=>[3,4].includes(u.x)&&[4,5].includes(u.y));const enemies=e.filter(u=>[3,4].includes(u.x)&&[4,5].includes(u.y));state.hillTurns=allies.length>enemies.length&&allies.length?state.hillTurns+1:0;if(state.hillTurns>=2)return 'victory'}if(state.round>sc.limit)return 'defeat';return null}
function finish(result){anim=null;mode=null;selected=null;const i=state.scene;if(result==='victory'){const wounds=state.wounds+state.units.filter(u=>u.side==='ally'&&u.men===0).length;state.wounds=wounds;if(i===SCENES.length-1){screen='complete';showPanel('complete','III · ПОСЛЕДНЯЯ ЗАПИСЬ','Знамёна стоят','Три боя пережиты. Не хронисты, а ваши решения определили, кто вернулся домой.',[{label:'Сыграть новую летопись →',fn:()=>enterPlay(0)}]);}else{screen='interlude';showPanel('interlude','ПОБЕДА · КНИГА ЗАКРЫТА',i===0?'Брод удержан':'Обоз захвачен',i===0?'К вечеру переправа осталась за вами. За лесом ещё слышны чужие трубы.':'На дороге остались брошенные мешки с серебром. Теперь путь ведёт к коронному холму.',[{label:'Следующая книга →',fn:()=>enterPlay(i+1,wounds)},{label:'Повторить сражение',secondary:true,fn:()=>enterPlay(i,state.wounds)}]);}}else{screen='defeat';showPanel('defeat','ЛЕТОПИСЬ ПРЕРВАНА','Хоругвь пала','Знамя воеводы повержено или время вышло. Перепишите исход этого боя.',[{label:'Повторить битву →',fn:()=>enterPlay(i,state.wounds)},{label:'Новая летопись',secondary:true,fn:askRestart}]);}save()}
function pointerStart(evt){if(evt.button!==0)return;canvas._pointer={id:evt.pointerId,x:evt.clientX,y:evt.clientY};try{canvas.setPointerCapture(evt.pointerId)}catch{}}
function pointerEnd(evt){const p=canvas._pointer;if(!p||p.id!==evt.pointerId)return;canvas._pointer=null;if(Math.hypot(evt.clientX-p.x,evt.clientY-p.y)<12)onBoardTap(evt)}
canvas.addEventListener('pointerdown',pointerStart);canvas.addEventListener('pointerup',pointerEnd);canvas.addEventListener('pointercancel',()=>canvas._pointer=null);
for(const btn of document.querySelectorAll('.orders button'))btn.addEventListener('click',()=>selectCommand(btn.dataset.command));
$('endTurn').addEventListener('click',resolve);$('menuBtn').addEventListener('click',()=>{if(screen==='play'&&!anim)pause();else if(screen==='menu')hidePanel()});
document.addEventListener('visibilitychange',()=>{suspended=document.hidden;save();if(!suspended)requestAnimationFrame(frame)});window.addEventListener('pagehide',save);

// Illuminated manuscript landscape. Cached static painting; the living banners remain on a separate layer.
function createField(){const off=document.createElement('canvas');off.width=Math.max(1,Math.round(w*dpr));off.height=Math.max(1,Math.round(h*dpr));const g=off.getContext('2d');g.setTransform(dpr,0,0,dpr,0,0);drawGround(g);return off}
function polygon(g,points,fill,stroke=null,width=1){g.beginPath();points.forEach(([x,y],i)=>i?g.lineTo(x,y):g.moveTo(x,y));g.closePath();if(fill){g.fillStyle=fill;g.fill()}if(stroke){g.lineWidth=width;g.strokeStyle=stroke;g.stroke()}}
function ellipse(g,x,y,rx,ry,fill,stroke=null,width=1){g.beginPath();g.ellipse(x,y,Math.max(.1,rx),Math.max(.1,ry),0,0,Math.PI*2);if(fill){g.fillStyle=fill;g.fill()}if(stroke){g.strokeStyle=stroke;g.lineWidth=width;g.stroke()}}
function stroke(g,x1,y1,x2,y2,color,width=1){g.beginPath();g.moveTo(x1,y1);g.lineTo(x2,y2);g.strokeStyle=color;g.lineWidth=width;g.stroke()}
function tree(g,x,y,s,rng){ellipse(g,x+2,y+s*.32,s*.75,s*.27,'#4d513545');stroke(g,x,y+s*.3,x,y-s*.2,'#52422d',Math.max(1,s*.13));const offsets=[[-.43,-.14],[.3,-.22],[.02,-.5],[-.02,-.13]];offsets.forEach(([dx,dy],i)=>{const size=s*(i===2?.52:.47);ellipse(g,x+dx*s,y+dy*s,size,size*.82,['#496447','#60764d','#42624b','#718057'][i],'#344a3a',.9);ellipse(g,x+dx*s-s*.13,y+dy*s-s*.15,size*.35,size*.24,'#b1a77b42')});}
function soldier(g,x,y,s,side,type,phase,rng){const helm=side==='ally'?'#5b615c':'#494744',body=side==='ally'?'#477180':'#9c4d42';ellipse(g,x+.6*s,y+1.15*s,s*.63,s*.26,'#46413142');stroke(g,x-s*.23,y+.5*s,x-s*.38,y+s,helm,Math.max(.6,s*.21));stroke(g,x+s*.2,y+.5*s,x+s*.43,y+s,helm,Math.max(.6,s*.21));polygon(g,[[x-s*.39,y-s*.15],[x+s*.34,y-s*.14],[x+s*.46,y+.64*s],[x-s*.43,y+.64*s]],body,'#38382e',.7);ellipse(g,x,y-s*.47,s*.38,s*.4,'#d8b68b','#2b3333',.8);polygon(g,[[x-s*.46,y-s*.46],[x-s*.25,y-s*.78],[x+s*.25,y-s*.79],[x+s*.49,y-s*.43]],helm,'#373a33',.7);if(type==='spears'){stroke(g,x+s*.54,y+.4*s,x+s*.65,y-1.7*s,'#45372d',1);polygon(g,[[x+s*.65,y-1.98*s],[x+s*.48,y-1.6*s],[x+s*.77,y-1.6*s]],'#d0d0b0','#55574d',.4)}else if(type==='archers'){g.beginPath();g.arc(x+s*.75,y-.1*s,s*.62,-1.3,1.3);g.strokeStyle='#674b2c';g.lineWidth=1;g.stroke();stroke(g,x+s*.97,y-.69*s,x+s*.97,y+.49*s,'#d3b990',.6)}else {polygon(g,[[x+s*.35,y-.2*s],[x+s*.75,y+.13*s],[x+s*.61,y+.7*s],[x+s*.22,y+.48*s]],side==='ally'?'#b6ab70':'#c8b792','#403e36',.8)}}
function banner(g,x,y,side,type,s,t){const main=side==='ally'?'#416678':'#9b493e',edge=side==='ally'?'#223f47':'#64332c',gold='#e7cd92';stroke(g,x,y+8*s,x,y-25*s,'#3b3028',Math.max(1.5,1.65*s));polygon(g,[[x,y-25*s],[x+17*s+t*.3,y-22*s],[x+12*s+t*.4,y-13*s],[x,y-15*s]],main,edge,1.3);stroke(g,x+6*s,y-22*s,x+6*s,y-17*s,gold,1.3);stroke(g,x+3*s,y-19.5*s,x+11*s,y-19.5*s,gold,1.2);if(type==='general'){ellipse(g,x+8*s,y-19.4*s,2.9*s,2.8*s,gold);stroke(g,x+8*s,y-22*s,x+8*s,y-17*s,main,1.1)}ellipse(g,x,y-25*s,2*s,2.7*s,gold,'#4c4230',.4)}
function tileDesign(g,x,y,t,rng){const c=cellSize(),p=pixel(x,y),X=p.x,Y=p.y,s=Math.min(c.x,c.y);if(t==='field'||t==='road'||t==='hill'||t==='wood'){if(t==='road'){polygon(g,[[X-s*.4,Y-s*.57],[X+s*.28,Y-s*.57],[X+s*.42,Y+s*.57],[X-s*.2,Y+s*.57]],'#c0a87899')}for(let k=0;k<11;k++){const xx=X+(rng()-.5)*c.x,yy=Y+(rng()-.5)*c.y;stroke(g,xx,yy,xx+1+rng()*3,yy-2-rng()*3,k%3===0?'#536c4688':'#ddcd8f88',.5+rng()*.4)}}if(t==='wood'){tree(g,X-c.x*.16,Y-c.y*.06,s*.46,rng);tree(g,X+c.x*.17,Y+c.y*.2,s*.40,rng);tree(g,X+c.x*.15,Y-c.y*.15,s*.37,rng)}if(t==='hill'){ellipse(g,X,Y+s*.22,s*.61,s*.31,'#9e966f','#6c7554',1);ellipse(g,X-s*.08,Y+s*.05,s*.55,s*.28,'#acaa7d','#78835f',1);for(let i=0;i<6;i++)stroke(g,X-s*.37+i*s*.12,Y+s*.2-(i%2)*2,X-s*.26+i*s*.12,Y+s*.16-(i%2)*2,'#766f53',.8)}if(t==='village'){polygon(g,[[X-s*.40,Y-s*.15],[X+s*.28,Y-s*.15],[X+s*.28,Y+s*.36],[X-s*.40,Y+s*.36]],'#e5cf9d','#69513d',1);polygon(g,[[X-s*.50,Y-s*.18],[X-s*.08,Y-s*.47],[X+s*.40,Y-s*.17]],'#965747','#654336',1);stroke(g,X-s*.05,Y+s*.36,X-s*.05,Y+s*.09,'#77553c',3);ellipse(g,X+s*.15,Y+s*.08,1.7,1.7,'#4a4940')}if(t==='river'||t==='bridge'){g.fillStyle='#638b91';g.fillRect(X-c.x*.52,Y-c.y*.55,c.x*1.04,c.y*1.1);for(let i=0;i<9;i++){const xx=X+(rng()-.5)*c.x*1.1,yy=Y+(rng()-.5)*c.y;stroke(g,xx,yy,xx+6+rng()*8,yy-1,'#b3c7b1aa',.8);stroke(g,xx+3,yy+3,xx+7,yy+2,'#456e77a0',.5)}if(t==='bridge'){g.fillStyle='#776144';g.fillRect(X-c.x*.41,Y-c.y*.55,c.x*.82,c.y*1.10);g.fillStyle='#b59a6e';g.fillRect(X-c.x*.34,Y-c.y*.55,c.x*.68,c.y*1.1);for(let q=-3;q<4;q++)stroke(g,X-c.x*.34,Y+q*c.y*.16,X+c.x*.34,Y+q*c.y*.16,'#66543d',1);stroke(g,X-c.x*.46,Y-c.y*.55,X-c.x*.46,Y+c.y*.55,'#584e39',2);stroke(g,X+c.x*.46,Y-c.y*.55,X+c.x*.46,Y+c.y*.55,'#584e39',2)}}}
function drawGround(g){const rng=seedRandom(2448+state.scene*13);g.fillStyle=['#a3af89','#9da986','#adb08a'][state.scene];g.fillRect(0,0,w,h);const c=cellSize();for(let q=0;q<170;q++){let x=rng()*w,y=rng()*h,r=2+rng()*c.x*.95;ellipse(g,x,y,r,r*.65,q%3?'#d2c79211':'#526e4912')}for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++){const p=pixel(x,y);const f=terrain(x,y);if(f!=='river'&&f!=='bridge'&&rng()>.5){ellipse(g,p.x,p.y,c.x*.48,c.y*.48,'#d3ce9740')}tileDesign(g,x,y,f,rng)}
 if(state.scene===2){for(let i=0;i<5;i++){const pp=pixel(3.5,4.5);ellipse(g,pp.x,pp.y,Math.max(c.x,c.y)*(1.1+i*.22),Math.max(c.y,c.x)*(.8+i*.2),null,'#606e4d2c',.6)}}
 // Sparse inked contour strokes, pebbles, a parchment vignette and corners.
 for(let i=0;i<115;i++){const x=rng()*w,y=rng()*h;if(terrain(clamp(Math.floor((x-15)/c.x),0,7),clamp(Math.floor((y-16)/c.y),0,9))==='river')continue;ellipse(g,x,y,rng()*1.3+.2,rng()*1+.2,i%2?'#ecdaac66':'#55694c48')}
 const vignette=g.createRadialGradient(w*.5,h*.43,w*.18,w*.5,h*.43,Math.max(w,h)*.77);vignette.addColorStop(0,'#ffffff00');vignette.addColorStop(1,'#53422269');g.fillStyle=vignette;g.fillRect(0,0,w,h);g.strokeStyle='#493e2880';g.strokeRect(8,8,w-16,h-16);g.strokeStyle='#e3d2a282';g.strokeRect(11,11,w-22,h-22);
 for(let y=0;y<ROWS;y++){for(let x=0;x<COLS;x++){const p=pixel(x,y);if(terrain(x,y)!=='field')continue;if((x*11+y*7+state.scene)%17===0){stroke(g,p.x-3,p.y+3,p.x,p.y-1,'#dcd18a',.8);stroke(g,p.x,p.y-1,p.x+2,p.y+2,'#5f754d',.7)}}}
 if(state.scene===1){const p=pixel(6,2);drawCart(g,p.x,p.y,Math.min(c.x,c.y)*.75)}if(state.scene===2){const p=pixel(3.5,4.5);drawCrown(g,p.x,p.y,Math.min(c.x,c.y)*.65)}}
function drawCart(g,x,y,s){ellipse(g,x,y+s*.4,s*.76,s*.35,'#332b2450');polygon(g,[[x-s*.63,y-s*.2],[x+s*.53,y-s*.2],[x+s*.45,y+s*.27],[x-s*.59,y+s*.27]],'#a67c4c','#604630',1.5);ellipse(g,x-s*.36,y+s*.32,s*.24,s*.24,'#654b31','#332c25',1.4);ellipse(g,x+s*.38,y+s*.32,s*.24,s*.24,'#654b31','#332c25',1.4);polygon(g,[[x-s*.7,y-s*.25],[x-s*.10,y-s*.65],[x+s*.65,y-s*.28]],'#815543','#4d4032',1.5);stroke(g,x-s*.03,y-s*.39,x-s*.03,y-s*.05,'#e2c996',2)}
function drawCrown(g,x,y,s){ellipse(g,x,y+s*.5,s*.66,s*.18,'#5b553a66');polygon(g,[[x-s*.48,y+s*.2],[x-s*.59,y-s*.25],[x-s*.23,y-s*.1],[x,y-s*.65],[x+s*.25,y-s*.07],[x+s*.59,y-s*.23],[x+s*.45,y+s*.21]],'#d8b76c','#53462e',1.5);ellipse(g,x,y+s*.18,s*.4,s*.13,'#baa15b','#645236',1)}
function drawUnit(g,u,t){if(u.men<=0||u.rout!==0)return;const c=cellSize(),ss=Math.min(c.x,c.y),part=anim?Math.min(1,Math.max(0,(t-anim.start)/anim.duration)):1,origin=anim?.previous?.[u.id],a=origin?ease(part):1;const pos=pixel(origin?origin.x+(u.x-origin.x)*a:u.x,origin?origin.y+(u.y-origin.y)*a:u.y);const x=pos.x,y=pos.y;const s=clamp(ss/43,.55,1.12),r=seedRandom((u.id.charCodeAt(0)+u.id.charCodeAt(1))*97);const isSel=selected===u.id&&screen==='play';if(isSel){ellipse(g,x,y+ss*.08,ss*.55,ss*.33,'#e6d7a22b','#f3dc9c',2.3);ellipse(g,x,y+ss*.08,ss*.64,ss*.41,null,'#4e5540aa',.7)}ellipse(g,x+2,y+ss*.25,ss*.44,ss*.22,'#282e2538');const men=Math.max(2,Math.min(7,Math.ceil(u.men/17))),arr=[[-.23,.1],[.17,.19],[.05,-.25],[-.30,-.27],[.29,-.25],[-.07,.38],[.33,.39]];for(let i=0;i<men;i++){const [dx,dy]=arr[i];soldier(g,x+dx*ss*.92,y+dy*ss*.55,4.6*s,u.side,u.type,t,r)}banner(g,x-ss*.15,y-ss*.08,u.side,u.type,s,(Math.sin(t/330+u.x*.51)*2));
 // Tiny number and morale indicator as an ink-drawn cartouche at the feet.
 const bx=x+ss*.05,by=y+ss*.48;ellipse(g,bx,by,ss*.32,ss*.13,'#e9dcba','#514b35',.65);g.fillStyle=u.side==='ally'?'#2c5663':'#773b36';g.font=`bold ${Math.max(9,Math.min(12,ss*.24))}px Georgia`;g.textAlign='center';g.textBaseline='middle';g.fillText(String(u.men),bx,by-.4);if(u.flash===1&&(!anim||part<.75)){ellipse(g,x,y,ss*.46,ss*.37,'#b3523770','#a94d31',1.4)}if(u.morale<45){g.fillStyle='#563b35';g.font=`${Math.max(11,ss*.31)}px Georgia`;g.fillText('!',x+ss*.35,y-ss*.48)}}
const ease=t=>t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2;
function drawOrders(g,t){if(screen!=='play')return;const u=getUnit(selected);if(!u)return;const a=pixel(u.x,u.y),order=u.pending?.order||u.order;let dest=null;if(order?.type==='move')dest=pixel(order.x,order.y);if(order?.type==='attack'){const target=getUnit(order.target);if(target)dest=pixel(target.x,target.y)}if(dest){g.save();g.setLineDash([6,5]);g.lineDashOffset=-t/90;stroke(g,a.x,a.y,dest.x,dest.y,'#faf0b8',2.2);stroke(g,a.x,a.y,dest.x,dest.y,'#493a27',.6);g.restore();ellipse(g,dest.x,dest.y,5,5,'#eee0b3','#523d2f',1)}if(mode==='move'){g.save();g.setLineDash([2,5]);const c=cellSize();for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++)if(passable(x,y)){const p=pixel(x,y);g.strokeStyle='#e9d7a38a';g.lineWidth=.55;g.strokeRect(p.x-c.x*.5,p.y-c.y*.5,c.x,c.y)}g.restore()}}
function draw(t){if(!ctx||!state)return;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);if(!fieldCache)fieldCache=createField();ctx.drawImage(fieldCache,0,0,w,h);drawOrders(ctx,t);for(const u of state.units)drawUnit(ctx,u,t);if(anim&&t>=anim.start+anim.duration){const cb=anim.after;anim=null;cb();}}
function resize(){const r=canvas.getBoundingClientRect();if(r.width<10||r.height<10)return;w=r.width;h=r.height;dpr=Math.min(2,window.devicePixelRatio||1);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);fieldCache=null;draw(performance.now())}
const observer=new ResizeObserver(resize);observer.observe(canvas);
function frame(t){if(suspended)return;if(t-lastFrame>33||anim){draw(t);lastFrame=t}requestAnimationFrame(frame)}
window.__HORUGVI_QA__=()=>({screen,scene:state.scene,round:state.round,ordersLeft:state.ordersLeft,aliveAllies:alive('ally').length,aliveEnemies:alive('enemy').length,selected,mode,animating:!!anim,canvasSize:[w,h]});
intro();resize();requestAnimationFrame(frame);