import { HERO_BY_ID, PRESETS } from './data.js';
import { heroRating, analyzeTeam, partyRolePlan, recommendLoadouts, optimizeLoadoutChoices } from './core.js';
import { contextualRecommendations, evaluateMatchPlan, contextualAutoComplete, contextualOptimize, contextualCompare } from './match-core.js';
import { renderMatchPanels } from './match.js';
import { box,$,$$,esc,portrait,wireImageFallbacks,activeLimit,activeIds,assignedPlayer,targetSlot,planOptions,saveState,openSheet,haptic,clickSound,toast } from './store.js';
import { renderPlayerDock } from './profiles.js';

let compareIds=[];
export function setPlannerMode(mode){mode=mode==='full'?'full':'party';if(mode===box.state.plannerMode)return;box.state.plannerMode=mode;saveState();renderBuilder();clickSound('good');haptic();}
export function setPartySize(size){size=Math.max(1,Math.min(6,Number(size)||2));if(size===box.state.partySize)return;if(size<box.state.partySize&&box.state.team.slice(size,box.state.partySize).some(Boolean)&&!confirm('Уменьшить пати и убрать героев из лишних управляемых слотов?'))return;if(size<box.state.partySize)for(let i=size;i<box.state.partySize;i++){box.state.team[i]=null;box.state.locks[i]=false;box.state.playerAssignments[i]=null;}box.state.partySize=size;saveState();renderBuilder();haptic();}
function renderModeControls(){$$('#plannerModeButtons button').forEach(button=>button.classList.toggle('active',button.dataset.plannerMode===box.state.plannerMode));}
function renderPartySize(){const control=$('#partySizeControl');control.hidden=box.state.plannerMode==='full';$('#partySizeButtons').innerHTML=[1,2,3,4,5,6].map(size=>`<button class="${size===box.state.partySize?'active':''}" data-party-size="${size}">${size}</button>`).join('');$('#modeExplanation').textContent=box.state.plannerMode==='party'?`Вы выбираете ${box.state.partySize} ${box.state.partySize===1?'героя':'героев'} своей группы. Ещё ${6-box.state.partySize} слота остаются случайным союзникам; оценка учитывает, смогут ли они нормально достроить состав.`:'Вы управляете всеми шестью слотами и собираете точный состав без допущений о случайных союзниках.';}
function unknownHints(){const plan=partyRolePlan(box.state.team,box.state.partySize),order=[];for(const role of ['Vanguard','Strategist','Duelist'])for(let i=0;i<plan.requiredRoles[role];i++)order.push(role);return order;}
function playerBadge(index){const item=assignedPlayer(index);return`<button class="slot-player ${item?'assigned':''}" data-assign-player="${index}" style="--player:${item?.color||'#bbb'}"><span>${item?esc(item.name.split(/\s+/).map(part=>part[0]).join('').slice(0,2).toUpperCase()):'+'}</span><small>${esc(item?.name||'игрок')}</small></button>`;}
function teamSlotHTML(id,index,hints=[]){
  if(box.state.plannerMode==='party'&&index>=box.state.partySize){const hint=hints[index-box.state.partySize]||'Свободная роль';return`<article class="team-slot unknown-ally"><div class="unknown-glyph">?</div><strong>СЛУЧАЙНЫЙ СОЮЗНИК</strong><span>${esc(hint)}</span><small>не управляется вашей пати</small></article>`;}
  if(!id)return`<article class="team-slot empty ${targetSlot()===index?'recommend-target':''}" data-slot="${index}">${playerBadge(index)}<button data-pick-slot="${index}"><b>＋</b><span>${box.state.plannerMode==='party'?'ИГРОК ПАТИ':'СЛОТ'} ${index+1}</span></button></article>`;
  const hero=HERO_BY_ID[id],rating=Math.round(heroRating(hero,box.state.prefs)),fit=assignedPlayer(index)?Math.round((analyzeTeam(box.state.team,box.state.prefs,planOptions()).playerFit.items.find(item=>item.slot===index)?.score)||50):null;return`<article class="team-slot ${targetSlot()===index?'recommend-target':''}" style="--role:${hero.color}" data-slot="${index}">${portrait(hero,'portrait')}<div class="slot-gradient"></div>${playerBadge(index)}<div class="slot-top-actions"><button data-remove-slot="${index}">×</button><button data-lock-slot="${index}" class="${box.state.locks[index]?'locked':''}">${box.state.locks[index]?'◆':'◇'}</button></div><button class="slot-main-hit" data-pick-slot="${index}"></button><div class="slot-info"><strong>${esc(hero.name)}</strong><small><span><i class="role-dot"></i>${esc(hero.role)}</span><span>${fit!==null?`PLAYER FIT ${fit}`:esc(hero.archetype)}</span></small></div><button class="slot-rank" data-open-hero="${hero.id}">${box.state.prefs.tiers[hero.id]||hero.tier} · ${rating}</button></article>`;
}
export function verdictFor(analysis,filled){if(!filled)return['Добавь первого героя','Система оценит вашу группу внутри полноценного матча 6×6.'];if(box.state.plannerMode==='party'){if(analysis.unfixable)return['Пати загнала матч в угол',analysis.warnings.join(' · ')];if(analysis.overall>=82)return['Сильное автономное ядро',analysis.warnings[0]||'Остальные союзники могут свободно достроить состав.'];if(analysis.overall>=68)return['Хорошая пати для матчмейкинга',analysis.warnings[0]||'Связка полезна и не душит чужие пики.'];return['Играбельно, но без ясного плана',analysis.warnings.join(' · ')||'Добавьте прямую синергию или больше самостоятельности.'];}const complete=filled===6;if(analysis.overall>=88&&complete)return['Злая, связная машина','Роли закрыты, пики усиливают друг друга.'];if(analysis.overall>=76)return['Сильный состав',analysis.warnings.join(' · ')||'Состав работает как единое целое.'];if(analysis.overall>=62)return['Рабоче, но с дырками',analysis.warnings.join(' · ')||'Неплохая база.'];return['Пока это компания знакомых',analysis.warnings.join(' · ')||'Добавь роли и общую идею.'];}
function renderAnalysisStrip(){const analysis=evaluateMatchPlan(box.state.team,box.state.prefs,planOptions()),filled=activeIds().filter(Boolean).length,[title,copy]=verdictFor(analysis,filled);$('#overallScore').textContent=Math.round(analysis.overall);$('#analysisVerdict').textContent=title;const contextCopy=analysis.contextDelta>=2?`Контекст +${Math.round(analysis.contextDelta)}.`:analysis.contextDelta<=-2?`Контекст ${Math.round(analysis.contextDelta)}.`:'';$('#analysisWarnings').textContent=[contextCopy,copy].filter(Boolean).join(' ');$('#teamTitle').textContent=box.state.plannerMode==='party'?`Ваша пати ${filled}/${box.state.partySize} · матч 6×6`:`Полный состав ${filled}/6`;const fit=$('#playerFitScore');if(fit)fit.textContent=analysis.playerFit.assigned?`${Math.round(analysis.playerFit.score)} PLAYER FIT · ${Math.round(analysis.context)} MATCH FIT`:`${Math.round(analysis.context)} MATCH FIT`;}
function renderRecommendations(){const slot=targetSlot(),profile=assignedPlayer(slot),results=contextualRecommendations(box.state.team,box.state.prefs,{...planOptions(),limit:10,size:6,playerProfile:profile});$('#recommendationContext').textContent=profile?`СЛОТ ${slot+1} · ${profile.name} · MATCH-AWARE`:`СЛОТ ${slot+1} · MATCH-AWARE`;$('#recommendations').innerHTML=results.map(({hero,score,reasons,playerFit,context})=>`<article class="recommend-card ${compareIds.includes(hero.id)?'comparing':''}" style="--role-soft:${hero.color}25"><button class="recommend-main" data-open-hero="${hero.id}">${portrait(hero)}</button><span class="rec-score">${Math.round(score)}</span><div class="rec-copy"><strong>${esc(hero.name)}</strong><small>${esc(reasons.join(' · ')||`${hero.role} · ${hero.archetype}`)}</small>${profile?`<em>${esc(profile.name)} · ${Math.round(playerFit.score)} fit · контекст ${context.score>=0?'+':''}${Math.round(context.score)}</em>`:`<em>контекст ${context.score>=0?'+':''}${Math.round(context.score)}</em>`}</div><div class="rec-actions"><button class="rec-compare" data-compare-hero="${hero.id}">${compareIds.includes(hero.id)?'✓':'⇄'}</button><button class="rec-add" data-add-hero="${hero.id}" data-add-slot="${slot}">＋</button></div></article>`).join('')||'<div class="empty-inline">В управляемых слотах уже нет места.</div>';wireImageFallbacks($('#recommendations'));renderCompareDock();}
function loadoutStatus(option){if(option.partnerPresent)return`УСИЛЕНО · ${HERO_BY_ID[option.partner]?.name||option.partner} в составе`;if(!option.partnerAvailable)return`БАЗОВАЯ ВЕРСИЯ · The Hood ещё недоступен`;return`БАЗОВАЯ ВЕРСИЯ · усилится с ${HERO_BY_ID[option.partner]?.name||option.partner}`;}
export function loadoutOptionHTML(option,item){const selected=item.selected?.id===option.id,recommended=item.recommended?.id===option.id;return`<button class="loadout-option ${selected?'selected':''} ${option.partnerPresent?'enhanced':''}" data-set-loadout="${item.heroId}:${option.id}"><span class="loadout-radio">${selected?'●':'○'}</span><span class="loadout-option-copy"><b>${esc(option.name)} ${recommended?'<i>РЕКОМЕНДОВАНО</i>':''}</b><small>${esc(option.summary)}</small><em>${esc(loadoutStatus(option))}</em></span></button>`;}
function renderLoadouts(){const items=recommendLoadouts(activeIds(),box.state.loadoutChoices),root=$('#loadoutPlans');root.innerHTML=items.length?items.map(item=>{const hero=HERO_BY_ID[item.heroId];return`<article class="loadout-plan" style="--role-soft:${hero.color}24"><header>${portrait(hero)}<div><span>TEAM-UP LOADOUT</span><h3>${esc(hero.name)}</h3></div></header><div class="loadout-options">${item.options.map(option=>loadoutOptionHTML(option,item)).join('')}</div></article>`;}).join(''):'<div class="empty-inline wide">Добавь героя — здесь появится выбор его командной способности.</div>';wireImageFallbacks(root);}
function renderPresets(){$('#presetRail').innerHTML=PRESETS.map(preset=>`<button class="preset-card" data-preset="${preset.id}"><b>${esc(preset.name)}</b><small>${esc(preset.subtitle)}</small><span class="preset-faces">${preset.heroes.slice(0,6).map(id=>portrait(HERO_BY_ID[id])).join('')}</span></button>`).join('');wireImageFallbacks($('#presetRail'));}
function renderVariants(){const root=$('#variantRail');if(!root)return;root.innerHTML=box.state.variants.length?box.state.variants.map(variant=>`<article class="variant-card"><header><div><span>PLAN BRANCH</span><h3>${esc(variant.name)}</h3></div><b>${Math.round(variant.score||0)}</b></header><div class="variant-faces">${variant.team.slice(0,box.state.plannerMode==='party'?box.state.partySize:6).filter(Boolean).map(id=>portrait(HERO_BY_ID[id])).join('')}</div><div class="variant-players">${variant.playerAssignments.slice(0,box.state.plannerMode==='party'?box.state.partySize:6).map(id=>{const item=box.state.players.find(player=>player.id===id);return item?`<span style="--player:${item.color}">${esc(item.name)}</span>`:'';}).join('')}</div><small class="variant-context">${esc(variant.matchContext?.mapId||'any')} · ${(variant.enemyTeam||[]).filter(Boolean).length} врагов</small><div class="variant-actions"><button data-load-variant="${variant.id}">Загрузить</button><button data-delete-variant="${variant.id}">Удалить</button></div></article>`).join(''):'<div class="empty-inline wide">Сохрани основной вариант, затем делай ветки под разные ситуации.</div>';wireImageFallbacks(root);}
function renderCompareDock(){const root=$('#compareDock');if(!root)return;if(!compareIds.length){root.hidden=true;return;}root.hidden=false;root.innerHTML=`<div><span>СРАВНЕНИЕ ${compareIds.length}/2</span><b>${compareIds.map(id=>HERO_BY_ID[id]?.name).filter(Boolean).join(' vs ')}</b></div><button id="openCompareButton" ${compareIds.length<2?'disabled':''}>Сравнить</button>`;}
export function renderBuilder(){renderModeControls();renderPartySize();renderPlayerDock();renderMatchPanels();const hints=unknownHints();$('#teamSlots').innerHTML=box.state.team.map((id,index)=>teamSlotHTML(id,index,hints)).join('');renderAnalysisStrip();renderRecommendations();renderLoadouts();renderVariants();renderPresets();wireImageFallbacks($('#teamSlots'));$('#autoCompleteButton small').textContent=box.state.plannerMode==='party'?'заполнить только вашу пати':'заполнить все пустые слоты';$('#optimizeButton small').textContent=box.state.plannerMode==='party'?'пересобрать только вашу пати':'сохранив закреплённых';}
export function placeHero(heroId,preferredSlot=null){if(!HERO_BY_ID[heroId])return false;const limit=activeLimit();let slot=preferredSlot===null?targetSlot():Number(preferredSlot);if(slot<0||slot>=limit)slot=box.state.team.slice(0,limit).findIndex(id=>!id);if(slot<0){for(let i=limit-1;i>=0;i--)if(!box.state.locks[i]){slot=i;break;}}if(slot<0)return toast('Все управляемые слоты закреплены.','bad');const existing=box.state.team.slice(0,limit).indexOf(heroId);if(existing===slot)return true;if(existing>=0){const displaced=box.state.team[slot];box.state.team[slot]=heroId;box.state.team[existing]=displaced||null;const lock=box.state.locks[slot];box.state.locks[slot]=box.state.locks[existing];box.state.locks[existing]=lock;}else box.state.team[slot]=heroId;box.state.recommendationSlot=Math.min(limit-1,slot+1);saveState();renderBuilder();clickSound('good');haptic(10);return true;}
export function removeHero(index){box.state.team[index]=null;box.state.locks[index]=false;box.state.recommendationSlot=index;saveState();renderBuilder();}
export function toggleLock(index){box.state.locks[index]=!box.state.locks[index];saveState();renderBuilder();}
export function chooseLoadout(value){const[heroId,loadoutId]=value.split(':');box.state.loadoutChoices[heroId]=loadoutId;saveState();renderBuilder();clickSound('good');haptic();}
export function optimizeAllLoadouts(){box.state.loadoutChoices=optimizeLoadoutChoices(activeIds(),box.state.loadoutChoices);saveState();renderBuilder();clickSound('good');haptic([8,20,8]);toast('Team-Up способности оптимизированы для всей группы.','good');}
export function applyPreset(id){const preset=PRESETS.find(item=>item.id===id);if(!preset)return;const limit=activeLimit();for(let i=0;i<6;i++){if(i<limit)box.state.team[i]=preset.heroes[i]||null;else if(box.state.plannerMode==='party')box.state.team[i]=null;box.state.locks[i]=i<Math.min(2,limit)&&Boolean(box.state.team[i]);}saveState();renderBuilder();clickSound('good');toast(`Основа загружена: ${preset.name}`,'good');}
export function clearCurrent(){const limit=activeLimit();if(!activeIds().some(Boolean)||confirm(`Очистить ${box.state.plannerMode==='party'?'вашу пати':'весь состав'}?`)){for(let i=0;i<limit;i++){box.state.team[i]=null;box.state.locks[i]=false;}saveState();renderBuilder();}}
export function autoFill(){box.state.team=contextualAutoComplete(box.state.team,box.state.locks,box.state.prefs,planOptions());box.state.loadoutChoices=optimizeLoadoutChoices(activeIds(),box.state.loadoutChoices);saveState();renderBuilder();clickSound('good');haptic([10,30,10]);toast(box.state.plannerMode==='party'?'Пати дополнена под игроков и текущий матч.':'Команда заполнена под игроков и текущий матч.','good');}
export function optimize(){box.state.team=contextualOptimize(box.state.team,box.state.locks,box.state.prefs,planOptions());box.state.loadoutChoices=optimizeLoadoutChoices(activeIds(),box.state.loadoutChoices);saveState();renderBuilder();clickSound('good');haptic([12,25,12]);toast(box.state.plannerMode==='party'?'Пати пересобрана под карту и врагов.':'Состав пересобран под карту и врагов.','good');}
export function saveVariant(){const ids=activeIds().filter(Boolean);if(!ids.length)return toast('Сначала собери хотя бы часть состава.','bad');const suggested=box.state.variants.length?'Запасной вариант':'Основной вариант',name=(prompt('Название варианта',suggested)||suggested).trim().slice(0,50);const score=Math.round(evaluateMatchPlan(box.state.team,box.state.prefs,planOptions()).overall);box.state.variants.unshift({id:crypto.randomUUID?.()||`variant-${Date.now().toString(36)}`,name,team:[...box.state.team],locks:[...box.state.locks],playerAssignments:[...box.state.playerAssignments],loadoutChoices:{...box.state.loadoutChoices},matchContext:{...box.state.matchContext},enemyTeam:[...box.state.enemyTeam],score,updated:Date.now()});box.state.variants=box.state.variants.slice(0,16);saveState();renderVariants();toast('Вариант сохранён вместе с контекстом матча.','good');clickSound('good');}
export function loadVariant(id){const variant=box.state.variants.find(item=>item.id===id);if(!variant)return;box.state.team=Array.from({length:6},(_,i)=>HERO_BY_ID[variant.team?.[i]]?variant.team[i]:null);box.state.locks=Array.from({length:6},(_,i)=>Boolean(variant.locks?.[i]));box.state.playerAssignments=Array.from({length:6},(_,i)=>box.state.players.some(player=>player.id===variant.playerAssignments?.[i])?variant.playerAssignments[i]:null);box.state.loadoutChoices={...(variant.loadoutChoices||{})};box.state.matchContext={...box.state.matchContext,...(variant.matchContext||{})};box.state.enemyTeam=Array.from({length:6},(_,i)=>HERO_BY_ID[variant.enemyTeam?.[i]]?variant.enemyTeam[i]:null);saveState();renderBuilder();toast(`Загружен вариант: ${variant.name}`,'good');}
export function deleteVariant(id){const variant=box.state.variants.find(item=>item.id===id);if(!variant||!confirm(`Удалить вариант «${variant.name}»?`))return;box.state.variants=box.state.variants.filter(item=>item.id!==id);saveState();renderVariants();}
export function toggleCompareHero(id){if(!HERO_BY_ID[id])return;if(compareIds.includes(id))compareIds=compareIds.filter(value=>value!==id);else compareIds=[...compareIds.slice(-1),id];renderRecommendations();haptic();}
export function openCompare(){if(compareIds.length<2)return;const slot=targetSlot(),profile=assignedPlayer(slot),result=contextualCompare(compareIds[0],compareIds[1],box.state.team,box.state.prefs,{...planOptions(),playerProfile:profile}),root=$('#compareSheetContent');const metric=(label,key)=>`<div class="compare-row"><span>${label}</span><b>${Math.round(result.first[key])}</b><div><i style="--a:${result.first[key]}%;--b:${result.second[key]}%"></i></div><b>${Math.round(result.second[key])}</b></div>`;root.innerHTML=`<div class="compare-context">${profile?`Для слота ${slot+1}: <b>${esc(profile.name)}</b>`:'Без привязки к игроку'} · с учётом матча</div><div class="compare-heroes"><article>${portrait(result.first.hero)}<h3>${esc(result.first.hero.name)}</h3><b>${Math.round(result.first.total)}</b></article><span>VS</span><article>${portrait(result.second.hero)}<h3>${esc(result.second.hero.name)}</h3><b>${Math.round(result.second.total)}</b></article></div><div class="compare-metrics">${metric('Личный фит','personal')}${metric('Ролевая польза','role')}${metric('Синергия','synergy')}${metric('Контекст матча','context')}${metric('Простота','difficulty')}${metric('Новые инструменты','versatility')}</div><section class="compare-verdict"><span>ЛУЧШИЙ ВАРИАНТ</span><h3>${esc(result.winner.hero.name)}</h3><p>${esc(result.winner.reasons.join(' · '))}</p><button data-add-hero="${result.winner.hero.id}" data-add-slot="${slot}">Поставить в слот ${slot+1}</button></section>`;wireImageFallbacks(root);openSheet('compareSheet');}
