import { HERO_BY_ID, PRESETS } from './data.js';
import { heroRating, analyzeTeam, partyRolePlan, recommendHeroes, recommendLoadouts, autoComplete, optimizeTeam } from './core.js';
import { box,$,$$,esc,portrait,wireImageFallbacks,activeLimit,activeIds,planOptions,saveState,haptic,clickSound,toast } from './store.js';

export function setPlannerMode(mode){mode=mode==='full'?'full':'party';if(mode===box.state.plannerMode)return;box.state.plannerMode=mode;saveState();renderBuilder();clickSound('good');haptic();}
export function setPartySize(size){size=Math.max(1,Math.min(6,Number(size)||2));if(size===box.state.partySize)return;if(size<box.state.partySize&&box.state.team.slice(size,box.state.partySize).some(Boolean)&&!confirm('Уменьшить пати и убрать героев из лишних управляемых слотов?'))return;if(size<box.state.partySize)for(let i=size;i<box.state.partySize;i++){box.state.team[i]=null;box.state.locks[i]=false;}box.state.partySize=size;saveState();renderBuilder();haptic();}
function renderModeControls(){$$('#plannerModeButtons button').forEach(button=>button.classList.toggle('active',button.dataset.plannerMode===box.state.plannerMode));}
function renderPartySize(){const control=$('#partySizeControl');control.hidden=box.state.plannerMode==='full';$('#partySizeButtons').innerHTML=[1,2,3,4,5,6].map(size=>`<button class="${size===box.state.partySize?'active':''}" data-party-size="${size}">${size}</button>`).join('');$('#modeExplanation').textContent=box.state.plannerMode==='party'?`Вы выбираете ${box.state.partySize} ${box.state.partySize===1?'героя':'героев'} своей группы. Ещё ${6-box.state.partySize} слота остаются случайным союзникам; оценка учитывает, смогут ли они нормально достроить состав.`:'Вы управляете всеми шестью слотами и собираете точный состав без допущений о случайных союзниках.';}
function unknownHints(){const plan=partyRolePlan(box.state.team,box.state.partySize),order=[];for(const role of ['Vanguard','Strategist','Duelist'])for(let i=0;i<plan.requiredRoles[role];i++)order.push(role);return order;}
function teamSlotHTML(id,index,hints=[]){
  if(box.state.plannerMode==='party'&&index>=box.state.partySize){const hint=hints[index-box.state.partySize]||'Свободная роль';return`<article class="team-slot unknown-ally"><div class="unknown-glyph">?</div><strong>СЛУЧАЙНЫЙ СОЮЗНИК</strong><span>${esc(hint)}</span><small>не управляется вашей пати</small></article>`;}
  if(!id)return`<article class="team-slot empty" data-slot="${index}"><button data-pick-slot="${index}"><b>＋</b><span>${box.state.plannerMode==='party'?'ИГРОК ПАТИ':'СЛОТ'} ${index+1}</span></button></article>`;
  const hero=HERO_BY_ID[id],rating=Math.round(heroRating(hero,box.state.prefs));return`<article class="team-slot" style="--role:${hero.color}" data-slot="${index}">${portrait(hero,'portrait')}<div class="slot-gradient"></div><div class="slot-top-actions"><button data-remove-slot="${index}">×</button><button data-lock-slot="${index}" class="${box.state.locks[index]?'locked':''}">${box.state.locks[index]?'◆':'◇'}</button></div><button class="slot-main-hit" data-pick-slot="${index}"></button><div class="slot-info"><strong>${esc(hero.name)}</strong><small><span><i class="role-dot"></i>${esc(hero.role)}</span><span>${esc(hero.archetype)}</span></small></div><button class="slot-rank" data-open-hero="${hero.id}">${box.state.prefs.tiers[hero.id]||hero.tier} · ${rating}</button></article>`;
}
export function verdictFor(analysis,filled){
  if(!filled)return['Добавь первого героя','Система оценит вашу группу внутри полноценного матча 6×6.'];
  if(box.state.plannerMode==='party'){if(analysis.unfixable)return['Пати загнала матч в угол',analysis.warnings.join(' · ')];if(analysis.overall>=82)return['Сильное автономное ядро',analysis.warnings[0]||'Остальные союзники могут свободно достроить состав.'];if(analysis.overall>=68)return['Хорошая пати для матчмейкинга',analysis.warnings[0]||'Связка полезна и не душит чужие пики.'];return['Играбельно, но без ясного плана',analysis.warnings.join(' · ')||'Добавьте прямую синергию или больше самостоятельности.'];}
  const complete=filled===6;if(analysis.overall>=88&&complete)return['Злая, связная машина','Роли закрыты, пики усиливают друг друга.'];if(analysis.overall>=76)return['Сильный состав',analysis.warnings.join(' · ')||'Состав работает как единое целое.'];if(analysis.overall>=62)return['Рабоче, но с дырками',analysis.warnings.join(' · ')||'Неплохая база.'];return['Пока это компания знакомых',analysis.warnings.join(' · ')||'Добавь роли и общую идею.'];
}
function renderAnalysisStrip(){const analysis=analyzeTeam(box.state.team,box.state.prefs,planOptions()),filled=activeIds().filter(Boolean).length,[title,copy]=verdictFor(analysis,filled);$('#overallScore').textContent=Math.round(analysis.overall);$('#analysisVerdict').textContent=title;$('#analysisWarnings').textContent=copy;$('#teamTitle').textContent=box.state.plannerMode==='party'?`Ваша пати ${filled}/${box.state.partySize} · матч 6×6`:`Полный состав ${filled}/6`;}
function renderRecommendations(){const results=recommendHeroes(box.state.team,box.state.prefs,{limit:10,size:6,mode:box.state.plannerMode,partySize:box.state.partySize});$('#recommendations').innerHTML=results.map(({hero,score,reasons})=>`<article class="recommend-card" style="--role-soft:${hero.color}25"><button class="recommend-main" data-open-hero="${hero.id}">${portrait(hero)}</button><span class="rec-score">${Math.round(score)}</span><div class="rec-copy"><strong>${esc(hero.name)}</strong><small>${esc(reasons.join(' · ')||`${hero.role} · ${hero.archetype}`)}</small></div><button class="rec-add" data-add-hero="${hero.id}">＋</button></article>`).join('')||'<div class="empty-inline">В управляемых слотах уже нет места.</div>';wireImageFallbacks($('#recommendations'));}
function loadoutStatus(option){if(option.partnerPresent)return`УСИЛЕНО · ${HERO_BY_ID[option.partner]?.name||option.partner} в составе`;if(!option.partnerAvailable)return`БАЗОВАЯ ВЕРСИЯ · The Hood ещё недоступен`;return`БАЗОВАЯ ВЕРСИЯ · усилится с ${HERO_BY_ID[option.partner]?.name||option.partner}`;}
export function loadoutOptionHTML(option,item){const selected=item.selected?.id===option.id,recommended=item.recommended?.id===option.id;return`<button class="loadout-option ${selected?'selected':''} ${option.partnerPresent?'enhanced':''}" data-set-loadout="${item.heroId}:${option.id}"><span class="loadout-radio">${selected?'●':'○'}</span><span class="loadout-option-copy"><b>${esc(option.name)} ${recommended?'<i>РЕКОМЕНДОВАНО</i>':''}</b><small>${esc(option.summary)}</small><em>${esc(loadoutStatus(option))}</em></span></button>`;}
function renderLoadouts(){const items=recommendLoadouts(activeIds(),box.state.loadoutChoices),root=$('#loadoutPlans');root.innerHTML=items.length?items.map(item=>{const hero=HERO_BY_ID[item.heroId];return`<article class="loadout-plan" style="--role-soft:${hero.color}24"><header>${portrait(hero)}<div><span>TEAM-UP LOADOUT</span><h3>${esc(hero.name)}</h3></div></header><div class="loadout-options">${item.options.map(option=>loadoutOptionHTML(option,item)).join('')}</div></article>`;}).join(''):'<div class="empty-inline wide">Добавь героя — здесь появится выбор его командной способности.</div>';wireImageFallbacks(root);}
function renderPresets(){$('#presetRail').innerHTML=PRESETS.map(preset=>`<button class="preset-card" data-preset="${preset.id}"><b>${esc(preset.name)}</b><small>${esc(preset.subtitle)}</small><span class="preset-faces">${preset.heroes.slice(0,6).map(id=>portrait(HERO_BY_ID[id])).join('')}</span></button>`).join('');wireImageFallbacks($('#presetRail'));}
export function renderBuilder(){renderModeControls();renderPartySize();const hints=unknownHints();$('#teamSlots').innerHTML=box.state.team.map((id,index)=>teamSlotHTML(id,index,hints)).join('');renderAnalysisStrip();renderRecommendations();renderLoadouts();renderPresets();wireImageFallbacks($('#teamSlots'));$('#autoCompleteButton small').textContent=box.state.plannerMode==='party'?'заполнить только вашу пати':'заполнить все пустые слоты';$('#optimizeButton small').textContent=box.state.plannerMode==='party'?'пересобрать только вашу пати':'сохранив закреплённых';}
export function placeHero(heroId,preferredSlot=null){if(!HERO_BY_ID[heroId])return false;const limit=activeLimit();let slot=preferredSlot;if(slot===null||slot<0||slot>=limit)slot=box.state.team.slice(0,limit).findIndex(id=>!id);if(slot<0){for(let i=limit-1;i>=0;i--)if(!box.state.locks[i]){slot=i;break;}}if(slot<0)return toast('Все управляемые слоты закреплены.','bad');const existing=box.state.team.slice(0,limit).indexOf(heroId);if(existing===slot)return true;if(existing>=0){const displaced=box.state.team[slot];box.state.team[slot]=heroId;box.state.team[existing]=displaced||null;const lock=box.state.locks[slot];box.state.locks[slot]=box.state.locks[existing];box.state.locks[existing]=lock;}else box.state.team[slot]=heroId;saveState();renderBuilder();clickSound('good');haptic(10);return true;}
export function removeHero(index){box.state.team[index]=null;box.state.locks[index]=false;saveState();renderBuilder();}
export function toggleLock(index){box.state.locks[index]=!box.state.locks[index];saveState();renderBuilder();}
export function chooseLoadout(value){const [heroId,loadoutId]=value.split(':');box.state.loadoutChoices[heroId]=loadoutId;saveState();renderBuilder();clickSound('good');haptic();}
export function applyPreset(id){const preset=PRESETS.find(item=>item.id===id);if(!preset)return;const limit=activeLimit();for(let i=0;i<6;i++){if(i<limit)box.state.team[i]=preset.heroes[i]||null;else if(box.state.plannerMode==='party')box.state.team[i]=null;box.state.locks[i]=i<Math.min(2,limit)&&Boolean(box.state.team[i]);}saveState();renderBuilder();clickSound('good');toast(`Основа загружена: ${preset.name}`,'good');}
export function clearCurrent(){const limit=activeLimit();if(!activeIds().some(Boolean)||confirm(`Очистить ${box.state.plannerMode==='party'?'вашу пати':'весь состав'}?`)){for(let i=0;i<limit;i++){box.state.team[i]=null;box.state.locks[i]=false;}saveState();renderBuilder();}}
export function autoFill(){box.state.team=autoComplete(box.state.team,box.state.locks,box.state.prefs,planOptions());saveState();renderBuilder();clickSound('good');haptic([10,30,10]);toast(box.state.plannerMode==='party'?'Пати дополнена; чужие слоты не тронуты.':'Команда заполнена.','good');}
export function optimize(){box.state.team=optimizeTeam(box.state.team,box.state.locks,box.state.prefs,planOptions());saveState();renderBuilder();clickSound('good');haptic([12,25,12]);toast(box.state.plannerMode==='party'?'Пати пересобрана без присвоения чужих слотов.':'Состав пересобран.','good');}
