import { HEROES,HERO_BY_ID,TEAM_UPS,TIERS } from './data.js';
import { LOADOUTS,partnerName } from './loadouts.js';
import { heroRating,tierGroups } from './core.js';
import { box,$,esc,portrait,wireImageFallbacks,roleLabel,roleTabs,saveState } from './store.js';

export function filteredHeroes({picker=false,pickerRole='All',pickerSearch=''}={}){const role=picker?pickerRole:box.state.heroRole,query=(picker?pickerSearch:box.state.heroSearch).trim().toLowerCase();return HEROES.filter(hero=>(role==='All'||hero.role===role||(hero.role==='Flex'&&hero.roles.includes(role)))&&(!query||[hero.name,hero.role,hero.archetype,...hero.tags].join(' ').toLowerCase().includes(query))&&(picker||!box.state.favoriteOnly||box.state.prefs.favorites.includes(hero.id)));}
function heroCardHTML(hero){const rating=Math.round(heroRating(hero,box.state.prefs)),tier=box.state.prefs.tiers[hero.id]||hero.tier,favorite=box.state.prefs.favorites.includes(hero.id);return`<button class="hero-card" data-open-hero="${hero.id}" style="--role:${hero.color};--role-soft:${hero.color}28">${portrait(hero)}<span class="tier-pin">${tier}</span><span class="rating-pin">${rating}</span>${favorite?'<span class="favorite-pin">★</span>':''}<span class="hero-copy"><strong>${esc(hero.name)}</strong><small>${esc(roleLabel(hero))}</small></span></button>`;}
export function renderHeroes(){$('#heroRoleTabs').innerHTML=roleTabs(box.state.heroRole);$('#heroSearch').value=box.state.heroSearch;$('#heroFilterButton').textContent=box.state.favoriteOnly?'★ Избранные':'Фильтры';$('#heroFilterButton').classList.toggle('active',box.state.favoriteOnly);const heroes=filteredHeroes();$('#heroCountBadge').textContent=heroes.length;$('#heroGrid').innerHTML=heroes.map(heroCardHTML).join('')||'<div class="empty-inline wide">Никого не найдено.</div>';wireImageFallbacks($('#heroGrid'));}
export function renderTiers(){$('#tierRoleFilter').value=box.state.tierRole;$('#tierSort').value=box.state.tierSort;const groups=tierGroups(box.state.prefs),colors={'S+':'#d7ff45',S:'#ffda45',A:'#ff9c65',B:'#77d7c4',C:'#a99ae8',D:'#c9c5ba'};$('#tierBoard').innerHTML=TIERS.map(tier=>{let heroes=groups[tier].filter(hero=>box.state.tierRole==='all'||hero.role===box.state.tierRole||(hero.role==='Flex'&&hero.roles.includes(box.state.tierRole)));if(box.state.tierSort==='name')heroes.sort((a,b)=>a.name.localeCompare(b.name));if(box.state.tierSort==='difficulty')heroes.sort((a,b)=>b.difficulty-a.difficulty);return`<section class="tier-row"><div class="tier-label" style="--tier-color:${colors[tier]}">${tier}</div><div class="tier-heroes">${heroes.map(hero=>`<button class="tier-mini" data-open-hero="${hero.id}">${portrait(hero)}<span>${esc(hero.name)}</span></button>`).join('')||'<span class="tier-empty">—</span>'}</div></section>`;}).join('');wireImageFallbacks($('#tierBoard'));}
function filteredLoadouts(){const q=box.state.linkSearch.trim().toLowerCase();return LOADOUTS.filter(option=>!q||`${option.name} ${HERO_BY_ID[option.hero]?.name} ${partnerName(option.partner)} ${option.summary}`.toLowerCase().includes(q));}
function filteredTactical(){const q=box.state.linkSearch.trim().toLowerCase();return TEAM_UPS.filter(link=>link.type==='tactical'&&(!q||`${link.name} ${link.effect} ${link.members.map(id=>HERO_BY_ID[id]?.name).join(' ')}`.toLowerCase().includes(q)));}
export function renderLinks(){const tabs=[['all','Все'],['loadout','Способности'],['tactical','Тактика']];$('#linkTypeTabs').innerHTML=tabs.map(([id,label])=>`<button class="${box.state.linkType===id?'active':''}" data-link-type="${id}">${label}</button>`).join('');$('#linkSearch').value=box.state.linkSearch;const loadouts=box.state.linkType==='tactical'?[]:filteredLoadouts(),tactical=box.state.linkType==='loadout'?[]:filteredTactical();$('#linkCountBadge').textContent=loadouts.length+tactical.length;const loadoutHtml=loadouts.map(option=>{const hero=HERO_BY_ID[option.hero],partner=HERO_BY_ID[option.partner];return`<article class="link-card loadout-link"><span class="link-meta">SELECTABLE TEAM-UP · ${esc(hero.name)}</span><h3>${esc(option.name)}</h3><div class="link-members"><button class="link-member" data-open-hero="${hero.id}">${portrait(hero)}<span>${esc(hero.name)}</span></button>${partner?`<button class="link-member" data-open-hero="${partner.id}">${portrait(partner)}<span>УСИЛИТЕЛЬ · ${esc(partner.name)}</span></button>`:`<span class="future-partner">УСИЛИТЕЛЬ · ${esc(partnerName(option.partner))} (позже)</span>`}</div><p>${esc(option.summary)} Базовый эффект доступен всегда; партнёр включает усиленную версию.</p><div class="link-tags">${option.tags.map(tag=>`<span class="tag">${esc(tag)}</span>`).join('')}</div></article>`;}).join('');const tacticalHtml=tactical.map(link=>`<article class="link-card tactical"><span class="link-meta">TACTICAL SYNERGY</span><h3>${esc(link.name)}</h3><div class="link-members">${link.members.map(id=>{const hero=HERO_BY_ID[id];return`<button class="link-member" data-open-hero="${hero.id}">${portrait(hero)}<span>${esc(hero.name)}</span></button>`;}).join('')}</div><p>${esc(link.effect)}</p><div class="link-tags">${link.tags.map(tag=>`<span class="tag">${esc(tag)}</span>`).join('')}</div></article>`).join('');$('#linkList').innerHTML=loadoutHtml+tacticalHtml||'<div class="empty-inline wide">Ничего не найдено.</div>';wireImageFallbacks($('#linkList'));}
export function setHeroRole(role){box.state.heroRole=role;saveState();renderHeroes();}
export function toggleFavorites(){box.state.favoriteOnly=!box.state.favoriteOnly;saveState();renderHeroes();}
export function setLinkType(type){box.state.linkType=type;saveState();renderLinks();}
