import { HERO_BY_ID } from './data.js';

const O=(hero,id,name,partner,summary,tags=[],priority=50)=>({hero,id,name,partner,summary,tags,priority});
export const LOADOUTS=[
O('hulk','savage-slam','Savage Slam','captain-america','Надёжный контроль и более жёсткий вход в ближний бой.',['brawl','control'],55),
O('hulk','gamma-fastball','Gamma Fastball','wolverine','Запускает агрессивный dive и помогает Росомахе добраться до цели.',['dive','burst'],58),
O('the-punisher','ammo-overload','Ammo Overload','rocket-raccoon','Длительная стрельба и меньше пауз на перезарядку.',['sustain-damage','poke'],57),
O('the-punisher','bestial-hunt','Bestial Hunt','daredevil','Лучше добивает отмеченные и изолированные цели.',['pick','burst'],54),
O('storm','god-of-thunder','God of Thunder','thor','Усиливает молниеносный burst и командное зонирование.',['burst','area-control'],58),
O('storm','jaws-of-fate','Jaws of Fate','jeff-the-land-shark','Даёт больше спасения и контроля в затяжной драке.',['save','control'],52),
O('loki','vibrant-vitality','Vibrant Vitality','mantis','Усиливает лечение и полезность иллюзий.',['sustain','utility'],58),
O('loki','villains-illusion','Villain’s Illusion','hela','Добавляет опасную копию и давление по целям.',['burst','clones'],54),
O('doctor-strange','gamma-maelstrom','Gamma Maelstrom','hulk','Сильнее наказывает сгруппированных врагов.',['control','burst'],57),
O('doctor-strange','psionic-vortex','Psionic Vortex','invisible-woman','Создаёт дополнительный слой контроля пространства.',['control','frontline'],60),
O('mantis','star-blossom','Star Blossom','star-lord','Темповое усиление мобильного carry.',['damage-boost','mobility'],54),
O('mantis','vitality-pact','Vitality Pact','adam-warlock','Более надёжный sustain и командная выживаемость.',['sustain','save'],58),
O('hawkeye','moonlit-slash','Moonlit Slash','cloak-and-dagger','Даёт защитную опцию против ближнего давления.',['survival','anti-dive'],56),
O('hawkeye','senbonzakura-strike','Senbonzakura Strike','psylocke','Усиливает точечный burst и добивание.',['pick','burst'],55),
O('captain-america','voltaic-union','Voltaic Union','thor','Молниеносный engage и больше давления щитом.',['dive','burst'],60),
O('captain-america','stars-aligned','Stars Aligned','winter-soldier','Сильнее работает на изоляцию и добивание цели.',['pick','control'],54),
O('rocket-raccoon','planet-x-pals','Planet X Pals','groot','Безопасное лечение из-за прочного фронтлайна.',['sustain','frontline'],59),
O('rocket-raccoon','mammalian-bond','Mammalian Bond','squirrel-girl','Усиливает дальнее давление и экономику боеприпасов.',['poke','utility'],54),
O('hela','hel-tendrils','Hel Tendrils','venom','Добавляет контроль и удобный фокус после dive.',['control','dive'],55),
O('hela','deep-wrath','Deep Wrath','namor','Усиливает дальнее давление и добивание.',['poke','burst'],58),
O('cloak-and-dagger','oblivion-shroud','Oblivion Shroud','the-hood','Дополнительная защита и скрытие для опасного момента.',['save','stealth'],48),
O('cloak-and-dagger','frozen-haven','Frozen Haven','luna-snow','Сильнее удерживает союзников в затяжной драке.',['sustain','control'],60),
O('black-panther','damisa-yao','Damisa-Yao','storm','Ускоряет вход и повышает давление по площади.',['dive','area-control'],57),
O('black-panther','dimensional-shortcut','Dimensional Shortcut','magik','Даёт более безопасный маршрут входа и отхода.',['dive','mobility'],59),
O('groot','wild-wall','Wild Wall','mantis','Стена лучше поддерживает sustain и защиту позиции.',['wall','sustain'],57),
O('groot','bubble-buddies','Bubble Buddies','jeff-the-land-shark','Добавляет спасение и бонусное здоровье фронтлайну.',['save','frontline'],58),
O('magik','chain-of-cyttorak','Chain of Cyttorak','doctor-strange','Даёт надёжный контроль для brawl-комбо.',['control','brawl'],59),
O('magik','void-pentagram','Void Pentagram','the-hood','Повышает мобильность и темп заходов через порталы.',['mobility','dive'],48),
O('moon-knight','luminous-moon','Luminous Moon','cloak-and-dagger','Добавляет световую защиту и стабильность позиции.',['survival','poke'],56),
O('moon-knight','blood-moon','Blood Moon','elsa-bloodstone','Лучше наказывает цели внутри подготовленной зоны.',['setup','burst'],58),
O('luna-snow','atlas-bond','Atlas Bond','white-fox','Ускоряет поддержку и ротации команды.',['mobility','sustain'],59),
O('luna-snow','duality-dance','Duality Dance','adam-warlock','Даёт гибкую светло-тёмную утилиту и burst-heal.',['burst-heal','utility'],57),
O('squirrel-girl','squirrel-missile','Squirrel Missile','iron-man','Добавляет управляемый burst на дальности.',['poke','burst'],58),
O('squirrel-girl','esu-alumnus','ESU Alumnus','spider-man','Улучшает контроль и связку с мобильным dive.',['control','dive'],54),
O('black-widow','allied-agents','Allied Agents','hawkeye','Усиливает совместный дальний pick pressure.',['pick','range'],57),
O('black-widow','burning-bullets','Burning Bullets','phoenix','Добавляет огненный burst и давление по лечению.',['burst','anti-heal'],58),
O('iron-man','gamma-charge','Gamma Charge','hulk','Усиливает лучевой burst и пробивание позиции.',['burst','anti-tank'],59),
O('iron-man','thunder-overdrive','Thunder Overdrive','thor','Даёт более агрессивное воздушное давление.',['flight','burst'],57),
O('venom','blood-leech','Blood Leech','blade','Улучшает самоисцеление в долгом brawl.',['self-sustain','brawl'],58),
O('venom','abyssal-flames','Abyssal Flames','phoenix','Добавляет огненный burst после входа.',['dive','burst'],57),
O('spider-man','symbiote-bond','Symbiote Bond','venom','Безопаснее и сильнее при совместном dive.',['dive','survival'],59),
O('spider-man','parker-power-up','Parker Power-Up','peni-parker','Липкая бомба улучшает завершение комбо.',['burst','setup'],60),
O('magneto','metallic-chaos','Metallic Chaos','scarlet-witch','Добавляет взрывной дальний урон фронтлайну.',['burst','poke'],56),
O('magneto','magnetic-resonance','Magnetic Resonance','emma-frost','Усиливает щиты и контроль линии.',['shield','frontline'],60),
O('scarlet-witch','sorcerers-supreme','Sorcerers Supreme','doctor-strange','Даёт больше контроля и безопасного burst.',['control','burst'],57),
O('scarlet-witch','hex-fireworks','Hex Fireworks','jubilee','Усиливает взрывы по площади и самоподдержку.',['area-control','sustain'],59),
O('thor','ragnarok-rebirth','Ragnarok Rebirth','hela','Повышает агрессию и шанс вернуться в драку.',['brawl','survival'],57),
O('thor','divine-armory','Divine Armory','angela','Усиливает фронтлайн и совместный engage.',['frontline','dive'],59),
O('winter-soldier','timeless-veterans','Timeless Veterans','the-punisher','Сильнее в длительном огневом давлении.',['sustain-damage','range'],55),
O('winter-soldier','expert-instinct','Expert Instinct','elsa-bloodstone','Улучшает контроль и добивание отмеченной цели.',['pick','control'],59),
O('peni-parker','vibranium-mech','Vibranium Mech','black-panther','Повышает мобильность и защиту меха.',['mobility','frontline'],56),
O('peni-parker','rocket-network','Rocket Network','rocket-raccoon','Усиливает setup и технологическую поддержку точки.',['setup','sustain'],60),
O('star-lord','flora-munitions','Flora Munitions','groot','Безопаснее ведёт огонь рядом с фронтлайном.',['range','frontline'],54),
O('star-lord','star-soul','Star-Soul','adam-warlock','Даёт дополнительную жизнь и темп рискованному carry.',['revive','mobility'],60),
O('namor','chilling-charisma','Chilling Charisma','luna-snow','Ледяные призывы лучше держат линию.',['control','poke'],58),
O('namor','gamma-monstro','Gamma Monstro','hulk','Усиливает призванных существ против плотных целей.',['anti-tank','burst'],57),
O('adam-warlock','cosmic-cyclone','Cosmic Cyclone','storm','Добавляет контроль зоны и командную утилиту.',['area-control','utility'],57),
O('adam-warlock','flawless-design','Flawless Design','ultron','Усиливает технологическую поддержку и poke.',['poke','utility'],56),
O('jeff-the-land-shark','guardian-of-the-deep','Guardian of the Deep','venom','Даёт Веному аварийный sustain и бонусное здоровье.',['save','sustain'],60),
O('jeff-the-land-shark','mr-pools-toy-box','Mr. Pool’s Interdimensional Toy Box','deadpool','Добавляет спасение, мобильность и хаотичную утилиту.',['save','utility'],58),
O('psylocke','light-dark-arts','Light & Dark Arts','cloak-and-dagger','Гибкая защита и продолжение dive.',['survival','dive'],58),
O('psylocke','mental-projection','Mental Projection','emma-frost','Усиливает психический burst и фокус цели.',['burst','pick'],59),
O('wolverine','pair-of-threes','Pair of Threes','gambit','Скорость, прыжок и лечение для долгого brawl.',['brawl','sustain'],60),
O('wolverine','blast-slash','Blast Slash','cyclops','Расширяет reach и помогает резать фронтлайн.',['anti-tank','burst'],58),
O('iron-fist','kumiho-palm','Kumiho Palm','white-fox','Даёт больше темпа, лечения и преследования.',['sustain','mobility'],58),
O('iron-fist','iron-and-stone','Iron & Stone','the-thing','Повышает стойкость в ближнем brawl.',['brawl','survival'],56),
O('invisible-woman','united-siblings','United Siblings','human-torch','Помогает огненному carry держать темп и позицию.',['peel','area-control'],55),
O('invisible-woman','first-family','First Family','mister-fantastic','Щиты и peel идеально прикрывают вход Рида.',['shield','brawl'],62),
O('mister-fantastic','fantastic-amplifier','Fantastic Amplifier','rocket-raccoon','Добавляет дальнюю технологическую опцию.',['utility','poke'],55),
O('mister-fantastic','clobberin-research','Clobberin’ Research Dept.','the-thing','Усиливает совместный brawl и удержание пространства.',['brawl','frontline'],59),
O('the-thing','two-in-one','Two in One','human-torch','Фиксирует врагов внутри огненного давления.',['brawl','area-control'],59),
O('the-thing','unbreakable-forces','Unbreakable Forces','invisible-woman','Щиты делают фронтлайн заметно надёжнее.',['shield','frontline'],60),
O('human-torch','fiery-sparks','Fiery Sparks','jubilee','Усиливает взрывы и темп огненных зон.',['burst','area-control'],59),
O('human-torch','storming-ignition','Storming Ignition','storm','Ветер распространяет огонь и улучшает ротации.',['area-control','mobility'],60),
O('ultron','stark-protocol','Stark Protocol','iron-man','Усиливает воздушный poke и общую технологическую связку.',['flight','poke'],58),
O('ultron','spdr-sync','SP//DR Sync','peni-parker','Лучше поддерживает setup и контроль точки.',['setup','utility'],57),
O('emma-frost','iced-out-diamond','Iced Out Diamond','luna-snow','Добавляет ледяной контроль и живучесть фронтлайна.',['control','frontline'],60),
O('emma-frost','spirit-breaker','Spirit Breaker','mantis','Усиливает психический pressure и disruption.',['disrupt','burst'],56),
O('phoenix','circle-of-life','Circle of Life','hela','Повышает выживаемость и темп после размена.',['survival','burst'],57),
O('phoenix','telekinetic-beatdown','Telekinetic Beatdown','rogue','Добавляет контроль и brawl-связку с фронтлайном.',['control','brawl'],59),
O('blade','blade-of-khonshu','Blade of Khonshu','moon-knight','Усиливает охоту ночью и давление по отмеченным целям.',['pick','anti-heal'],57),
O('blade','bleed-for-battle','Bleed for Battle','captain-america','Лучше держится рядом с агрессивным фронтлайном.',['brawl','self-sustain'],59),
O('angela','odins-unacknowledged','Odin’s Unacknowledged','loki','Добавляет обман, защиту и утилиту engage.',['utility','dive'],55),
O('angela','asgardians-galaxy','Asgardians of the Galaxy','star-lord','Поддерживает мобильное давление и преследование.',['mobility','burst'],58),
O('daredevil','comprehensive-defense','Comprehensive Defense','iron-fist','Повышает стойкость и защиту в ближнем бою.',['survival','brawl'],57),
O('daredevil','devilish-affair','Devilish Affair','black-widow','Усиливает совместную охоту на изолированные цели.',['pick','mobility'],60),
O('gambit','favorable-odds','Favorable Odds','magneto','Поддерживает фронтлайн лечением и кинетическим темпом.',['sustain','frontline'],60),
O('gambit','sparkling-staff','Sparkling Staff','jubilee','Усиливает мобильность и взрывной темп поддержки.',['mobility','burst'],57),
O('rogue','mr-mrs-x','Mr. & Mrs. X','gambit','Лучший выбор для самодостаточного brawl-дуо.',['brawl','sustain'],63),
O('rogue','explosive-entanglement','Explosive Entanglement','magneto','Добавляет взрывной контроль вокруг фронтлайна.',['burst','control'],59),
O('deadpool','gumbo-chimichangas','Gumbo Chimichangas','gambit','Смешивает sustain и адаптивный темп.',['sustain','adaptable'],58),
O('deadpool','hel-yeah-honey','Hel-Yeah Honey','hela','Усиливает burst и агрессивные размены.',['burst','pick'],57),
O('elsa-bloodstone','prehistoric-trap','Prehistoric Trap','devil-dinosaur','Контроль превращается в гарантированный burst.',['control','burst'],60),
O('elsa-bloodstone','loudmouth-mercs','Loudmouth Mercs','deadpool','Добавляет мобильную огневую поддержку и хаос.',['range','utility'],55),
O('white-fox','lucky-loan','Lucky Loan','black-cat','Ускоряет погоню и поддерживает фланк.',['mobility','damage-boost'],60),
O('white-fox','psionic-fox','Psionic Fox','psylocke','Поддерживает assassin и помогает пережить выход.',['dive','save'],58),
O('black-cat','feline-alliance','Feline Alliance','black-panther','Усиливает быстрый двойной фланг.',['dive','mobility'],58),
O('black-cat','binding-ties','Binding Ties','spider-man','Лучше фиксирует цель для совместного burst.',['pick','control'],60),
O('devil-dinosaur','surf-turf','Surf & Turf','jeff-the-land-shark','Лучший sustain и спасение для агрессивного фронтлайна.',['brawl','save'],61),
O('devil-dinosaur','primal-punishment','Primal Punishment','the-punisher','Превращает динозавра в платформу длительного огня.',['frontline','sustain-damage'],59),
O('cyclops','slim-and-red','Slim and Red','phoenix','Усиливает burst и давление по линии.',['burst','poke'],58),
O('cyclops','kinetic-kin','Kinetic Kin','gambit','Даёт мобильность и более высокий темп стрельбы.',['mobility','poke'],60),
O('jubilee','hellfire-sparks','Hellfire Sparks','the-hood','Добавляет теневой burst и контроль зоны.',['burst','area-control'],48),
O('jubilee','vampiric-kin','Vampiric Kin','blade','Усиливает sustain и агрессию в ближней драке.',['sustain','brawl'],60)
];

export const LOADOUT_BY_ID=Object.fromEntries(LOADOUTS.map(option=>[option.id,option]));
export const LOADOUTS_BY_HERO=Object.fromEntries(Object.keys(HERO_BY_ID).map(id=>[id,LOADOUTS.filter(option=>option.hero===id)]));
export const FUTURE_PARTNERS={ 'the-hood':'The Hood' };
export function partnerName(id){ return HERO_BY_ID[id]?.name || FUTURE_PARTNERS[id] || id; }
