import { HEROES,HERO_BY_ID } from './data.js';
import { analyzeTeam,compareHeroCandidates,partyRolePlan,recommendHeroes } from './core.js';

export const MAPS=[
{id:'any',name:'Любая карта',mode:'Любой режим',tags:[],note:'Без специального модификатора карты.'},
{id:'thebes',name:'Thebes',mode:'Season 9',tags:['control','mobility','poke','area-control'],note:'Открытые линии, смена высот и важные зоны контроля.'},
{id:'yggdrasill-path',name:'Yggsgard: Yggdrasill Path',mode:'Convoy',tags:['frontline','sustain','mobility','control'],note:'Длинное сопровождение и постоянная смена дистанции.'},
{id:'royal-palace',name:'Yggsgard: Royal Palace',mode:'Domination',tags:['brawl','area-control','sustain','frontline'],note:'Плотные бои за точку и сильная ценность удержания пространства.'},
{id:'shin-shibuya',name:'Tokyo 2099: Shin-Shibuya',mode:'Convergence',tags:['mobility','poke','control','range'],note:'Вертикальность и длинные углы усиливают мобильность и дальнюю игру.'},
{id:'midtown',name:'Empire of Eternal Night: Midtown',mode:'Convoy',tags:['shield','poke','control','frontline'],note:'Коридоры и открытые участки требуют прикрытия и стабильного фронта.'},
{id:'central-park',name:'Empire of Eternal Night: Central Park',mode:'Convergence',tags:['mobility','area-control','save','sustain'],note:'Переходы между пространствами ценят мобильность и спасательные способности.'},
{id:'arakko',name:'Hellfire Gala: Arakko',mode:'Convoy',tags:['poke','mobility','frontline','sustain'],note:'Открытые дистанции перемежаются затяжными боями у груза.'},
{id:'celestial-husk',name:'Klyntar: Celestial Husk',mode:'Domination',tags:['brawl','area-control','control','sustain'],note:'Сильная ценность постоянного присутствия на точке.'},
{id:'other',name:'Другая карта',mode:'Пользовательская',tags:[],note:'Используются только режим, сторона и выбранный стиль.'}
];
export const MAP_BY_ID=Object.fromEntries(MAPS.map(map=>[map.id,map]));
export const MATCH_MODES=[['competitive','Рейтинг'],['quick','Быстрая'],['custom','Своя игра']];
export const SIDES=[['attack','Атака'],['defense','Защита'],['neutral','Без стороны']];
export const INTENTS=[['aggressive','Давить'],['stable','Стабильно'],['experimental','Эксперимент']];
const ARCHETYPES={dive:{label:'DIVE',tags:['dive','mobility','stealth','flank'],counters:['anti-dive','control','peel','save','frontline']},poke:{label:'POKE',tags:['poke','range','pick'],counters:['mobility','dive','shield','flank','save']},brawl:{label:'BRAWL',tags:['brawl','frontline','self-sustain','melee'],counters:['poke','control','anti-tank','mobility','anti-heal']},sustain:{label:'SUSTAIN',tags:['sustain','burst-heal','shield','save'],counters:['burst','anti-heal','pick','anti-tank','disrupt']},setup:{label:'SETUP',tags:['setup','area-control','control','wall'],counters:['range','poke','disrupt','mobility','burst']}};
const SIDE_TAGS={attack:['mobility','burst','dive','disrupt','pick'],defense:['setup','area-control','anti-dive','control','shield'],neutral:['sustain','frontline','utility','control']};
const INTENT_TAGS={aggressive:['burst','dive','brawl','pick','anti-tank'],stable:['sustain','frontline','shield','control','save'],experimental:['adaptable','mobility','utility','disrupt','flex']};
const clamp=(value,min=0,max=100)=>Math.max(min,Math.min(max,Number(value)||0));
const resultWin=result=>result==='win'?1:result==='draw'?0.5:0;
const stateOptions=state=>({mode:state.plannerMode,partySize:state.partySize,loadoutChoices:state.loadoutChoices,players:state.players,playerAssignments:state.playerAssignments,matchContext:state.matchContext,enemyTeam:state.enemyTeam,matchHistory:state.matchHistory});

export function classifyEnemyPlan(ids=[]){const picked=ids.filter(Boolean).map(id=>HERO_BY_ID[id]).filter(Boolean);if(!picked.length)return{id:'unknown',label:'ВРАГИ НЕ УКАЗАНЫ',confidence:0,scores:{},counters:[],picked:0};const scores={};for(const[id,archetype]of Object.entries(ARCHETYPES))scores[id]=picked.reduce((sum,hero)=>sum+archetype.tags.filter(tag=>hero.tags?.includes(tag)).length,0);const[id,score]=Object.entries(scores).sort((a,b)=>b[1]-a[1])[0],total=Object.values(scores).reduce((sum,value)=>sum+value,0)||1;return{id,label:ARCHETYPES[id].label,confidence:clamp(score/total*100),scores,counters:ARCHETYPES[id].counters,picked:picked.length};}
export function buildLocalMeta(history=[]){const records=Array.isArray(history)?history.filter(record=>['win','loss','draw'].includes(record?.result)):[],hero={},pairs={},maps={},loadouts={};let wins=0,comfort=0;for(const record of records){const value=resultWin(record.result);wins+=value;comfort+=clamp(record.comfort,1,5);const team=[...new Set((record.team||[]).filter(id=>HERO_BY_ID[id]))];for(const id of team){const item=hero[id]||={games:0,wins:0,comfort:0};item.games++;item.wins+=value;item.comfort+=clamp(record.comfort,1,5);}for(let i=0;i<team.length;i++)for(let j=i+1;j<team.length;j++){const key=[team[i],team[j]].sort().join('|'),item=pairs[key]||={games:0,wins:0};item.games++;item.wins+=value;}const map=maps[record.mapId||'any']||={games:0,wins:0};map.games++;map.wins+=value;for(const[heroId,loadoutId]of Object.entries(record.loadoutChoices||{})){if(!HERO_BY_ID[heroId])continue;const key=`${heroId}|${loadoutId}`,item=loadouts[key]||={games:0,wins:0};item.games++;item.wins+=value;}}for(const item of Object.values(hero))item.comfort=item.games?item.comfort/item.games:0;return{games:records.length,wins,winRate:records.length?wins/records.length:0,comfort:records.length?comfort/records.length:0,hero,pairs,maps,loadouts};}
export function heroHistoryBonus(heroId,history=[]){const item=buildLocalMeta(history).hero[heroId];if(!item?.games)return 0;const sample=Math.min(1,item.games/8),winSignal=(item.wins/item.games-.5)*22*sample,comfortSignal=(item.comfort-3)*2.5*sample;return clamp(winSignal+comfortSignal,-12,12);}
export function heroContextScore(hero,options={}){const context=options.matchContext||{},map=MAP_BY_ID[context.mapId]||MAP_BY_ID.any,enemy=classifyEnemyPlan(options.enemyTeam||[]),reasons=[];let score=0;const addTags=(tags,weight,reason)=>{const hits=(tags||[]).filter(tag=>hero.tags?.includes(tag)).length;if(hits){score+=hits*weight;reasons.push(`${reason} +${Math.round(hits*weight)}`);}};addTags(map.tags,3.2,map.name);addTags(SIDE_TAGS[context.side]||SIDE_TAGS.neutral,2.5,context.side==='attack'?'атака':context.side==='defense'?'защита':'режим');addTags(INTENT_TAGS[context.intent]||INTENT_TAGS.stable,2.4,context.intent==='aggressive'?'темп':context.intent==='experimental'?'эксперимент':'стабильность');if(enemy.id!=='unknown')addTags(enemy.counters,4.2,`ответ на ${enemy.label}`);const historyBonus=heroHistoryBonus(hero.id,options.matchHistory||[]);if(Math.abs(historyBonus)>=1.5)reasons.push(`${historyBonus>0?'локальная мета':'слабая история'} ${historyBonus>0?'+':''}${Math.round(historyBonus)}`);score+=historyBonus;return{score,reasons:reasons.slice(0,3),enemy,map};}
export function contextualRecommendations(ids,prefs={},options={}){const base=recommendHeroes(ids,prefs,{...options,limit:HEROES.length});return base.map(item=>{const context=heroContextScore(item.hero,options);return{...item,context,score:item.score+context.score,reasons:[...context.reasons,...item.reasons].slice(0,3)};}).sort((a,b)=>b.score-a.score||a.hero.order-b.hero.order).slice(0,options.limit||10);}
export function evaluateMatchPlan(ids,prefs={},options={}){const base=analyzeTeam(ids,prefs,options),limit=options.mode==='party'?(options.partySize||2):6,heroes=ids.slice(0,limit).filter(Boolean).map(id=>HERO_BY_ID[id]).filter(Boolean),values=heroes.map(hero=>heroContextScore(hero,options).score),contextRaw=values.length?values.reduce((sum,value)=>sum+value,0)/values.length:0,context=clamp(50+contextRaw*2.2),overall=heroes.length?clamp(base.overall*.82+context*.18):0;return{...base,baseOverall:base.overall,context,contextDelta:overall-base.overall,overall,enemyPlan:classifyEnemyPlan(options.enemyTeam||[]),map:MAP_BY_ID[options.matchContext?.mapId]||MAP_BY_ID.any};}
export function contextualAutoComplete(ids,locks=[],prefs={},options={}){const result=Array.from({length:6},(_,index)=>ids[index]||null),limit=options.mode==='party'?(options.partySize||2):6,players=new Map((options.players||[]).map(player=>[player.id,player]));for(let index=0;index<limit;index++){if(result[index]||locks[index])continue;const playerProfile=players.get(options.playerAssignments?.[index])||null;result[index]=contextualRecommendations(result,prefs,{...options,limit:1,size:6,playerProfile})[0]?.hero.id||null;}if(options.mode==='party')for(let index=limit;index<6;index++)result[index]=null;return result;}
export function contextualOptimize(ids,locks=[],prefs={},options={}){const limit=options.mode==='party'?(options.partySize||2):6,result=Array.from({length:6},(_,index)=>index<limit&&locks[index]?ids[index]:null),players=new Map((options.players||[]).map(player=>[player.id,player]));for(let index=0;index<limit;index++){if(result[index])continue;const playerProfile=players.get(options.playerAssignments?.[index])||null;result[index]=contextualRecommendations(result,prefs,{...options,limit:1,size:6,playerProfile})[0]?.hero.id||null;}return result;}
export function contextualCompare(firstId,secondId,ids,prefs={},options={}){const base=compareHeroCandidates(firstId,secondId,ids,prefs,options),enhance=item=>{if(!item)return null;const context=heroContextScore(item.hero,options),contextMetric=clamp(50+context.score*2.2);return{...item,context:contextMetric,total:clamp(item.total*.82+contextMetric*.18),reasons:[...context.reasons,...item.reasons].slice(0,3)};},first=enhance(base.first),second=enhance(base.second);return{first,second,winner:!first?second:!second?first:first.total>=second.total?first:second};}
export function replacementSuggestions(state,limit=4){const options=stateOptions(state),currentScore=evaluateMatchPlan(state.team,state.prefs,options).overall,controlled=state.plannerMode==='full'?6:state.partySize,selected=new Set(state.team.slice(0,controlled).filter(Boolean)),suggestions=[];for(let slot=0;slot<controlled;slot++){const current=state.team[slot];if(!current)continue;const locked=Boolean(state.locks?.[slot]),profile=state.players?.find(player=>player.id===state.playerAssignments?.[slot])||null,candidates=contextualRecommendations(state.team,state.prefs,{...options,playerProfile:profile,limit:8});for(const candidate of candidates){if(selected.has(candidate.hero.id))continue;const draft=[...state.team];draft[slot]=candidate.hero.id;const score=evaluateMatchPlan(draft,state.prefs,options).overall;suggestions.push({slot,from:current,to:candidate.hero.id,locked,score,delta:score-currentScore,reasons:candidate.reasons});}}const unique=suggestions.sort((a,b)=>Number(a.locked)-Number(b.locked)||b.delta-a.delta||b.score-a.score).filter((item,index,array)=>array.findIndex(other=>other.slot===item.slot&&other.to===item.to)===index),unlocked=unique.filter(item=>!item.locked);return(unlocked.length?unlocked:unique).slice(0,limit);}
export function buildDecisionTree(state){const branches=[],enemy=classifyEnemyPlan(state.enemyTeam||[]),replacements=replacementSuggestions(state,3);if(enemy.id!=='unknown'){const best=replacements[0];branches.push({trigger:`Если враг продолжает ${enemy.label}`,action:best?`${HERO_BY_ID[best.from]?.name} → ${HERO_BY_ID[best.to]?.name}`:'Сохранять текущий состав',reason:best?best.reasons.join(' · '):`В составе уже достаточно инструментов против ${enemy.label}.`,tone:'enemy'});}if(state.plannerMode==='party'){const plan=partyRolePlan(state.team,state.partySize),need=Object.entries(plan.requiredRoles).filter(([,value])=>value).map(([role,value])=>`${value} ${role}`).join(' · ');branches.push({trigger:'Если рандомы ещё ничего не показали',action:plan.unfixable?'Освободить один управляемый слот под нужную роль':'Не паниковать и дождаться чужих пиков',reason:plan.unfixable?'Текущий перекос уже нельзя полностью исправить оставшимися местами.':`Безопасный бюджет для матчмейкинга: ${need||'роли уже гибкие'}.`,tone:'roles'});}const map=MAP_BY_ID[state.matchContext?.mapId]||MAP_BY_ID.any;if(map.id!=='any')branches.push({trigger:`Если бой упирается в геометрию ${map.name}`,action:`Опирайтесь на ${map.tags.slice(0,2).join(' + ')||'сильные стороны состава'}`,reason:map.note,tone:'map'});if(replacements[1])branches.push({trigger:'Если основной план не работает после первого боя',action:`${HERO_BY_ID[replacements[1].from]?.name} → ${HERO_BY_ID[replacements[1].to]?.name}`,reason:`Минимальная перестройка, прогноз ${replacements[1].delta>=0?'+':''}${Math.round(replacements[1].delta)} к Match Score.`,tone:'fallback'});if(!branches.length)branches.push({trigger:'После первого боя',action:'Сначала определить план врага',reason:'Добавьте хотя бы один вражеский пик — появятся конкретные ветки и замены.',tone:'empty'});return branches.slice(0,4);}
