import { HEROES, HERO_BY_ID } from './data.js';
import {
  MAPS,
  MAP_BY_ID,
  MATCH_MODES,
  SIDES,
  INTENTS,
  classifyEnemyPlan,
  buildLocalMeta,
  replacementSuggestions,
  buildDecisionTree
} from './match-core.js';
import {
  box,
  $,
  esc,
  portrait,
  wireImageFallbacks,
  activeLimit,
  saveState,
  openSheet,
  closeSheet,
  toast,
  clickSound,
  haptic,
  clamp
} from './store.js';

const mapName=id=>MAP_BY_ID[id]?.name||'Другая карта';
const controlledIds=state=>state.team.slice(0,state.plannerMode==='full'?6:state.partySize).filter(Boolean);
const emitChanged=()=>{saveState();document.dispatchEvent(new CustomEvent('rival-forge:match-changed'));};

function contextControlsHTML(){
  const context=box.state.matchContext;
  return `<div class="match-context-grid">
    <label><span>ОЧЕРЕДЬ</span><select id="matchModeSelect">${MATCH_MODES.map(([value,label])=>`<option value="${value}" ${context.mode===value?'selected':''}>${label}</option>`).join('')}</select></label>
    <label><span>КАРТА</span><select id="matchMapSelect">${MAPS.map(map=>`<option value="${map.id}" ${context.mapId===map.id?'selected':''}>${esc(map.name)}</option>`).join('')}</select></label>
  </div>
  <div class="match-segment"><span>СТОРОНА</span><div>${SIDES.map(([value,label])=>`<button class="${context.side===value?'active':''}" data-match-context="side:${value}">${label}</button>`).join('')}</div></div>
  <div class="match-segment"><span>ПЛАН</span><div>${INTENTS.map(([value,label])=>`<button class="${context.intent===value?'active':''}" data-match-context="intent:${value}">${label}</button>`).join('')}</div></div>`;
}
function enemySlotsHTML(){return box.state.enemyTeam.map((id,index)=>{const hero=HERO_BY_ID[id];return hero?`<article class="enemy-slot" style="--enemy:${hero.color}"><button class="enemy-main" data-enemy-slot="${index}">${portrait(hero)}<span>${esc(hero.name)}</span></button><button class="enemy-remove" data-clear-enemy="${index}">×</button></article>`:`<button class="enemy-slot empty" data-enemy-slot="${index}"><b>＋</b><span>ВРАГ ${index+1}</span></button>`;}).join('');}
function replacementHTML(items){if(!items.length)return'<div class="empty-inline wide">Заполни хотя бы один управляемый слот — появятся безопасные замены.</div>';return items.map(item=>`<article class="replacement-card ${item.locked?'locked':''}"><div class="replacement-faces">${portrait(HERO_BY_ID[item.from])}<span>→</span>${portrait(HERO_BY_ID[item.to])}</div><div><span>СЛОТ ${item.slot+1} · ${item.locked?'ЗАКРЕПЛЁН · ':''}${item.delta>=0?'+':''}${Math.round(item.delta)}</span><h3>${esc(HERO_BY_ID[item.to].name)}</h3><p>${esc(item.reasons.join(' · '))}</p></div><button data-apply-replacement="${item.slot}:${item.to}">${item.locked?'Разблокировать и заменить':'Заменить'}</button></article>`).join('');}

export function renderMatchPanels(){
  const contextRoot=$('#matchContextPanel');if(contextRoot){const map=MAP_BY_ID[box.state.matchContext.mapId]||MAP_BY_ID.any;contextRoot.innerHTML=`<div class="section-head"><div><span class="section-kicker">MATCH CONTEXT</span><h2>Условия текущего матча</h2></div><b class="context-map-mode">${esc(map.mode)}</b></div>${contextControlsHTML()}<p class="context-note">${esc(map.note)}</p>`;}
  const enemyRoot=$('#enemyIntelPanel');if(enemyRoot){const plan=classifyEnemyPlan(box.state.enemyTeam);enemyRoot.innerHTML=`<div class="section-head"><div><span class="section-kicker">ENEMY READ</span><h2>Что показывает враг</h2></div><button class="text-button" id="clearEnemiesButton">Очистить</button></div><div class="enemy-slots">${enemySlotsHTML()}</div><div class="enemy-plan"><span>${plan.label}</span><b>${plan.picked?`${Math.round(plan.confidence)}% уверенности`:'добавьте известные пики'}</b><p>${plan.id==='unknown'?'Контрпики появятся после первого известного героя.':`Приоритет ответа: ${plan.counters.slice(0,4).join(' · ')}`}</p></div>`;wireImageFallbacks(enemyRoot);}
  const responseRoot=$('#matchResponsePanel');if(responseRoot){responseRoot.innerHTML=`<div class="section-head"><div><span class="section-kicker">LOW-DAMAGE SWITCHES</span><h2>Кого заменить</h2></div></div><div class="replacement-list">${replacementHTML(replacementSuggestions(box.state,4))}</div>`;wireImageFallbacks(responseRoot);}
  const treeRoot=$('#decisionTreePanel');if(treeRoot)treeRoot.innerHTML=`<div class="section-head"><div><span class="section-kicker">LIVE DECISION TREE</span><h2>План на выбор героев</h2></div></div><div class="decision-tree">${buildDecisionTree(box.state).map((branch,index)=>`<article class="decision-card ${branch.tone}"><span>${String(index+1).padStart(2,'0')} · ${esc(branch.trigger)}</span><h3>${esc(branch.action)}</h3><p>${esc(branch.reason)}</p></article>`).join('')}</div>`;
  const historyRoot=$('#matchHistoryPanel');if(historyRoot){const meta=buildLocalMeta(box.state.matchHistory);historyRoot.innerHTML=`<div class="section-head"><div><span class="section-kicker">GROUP MEMORY</span><h2>История и локальная мета</h2></div><b>${meta.games} игр</b></div><div class="memory-score"><div><b>${meta.games?Math.round(meta.winRate*100):'—'}%</b><span>винрейт</span></div><div><b>${meta.games?meta.comfort.toFixed(1):'—'}</b><span>комфорт</span></div><div><b>${Object.keys(meta.hero).length}</b><span>героев</span></div></div><div class="memory-actions"><button id="openMatchLogButton">Записать матч</button><button id="openHistoryButton">История</button><button id="openLocalMetaButton">Локальная мета</button></div><p>Статистика влияет мягко и только после нескольких игр. Она не считается доказательством причины победы или поражения.</p>`;}
}
export function setMatchContext(field,value){if(!['mode','mapId','side','intent'].includes(field))return;if(field==='mapId'&&!MAP_BY_ID[value])value='any';if(field==='mode'&&!MATCH_MODES.some(item=>item[0]===value))return;if(field==='side'&&!SIDES.some(item=>item[0]===value))return;if(field==='intent'&&!INTENTS.some(item=>item[0]===value))return;box.state.matchContext[field]=value;emitChanged();haptic();}

let enemyPickerSlot=0,enemySearch='';
export function openEnemyPicker(slot){enemyPickerSlot=Math.max(0,Math.min(5,Number(slot)||0));enemySearch='';renderEnemyPicker();openSheet('enemyPickerSheet');}
export function setEnemySearch(value){enemySearch=String(value||'');renderEnemyPicker();}
export function renderEnemyPicker(){const root=$('#enemyPickerGrid');if(!root)return;const query=enemySearch.trim().toLowerCase(),selected=new Set(box.state.enemyTeam.filter(Boolean)),heroes=HEROES.filter(hero=>!query||`${hero.name} ${hero.role} ${hero.archetype} ${hero.tags.join(' ')}`.toLowerCase().includes(query));$('#enemyPickerSearch').value=enemySearch;$('#enemyPickerTitle').textContent=`Вражеский слот ${enemyPickerSlot+1}`;root.innerHTML=`<button class="picker-card clear-pick" data-clear-enemy="${enemyPickerSlot}"><span class="clear-symbol">×</span><span>Неизвестно</span></button>${heroes.map(hero=>`<button class="picker-card ${selected.has(hero.id)?'already-picked':''}" data-pick-enemy="${hero.id}" style="--role-soft:${hero.color}28">${portrait(hero)}<span>${esc(hero.name)}</span><i class="picker-score">${hero.role[0]}</i></button>`).join('')}`;wireImageFallbacks(root);}
export function pickEnemy(heroId){if(!HERO_BY_ID[heroId])return;const existing=box.state.enemyTeam.indexOf(heroId);if(existing>=0&&existing!==enemyPickerSlot)box.state.enemyTeam[existing]=box.state.enemyTeam[enemyPickerSlot]||null;box.state.enemyTeam[enemyPickerSlot]=heroId;closeSheet(false);emitChanged();clickSound('good');haptic(10);}
export function clearEnemySlot(slot){box.state.enemyTeam[Math.max(0,Math.min(5,Number(slot)||0))]=null;if(box.activeSheet==='enemyPickerSheet')closeSheet(false);emitChanged();}
export function clearEnemies(){if(!box.state.enemyTeam.some(Boolean)||confirm('Очистить все известные вражеские пики?')){box.state.enemyTeam=[null,null,null,null,null,null];emitChanged();}}
export function applyReplacement(value){const[slotRaw,heroId]=String(value).split(':'),slot=Number(slotRaw);if(!HERO_BY_ID[heroId]||slot<0||slot>=activeLimit())return;const existing=box.state.team.slice(0,activeLimit()).indexOf(heroId);if(existing>=0&&existing!==slot)box.state.team[existing]=box.state.team[slot];box.state.team[slot]=heroId;box.state.locks[slot]=false;emitChanged();clickSound('good');haptic([10,20,10]);}

export function openMatchLog(){const root=$('#matchLogSheetContent');if(!root)return;const map=MAP_BY_ID[box.state.matchContext.mapId]||MAP_BY_ID.any;root.innerHTML=`<div class="match-log-summary"><span>${esc(map.name)} · ${box.state.matchContext.side==='attack'?'Атака':box.state.matchContext.side==='defense'?'Защита':'Без стороны'}</span><h3>${controlledIds(box.state).map(id=>HERO_BY_ID[id]?.name).filter(Boolean).join(' + ')||'Состав пока пуст'}</h3></div><fieldset class="result-picker"><legend>РЕЗУЛЬТАТ</legend><label><input type="radio" name="matchResult" value="win" checked><span>Победа</span></label><label><input type="radio" name="matchResult" value="loss"><span>Поражение</span></label><label><input type="radio" name="matchResult" value="draw"><span>Ничья</span></label></fieldset><label class="profile-field"><span>НАСКОЛЬКО УДОБНО ИГРАЛОСЬ · <output id="matchComfortOutput">3</output>/5</span><input id="matchComfort" type="range" min="1" max="5" value="3"></label><label class="profile-field"><span>ЧЕГО НЕ ХВАТИЛО</span><input id="matchMissing" maxlength="120" placeholder="например: защиты от dive"></label><label class="profile-field"><span>ЗАМЕТКА</span><textarea id="matchNotes" class="hero-notes" maxlength="500" placeholder="что реально сработало или сломалось"></textarea></label><button id="saveMatchRecordButton" class="hero-add-command">СОХРАНИТЬ МАТЧ <span>＋</span></button>`;openSheet('matchLogSheet');}
export function saveMatchRecord(){const result=$('#matchLogSheet input[name="matchResult"]:checked')?.value||'win',record={id:crypto.randomUUID?.()||`match-${Date.now().toString(36)}`,playedAt:Date.now(),result,mode:box.state.matchContext.mode,mapId:box.state.matchContext.mapId,side:box.state.matchContext.side,intent:box.state.matchContext.intent,team:[...box.state.team],playerAssignments:[...box.state.playerAssignments],loadoutChoices:{...box.state.loadoutChoices},enemyTeam:[...box.state.enemyTeam],comfort:clamp($('#matchComfort')?.value||3,1,5),missing:String($('#matchMissing')?.value||'').trim().slice(0,120),notes:String($('#matchNotes')?.value||'').trim().slice(0,500)};box.state.matchHistory.unshift(record);box.state.matchHistory=box.state.matchHistory.slice(0,160);closeSheet(false);emitChanged();clickSound('good');haptic([12,25,12]);toast('Матч добавлен в локальную мету.','good');}
export function renderHistorySheet(){const root=$('#historySheetContent');if(!root)return;root.innerHTML=box.state.matchHistory.length?box.state.matchHistory.map(record=>`<article class="history-card ${record.result}"><header><div><span>${new Date(record.playedAt).toLocaleString('ru-RU',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}</span><h3>${record.result==='win'?'Победа':record.result==='loss'?'Поражение':'Ничья'} · ${esc(mapName(record.mapId))}</h3></div><b>${record.comfort||3}/5</b></header><div class="history-faces">${(record.team||[]).filter(Boolean).map(id=>HERO_BY_ID[id]?portrait(HERO_BY_ID[id]):'').join('')}</div>${record.missing?`<p><b>Не хватило:</b> ${esc(record.missing)}</p>`:''}${record.notes?`<p>${esc(record.notes)}</p>`:''}<button data-delete-match="${record.id}">Удалить запись</button></article>`).join(''):'<div class="saved-empty">История пуста. Запишите первый матч после игры.</div>';wireImageFallbacks(root);openSheet('historySheet');}
export function deleteMatchRecord(id){const record=box.state.matchHistory.find(item=>item.id===id);if(!record||!confirm('Удалить эту запись матча?'))return;box.state.matchHistory=box.state.matchHistory.filter(item=>item.id!==id);saveState();document.dispatchEvent(new CustomEvent('rival-forge:match-changed'));renderHistorySheet();}
const rate=item=>item?.games?item.wins/item.games:0;
export function renderLocalMetaSheet(){const root=$('#localMetaSheetContent');if(!root)return;const meta=buildLocalMeta(box.state.matchHistory),heroes=Object.entries(meta.hero).sort((a,b)=>rate(b[1])-rate(a[1])||b[1].games-a[1].games).slice(0,8),pairs=Object.entries(meta.pairs).filter(([,item])=>item.games>=2).sort((a,b)=>rate(b[1])-rate(a[1])||b[1].games-a[1].games).slice(0,6),maps=Object.entries(meta.maps).sort((a,b)=>b[1].games-a[1].games).slice(0,6);root.innerHTML=`<div class="local-meta-hero"><b>${meta.games?Math.round(meta.winRate*100):'—'}%</b><span>ЛОКАЛЬНЫЙ ВИНРЕЙТ · ${meta.games} ИГР</span><p>Маленькие выборки специально имеют слабый вес в рекомендациях.</p></div><section class="meta-section"><h3>ГЕРОИ ГРУППЫ</h3><div class="meta-list">${heroes.length?heroes.map(([id,item])=>`<div>${portrait(HERO_BY_ID[id])}<span><b>${esc(HERO_BY_ID[id].name)}</b><small>${item.games} игр · комфорт ${item.comfort.toFixed(1)}</small></span><strong>${Math.round(rate(item)*100)}%</strong></div>`).join(''):'<div class="saved-empty compact">Пока нет данных.</div>'}</div></section><section class="meta-section"><h3>ПРОВЕРЕННЫЕ ДУО</h3><div class="meta-pairs">${pairs.length?pairs.map(([key,item])=>`<div><span>${key.split('|').map(id=>HERO_BY_ID[id]?.name).filter(Boolean).join(' + ')}</span><b>${Math.round(rate(item)*100)}%</b><small>${item.games} игр</small></div>`).join(''):'<div class="saved-empty compact">Для связок нужно минимум две игры.</div>'}</div></section><section class="meta-section"><h3>КАРТЫ</h3><div class="meta-pairs">${maps.map(([id,item])=>`<div><span>${esc(mapName(id))}</span><b>${Math.round(rate(item)*100)}%</b><small>${item.games} игр</small></div>`).join('')||'<div class="saved-empty compact">Пока нет данных.</div>'}</div></section>`;wireImageFallbacks(root);openSheet('localMetaSheet');}
