import { HERO_BY_ID } from './data.js';
import { playerHeroFit } from './core.js';
import { box,$,esc,portrait,wireImageFallbacks,saveState,openSheet,closeSheet,toast,haptic,clickSound,activeLimit,assignedPlayer } from './store.js';

const ROLES=['Vanguard','Duelist','Strategist'];
const STYLES={aggressive:'Агрессивный',supportive:'Поддержка',tactical:'Тактический',mobile:'Мобильный',steady:'Стабильный'};
const COLORS=['#9d65ff','#2dbf9f','#ff6b4a','#f2bd31','#77a9ff','#ff4f8b'];
let editingPlayerId=null,assignmentSlot=0;
const notify=()=>document.dispatchEvent(new CustomEvent('rival-forge:profiles-changed'));
const initials=name=>String(name||'?').split(/\s+/).map(part=>part[0]).join('').slice(0,2).toUpperCase();
const player=id=>box.state.players.find(item=>item.id===id)||null;
const playerChip=(item,small=false)=>`<span class="player-avatar ${small?'small':''}" style="--player:${item.color}">${esc(initials(item.name))}</span>`;

export function renderPlayerDock(){
  const root=$('#playerDock');if(!root)return;const limit=activeLimit();
  root.innerHTML=`<div class="player-dock-head"><div><span class="section-kicker">WHO PLAYS WHAT</span><h2>Игроки в этой сборке</h2></div><button id="openPlayersButton" class="text-button">Профили</button></div><div class="player-dock-rail">${Array.from({length:limit},(_,slot)=>{const assigned=assignedPlayer(slot),hero=HERO_BY_ID[box.state.team[slot]];return`<button class="player-dock-card ${assigned?'assigned':'empty'}" data-assign-player="${slot}" style="--player:${assigned?.color||'#bbb'}"><span class="slot-number">${slot+1}</span>${assigned?playerChip(assigned):'<span class="player-avatar">＋</span>'}<span class="player-dock-copy"><b>${esc(assigned?.name||'Назначить')}</b><small>${hero?esc(hero.name):assigned?`${assigned.primaryRole} · ${STYLES[assigned.style]}`:'кто играет в этом слоте'}</small></span></button>`;}).join('')}</div>`;
}

export function openPlayersSheet(id=null){editingPlayerId=player(id)?.id||box.state.players[0]?.id||null;renderPlayersSheet();openSheet('playersSheet');}
export function renderPlayersSheet(){
  const root=$('#playersSheetContent');if(!root)return;const selected=player(editingPlayerId)||box.state.players[0]||null;if(selected)editingPlayerId=selected.id;
  root.innerHTML=`<div class="profile-rail">${box.state.players.map(item=>`<button class="profile-tab ${item.id===editingPlayerId?'active':''}" data-edit-player="${item.id}">${playerChip(item)}<span>${esc(item.name)}</span></button>`).join('')}<button class="profile-tab add" data-add-player="1"><span class="player-avatar">＋</span><span>Новый</span></button></div>${selected?profileEditor(selected):'<div class="saved-empty">Добавьте первого игрока.</div>'}`;
  wireImageFallbacks(root);
}
function profileEditor(item){
  const skills=Object.entries(item.heroSkill||{}).sort((a,b)=>b[1]-a[1]).slice(0,6),blocked=item.blocked||[];
  return`<section class="profile-editor" style="--player:${item.color}"><header><span class="player-avatar large" style="--player:${item.color}">${esc(initials(item.name))}</span><div><span>PLAYER PROFILE</span><h3>${esc(item.name)}</h3></div></header><label class="profile-field"><span>ИМЯ</span><input data-player-field="name" value="${esc(item.name)}" maxlength="32"></label><div class="profile-field-grid"><label class="profile-field"><span>ОСНОВНАЯ РОЛЬ</span><select data-player-field="primaryRole">${ROLES.map(role=>`<option ${role===item.primaryRole?'selected':''}>${role}</option>`).join('')}</select></label><label class="profile-field"><span>ЗАПАСНАЯ РОЛЬ</span><select data-player-field="backupRole">${ROLES.map(role=>`<option ${role===item.backupRole?'selected':''}>${role}</option>`).join('')}</select></label></div><label class="profile-field"><span>СТИЛЬ ИГРЫ</span><select data-player-field="style">${Object.entries(STYLES).map(([value,label])=>`<option value="${value}" ${value===item.style?'selected':''}>${label}</option>`).join('')}</select></label><div class="profile-colors"><span>ЦВЕТ</span><div>${COLORS.map(color=>`<button class="${color.toLowerCase()===item.color.toLowerCase()?'active':''}" style="--swatch:${color}" data-player-color="${color}" aria-label="${color}"></button>`).join('')}</div></div><section class="profile-summary"><header><span>ЛУЧШИЕ ГЕРОИ</span><small>редактируются в карточке героя</small></header><div class="profile-hero-list">${skills.length?skills.map(([heroId,value])=>{const hero=HERO_BY_ID[heroId];return hero?`<button data-open-hero="${hero.id}">${portrait(hero)}<span>${esc(hero.name)}</span><b>${Math.round(value)}</b></button>`:'';}).join(''):'<div class="saved-empty compact">Откройте героя и задайте навык этого игрока.</div>'}</div><p>${blocked.length?`Исключено героев: ${blocked.length}`:'Нет запрещённых героев.'}</p></section>${box.state.players.length>1?`<button class="profile-delete" data-delete-player="${item.id}">Удалить профиль</button>`:''}</section>`;
}
export function selectEditingPlayer(id){if(!player(id))return;editingPlayerId=id;renderPlayersSheet();clickSound();}
export function addPlayer(){if(box.state.players.length>=8)return toast('Поддерживается до восьми профилей.','bad');const index=box.state.players.length+1,id=`player-${Date.now().toString(36)}`,item={id,name:`Игрок ${index}`,color:COLORS[(index-1)%COLORS.length],primaryRole:'Duelist',backupRole:'Strategist',style:'steady',heroSkill:{},blocked:[]};box.state.players.push(item);editingPlayerId=id;saveState();renderPlayersSheet();notify();clickSound('good');}
export function deletePlayer(id){const item=player(id);if(!item||box.state.players.length<=1||!confirm(`Удалить профиль «${item.name}»?`))return;box.state.players=box.state.players.filter(profile=>profile.id!==id);box.state.playerAssignments=box.state.playerAssignments.map(value=>value===id?null:value);editingPlayerId=box.state.players[0]?.id||null;saveState();renderPlayersSheet();notify();}
export function updateProfileField(field,value){const item=player(editingPlayerId);if(!item)return;if(field==='name')item.name=String(value).trimStart().slice(0,32)||'Игрок';if(field==='primaryRole'&&ROLES.includes(value))item.primaryRole=value;if(field==='backupRole'&&ROLES.includes(value))item.backupRole=value;if(field==='style'&&STYLES[value])item.style=value;saveState();notify();}
export function updateProfileColor(color){const item=player(editingPlayerId);if(!item||!COLORS.includes(color))return;item.color=color;saveState();renderPlayersSheet();notify();haptic();}

export function openAssignmentSheet(slot){assignmentSlot=Math.max(0,Math.min(activeLimit()-1,Number(slot)||0));renderAssignmentSheet();openSheet('assignmentSheet');}
export function renderAssignmentSheet(){const root=$('#assignmentSheetContent');if(!root)return;const current=box.state.playerAssignments[assignmentSlot];root.innerHTML=`<div class="assignment-summary"><span>СЛОТ ${assignmentSlot+1}</span><h3>${HERO_BY_ID[box.state.team[assignmentSlot]]?.name||'Пока без героя'}</h3><p>Назначенный игрок меняет рекомендации, автоподбор и оценку состава.</p></div><div class="assignment-list"><button class="assignment-card ${!current?'active':''}" data-select-player=""><span class="player-avatar">×</span><div><b>Без игрока</b><small>оценивать только героя и состав</small></div></button>${box.state.players.map(item=>{const fit=HERO_BY_ID[box.state.team[assignmentSlot]]?playerHeroFit(HERO_BY_ID[box.state.team[assignmentSlot]],item):null;return`<button class="assignment-card ${current===item.id?'active':''}" data-select-player="${item.id}" style="--player:${item.color}">${playerChip(item)}<div><b>${esc(item.name)}</b><small>${item.primaryRole} · ${STYLES[item.style]}${fit?` · подходит на ${Math.round(fit.score)}`:''}</small></div></button>`;}).join('')}</div>`;}
export function assignPlayer(id){if(id&&!player(id))return;for(let i=0;i<box.state.playerAssignments.length;i++)if(box.state.playerAssignments[i]===id)box.state.playerAssignments[i]=null;box.state.playerAssignments[assignmentSlot]=id||null;box.state.recommendationSlot=assignmentSlot;saveState();closeSheet(false);notify();clickSound('good');haptic();}

export function playerHeroEditorHTML(heroId){const hero=HERO_BY_ID[heroId];if(!hero||!box.state.players.length)return'';return`<section class="editor-block player-skill-editor"><span>КТО КАК ИГРАЕТ ЭТИМ ГЕРОЕМ</span><p>Навык и запреты учитываются только при назначении конкретного игрока в слот.</p>${box.state.players.map(item=>{const value=item.heroSkill?.[hero.id]??50,blocked=item.blocked?.includes(hero.id),fit=playerHeroFit(hero,item);return`<div class="player-skill-row ${blocked?'blocked':''}" style="--player:${item.color}">${playerChip(item,true)}<div><header><b>${esc(item.name)}</b><output id="playerSkillOutput-${item.id}">${Math.round(value)}</output></header><input type="range" min="0" max="100" value="${value}" data-player-skill="${item.id}" data-hero-id="${hero.id}"><small>${blocked?'ИСКЛЮЧЁН ИЗ РЕКОМЕНДАЦИЙ':`совместимость ${Math.round(fit.score)}`}</small></div><button data-toggle-player-block="${item.id}:${hero.id}" class="block-hero ${blocked?'active':''}">${blocked?'Вернуть':'Исключить'}</button></div>`;}).join('')}</section>`;}
export function updatePlayerHeroSkill(playerId,heroId,value){const item=player(playerId);if(!item||!HERO_BY_ID[heroId])return;item.heroSkill||={};item.heroSkill[heroId]=Math.max(0,Math.min(100,Number(value)||0));saveState();const output=$(`#playerSkillOutput-${CSS.escape(playerId)}`);if(output)output.textContent=Math.round(item.heroSkill[heroId]);notify();}
export function togglePlayerHeroBlocked(value){const [playerId,heroId]=String(value).split(':'),item=player(playerId);if(!item||!HERO_BY_ID[heroId])return;const set=new Set(item.blocked||[]);set.has(heroId)?set.delete(heroId):set.add(heroId);item.blocked=[...set];saveState();notify();clickSound(set.has(heroId)?'bad':'good');}
