import { SNAPSHOT,HERO_BY_ID,TEAM_UPS,TIERS } from './data.js';
import { recommendLoadouts,heroRating,playerHeroFit,analyzeTeam,exportPayload,normalizeImported } from './core.js';
import { box,$,esc,portrait,wireImageFallbacks,roleLabel,roleTabs,activeLimit,activeIds,assignedPlayer,planOptions,saveState,replaceState,openSheet,closeSheet,setView,toast,clickSound,clamp,defaults } from './store.js';
import { filteredHeroes,renderHeroes,renderTiers,renderLinks } from './catalog.js';
import { renderBuilder,placeHero,loadoutOptionHTML,verdictFor } from './builder.js';
import { playerHeroEditorHTML } from './profiles.js';

let pickerSlot=0,pickerRole='All',pickerSearch='',currentHeroId=null,heroAddSlot=null;
export function openPicker(slot){if(box.state.plannerMode==='party'&&slot>=box.state.partySize)return;pickerSlot=Math.max(0,Math.min(activeLimit()-1,Number(slot)||0));box.state.recommendationSlot=pickerSlot;saveState();pickerRole='All';pickerSearch='';const player=assignedPlayer(pickerSlot);$('#pickerTitle').textContent=box.state.team[pickerSlot]?`Заменить слот ${pickerSlot+1}${player?` · ${player.name}`:''}`:`Заполнить слот ${pickerSlot+1}${player?` · ${player.name}`:''}`;renderPicker();openSheet('pickerSheet');}
export function renderPicker(){const search=$('#pickerSearch');if(search)search.value=pickerSearch;$('#pickerRoleTabs').innerHTML=roleTabs(pickerRole,'picker-role');const heroes=filteredHeroes({picker:true,pickerRole,pickerSearch}),selected=new Set(activeIds().filter(Boolean)),player=assignedPlayer(pickerSlot);$('#pickerGrid').innerHTML=`<button class="picker-card clear-pick" data-clear-picker="1"><span class="clear-symbol">×</span><span>Оставить пустым</span></button>${heroes.filter(hero=>!player?.blocked?.includes(hero.id)).map(hero=>{const fit=playerHeroFit(hero,player);return`<button class="picker-card ${selected.has(hero.id)?'already-picked':''}" data-picker-hero="${hero.id}" style="--role-soft:${hero.color}28">${portrait(hero)}<span>${esc(hero.name)}</span><i class="picker-score">${player?Math.round(fit.score):Math.round(heroRating(hero,box.state.prefs))}</i>${player?`<small>${esc(player.name)}</small>`:''}</button>`;}).join('')}`;wireImageFallbacks($('#pickerGrid'));}
export function setPickerRole(role){pickerRole=role;renderPicker();}
export function setPickerSearch(value){pickerSearch=value;renderPicker();}
export function pickHero(id){placeHero(id,pickerSlot);closeSheet(false);}
export function clearPicker(){box.state.team[pickerSlot]=null;box.state.locks[pickerSlot]=false;saveState();renderBuilder();closeSheet(false);}
function heroLoadoutEditor(heroId){const item=recommendLoadouts([heroId,...activeIds().filter(id=>id&&id!==heroId)],box.state.loadoutChoices).find(x=>x.heroId===heroId);if(!item)return'';return`<section class="editor-block hero-loadout-editor"><span>КОМАНДНАЯ СПОСОБНОСТЬ</span><p>Базовая версия работает всегда. Выбранный партнёр включает усиление.</p>${item.options.map(option=>loadoutOptionHTML(option,item)).join('')}</section>`;}
export function openHero(heroId){heroAddSlot=box.activeSheet==='pickerSheet'?pickerSlot:null;const hero=HERO_BY_ID[heroId];if(!hero)return;currentHeroId=hero.id;renderHeroSheet();openSheet('heroSheet');}
export function renderHeroSheet(){const hero=HERO_BY_ID[currentHeroId];if(!hero)return;const score=box.state.prefs.scores[hero.id]??hero.power,confidence=box.state.prefs.confidence[hero.id]??50,tier=box.state.prefs.tiers[hero.id]||hero.tier,rating=Math.round(heroRating(hero,box.state.prefs)),favorite=box.state.prefs.favorites.includes(hero.id),links=TEAM_UPS.filter(link=>link.type==='tactical'&&link.members.includes(hero.id));$('#heroSheetContent').innerHTML=`<div class="hero-hero" style="--role-soft:${hero.color}32">${portrait(hero)}<button class="favorite-button ${favorite?'active':''}" data-favorite-hero="${hero.id}">★</button><div class="hero-hero-copy"><h2>${esc(hero.name)}</h2><p>${esc(roleLabel(hero))} · ${esc(hero.archetype)}</p></div></div><div class="hero-metrics"><div class="hero-metric"><span>ИТОГ</span><b id="sheetRating">${rating}</b></div><div class="hero-metric"><span>ТИР</span><b id="sheetTier">${tier}</b></div><div class="hero-metric"><span>СЛОЖНОСТЬ</span><b>${'◆'.repeat(hero.difficulty)}${'◇'.repeat(5-hero.difficulty)}</b></div></div><button class="hero-add-command" data-add-hero="${hero.id}" ${heroAddSlot!==null?`data-add-slot="${heroAddSlot}"`:''}>ДОБАВИТЬ В ${box.state.plannerMode==='party'?'ПАТИ':'КОМАНДУ'} <span>＋</span></button>${heroLoadoutEditor(hero.id)}${playerHeroEditorHTML(hero.id)}<section class="editor-block"><label><span>СИЛА ПЕРСОНАЖА <b id="powerOutput">${score}</b></span><input id="heroPowerRange" type="range" min="0" max="100" value="${score}"></label></section><section class="editor-block"><label><span>МОЯ ОБЩАЯ УВЕРЕННОСТЬ <b id="confidenceOutput">${confidence}</b></span><input id="heroConfidenceRange" type="range" min="0" max="100" value="${confidence}"></label></section><section class="editor-block"><span>ПОЗИЦИЯ В ТИРЛИСТЕ</span><div class="tier-buttons">${TIERS.map(value=>`<button class="${tier===value?'active':''}" data-set-tier="${value}">${value}</button>`).join('')}</div></section><section class="editor-block"><span>ИНСТРУМЕНТЫ</span><div class="tag-cloud">${hero.tags.map(tag=>`<span class="tag">${esc(tag)}</span>`).join('')}</div></section><section class="editor-block"><label><span>ЛИЧНЫЕ ЗАМЕТКИ</span><textarea id="heroNotes" class="hero-notes">${esc(box.state.prefs.notes[hero.id]||'')}</textarea></label></section><section class="editor-block"><span>ТАКТИЧЕСКИЕ СВЯЗКИ · ${links.length}</span><div class="mini-link-list">${links.map(link=>`<button data-jump-link="${link.id}"><b>${esc(link.name)}</b><small>${esc(link.members.filter(id=>id!==hero.id).map(id=>HERO_BY_ID[id].name).join(', '))}</small></button>`).join('')||'<div class="saved-empty">Пока нет отдельной тактической заметки.</div>'}</div></section>`;wireImageFallbacks($('#heroSheetContent'));}
export function addCurrentHero(slot=null){placeHero(currentHeroId,slot===null?heroAddSlot:slot);closeSheet(false);}
export function toggleFavorite(id){const set=new Set(box.state.prefs.favorites);set.has(id)?set.delete(id):set.add(id);box.state.prefs.favorites=[...set];saveState();renderHeroSheet();renderHeroes();}
export function updateHeroPreference(kind,value){const hero=HERO_BY_ID[currentHeroId];if(!hero)return;if(kind==='score')box.state.prefs.scores[hero.id]=clamp(value);if(kind==='confidence')box.state.prefs.confidence[hero.id]=clamp(value);if(kind==='tier'&&TIERS.includes(value))box.state.prefs.tiers[hero.id]=value;if(kind==='notes')box.state.prefs.notes[hero.id]=String(value).slice(0,1200);saveState();if(kind!=='notes'){if($('#sheetRating'))$('#sheetRating').textContent=Math.round(heroRating(hero,box.state.prefs));if($('#sheetTier'))$('#sheetTier').textContent=box.state.prefs.tiers[hero.id]||hero.tier;}renderBuilder();renderHeroes();renderTiers();}
export function renderAnalysisSheet(){const analysis=analyzeTeam(box.state.team,box.state.prefs,planOptions()),roles=['Vanguard','Duelist','Strategist'],metrics=[['Гибкость ролей',analysis.flexibility,'#d7ff45'],['Подход игрокам',analysis.playerFit.score,'#141518'],['Синергия ядра',analysis.synergy,'#9d65ff'],['Фронтлайн',analysis.frontline,'#ff6b4a'],['Выживаемость',analysis.sustain,'#2dbf9f'],['Давление',analysis.pressure,'#ff4f8b'],['Контроль',analysis.control,'#f2bd31'],['Мобильность',analysis.mobility,'#77a9ff']];const allyPlan=box.state.plannerMode==='party'?`<section class="diagnostic-section ally-plan"><h3>ЧТО ОСТАВИТЬ МАТЧМЕЙКИНГУ</h3><div class="role-diagram">${roles.map(role=>`<div><b>${analysis.requiredRoles[role]}</b><span>${role}</span></div>`).join('')}</div><p>${analysis.unfixable?'Перекос уже нельзя полностью исправить оставшимися слотами.':'Это безопасный ролевой бюджет, а не приказ случайным союзникам.'}</p></section>`:'';const playerPlan=analysis.playerFit.items.length?`<section class="diagnostic-section"><h3>НАЗНАЧЕНИЯ ИГРОКОВ</h3><div class="player-fit-list">${analysis.playerFit.items.map(item=>{const player=box.state.players.find(profile=>profile.id===item.playerId),hero=HERO_BY_ID[item.heroId];return`<div><span>${esc(player?.name||'Игрок')} → ${esc(hero?.name||'Герой')}</span><b>${Math.round(item.score)}</b></div>`;}).join('')}</div></section>`:'';$('#analysisSheetContent').innerHTML=`<div class="analysis-hero-score"><b>${Math.round(analysis.overall)}</b><span>${box.state.plannerMode==='party'?'PARTY IN 6v6':'FULL TEAM'}</span><p>${verdictFor(analysis,activeIds().filter(Boolean).length)[0]}</p></div>${allyPlan}<div class="metric-grid">${metrics.map(([name,value,color])=>`<div class="metric-bar"><header><span>${name}</span><b>${Math.round(value)}</b></header><div class="track"><i style="--value:${clamp(value)}%;--bar:${color}"></i></div></div>`).join('')}</div>${playerPlan}<section class="diagnostic-section"><h3>ДИАГНОСТИКА</h3><div class="warning-list">${analysis.warnings.length?analysis.warnings.map(item=>`<div class="warning-item">${esc(item)}</div>`).join(''):'<div class="warning-item clean">Критичных дыр не обнаружено.</div>'}</div></section>`;}
export function saveCurrentTeam(){const ids=activeIds().filter(Boolean);if(!ids.length)return toast('Сначала добавь хотя бы одного героя.','bad');const suggested=ids.slice(0,2).map(id=>HERO_BY_ID[id].name).join(' + ')+(ids.length>2?` · ${ids.length}`:''),name=(prompt('Название сборки',suggested)||suggested).trim().slice(0,60);box.state.savedTeams.unshift({id:crypto.randomUUID?.()||`team-${Date.now().toString(36)}`,name,plannerMode:box.state.plannerMode,partySize:box.state.partySize,team:[...box.state.team],locks:[...box.state.locks],playerAssignments:[...box.state.playerAssignments],loadoutChoices:{...box.state.loadoutChoices},variants:structuredClone(box.state.variants),score:Math.round(analyzeTeam(box.state.team,box.state.prefs,planOptions()).overall),updated:Date.now()});box.state.savedTeams=box.state.savedTeams.slice(0,40);saveState();renderSavedTeams();clickSound('good');toast('Сборка и её варианты сохранены.','good');}
export function renderSavedTeams(){const root=$('#savedTeamsList');if(!box.state.savedTeams.length){root.innerHTML='<div class="saved-empty">Здесь будут ваши пати и полные составы.</div>';return;}root.innerHTML=box.state.savedTeams.map(team=>`<article class="saved-team"><header><div><h3>${esc(team.name)}</h3><small>${team.plannerMode==='party'?`Пати ${team.partySize||2}/6`:'Полный состав'} · ${(team.variants?.length||0)} вариантов · ${new Date(team.updated).toLocaleString('ru-RU',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}</small></div><b>${team.score||0}</b></header><div class="saved-faces">${(team.team||[]).slice(0,team.plannerMode==='party'?(team.partySize||2):6).filter(Boolean).map(id=>HERO_BY_ID[id]?portrait(HERO_BY_ID[id]):'').join('')}</div><div class="saved-player-line">${(team.playerAssignments||[]).slice(0,team.plannerMode==='party'?(team.partySize||2):6).map(id=>box.state.players.find(player=>player.id===id)?.name).filter(Boolean).map(name=>`<span>${esc(name)}</span>`).join('')}</div><div class="saved-actions"><button class="primary" data-load-team="${team.id}">Загрузить</button><button data-duplicate-team="${team.id}">Копия</button><button data-delete-team="${team.id}">Удалить</button></div></article>`).join('');wireImageFallbacks(root);}
export function loadSavedTeam(id){const record=box.state.savedTeams.find(team=>team.id===id);if(!record)return;box.state.plannerMode=record.plannerMode==='party'?'party':'full';box.state.partySize=Math.max(1,Math.min(6,Number(record.partySize)||2));box.state.team=Array.from({length:6},(_,i)=>HERO_BY_ID[record.team?.[i]]?record.team[i]:null);box.state.locks=Array.from({length:6},(_,i)=>Boolean(record.locks?.[i]));box.state.playerAssignments=Array.from({length:6},(_,i)=>box.state.players.some(player=>player.id===record.playerAssignments?.[i])?record.playerAssignments[i]:null);box.state.loadoutChoices={...(record.loadoutChoices||{})};box.state.variants=structuredClone(record.variants||[]);saveState();renderBuilder();closeSheet(false);setView('builder');toast(`Загружено: ${record.name}`,'good');}
export function duplicateSaved(id){const original=box.state.savedTeams.find(team=>team.id===id);if(!original)return;box.state.savedTeams.unshift({...structuredClone(original),id:crypto.randomUUID?.()||`team-${Date.now()}`,name:`${original.name} · копия`,updated:Date.now()});saveState();renderSavedTeams();toast('Копия создана.','good');}
export function deleteSaved(id){const record=box.state.savedTeams.find(team=>team.id===id);if(!record||!confirm(`Удалить «${record.name}»?`))return;box.state.savedTeams=box.state.savedTeams.filter(team=>team.id!==id);saveState();renderSavedTeams();}
export function exportData(){const payload=JSON.stringify(exportPayload(box.state),null,2),blob=new Blob([payload],{type:'application/json'}),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=`rival-forge-${new Date().toISOString().slice(0,10)}.json`;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Данные экспортированы.','good');}
export async function importData(file,renderAll){try{replaceState({...box.state,...normalizeImported(JSON.parse(await file.text()))});saveState();renderAll();closeSheet(false);toast('Данные восстановлены.','good');}catch(error){toast(`Импорт не удался: ${error.message}`,'bad');}finally{$('#importInput').value='';}}
export function resetAll(renderAll){if(!confirm('Удалить все профили, команды, варианты, оценки и заметки?'))return;replaceState(structuredClone(defaults));saveState();renderAll();closeSheet(false);toast('Rival Forge сброшен.','good');}
export function renderMeta(){$('#snapshotLabel').textContent=SNAPSHOT.label;$('#aboutSnapshot').textContent=`${SNAPSHOT.season} · ${SNAPSHOT.patch}`;$('#sourceNote').textContent=SNAPSHOT.sourceNote;$('#soundToggleValue').textContent=box.state.sound?'Включены':'Выключены';}
