import{WORLD,VIEW,gridInfo}from'./sim.js';
const{nx,ny,SOIL}=gridInfo(),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function rgba(hex,a){const n=parseInt(hex.slice(1),16);return`rgba(${n>>16},${n>>8&255},${n&255},${a})`}
export class WorldRenderer{
 constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:false});this.width=0;this.height=0;this.dpr=1;this.resize()}
 resize(){const r=this.canvas.getBoundingClientRect();this.dpr=Math.min(2,window.devicePixelRatio||1);this.width=Math.max(1,r.width);this.height=Math.max(1,r.height);this.canvas.width=Math.round(this.width*this.dpr);this.canvas.height=Math.round(this.height*this.dpr);this.ctx.setTransform(this.dpr,0,0,this.dpr,0,0)}
 worldToScreen(c,x,y){return{x:(x-c.x)*c.zoom+this.width/2,y:(y-c.y)*c.zoom+this.height/2}}
 screenToWorld(c,x,y){return{x:(x-this.width/2)/c.zoom+c.x,y:(y-this.height/2)/c.zoom+c.y}}
 draw(w,c,selection,view,now=0){const g=this.ctx,W=this.width,H=this.height;g.setTransform(this.dpr,0,0,this.dpr,0,0);g.fillStyle='#d7ceb6';g.fillRect(0,0,W,H);g.save();g.translate(W/2-c.x*c.zoom,H/2-c.y*c.zoom);g.scale(c.zoom,c.zoom);this.drawWorld(w,g,c,W,H,view,now,selection);g.restore()}
 drawWorld(w,g,c,W,H,view,now,selection){const left=clamp(Math.floor((c.x-W/(2*c.zoom))/WORLD.cell)-1,0,nx-1),right=clamp(Math.ceil((c.x+W/(2*c.zoom))/WORLD.cell)+1,0,nx-1),top=clamp(Math.floor((c.y-H/(2*c.zoom))/WORLD.cell)-1,0,ny-1),bottom=clamp(Math.ceil((c.y+H/(2*c.zoom))/WORLD.cell)+1,0,ny-1);g.fillStyle='#c6d0ba';g.fillRect(0,0,WORLD.width,WORLD.surfaceY);this.surface(g);const soil={1:'#a57f59',2:'#805f47',3:'#64483b',4:'#4b4640'};for(let y=Math.max(top,Math.floor(WORLD.surfaceY/WORLD.cell));y<=bottom;y++)for(let x=left;x<=right;x++){const i=y*nx+x,t=w.soil[i];if(t===SOIL.AIR)continue;let color=soil[t]||'#6b4f3d';if(view===VIEW.MOISTURE){const m=w.moisture[i];color=`rgb(${Math.round(133-55*m)},${Math.round(103-30*m)},${Math.round(78+72*m)})`}else if(view===VIEW.TEMPERATURE){const q=w.temp[i];color=`rgb(${Math.round(65+150*q)},${Math.round(92+70*q)},${Math.round(130-55*q)})`}g.fillStyle=color;g.fillRect(x*WORLD.cell,y*WORLD.cell,WORLD.cell+.5,WORLD.cell+.5)}if(view===VIEW.PHEROMONE)this.pheromones(w,g,left,right,top,bottom);this.soilPiles(w,g);this.food(w,g);this.bugs(w,g,now);this.brood(w,g);this.queen(w,g,now);this.ants(w,g,now,selection);if(w.weather.rain>0)this.rain(g,w.time)}
 surface(g){g.fillStyle='#768a5d';g.fillRect(0,WORLD.surfaceY-9,WORLD.width,9);g.strokeStyle='#64754f';g.lineWidth=2;for(let x=28;x<WORLD.width;x+=55){const h=18+((x*13)%24);g.beginPath();g.moveTo(x,WORLD.surfaceY-7);g.quadraticCurveTo(x-10,WORLD.surfaceY-h,x-5,WORLD.surfaceY-h-9);g.stroke();g.beginPath();g.moveTo(x+5,WORLD.surfaceY-7);g.quadraticCurveTo(x+14,WORLD.surfaceY-h*.7,x+19,WORLD.surfaceY-h-2);g.stroke()}g.fillStyle='#8b7359';for(let x=65;x<WORLD.width;x+=180){g.beginPath();g.ellipse(x,WORLD.surfaceY-5,18,7,-.2,0,Math.PI*2);g.fill()}}
 soilPiles(w,g){g.fillStyle='#8d694c';for(const p of w.soilPiles){g.beginPath();g.ellipse(p.x,p.y,5+p.mass*2.5,2.5+p.mass*.8,0,0,Math.PI*2);g.fill()}}
 food(w,g){for(const f of w.food){if(f.carriedBy)continue;if(f.type==='seed'){g.fillStyle='#b78543';g.beginPath();g.ellipse(f.x,f.y,5+f.amount*2,3+f.amount,.4,0,Math.PI*2);g.fill()}else if(f.type==='nectar'){g.fillStyle='#d2a947';g.beginPath();g.arc(f.x,f.y,4+f.amount,0,Math.PI*2);g.fill()}else{g.fillStyle='#73584d';g.beginPath();g.ellipse(f.x,f.y,7+f.amount,4+f.amount*.4,.2,0,Math.PI*2);g.fill()}}}
 bugs(w,g,now){for(const b of w.bugs){if(b.dead)continue;g.save();g.translate(b.x,b.y);g.rotate(Math.sin(now*.004+b.id)*.15);g.fillStyle=b.species==='beetle'?'#403b35':'#6e4b3c';g.beginPath();g.ellipse(0,0,b.species==='beetle'?13:8,b.species==='beetle'?8:5,0,0,Math.PI*2);g.fill();g.strokeStyle='#2c2926';g.lineWidth=1.4;for(const s of[-1,1])for(const yy of[-5,0,5]){g.beginPath();g.moveTo(s*4,yy*.55);g.lineTo(s*13,yy+s*3);g.stroke()}g.restore()}}
 brood(w,g){for(const b of w.brood){g.fillStyle=b.stage==='egg'?'#f0ead7':b.stage==='larva'?'#e1d4b5':'#bba786';g.beginPath();g.ellipse(b.x,b.y,b.stage==='egg'?4:6,b.stage==='egg'?3:4.5,.1,0,Math.PI*2);g.fill()}}
 queen(w,g,now){if(!w.queen.alive)return;g.save();g.translate(w.queen.x,w.queen.y);g.rotate(Math.sin(now*.001)*.04);g.fillStyle='#3a2018';g.beginPath();g.ellipse(-8,0,14,9,0,0,Math.PI*2);g.ellipse(11,0,18,11,0,0,Math.PI*2);g.fill();g.fillStyle='#5b2c1d';g.beginPath();g.arc(-22,0,7,0,Math.PI*2);g.fill();g.restore()}
 ants(w,g,now,selection){for(const a of w.ants){g.save();g.translate(a.x,a.y);g.rotate(Math.atan2(a.vy||Math.sin(a.wander),a.vx||Math.cos(a.wander)));if(selection?.kind==='ant'&&selection.id===a.id){g.strokeStyle='#e2b74f';g.lineWidth=2;g.beginPath();g.arc(0,0,11+Math.sin(now*.008)*1.5,0,Math.PI*2);g.stroke()}g.fillStyle='#2a1c16';g.beginPath();g.ellipse(-4,0,4.2,3,0,0,Math.PI*2);g.ellipse(2,0,3,2.4,0,0,Math.PI*2);g.arc(6,0,2.8,0,Math.PI*2);g.fill();g.strokeStyle='#2a1c16';g.lineWidth=1;for(const s of[-1,1]){g.beginPath();g.moveTo(-1,0);g.lineTo(-5,s*6);g.moveTo(2,0);g.lineTo(2,s*7);g.moveTo(4,0);g.lineTo(7,s*6);g.stroke()}if(a.carry?.type==='soil'){g.fillStyle='#a57f59';g.beginPath();g.arc(10,0,3.2,0,Math.PI*2);g.fill()}if(a.carry?.type==='food'){g.fillStyle='#b78543';g.beginPath();g.arc(10,0,3.4,0,Math.PI*2);g.fill()}g.restore()}}
 pheromones(w,g,l,r,t,b){g.save();g.globalCompositeOperation='screen';for(let y=t;y<=b;y+=2)for(let x=l;x<=r;x+=2){const i=y*nx+x,food=w.pherFood[i],alarm=w.pherAlarm[i],build=w.pherBuild[i];if(food>.04){g.fillStyle=rgba('#d79e4b',food*.55);g.fillRect(x*WORLD.cell,y*WORLD.cell,WORLD.cell*2,WORLD.cell*2)}if(build>.05){g.fillStyle=rgba('#5f968e',build*.48);g.fillRect(x*WORLD.cell,y*WORLD.cell,WORLD.cell*2,WORLD.cell*2)}if(alarm>.04){g.fillStyle=rgba('#b54a38',alarm*.65);g.fillRect(x*WORLD.cell,y*WORLD.cell,WORLD.cell*2,WORLD.cell*2)}}g.restore()}
 rain(g,time){g.strokeStyle='rgba(190,211,219,.35)';g.lineWidth=1.2;for(let i=0;i<95;i++){const x=(i*79+time*85)%WORLD.width,y=(i*41+time*160)%WORLD.surfaceY;g.beginPath();g.moveTo(x,y);g.lineTo(x-6,y+18);g.stroke()}}
}