import './styles.css';
import { Color3, Color4, DirectionalLight, DynamicTexture, Engine, FreeCamera, HemisphericLight, MeshBuilder, ParticleSystem, Quaternion, Scene, ShaderMaterial, ShadowGenerator, StandardMaterial, Vector3 } from '@babylonjs/core';
import { registerSW } from 'virtual:pwa-register';
import { FlightAudio } from './audio';
import { makeFlightState, stepFlight, terrainSafeAltitude } from './core';
import { DragonRig } from './dragon';
import { createControls } from './input';
import { WorldStreamer } from './world';

const canvas=document.querySelector<HTMLCanvasElement>('#renderCanvas')!;const touch=document.querySelector<HTMLElement>('#touchSurface')!;const loading=document.querySelector<HTMLElement>('#loading')!;const loadingText=document.querySelector<HTMLElement>('#loadingText')!;const startBtn=document.querySelector<HTMLButtonElement>('#startBtn')!;const speedEl=document.querySelector<HTMLElement>('#speed')!;const altEl=document.querySelector<HTMLElement>('#alt')!;const modeEl=document.querySelector<HTMLElement>('#mode')!;const soundBtn=document.querySelector<HTMLButtonElement>('#soundBtn')!;const speedLines=document.querySelector<HTMLElement>('#speedlines')!;const hints=[document.querySelector<HTMLElement>('#leftHint')!,document.querySelector<HTMLElement>('#rightHint')!];
registerSW({immediate:true});

const engine=new Engine(canvas,true,{preserveDrawingBuffer:false,stencil:true,antialias:true,adaptToDeviceRatio:false});engine.setHardwareScalingLevel(Math.min(1.55,Math.max(1,devicePixelRatio*.72)));
const scene=new Scene(engine);scene.clearColor=new Color4(.57,.73,.77,1);scene.fogMode=Scene.FOGMODE_EXP2;scene.fogDensity=.00072;scene.fogColor=new Color3(.61,.74,.75);scene.skipPointerMovePicking=true;
const hemi=new HemisphericLight('skyLight',new Vector3(.18,1,.22),scene);hemi.intensity=1.18;hemi.diffuse=new Color3(.93,.94,.82);hemi.groundColor=new Color3(.18,.26,.22);
const sun=new DirectionalLight('sun',new Vector3(-.42,-.74,.26),scene);sun.position=new Vector3(350,680,-260);sun.intensity=2.25;sun.diffuse=new Color3(1,.88,.68);
const shadows=new ShadowGenerator(1024,sun);shadows.usePercentageCloserFiltering=true;shadows.bias=.0016;

const skyVertex=`precision highp float;attribute vec3 position;uniform mat4 worldViewProjection;varying vec3 v;void main(){v=normalize(position);gl_Position=worldViewProjection*vec4(position,1.0);}`;
const skyFragment=`precision highp float;varying vec3 v;void main(){float h=clamp(v.y*.5+.5,0.0,1.0);vec3 horizon=vec3(.69,.79,.77),zenith=vec3(.20,.43,.55);float sun=pow(max(dot(normalize(v),normalize(vec3(.38,.62,-.25))),0.0),280.0);vec3 c=mix(horizon,zenith,pow(h,.72))+sun*vec3(1.0,.72,.38)*1.4;gl_FragColor=vec4(c,1.0);}`;
const sky=MeshBuilder.CreateSphere('sky',{diameter:3600,segments:18,sideOrientation:1},scene);const skyMat=new ShaderMaterial('skyMat',scene,{vertexSource:skyVertex,fragmentSource:skyFragment},{attributes:['position'],uniforms:['worldViewProjection']});skyMat.backFaceCulling=false;sky.material=skyMat;sky.infiniteDistance=true;sky.isPickable=false;

const camera=new FreeCamera('camera',new Vector3(0,205,-24),scene);camera.minZ=.35;camera.maxZ=4200;camera.fov=.92;scene.activeCamera=camera;
const state=makeFlightState();const controls=createControls(touch);const audio=new FlightAudio();const world=new WorldStreamer(scene);const dragon=new DragonRig(scene);
let lookYaw=0,lookPitch=.08;let started=false,last=performance.now(),fpsEMA=60,quality=1,frameCount=0;

function makeWindParticles(){const tex=new DynamicTexture('windTex',{width:32,height:8},scene,false);const ctx=tex.getContext();ctx.clearRect(0,0,32,8);const g=ctx.createLinearGradient(0,0,32,0);g.addColorStop(0,'rgba(255,255,255,0)');g.addColorStop(.5,'rgba(255,255,255,.8)');g.addColorStop(1,'rgba(255,255,255,0)');ctx.fillStyle=g;ctx.fillRect(0,3,32,2);tex.update();const p=new ParticleSystem('wind',180,scene);p.particleTexture=tex;p.emitter=dragon.root;p.minEmitBox=new Vector3(-18,-9,-20);p.maxEmitBox=new Vector3(18,9,18);p.color1=new Color4(1,1,.9,.15);p.color2=new Color4(.8,.95,1,.06);p.minSize=2;p.maxSize=7;p.minLifeTime=.2;p.maxLifeTime=.55;p.emitRate=60;p.direction1=new Vector3(0,0,-38);p.direction2=new Vector3(0,0,-62);p.minEmitPower=.5;p.maxEmitPower=1;p.updateSpeed=.012;p.start();return p;}const windParticles=makeWindParticles();

function modeLabel(){return state.mode==='glide'?'GLIDE':state.mode==='flap'?'POWER':state.mode==='climb'?'CLIMB':state.mode==='dive'?'DIVE':'AIR BRAKE';}
function forward(){const cp=Math.cos(state.pitch);return new Vector3(Math.sin(state.yaw)*cp,Math.sin(state.pitch),Math.cos(state.yaw)*cp).normalize();}
function updateCamera(dt:number){const look=controls.consumeLook();lookYaw-=look.x;lookPitch=Math.max(-.45,Math.min(.58,lookPitch-look.y));lookYaw*=Math.pow(.994,dt*60);const target=new Vector3(state.position.x,state.position.y+1.6,state.position.z);const yaw=state.yaw+lookYaw;const horiz=new Vector3(Math.sin(yaw),0,Math.cos(yaw));const speedN=Math.max(0,Math.min(1,(state.speed-20)/65));const dist=20+speedN*8;const height=7+lookPitch*14+speedN*1.5;const desired=target.subtract(horiz.scale(dist)).add(new Vector3(0,height,0));const lag=1-Math.exp(-dt*(2.7-speedN*.8));camera.position=Vector3.Lerp(camera.position,desired,lag);const aim=target.add(forward().scale(5+speedN*8)).add(new Vector3(0,lookPitch*4,0));camera.setTarget(Vector3.Lerp(camera.getTarget(),aim,1-Math.exp(-dt*5)));camera.fov+=(.91+speedN*.22+(state.mode==='dive'?.055:0)-camera.fov)*(1-Math.exp(-dt*3.4));}
function updateQuality(dt:number){fpsEMA+=(1/Math.max(dt,.001)-fpsEMA)*.03;if(++frameCount%180)return;if(fpsEMA<41&&quality>.6){quality=Math.max(.6,quality-.12);engine.setHardwareScalingLevel(Math.min(1.85,engine.getHardwareScalingLevel()+.12));world.setQuality(quality);}else if(fpsEMA>57&&quality<1){quality=Math.min(1,quality+.08);engine.setHardwareScalingLevel(Math.max(1,engine.getHardwareScalingLevel()-.07));world.setQuality(quality);}}

async function boot(){loadingText.textContent='Риггинг дракона и проверка материалов…';await dragon.load(p=>loadingText.textContent=`Дракон ${(p*100|0)}%`);for(const m of dragon.meshes){shadows.addShadowCaster(m,true);m.receiveShadows=true;}loadingText.textContent=dragon.usedFallback?'Forge-модель ещё генерируется; включён цветной резервный дракон.':'Скелет, материалы и анимации готовы.';world.update(new Vector3(state.position.x,state.position.y,state.position.z),0);startBtn.disabled=false;loading.classList.add('ready');startBtn.textContent='В НЕБО';}
startBtn.addEventListener('click',async()=>{await audio.start();started=true;loading.classList.add('dismiss');hints.forEach((h,i)=>setTimeout(()=>h.style.opacity='0',3600+i*500));});
soundBtn.addEventListener('click',async()=>{await audio.start();soundBtn.textContent='SND';});
addEventListener('resize',()=>engine.resize(),{passive:true});document.addEventListener('visibilitychange',()=>{if(document.hidden)engine.stopRenderLoop();else engine.runRenderLoop(loop);});
function loop(){const now=performance.now();const dt=Math.min(.04,Math.max(.001,(now-last)/1000));last=now;if(started){const input={x:controls.x,y:controls.y,boost:controls.boost,brake:controls.brake};stepFlight(state,input,dt);const ground=world.heightAt(state.position.x,state.position.z);terrainSafeAltitude(state,ground,dt);dragon.update(state,input,dt);updateCamera(dt);world.update(dragon.root.position,now/1000);audio.update(state,dt);updateQuality(dt);speedEl.textContent=String(Math.round(state.speed));altEl.textContent=String(Math.max(0,Math.round(state.position.y-ground)));modeEl.textContent=modeLabel();const speedN=Math.max(0,Math.min(1,(state.speed-28)/58));speedLines.style.opacity=String(speedN*.55);windParticles.emitRate=35+speedN*155;windParticles.minEmitPower=.3+speedN;windParticles.maxEmitPower=.7+speedN*1.8;}sky.position.copyFrom(camera.position);scene.render();}
boot().catch(err=>{console.error(err);loadingText.textContent='Не удалось инициализировать сцену.';startBtn.disabled=true;});engine.runRenderLoop(loop);
