import './styles.css';
import { Color3, Color4, DirectionalLight, Engine, FreeCamera, HemisphericLight, LinesMesh, MeshBuilder, Scene, ShaderMaterial, ShadowGenerator, Vector3 } from '@babylonjs/core';
import { registerSW } from 'virtual:pwa-register';
import { FlightAudio } from './audio';
import { makeFlightState, stepFlight, terrainSafeAltitude } from './core';
import { DragonRig } from './dragon';
import { FaunaSystem } from './fauna';
import { createControls } from './input';
import { riverCenter, WorldStreamer } from './world';

const canvas=document.querySelector<HTMLCanvasElement>('#renderCanvas')!;const touch=document.querySelector<HTMLElement>('#touchSurface')!;const loading=document.querySelector<HTMLElement>('#loading')!;const loadingText=document.querySelector<HTMLElement>('#loadingText')!;const startBtn=document.querySelector<HTMLButtonElement>('#startBtn')!;const speedEl=document.querySelector<HTMLElement>('#speed')!;const altEl=document.querySelector<HTMLElement>('#alt')!;const modeEl=document.querySelector<HTMLElement>('#mode')!;const soundBtn=document.querySelector<HTMLButtonElement>('#soundBtn')!;const speedLines=document.querySelector<HTMLElement>('#speedlines')!;const hints=[document.querySelector<HTMLElement>('#leftHint')!,document.querySelector<HTMLElement>('#rightHint')!];
registerSW({immediate:true});

const engine=new Engine(canvas,true,{preserveDrawingBuffer:false,stencil:true,antialias:true,adaptToDeviceRatio:false});engine.setHardwareScalingLevel(Math.min(1.32,Math.max(1,devicePixelRatio*.58)));
const scene=new Scene(engine);scene.clearColor=new Color4(.56,.72,.78,1);scene.fogMode=Scene.FOGMODE_EXP2;scene.fogDensity=.00024;scene.fogColor=new Color3(.62,.72,.72);scene.skipPointerMovePicking=true;scene.imageProcessingConfiguration.exposure=1.07;scene.imageProcessingConfiguration.contrast=1.07;
const hemi=new HemisphericLight('skyLight',new Vector3(.18,1,.22),scene);hemi.intensity=.98;hemi.diffuse=new Color3(.92,.94,.84);hemi.groundColor=new Color3(.18,.24,.17);
const sun=new DirectionalLight('sun',new Vector3(-.42,-.74,.26),scene);sun.position=new Vector3(350,680,-260);sun.intensity=1.78;sun.diffuse=new Color3(1,.90,.72);
const shadows=new ShadowGenerator(1024,sun);shadows.usePercentageCloserFiltering=true;shadows.bias=.0018;

const skyVertex=`precision highp float;attribute vec3 position;uniform mat4 worldViewProjection;varying vec3 v;void main(){v=normalize(position);gl_Position=worldViewProjection*vec4(position,1.0);}`;
const skyFragment=`precision highp float;varying vec3 v;uniform float time;void main(){float h=clamp(v.y*.5+.5,0.0,1.0);vec3 horizon=vec3(.68,.78,.76),zenith=vec3(.18,.40,.54);float sun=pow(max(dot(normalize(v),normalize(vec3(.38,.62,-.25))),0.0),260.0);vec3 c=mix(horizon,zenith,pow(h,.72))+sun*vec3(1.0,.75,.42)*1.28;float band=smoothstep(.08,.24,v.y)*(1.0-smoothstep(.62,.82,v.y));float n=sin(v.x*10.0+time*.018)+sin(v.z*13.0-time*.014)+sin((v.x+v.z)*23.0+time*.010)+sin((v.x-v.z)*31.0-time*.006)*.45;float cloud=smoothstep(1.55,2.35,n)*band;c=mix(c,vec3(.90,.92,.88),cloud*.48);gl_FragColor=vec4(c,1.0);}`;
const sky=MeshBuilder.CreateSphere('sky',{diameter:4200,segments:20,sideOrientation:1},scene);const skyMat=new ShaderMaterial('skyMat',scene,{vertexSource:skyVertex,fragmentSource:skyFragment},{attributes:['position'],uniforms:['worldViewProjection','time']});skyMat.backFaceCulling=false;sky.material=skyMat;sky.infiniteDistance=true;sky.isPickable=false;

const camera=new FreeCamera('camera',new Vector3(0,205,-20),scene);camera.minZ=.28;camera.maxZ=4600;camera.fov=.86;scene.activeCamera=camera;
const state=makeFlightState();const controls=createControls(touch);const audio=new FlightAudio();const world=new WorldStreamer(scene);const dragon=new DragonRig(scene);const fauna=new FaunaSystem(scene);
// Start in a deterministic river valley and point along the local tangent of the
// river. The first seconds therefore showcase terrain scale instead of crossing
// the valley into a hillside by accident.
state.position.x=1750;state.position.z=riverCenter(state.position.x);
const tangentDz=riverCenter(state.position.x+8)-riverCenter(state.position.x-8);state.yaw=Math.atan2(16,tangentDz);state.velocity={x:Math.sin(state.yaw)*29,y:0,z:Math.cos(state.yaw)*29};state.speed=29;
const initialGround=world.heightAt(state.position.x,state.position.z);state.position.y=initialGround+86;const initialForward=new Vector3(Math.sin(state.yaw),0,Math.cos(state.yaw));camera.position=new Vector3(state.position.x,state.position.y+5,state.position.z).subtract(initialForward.scale(18));altEl.textContent=String(Math.round(state.position.y-initialGround));
let lookYaw=0,lookPitch=-.035;let started=false,last=performance.now(),fpsEMA=60,quality=1,frameCount=0;
const qaState={version:'1.0.2',loadingState:'booting',started:false,dragonReady:false,usedFallback:false,animationGroups:0,boneCount:0,chunks:0,fauna:fauna.activeCount,mode:state.mode,speed:state.speed,altitude:Number((state.position.y-initialGround).toFixed(2)),groundHeight:Number(initialGround.toFixed(2)),terrainMeshes:0,waterMeshes:0,vegetationInstances:0,treeInstances:0,brakeEvents:0,lastGesture:'',position:{...state.position},pitch:state.pitch,roll:state.roll,yaw:state.yaw,quality,assetErrors:[] as string[]};
(window as typeof window & {__AI_TEST_STATE__?:typeof qaState}).__AI_TEST_STATE__=qaState;

type WindStreak={line:LinesMesh;side:number;lift:number;depth:number;phase:number};
const windStreaks:WindStreak[]=Array.from({length:16},(_,i)=>{const line=MeshBuilder.CreateLines(`wind_${i}`,{points:[Vector3.Zero(),new Vector3(0,0,-1)],updatable:true},scene);line.color=new Color3(.72,.84,.82);line.isPickable=false;line.alwaysSelectAsActiveMesh=true;line.setEnabled(false);const seed=(i*47%113)/113;return{line,side:(seed-.5)*30,lift:((((i*71)%97)/97)-.5)*13,depth:((i*29)%101)/101,phase:((i*61)%103)/103};});

function modeLabel(){return state.mode==='glide'?'GLIDE':state.mode==='flap'?'POWER':state.mode==='climb'?'CLIMB':state.mode==='dive'?'DIVE':'AIR BRAKE';}
function forward(){const cp=Math.cos(state.pitch);return new Vector3(Math.sin(state.yaw)*cp,Math.sin(state.pitch),Math.cos(state.yaw)*cp).normalize();}
function updateWindStreaks(speedN:number,time:number,ground:number){const altitude=Math.max(0,state.position.y-ground);const lowFlight=1-Math.max(0,Math.min(1,(altitude-25)/180));const visible=speedN>.08;const f=forward();let right=Vector3.Cross(Vector3.Up(),f);if(right.lengthSquared()<.01)right=Vector3.Right();else right.normalize();const up=Vector3.Cross(f,right).normalize();const base=new Vector3(state.position.x,state.position.y,state.position.z);for(const streak of windStreaks){streak.line.setEnabled(visible);if(!visible)continue;const cycle=(streak.phase+time*(.34+speedN*.95))%1;const forwardOffset=18-cycle*(42+speedN*70)+streak.depth*10;const start=base.add(right.scale(streak.side)).add(up.scale(streak.lift)).add(f.scale(forwardOffset));const length=1.5+speedN*(4.5+streak.depth*7);MeshBuilder.CreateLines(streak.line.name,{points:[Vector3.Zero(),f.scale(-length)],instance:streak.line});streak.line.position.copyFrom(start);streak.line.visibility=.08+speedN*(.24+.18*lowFlight);}}
function updateCamera(dt:number,ground:number){const look=controls.consumeLook();lookYaw-=look.x;lookPitch=Math.max(-.36,Math.min(.48,lookPitch-look.y));lookYaw*=Math.pow(.994,dt*60);const target=new Vector3(state.position.x,state.position.y+.9,state.position.z);const yaw=state.yaw+lookYaw;const horiz=new Vector3(Math.sin(yaw),0,Math.cos(yaw));const speedN=Math.max(0,Math.min(1,(state.speed-20)/65));const altitude=Math.max(0,state.position.y-ground);const dist=16.5+speedN*5.5;const height=4.4+lookPitch*7.5+speedN*.9;const desired=target.subtract(horiz.scale(dist)).add(new Vector3(0,height,0));const lag=1-Math.exp(-dt*(3.3-speedN*.72));camera.position=Vector3.Lerp(camera.position,desired,lag);const downBias=Math.max(5.8,Math.min(15,altitude*.075));const aim=target.add(forward().scale(18+speedN*14)).add(new Vector3(0,lookPitch*9-downBias,0));camera.setTarget(Vector3.Lerp(camera.getTarget(),aim,1-Math.exp(-dt*5.8)));camera.fov+=(.84+speedN*.18+(state.mode==='dive'?.055:0)-camera.fov)*(1-Math.exp(-dt*3.6));}
function updateQuality(dt:number){fpsEMA+=(1/Math.max(dt,.001)-fpsEMA)*.03;if(++frameCount%180)return;if(fpsEMA<40&&quality>.6){quality=Math.max(.6,quality-.12);engine.setHardwareScalingLevel(Math.min(1.82,engine.getHardwareScalingLevel()+.12));world.setQuality(quality);}else if(fpsEMA>57&&quality<1){quality=Math.min(1,quality+.08);engine.setHardwareScalingLevel(Math.max(1,engine.getHardwareScalingLevel()-.07));world.setQuality(quality);}}
function publishQA(ground:number){qaState.started=started;qaState.dragonReady=dragon.ready;qaState.usedFallback=dragon.usedFallback;qaState.animationGroups=dragon.groups.size;qaState.boneCount=dragon.bones.size;qaState.chunks=world.chunks.size;qaState.fauna=fauna.activeCount;qaState.mode=state.mode;qaState.speed=Number(state.speed.toFixed(2));qaState.altitude=Number((state.position.y-ground).toFixed(2));qaState.groundHeight=Number(ground.toFixed(2));qaState.terrainMeshes=scene.meshes.filter(m=>m.name.startsWith('terrain_')&&m.isEnabled()).length;qaState.waterMeshes=scene.meshes.filter(m=>(m.name.startsWith('river_')||m.name.startsWith('lake_'))&&m.isEnabled()).length;qaState.vegetationInstances=world.instanceCount;qaState.treeInstances=world.treeCount;qaState.brakeEvents=controls.brakeEvents;qaState.lastGesture=controls.lastGesture;qaState.position={x:Number(state.position.x.toFixed(2)),y:Number(state.position.y.toFixed(2)),z:Number(state.position.z.toFixed(2))};qaState.pitch=Number(state.pitch.toFixed(3));qaState.roll=Number(state.roll.toFixed(3));qaState.yaw=Number(state.yaw.toFixed(3));qaState.quality=Number(quality.toFixed(2));}

async function boot(){try{loadingText.textContent='Риггинг дракона и проверка материалов…';await dragon.load(p=>loadingText.textContent=`Дракон ${(p*100|0)}%`);for(const m of dragon.meshes){shadows.addShadowCaster(m,true);m.receiveShadows=true;}loadingText.textContent=dragon.usedFallback?'Forge-модель не загрузилась; включён цветной резервный дракон.':'Скелет, материалы и анимации готовы.';world.update(new Vector3(state.position.x,state.position.y,state.position.z),0);qaState.loadingState='awaiting-start';qaState.dragonReady=dragon.ready;qaState.usedFallback=dragon.usedFallback;qaState.animationGroups=dragon.groups.size;qaState.boneCount=dragon.bones.size;startBtn.disabled=false;loading.classList.add('ready');startBtn.textContent='В НЕБО';}catch(err){const message=err instanceof Error?err.message:String(err);qaState.loadingState='error';qaState.assetErrors.push(message);throw err;}}
startBtn.addEventListener('click',async()=>{await audio.start();started=true;qaState.loadingState='flying';loading.classList.add('dismiss');hints.forEach((h,i)=>setTimeout(()=>h.style.opacity='0',3600+i*500));});
soundBtn.addEventListener('click',async()=>{await audio.start();soundBtn.textContent='SND';});
addEventListener('resize',()=>engine.resize(),{passive:true});document.addEventListener('visibilitychange',()=>{if(document.hidden)engine.stopRenderLoop();else engine.runRenderLoop(loop);});
function loop(){const now=performance.now();const dt=Math.min(.04,Math.max(.001,(now-last)/1000));last=now;let ground=world.heightAt(state.position.x,state.position.z);if(started){const input={x:controls.x,y:controls.y,boost:controls.boost,brake:controls.brake};stepFlight(state,input,dt);ground=world.heightAt(state.position.x,state.position.z);terrainSafeAltitude(state,ground,dt);dragon.update(state,input,dt);updateCamera(dt,ground);world.update(dragon.root.position,now/1000);fauna.update(dragon.root.position,new Vector3(state.velocity.x,state.velocity.y,state.velocity.z),now/1000);audio.update(state,dt);updateQuality(dt);speedEl.textContent=String(Math.round(state.speed));altEl.textContent=String(Math.max(0,Math.round(state.position.y-ground)));modeEl.textContent=modeLabel();const speedN=Math.max(0,Math.min(1,(state.speed-27)/58));const lowFlight=1-Math.max(0,Math.min(1,((state.position.y-ground)-20)/170));speedLines.style.opacity=String(speedN*(.18+.18*lowFlight));updateWindStreaks(speedN,now/1000,ground);}else updateWindStreaks(0,now/1000,ground);sky.position.copyFrom(camera.position);skyMat.setFloat('time',now/1000);publishQA(ground);scene.render();}
boot().catch(err=>{console.error(err);loadingText.textContent='Не удалось инициализировать сцену.';startBtn.disabled=true;});engine.runRenderLoop(loop);
