import { Node, clamp, damp, smoothstep, TAU, add3, sub3, mul3, dot3, len3, norm3 } from './engine.js';
import { SiegeAudio } from './audio.js';
import { STORAGE_KEY, AMMO, CAMPAIGN } from './config.js';

export function startSiegeGame({ ui, renderer, scene }) {
  let profile=loadProfile();
  const {
    GEO, root, world, castle, camp, ballista, effects, COLORS, node, box, cylinder, sphere, beamBetween, rand,
    targets, colliders, props, gate, towerLeft, towerRight, keep,
    loadedProjectile, loadedShaft, loadedTip, winch, turret, stringLeft, stringRight,
    particles, smokeColumns, flags, flames, crew, clouds, water, dynamicDebris, stuckProjectiles,
    spawnParticle, terrainHeight,
  }=scene;

  const state={
    mode:'intro', ammo:'bolt', power:74, angle:19, yaw:0, wind:(rand()-.5)*5.4, gust:0, selected:gate,
    shot:null, cameraMode:'ballista', sound:profile.sound!==false, time:0, shake:0, drag:null,
    stage:0, score:0, streak:0, integrity:100, volleyClock:CAMPAIGN[0].volley, incoming:[],
    ammoStock:{bolt:6,heavy:5,fire:3,stone:3}, hitCount:0, runShots:0, finished:false,
  };

  const audio=new SiegeAudio(()=>state.sound);
  function loadProfile(){try{const raw=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');return{bestHit:Number(raw.bestHit)||0,destroyed:Number(raw.destroyed)||0,shots:Number(raw.shots)||0,bestScore:Number(raw.bestScore)||0,sound:raw.sound!==false};}catch{return{bestHit:0,destroyed:0,shots:0,bestScore:0,sound:true};}}
  function saveProfile(){localStorage.setItem(STORAGE_KEY,JSON.stringify(profile));}
  function renderRecords(){ui.bestHit.textContent=Math.round(profile.bestHit);ui.destroyedCount.textContent=profile.destroyed;ui.shotCount.textContent=profile.shots;}
  renderRecords();
  const haptic=p=>navigator.vibrate?.(p);
  function setCallout(title,sub='',duration=1250){ui.callout.querySelector('b').textContent=title;ui.callout.querySelector('span').textContent=sub;ui.callout.classList.add('show');clearTimeout(setCallout.timer);setCallout.timer=setTimeout(()=>ui.callout.classList.remove('show'),duration);}

  const hud=document.createElement('section');hud.className='siege-run-hud';hud.hidden=true;
  hud.innerHTML=`<div class="operation"><small id="operationStage"></small><b id="operationObjective"></b><div><i id="operationProgress"></i></div></div><div class="run-metrics"><span>СЧЁТ<b id="runScore">0</b></span><span>БОЕЗАПАС<b id="runAmmo">17</b></span><span>БАЛЛИСТА<b id="runIntegrity">100%</b></span><span>ЗАЛП ЧЕРЕЗ<b id="runVolley">20с</b></span></div>`;
  ui.canvas.parentElement.append(hud);
  const h={stage:hud.querySelector('#operationStage'),objective:hud.querySelector('#operationObjective'),progress:hud.querySelector('#operationProgress'),score:hud.querySelector('#runScore'),ammo:hud.querySelector('#runAmmo'),integrity:hud.querySelector('#runIntegrity'),volley:hud.querySelector('#runVolley')};
  function setGameVisible(value){for(const el of [ui.topbar,ui.controls,ui.targetCard,ui.windCard,ui.reticle,hud])el.hidden=!value;}
  const totalAmmo=()=>Object.values(state.ammoStock).reduce((a,b)=>a+b,0);
  const currentMission=()=>CAMPAIGN[Math.min(state.stage,CAMPAIGN.length-1)];
  function missionProgress(){if(state.stage===0)return gate.destroyed?1:1-gate.health/gate.maxHealth;if(state.stage===1)return((towerLeft.destroyed?1:1-towerLeft.health/towerLeft.maxHealth)+(towerRight.destroyed?1:1-towerRight.health/towerRight.maxHealth))/2;return keep.destroyed?1:1-keep.health/keep.maxHealth;}
  function missionComplete(){return state.stage===0?gate.destroyed:state.stage===1?(towerLeft.destroyed&&towerRight.destroyed):keep.destroyed;}
  function updateHud(){const mission=currentMission();h.stage.textContent=mission.label;h.objective.textContent=mission.objective;h.progress.style.width=`${clamp(missionProgress(),0,1)*100}%`;h.score.textContent=Math.round(state.score).toLocaleString('ru-RU');h.ammo.textContent=totalAmmo();h.integrity.textContent=`${Math.max(0,Math.round(state.integrity))}%`;h.volley.textContent=`${Math.max(0,Math.ceil(state.volleyClock))}с`;hud.classList.toggle('danger',state.integrity<35||state.volleyClock<5);for(const b of ui.ammoRow.querySelectorAll('[data-ammo]')){const key=b.dataset.ammo,small=b.querySelector('small');small.textContent=`${key==='bolt'?'точность':key==='heavy'?'камень':key==='fire'?'дерево':'область'} · ${state.ammoStock[key]}`;b.classList.toggle('empty',state.ammoStock[key]<=0);}}

  function resetRun(){state.stage=0;state.score=0;state.streak=0;state.integrity=100;state.volleyClock=CAMPAIGN[0].volley;state.ammoStock={bolt:6,heavy:5,fire:3,stone:3};state.hitCount=0;state.runShots=0;state.finished=false;resetCastle();updateHud();}
  function beginGame(){ui.intro.hidden=true;ui.brief.hidden=true;ui.result.hidden=true;setGameVisible(true);resetRun();state.mode='ready';updateControls();setCallout('ОПЕРАЦИЯ «БАСТИОН»','боезапас ограничен — выбирай снаряд с умом',1700);audio.ensure();}
  ui.start.addEventListener('click',beginGame);ui.briefStart.addEventListener('click',beginGame);ui.briefButton.addEventListener('click',()=>ui.brief.hidden=false);ui.briefClose.addEventListener('click',()=>ui.brief.hidden=true);

  function updateControls(){state.power=Number(ui.power.value);state.angle=Number(ui.angle.value);state.yaw=Number(ui.yaw.value);ui.powerOut.textContent=`${state.power}%`;ui.angleOut.textContent=`${state.angle}°`;ui.yawOut.textContent=`${state.yaw>0?'+':''}${state.yaw.toFixed(1)}°`;const liveWind=state.wind+state.gust;ui.windValue.textContent=Math.abs(liveWind).toFixed(1);ui.windArrow.textContent=liveWind>=0?'→':'←';ui.fireHint.textContent=state.ammoStock[state.ammo]>0?`${AMMO[state.ammo].label} · ${state.ammoStock[state.ammo]} шт.`:'боеприпас закончился';ui.fire.disabled=state.mode!=='ready'||state.ammoStock[state.ammo]<=0;updateTargetCard();updateHud();}
  [ui.power,ui.angle,ui.yaw].forEach(input=>input.addEventListener('input',()=>{if(state.mode==='ready'){updateControls();audio.tone(55,.03,'square',.025,5);}}));
  ui.ammoRow.addEventListener('click',event=>{const button=event.target.closest('[data-ammo]');if(!button||state.mode!=='ready')return;const key=button.dataset.ammo;if(state.ammoStock[key]<=0){setCallout('ПУСТО','этот боеприпас закончился',650);haptic(8);return;}state.ammo=key;for(const b of ui.ammoRow.querySelectorAll('button'))b.setAttribute('aria-checked',String(b===button));loadedShaft.color=[...AMMO[key].color];loadedTip.color=[...AMMO[key].tip];loadedShaft.visible=key!=='stone';loadedTip.visible=key!=='stone';updateControls();haptic(10);});
  ui.reset.addEventListener('click',()=>{if(state.mode!=='ready')return;ui.power.value=74;ui.angle.value=19;ui.yaw.value=0;state.selected=state.stage===0?gate:state.stage===1?(towerLeft.destroyed?towerRight:towerLeft):keep;updateControls();setCallout('ПОПРАВКИ СБРОШЕНЫ','базовая пристрелка');});
  ui.camera.addEventListener('click',()=>{if(state.mode!=='ready')return;state.cameraMode=state.cameraMode==='ballista'?'wide':'ballista';setCallout(state.cameraMode==='wide'?'ОБЩИЙ ВИД':'У БАЛЛИСТЫ','камера переключена',650);});
  ui.sound.addEventListener('click',()=>{state.sound=!state.sound;profile.sound=state.sound;saveProfile();ui.sound.classList.toggle('off',!state.sound);if(state.sound)audio.tone(220,.08,'triangle',.08,30);});ui.sound.classList.toggle('off',!state.sound);

  function updateTargetCard(){const t=state.selected;if(!t)return;const ratio=clamp(t.health/t.maxHealth,0,1);ui.targetName.textContent=t.label;ui.targetHealth.style.width=`${ratio*100}%`;ui.targetStatus.textContent=t.destroyed?'РАЗРУШЕНО':ratio>.72?'ЦЕЛЫ':ratio>.36?'ПОВРЕЖДЕНЫ':'НА ГРАНИ';}
  function selectTargetAt(clientX,clientY){let best=null,bestD=88;for(const t of targets){if(t.destroyed||t.side==='friendly')continue;const p=renderer.project(t.center);if(!p||p.z>1||p.z<0)continue;const d=Math.hypot(clientX-p.x,clientY-p.y);if(d<bestD){best=t;bestD=d;}}if(best){state.selected=best;updateTargetCard();const predicted=estimateAtCastle();const desiredYaw=Math.atan2(best.center[0]-predicted.x,100)*180/Math.PI+state.yaw;ui.yaw.value=clamp(desiredYaw,-18,18);updateControls();setCallout(best.label,best.optional?'вспомогательная цель':'цель отмечена',700);haptic(8);}}
  ui.canvas.addEventListener('pointerdown',event=>{if(state.mode!=='ready')return;state.drag={x:event.clientX,y:event.clientY,yaw:Number(ui.yaw.value),angle:Number(ui.angle.value),moved:false};ui.canvas.setPointerCapture?.(event.pointerId);});
  ui.canvas.addEventListener('pointermove',event=>{if(!state.drag||state.mode!=='ready')return;const dx=event.clientX-state.drag.x,dy=event.clientY-state.drag.y;if(Math.hypot(dx,dy)>7)state.drag.moved=true;ui.yaw.value=clamp(state.drag.yaw+dx*.06,-18,18);ui.angle.value=clamp(state.drag.angle-dy*.047,4,45);updateControls();});
  ui.canvas.addEventListener('pointerup',event=>{if(!state.drag)return;if(!state.drag.moved)selectTargetAt(event.clientX,event.clientY);state.drag=null;});ui.canvas.addEventListener('pointercancel',()=>state.drag=null);

  function aimDispersion(){const damage=(100-state.integrity)/100,overdraw=Math.max(0,(state.power-88)/12);return.0015+damage*.015+overdraw*.006;}
  function initialVelocity(){const cfg=AMMO[state.ammo],speed=(25+state.power*.31)*cfg.speed,ang=state.angle*Math.PI/180,yaw=state.yaw*Math.PI/180,spread=aimDispersion(),dy=(rand()-.5)*spread,dx=(rand()-.5)*spread;return[Math.sin(yaw+dx)*Math.cos(ang+dy)*speed,Math.sin(ang+dy)*speed,-Math.cos(yaw+dx)*Math.cos(ang+dy)*speed];}
  function muzzlePosition(){const yaw=state.yaw*Math.PI/180;return[Math.sin(yaw)*6.55,4.62,19-Math.cos(yaw)*6.55];}
  function estimateAtCastle(){let p=muzzlePosition(),v=initialVelocity(),t=0;const cfg=AMMO[state.ammo];while(t<8&&p[2]>-84&&p[1]>terrainHeight(p[0],p[2])){const dt=.025,drag=Math.max(0,1-cfg.drag*len3(v)*dt);v=mul3(v,drag);v[0]+=(state.wind+state.gust*.4)*.055*cfg.wind*dt;v[1]-=9.81*cfg.gravity*dt;p=add3(p,mul3(v,dt));t+=dt;}return{x:p[0],y:p[1],t,distance:Math.hypot(p[0],p[2]-19)};}
  function setBallistaAim(){const yaw=state.yaw*Math.PI/180,angle=state.angle*Math.PI/180;ballista.rotation[1]=yaw;turret.rotation[0]=-angle*.62;}
  function updateReticle(){const est=estimateAtCastle(),p=renderer.project([est.x,clamp(est.y,1,28),-81]);if(p){ui.reticle.style.left=`${p.x}px`;ui.reticle.style.top=`${p.y}px`;ui.rangeLabel.textContent=`${Math.round(est.distance)} м · ${Math.max(0,est.y).toFixed(1)} м`;ui.reticle.style.setProperty('--spread',`${10+aimDispersion()*650}px`);}}

  function fireShot(){if(state.mode!=='ready'||state.ammoStock[state.ammo]<=0)return;state.mode='charging';ui.fire.disabled=true;state.ammoStock[state.ammo]--;state.runShots++;state.shot={phase:'charge',timer:0,flightTime:0,position:muzzlePosition(),previous:muzzlePosition(),velocity:initialVelocity(),ammo:state.ammo,node:null,trailTimer:0,start:muzzlePosition(),impact:null,bounces:0,penetrations:0};profile.shots++;saveProfile();renderRecords();updateHud();setCallout('НАТЯЖЕНИЕ','рама принимает нагрузку',900);audio.creak();haptic(18);}
  ui.fire.addEventListener('click',fireShot);
  function createProjectile(){const cfg=AMMO[state.shot.ammo],g=new Node({name:'projectile'});effects.add(g);if(state.shot.ammo==='stone'){sphere(cfg.color,[0,0,0],[1.15,1.15,1.15],[0,0,0],g,{roughness:1});}else{box(cfg.color,[0,0,0],[.18,.18,3.4],[0,0,0],g,{roughness:1});node(GEO.cone,cfg.tip,[0,0,-2.05],[.48,1.0,.48],[Math.PI/2,0,0],g,{emissive:state.shot.ammo==='fire'?.8:0,roughness:.2});for(const side of[-1,1])box(COLORS.woodLight,[side*.34,0,1.15],[.58,.055,.72],[0,0,side*.35],g);}g.position=[...state.shot.position];state.shot.node=g;loadedProjectile.visible=false;}
  function orientProjectile(){const s=state.shot;if(!s?.node)return;const v=s.velocity;s.node.rotation[1]=Math.atan2(v[0],-v[2]);s.node.rotation[0]=Math.atan2(v[1],Math.hypot(v[0],v[2]));}
  const colliderCenter=c=>c.node?c.node.position:c.center;
  function segmentAabb(a,b,c,r=0){const center=colliderCenter(c),half=[c.size[0]/2+r,c.size[1]/2+r,c.size[2]/2+r],min=[center[0]-half[0],center[1]-half[1],center[2]-half[2]],max=[center[0]+half[0],center[1]+half[1],center[2]+half[2]],d=sub3(b,a);let tmin=0,tmax=1,normal=[0,0,0];for(let axis=0;axis<3;axis++){if(Math.abs(d[axis])<1e-7){if(a[axis]<min[axis]||a[axis]>max[axis])return null;continue;}let t1=(min[axis]-a[axis])/d[axis],t2=(max[axis]-a[axis])/d[axis],n1=[0,0,0],n2=[0,0,0];n1[axis]=-1;n2[axis]=1;if(t1>t2){[t1,t2]=[t2,t1];[n1,n2]=[n2,n1];}if(t1>tmin){tmin=t1;normal=n1;}tmax=Math.min(tmax,t2);if(tmin>tmax)return null;}return tmin>=0&&tmin<=1?{t:tmin,normal}:null;}
  function segmentSphere(a,b,c,r=0){const center=colliderCenter(c),radius=(c.radius||1)+r,d=sub3(b,a),m=sub3(a,center),A=dot3(d,d),B=2*dot3(m,d),C=dot3(m,m)-radius*radius,disc=B*B-4*A*C;if(disc<0||A<1e-8)return null;const root=Math.sqrt(disc),t=(-B-root)/(2*A);if(t<0||t>1)return null;const p=add3(a,mul3(d,t));return{t,normal:norm3(sub3(p,center))};}
  function groundHit(a,b,r){const steps=7;let prevGap=a[1]-terrainHeight(a[0],a[2])-r;for(let i=1;i<=steps;i++){const t=i/steps,p=add3(a,mul3(sub3(b,a),t)),gap=p[1]-terrainHeight(p[0],p[2])-r;if(gap<=0&&prevGap>0){let lo=(i-1)/steps,hi=t;for(let j=0;j<5;j++){const mid=(lo+hi)/2,q=add3(a,mul3(sub3(b,a),mid));if(q[1]-terrainHeight(q[0],q[2])-r>0)lo=mid;else hi=mid;}const hit=add3(a,mul3(sub3(b,a),hi));return{t:hi,normal:norm3([-.15*Math.cos(hit[0]*.15),1,.11*Math.sin(hit[2]*.11)]),ground:true};}prevGap=gap;}return null;}
  function firstCollision(a,b,r){let best=groundHit(a,b,r);for(const c of colliders){if(!c.enabled||c.side==='friendly'&&state.shot?.flightTime<.12)continue;const hit=c.shape==='sphere'?segmentSphere(a,b,c,r):segmentAabb(a,b,c,r);if(hit&&(!best||hit.t<best.t))best={...hit,collider:c};}return best;}
  const reflect=(v,n)=>sub3(v,mul3(n,2*dot3(v,n)));

  function detachChunk(ch,origin,impulse=8,extra=[0,0,0]){if(!ch||!ch.attached)return;ch.attached=false;ch.dynamic=true;ch.collider.enabled=false;const dir=norm3(add3(sub3(ch.node.position,origin),[(rand()-.5)*.7,.35+rand()*.6,(rand()-.5)*.7]));ch.velocity=add3(mul3(dir,impulse/(1+Math.sqrt(ch.mass)*.15)),extra);ch.angular=[(rand()-.5)*4,(rand()-.5)*4,(rand()-.5)*4];ch.sleep=0;dynamicDebris.push(ch);if(dynamicDebris.length>115){const old=dynamicDebris.shift();if(old?.node)old.node.visible=false;}}
  function evaluateSupport(target,origin){for(const ch of target.chunks){if(!ch.attached||ch.level<=0||!ch.support.length)continue;const attached=ch.support.filter(s=>s.attached).length;if(attached===0||(attached/ch.support.length<.34&&target.health/target.maxHealth<.5&&rand()<.34))detachChunk(ch,origin,4+rand()*5);}}
  function beginCollapse(target,origin){if(target.collapsing)return;target.collapsing=true;target.destroyed=true;profile.destroyed++;state.score+=target.score*(1+state.streak*.08);for(const c of target.colliders)if(!c.chunk)c.enabled=false;for(const ch of target.chunks){if(!ch.attached)continue;ch.detachAt=state.time+rand()*1.15+Math.max(0,7-ch.level)*.035;ch.collapseOrigin=[...origin];}if(target.material==='wood')target.burn=Math.max(target.burn,2.5);saveProfile();renderRecords();}
  function fractureTarget(target,hitCollider,position,damage,normal,cfg){target.health=Math.max(0,target.health-damage);const impactImpulse=damage*.13+len3(state.shot.velocity)*cfg.mass*.018;if(hitCollider?.chunk){hitCollider.chunk.hp-=damage*(.75+cfg.fracture*.08);if(hitCollider.chunk.hp<=0||impactImpulse>hitCollider.chunk.mass*1.8)detachChunk(hitCollider.chunk,position,impactImpulse,mul3(normal,-2));}const radius=cfg.fracture*(.75+damage/120);for(const ch of target.chunks){if(!ch.attached)continue;const distance=len3(sub3(ch.node.position,position));if(distance<radius){const falloff=1-distance/radius;ch.hp-=damage*falloff*.34;if(ch.hp<=0||rand()<falloff*.13*cfg.fracture)detachChunk(ch,position,impactImpulse*falloff);}}if(target.material==='wood'&&state.shot.ammo==='fire')target.burn=Math.max(target.burn,8);evaluateSupport(target,position);if(target.health<=0)beginCollapse(target,position);}
  function addScar(position,material,damage){const color=material==='wood'?COLORS.ash:COLORS.stoneDark,scar=box(color,[position[0],position[1],position[2]+.12],[.55+damage/95,.07,.55+damage/95],[Math.PI/2,0,rand()*TAU],castle,{roughness:1});stuckProjectiles.push(scar);}
  function spawnImpactFX(position,cfg,target,kind='solid'){const dustColor=kind==='ground'?COLORS.earth:kind==='water'?COLORS.water:(target?.material==='wood'?COLORS.woodLight:COLORS.stoneLight),count=kind==='water'?34:28;for(let i=0;i<count;i++){const dir=norm3([(rand()-.5)*2,.2+rand()*1.7,(rand()-.5)*2]),speed=kind==='water'?3+rand()*8:2+rand()*10;spawnParticle({position:add3(position,[(rand()-.5),rand()*.45,(rand()-.5)]),velocity:mul3(dir,speed),color:dustColor,scale:.18+rand()*(kind==='water'?.32:.5),life:.55+rand()*1.3,gravity:kind==='water'?-8:-5,alpha:.72,kind:kind==='water'?'splash':'dust'});}if(cfg.trail&&target)target.burn=Math.max(target.burn,7);}
  function materialMultiplier(cfg,material){return material==='wood'?cfg.wood:material==='metal'?cfg.metal:material==='flesh'?1.8:cfg.stone;}

  function resolveCollision(hit){const s=state.shot,cfg=AMMO[s.ammo],c=hit.collider,position=add3(s.previous,mul3(sub3(s.position,s.previous),hit.t)),speed=len3(s.velocity),velocityN=norm3(s.velocity),incidence=clamp(-dot3(velocityN,hit.normal),0,1);if(hit.ground){finishImpact(null,position,'ground',0);return;}if(c.kind==='water'){finishImpact(null,position,'water',0);return;}const target=c.target||null,impactTarget=target||(c.kind==='defender'?{label:'ЗАЩИТНИК',material:'flesh',center:[...colliderCenter(c)],destroyed:true,optional:true}:null),hardness=c.hardness||.5,energy=cfg.mass*speed*speed*.5,base=cfg.damage*Math.pow(clamp(speed/45,.35,1.5),1.35),damage=Math.round(base*materialMultiplier(cfg,c.material)*(0.52+incidence*.65));if(target)fractureTarget(target,c,position,damage,hit.normal,cfg);if(c.kind==='defender'){c.enabled=false;c.node.visible=false;state.score+=75;setCallout('ЗАЩИТНИК СБИТ','ответный залп ослаблен',900);}const canRicochet=c.material!=='wood'&&c.material!=='flesh'&&s.ammo!=='stone'&&incidence<.38&&s.bounces<2;if(canRicochet){s.bounces++;s.velocity=mul3(reflect(s.velocity,hit.normal),cfg.restitution*(.72+incidence));s.position=add3(position,mul3(hit.normal,.12));s.previous=[...s.position];spawnImpactFX(position,cfg,target,'solid');audio.impact(.75,false);setCallout('РИКОШЕТ',`${target?.label||'камень'} · ${damage} урона`,700);return;}const canPenetrate=c.material==='wood'&&cfg.penetration>hardness&&incidence>.68&&energy>2200&&s.penetrations<1;if(canPenetrate){s.penetrations++;s.velocity=mul3(s.velocity,.46);s.position=add3(position,mul3(velocityN,.55));s.previous=[...s.position];spawnImpactFX(position,cfg,target,'solid');audio.impact(.85,true);setCallout('ПРОБИТИЕ',`${target?.label||'дерево'} · ${damage} урона`,800);return;}addScar(position,c.material,damage);finishImpact(impactTarget,position,'solid',damage);}
  function finishImpact(target,position,kind,damage){const s=state.shot;s.phase='impact';s.timer=0;s.impact={target,position:[...position],kind,damage,error:target?len3(sub3(position,target.center)):len3(sub3(position,state.selected.center))};state.mode='impact';if(s.node){if(target?.material==='wood'&&s.ammo!=='stone'){s.node.position=[...position];s.node.scale=mul3(s.node.scale,.92);stuckProjectiles.push(s.node);}else{s.node.visible=false;}}if(target){state.hitCount++;state.streak++;state.score+=damage*10*(1+Math.min(4,state.streak)*.12);profile.bestHit=Math.max(profile.bestHit,damage);saveProfile();renderRecords();}else state.streak=0;audio.impact(clamp(len3(s.velocity)/48,.7,1.5),target?.material==='wood');haptic(damage>80?[35,25,55]:[22,18,30]);spawnImpactFX(position,AMMO[s.ammo],target,kind);ui.flash.classList.remove('active');void ui.flash.offsetWidth;ui.flash.classList.add('active');if(target)setCallout(target.destroyed?'ОБРУШЕНИЕ':damage>90?'ТЯЖЁЛОЕ ПОПАДАНИЕ':'ПОПАДАНИЕ',`${target.label} · ${damage} урона`,1500);else setCallout(kind==='water'?'В РОВ':'ПРОМАХ',kind==='water'?'снаряд утонул':'земля победила',1200);updateTargetCard();updateHud();}

  function advanceMission(){if(!missionComplete())return false;if(state.stage>=CAMPAIGN.length-1){finishRun(true,'КРЕПОСТЬ ПАЛА','Три рубежа разрушены. Осадный расчёт сделал всё, что от него требовали.');return true;}const reward=currentMission().reward;for(const[key,value]of Object.entries(reward))state.ammoStock[key]+=value;state.integrity=Math.min(100,state.integrity+8);state.stage++;state.volleyClock=currentMission().volley;state.selected=state.stage===1?(towerLeft.destroyed?towerRight:towerLeft):keep;setCallout(currentMission().label,currentMission().objective,1800);updateControls();return true;}
  function showShotResult(){const s=state.shot,hit=s.impact.target,damage=s.impact.damage;state.mode='result';setGameVisible(false);ui.result.hidden=false;ui.damageValue.nextElementSibling.textContent='УРОНА';ui.resultKicker.textContent=hit?(hit.destroyed?'УЗЕЛ РАЗРУШЕН':'ПОПАДАНИЕ'):'ПРОМАХ';ui.resultTitle.textContent=hit?(hit.destroyed?'Конструкция потеряла опору.':damage>90?'Вот теперь они заметили.':'Камень помнит.'):'Боезапас помнит такие решения.';ui.damageValue.textContent=damage;ui.resultTarget.textContent=hit?hit.label:(s.impact.kind==='water'?'РОВ':'ЗЕМЛЯ');ui.resultDistance.textContent=`${Math.round(len3(sub3(s.impact.position,s.start)))} м`;ui.resultTime.textContent=`${s.flightTime.toFixed(2)} с`;ui.resultError.textContent=`${s.impact.error.toFixed(1)} м`;}
  function finishRun(victory,title,description){state.finished=true;state.mode='result';setGameVisible(false);ui.result.hidden=false;ui.damageValue.nextElementSibling.textContent='ОЧКОВ';ui.resultKicker.textContent=victory?'ОСАДА ЗАВЕРШЕНА':'РАСЧЁТ РАЗБИТ';ui.resultTitle.textContent=title;ui.damageValue.textContent=Math.round(state.score);ui.resultTarget.textContent=victory?'КРЕПОСТЬ':'БАЛЛИСТА';ui.resultDistance.textContent=`${state.hitCount}/${state.runShots} попаданий`;ui.resultTime.textContent=`${Math.round(state.time)} с`;ui.resultError.textContent=`${Math.round(state.integrity)}%`;ui.reload.querySelector('span').textContent='НОВАЯ ОСАДА';ui.reload.querySelector('small').textContent=description;profile.bestScore=Math.max(profile.bestScore,state.score);saveProfile();}
  ui.reload.addEventListener('click',()=>{if(state.finished){ui.reload.querySelector('span').textContent='ПЕРЕЗАРЯДИТЬ';ui.reload.querySelector('small').textContent='следующий выстрел';beginGame();return;}ui.result.hidden=true;setGameVisible(true);state.mode='ready';state.shot=null;loadedProjectile.visible=true;loadedProjectile.position[2]=0;stringLeft.scale[2]=1;stringRight.scale[2]=1;turret.position[2]=-.6;state.wind=clamp(state.wind+(rand()-.5)*2.8,-7.5,7.5);advanceMission();if(totalAmmo()<=0&&!missionComplete()){finishRun(false,'Снаряды закончились','Крепость пережила ваш последний аргумент.');return;}autoSelectAmmo();updateControls();});
  ui.resultReset.addEventListener('click',()=>{ui.reload.querySelector('span').textContent='ПЕРЕЗАРЯДИТЬ';ui.reload.querySelector('small').textContent='следующий выстрел';beginGame();});
  function autoSelectAmmo(){if(state.ammoStock[state.ammo]>0)return;const next=Object.keys(state.ammoStock).find(k=>state.ammoStock[k]>0);if(!next)return;state.ammo=next;for(const b of ui.ammoRow.querySelectorAll('button'))b.setAttribute('aria-checked',String(b.dataset.ammo===next));loadedShaft.visible=next!=='stone';loadedTip.visible=next!=='stone';loadedShaft.color=[...AMMO[next].color];loadedTip.color=[...AMMO[next].tip];}
  function resetCastle(){for(const t of targets){t.health=t.maxHealth;t.destroyed=false;t.collapsing=false;t.burn=0;for(const ch of t.chunks){ch.attached=true;ch.dynamic=false;ch.hp=ch.maxHp;ch.node.visible=true;ch.node.position=[...ch.basePosition];ch.node.rotation=[...ch.baseRotation];ch.collider.enabled=true;delete ch.detachAt;}}for(const d of dynamicDebris)d.dynamic=false;dynamicDebris.length=0;for(const a of state.incoming)a.node.visible=false;state.incoming.length=0;for(const s of stuckProjectiles)s.visible=false;stuckProjectiles.length=0;for(const c of colliders)if(c.kind==='defender'){c.enabled=true;c.node.visible=true;}updateTargetCard();}

  function spawnDefenderVolley(){const liveTowers=[towerLeft,towerRight].filter(t=>!t.destroyed),count=Math.max(3,liveTowers.length*4+2),damage=6+state.stage*4+liveTowers.length*2;state.volleyClock=currentMission().volley*(.82+rand()*.34);setCallout('ОТВЕТНЫЙ ЗАЛП',`${count} стрел идут к расчёту`,950);audio.tone(110,.16,'sawtooth',.04,-45);haptic([10,35,10]);for(let i=0;i<count;i++){const source=liveTowers.length?liveTowers[i%liveTowers.length].center:[(rand()-.5)*20,17,-83],end=[(rand()-.5)*7,1.8+rand()*2,17+(rand()-.5)*7],g=new Node({name:'enemy-arrow'});effects.add(g);box(COLORS.woodDark,[0,0,0],[.07,.07,2.3],[0,0,0],g,{roughness:.8});node(GEO.cone,COLORS.iron,[0,0,-1.35],[.19,.38,.19],[Math.PI/2,0,0],g,{roughness:.2});state.incoming.push({node:g,start:[...source],end,t:-i*.055,duration:.75+rand()*.35,damage:damage/count,hit:false});}}
  function updateIncoming(dt){for(let i=state.incoming.length-1;i>=0;i--){const a=state.incoming[i];a.t+=dt;if(a.t<0)continue;const q=clamp(a.t/a.duration,0,1),arc=Math.sin(q*Math.PI)*12;a.node.position=[a.start[0]+(a.end[0]-a.start[0])*q,a.start[1]+(a.end[1]-a.start[1])*q+arc,a.start[2]+(a.end[2]-a.start[2])*q];const dir=sub3(a.end,a.start);a.node.rotation[1]=Math.atan2(dir[0],-dir[2]);a.node.rotation[0]=Math.atan2(dir[1]-Math.cos(q*Math.PI)*12,Math.hypot(dir[0],dir[2]));if(q>=1){a.node.visible=false;state.incoming.splice(i,1);state.integrity=Math.max(0,state.integrity-a.damage);state.shake=Math.max(state.shake,.22);for(let p=0;p<3;p++)spawnParticle({position:a.end,velocity:[(rand()-.5)*3,2+rand()*4,(rand()-.5)*3],color:COLORS.woodLight,scale:.12+rand()*.16,life:.5+rand()*.5,gravity:-7,kind:'debris'});if(state.integrity<=0)finishRun(false,'БАЛЛИСТА УНИЧТОЖЕНА','Защитники получили слишком много времени на пристрелку.');}}updateHud();}

  function updateShot(dt){const s=state.shot;if(!s)return;if(s.phase==='charge'){s.timer+=dt;const t=clamp(s.timer/(1.02+(100-state.integrity)*.003),0,1),pull=smoothstep(0,1,t);winch.rotation[0]+=dt*4;turret.position[2]=-.6+Math.sin(t*Math.PI)*.14;stringLeft.scale[2]=1-pull*.05;stringRight.scale[2]=1-pull*.05;loadedProjectile.position[2]=pull*.82;if(t>=1){s.phase='flight';s.timer=0;state.mode='flight';createProjectile();audio.fire();haptic(28);setCallout('ВЫСТРЕЛ','ветер меняется по траектории',700);state.shake=.36;}return;}if(s.phase==='flight'){const cfg=AMMO[s.ammo],step=Math.min(dt,.024);s.flightTime+=step;s.previous=[...s.position];const drag=Math.max(0,1-cfg.drag*len3(s.velocity)*step);s.velocity=mul3(s.velocity,drag);s.velocity[0]+=(state.wind+state.gust)*.055*cfg.wind*step;s.velocity[1]-=9.81*cfg.gravity*step;s.position=add3(s.position,mul3(s.velocity,step));s.node.position=[...s.position];orientProjectile();s.trailTimer-=step;if(cfg.trail&&s.trailTimer<=0){s.trailTimer=.042;spawnParticle({position:add3(s.position,[0,0,.8]),velocity:[(rand()-.5)*.4,.5+rand(),1.5],color:rand()>.5?[1,.28,.05]:[.9,.58,.12],scale:.16+rand()*.14,life:.42+rand()*.35,gravity:.1,alpha:.9,emissive:1.2,kind:'fire'});}const hit=firstCollision(s.previous,s.position,cfg.radius);if(hit){resolveCollision(hit);return;}if(s.flightTime>10||s.position[2]<-158||Math.abs(s.position[0])>105){finishImpact(null,s.position,'miss',0);return;}}else if(s.phase==='impact'){s.timer+=dt;if(s.timer>1.4)showShotResult();}}
  function collideDebris(ch){const radius=Math.max(ch.size[0],ch.size[1],ch.size[2])*.28,ground=terrainHeight(ch.node.position[0],ch.node.position[2])+radius;if(ch.node.position[1]<ground){ch.node.position[1]=ground;if(Math.abs(ch.velocity[1])>1.2)ch.velocity[1]=Math.abs(ch.velocity[1])*.22;else ch.velocity[1]=0;ch.velocity[0]*=.76;ch.velocity[2]*=.76;ch.angular=mul3(ch.angular,.72);ch.sleep+=.12;}for(const c of colliders){if(!c.enabled||c.target===ch.target||c.kind==='water'||c.kind==='defender'||c.kind==='ballista')continue;const center=colliderCenter(c);if(c.shape==='aabb'&&Math.abs(ch.node.position[0]-center[0])<c.size[0]/2+radius&&Math.abs(ch.node.position[1]-center[1])<c.size[1]/2+radius&&Math.abs(ch.node.position[2]-center[2])<c.size[2]/2+radius){const dx=c.size[0]/2+radius-Math.abs(ch.node.position[0]-center[0]),dy=c.size[1]/2+radius-Math.abs(ch.node.position[1]-center[1]),dz=c.size[2]/2+radius-Math.abs(ch.node.position[2]-center[2]);if(dy<dx&&dy<dz){ch.node.position[1]+=Math.sign(ch.node.position[1]-center[1]||1)*dy;ch.velocity[1]*=-.18;}else if(dx<dz){ch.node.position[0]+=Math.sign(ch.node.position[0]-center[0]||1)*dx;ch.velocity[0]*=-.2;}else{ch.node.position[2]+=Math.sign(ch.node.position[2]-center[2]||1)*dz;ch.velocity[2]*=-.2;}}}}
  function updateStructures(dt){for(const t of targets){if(t.burn>0){t.burn-=dt;t.health=Math.max(0,t.health-dt*(t.material==='wood'?3.8:.4));if(rand()<dt*10){const p=add3(t.center,[(rand()-.5)*t.size[0]*.42,(rand()-.5)*t.size[1]*.25,(rand()-.5)*2]);spawnParticle({position:p,velocity:[(rand()-.5)*.4,1.3+rand()*2,(rand()-.5)*.4],color:rand()>.5?COLORS.fire:COLORS.ember,scale:.14+rand()*.2,life:.45+rand()*.6,gravity:.1,alpha:.9,emissive:1.2,kind:'fire'});}if(t.health<=0&&!t.destroyed)beginCollapse(t,t.center);}if(t.collapsing)for(const ch of t.chunks)if(ch.attached&&ch.detachAt&&state.time>=ch.detachAt)detachChunk(ch,ch.collapseOrigin,3+rand()*8);}if(state.mode==='ready'&&missionComplete()&&!state.finished)advanceMission();for(let i=dynamicDebris.length-1;i>=0;i--){const ch=dynamicDebris[i];if(!ch.dynamic)continue;ch.velocity[1]-=9.81*dt;ch.node.position=add3(ch.node.position,mul3(ch.velocity,dt));ch.node.rotation=add3(ch.node.rotation,mul3(ch.angular,dt));collideDebris(ch);if(ch.sleep>1.2||len3(ch.velocity)<.08&&ch.node.position[1]<terrainHeight(ch.node.position[0],ch.node.position[2])+2){ch.dynamic=false;ch.velocity=[0,0,0];}}}
  function updateParticles(dt){for(let i=particles.length-1;i>=0;i--){const p=particles[i],u=p.userData;if(!p.visible||!u||!Number.isFinite(u.life)){particles.splice(i,1);continue;}u.life-=dt;if(u.life<=0){p.parent?.remove(p);particles.splice(i,1);continue;}u.velocity[1]+=u.gravity*dt;p.position=add3(p.position,mul3(u.velocity,dt));p.rotation[0]+=dt*(u.kind==='debris'?3:1);p.rotation[2]+=dt*2;const life=clamp(u.life/(u.maxLife||u.life),0,1);if(u.kind==='dust'){p.alpha=life*.68;p.scale=p.scale.map(()=>u.baseScale*(1+(1-life)*2.5));}else if(u.kind==='splash'){p.alpha=life*.65;p.scale[1]=u.baseScale*(1+(1-life)*2);}else if(u.kind==='fire'){p.alpha=life;p.scale[0]=p.scale[2]=u.baseScale*(.65+life*.6);}else if(p.position[1]<terrainHeight(p.position[0],p.position[2])+.05){p.position[1]=terrainHeight(p.position[0],p.position[2])+.05;u.velocity=[0,0,0];u.gravity=0;p.alpha=Math.min(p.alpha,life);}}}
  function updateAmbient(dt){state.gust=damp(state.gust,Math.sin(state.time*.63)*1.25+Math.sin(state.time*1.71)*.55,1.1,dt);water.userData.phase+=dt;water.position[1]=-.53+Math.sin(water.userData.phase*.8)*.025;water.alpha=.72+Math.sin(water.userData.phase*.6)*.04;for(const flag of flags){flag.userData.phase+=dt*(2.1+Math.abs(state.wind)*.08);flag.rotation[1]=Math.sin(flag.userData.phase)*(.1+Math.abs(state.wind)*.012);flag.scale[0]=1+Math.sin(flag.userData.phase*1.7)*.06;}for(const flame of flames){flame.userData.phase+=dt*7;flame.scale[1]=1+Math.sin(flame.userData.phase)*.22;flame.position[1]+=Math.sin(flame.userData.phase*.7)*.002;}for(const c of clouds){c.position[0]+=c.userData.speed*dt;if(c.position[0]>80)c.position[0]=-80;}for(const person of crew){person.userData.phase+=dt;person.rotation[1]=Math.sin(person.userData.phase*.8)*.05;person.position[1]+=Math.sin(person.userData.phase*1.2)*.001;}for(const smoke of smokeColumns){smoke.t-=dt;if(smoke.t<=0){smoke.t=.28+rand()*.38;spawnParticle({position:[smoke.x,smoke.y||.5,smoke.z],velocity:[(rand()-.5)*.5,.8+rand()*1.2,(rand()-.5)*.4],color:[.20,.20,.18],scale:.5+rand()*.45,life:2.8+rand()*1.8,gravity:.04,alpha:.23,kind:'dust'});}}if(state.mode==='ready'&&!state.finished){state.volleyClock-=dt;if(state.volleyClock<=0)spawnDefenderVolley();}}
  function updateCamera(dt){let desiredPos,desiredTarget;if(state.mode==='intro'){desiredPos=[13+Math.sin(state.time*.12)*4,8.7,31];desiredTarget=[0,9,-82];renderer.camera.fov=damp(renderer.camera.fov,43*Math.PI/180,3,dt);}else if(state.mode==='flight'&&state.shot){const p=state.shot.position,v=norm3(state.shot.velocity);desiredPos=add3(p,[-v[0]*5+3,2.2,-v[2]*5+2]);desiredTarget=add3(p,mul3(v,9));renderer.camera.fov=damp(renderer.camera.fov,56*Math.PI/180,4,dt);}else if(state.mode==='impact'&&state.shot?.impact){const p=state.shot.impact.position;desiredPos=add3(p,[8,5,10]);desiredTarget=add3(p,[0,1,0]);renderer.camera.fov=damp(renderer.camera.fov,44*Math.PI/180,5,dt);}else if(state.cameraMode==='wide'){desiredPos=[31,19,34];desiredTarget=[0,10,-77];renderer.camera.fov=damp(renderer.camera.fov,49*Math.PI/180,4,dt);}else{desiredPos=[9.5,7.1,32];desiredTarget=[state.yaw*.48,7.8,-72];renderer.camera.fov=damp(renderer.camera.fov,46*Math.PI/180,4,dt);}const shake=state.shake;state.shake=Math.max(0,state.shake-dt*1.8);if(shake>0)desiredPos=add3(desiredPos,[(rand()-.5)*shake,(rand()-.5)*shake,(rand()-.5)*shake]);renderer.camera.position=renderer.camera.position.map((v,i)=>damp(v,desiredPos[i],state.mode==='flight'?6:3.4,dt));renderer.camera.target=renderer.camera.target.map((v,i)=>damp(v,desiredTarget[i],state.mode==='flight'?8:4,dt));}

  let last=performance.now();
  function frame(now){const dt=Math.min(.04,(now-last)/1000||.016);last=now;state.time+=dt;renderer.time=state.time;setBallistaAim();updateShot(dt);updateIncoming(dt);updateStructures(dt);updateParticles(dt);updateAmbient(dt);updateCamera(dt);renderer.render(root);if(state.mode==='ready')updateReticle();updateHud();requestAnimationFrame(frame);}
  function init(){const lines=['выкатываем тяжёлую раму','натягиваем торсионы','считаем зубцы и плохие решения'];let i=0;const timer=setInterval(()=>ui.loadingText.textContent=lines[i++%lines.length],380);setTimeout(()=>{clearInterval(timer);ui.loading.hidden=true;requestAnimationFrame(frame);},900);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});document.addEventListener('visibilitychange',()=>{last=performance.now();});updateControls();}
  init();
}
