import { Vector3 } from '@babylonjs/core';
import { clamp, pointSegmentDistanceSquared, weaponDamage } from './core.js';
const lerpVector=(a,b,t)=>Vector3.Lerp(a,b,t);const bladeClosestFactor=(point,base,tip)=>pointSegmentDistanceSquared(point,base,tip).t;
function segmentSegmentDistanceSquared(p1,q1,p2,q2){const d1=q1.subtract(p1),d2=q2.subtract(p2),r=p1.subtract(p2),a=Vector3.Dot(d1,d1),e=Vector3.Dot(d2,d2),f=Vector3.Dot(d2,r);let s,t;if(a<=1e-8&&e<=1e-8)return{distanceSquared:Vector3.DistanceSquared(p1,p2),s:0,t:0};if(a<=1e-8){s=0;t=clamp(f/e,0,1)}else{const c=Vector3.Dot(d1,r);if(e<=1e-8){t=0;s=clamp(-c/a,0,1)}else{const b=Vector3.Dot(d1,d2),den=a*e-b*b;s=den!==0?clamp((b*f-c*e)/den,0,1):0;t=(b*s+f)/e;if(t<0){t=0;s=clamp(-c/a,0,1)}else if(t>1){t=1;s=clamp((b-c)/a,0,1)}}}const c1=p1.add(d1.scale(s)),c2=p2.add(d2.scale(t));return{distanceSquared:Vector3.DistanceSquared(c1,c2),s,t,pointA:c1,pointB:c2}}
const swordVelocity=(trace,dt)=>trace.tip.subtract(trace.prevTip).scale(1/Math.max(dt,1/240));function sampleCount(trace){const distance=Vector3.Distance(trace.prevTip,trace.tip);return clamp(Math.max(3,Math.ceil(distance/.09)),3,14)}
function translateShield(warrior,delta){warrior.leftHand.position.addInPlace(delta);warrior.shield.center.addInPlace(delta);warrior.meshes.shield.position.addInPlace(delta);warrior.meshes.shieldRim.position.addInPlace(delta);warrior.meshes.shieldBoss.position.addInPlace(delta)}
function shieldBodyContact(shield,defender){let best=null;const normal=shield.normal.normalizeToNew();for(const sphere of defender.getHitSpheres()){const delta=sphere.center.subtract(shield.center),signed=Vector3.Dot(delta,normal),planar=delta.subtract(normal.scale(signed)),radialLimit=shield.radius+sphere.radius*.46,planeLimit=sphere.radius+.085;if(planar.length()>radialLimit||Math.abs(signed)>=planeLimit)continue;const penetration=planeLimit-Math.abs(signed);if(!best||penetration>best.penetration)best={sphere,penetration,point:sphere.center.subtract(normal.scale(signed)),normal:signed>=0?normal:normal.scale(-1)}}return best}
function intersectsShield(trace,shield,dt){const steps=sampleCount(trace);for(let i=0;i<=steps;i++){const tFrame=i/steps,base=lerpVector(trace.prevBase,trace.base,tFrame),tip=lerpVector(trace.prevTip,trace.tip,tFrame),center=lerpVector(shield.prevCenter,shield.center,tFrame),normal=lerpVector(shield.prevNormal,shield.normal,tFrame).normalize(),d0=Vector3.Dot(base.subtract(center),normal),d1=Vector3.Dot(tip.subtract(center),normal),thickness=.075;if(Math.min(Math.abs(d0),Math.abs(d1))>thickness&&d0*d1>0)continue;const den=d0-d1,bladeT=Math.abs(den)>1e-6?clamp(d0/den,0,1):(Math.abs(d0)<Math.abs(d1)?0:1),point=Vector3.Lerp(base,tip,bladeT),radial=point.subtract(center),planar=radial.subtract(normal.scale(Vector3.Dot(radial,normal))),distance=planar.length();if(distance<=shield.radius+.045)return{point,normal,frameT:tFrame,bladeT,distance}}return null}
function intersectsBody(trace,defender,dt){const steps=sampleCount(trace),spheres=defender.getHitSpheres();let best=null;for(let i=0;i<=steps;i++){const tFrame=i/steps,base=lerpVector(trace.prevBase,trace.base,tFrame),tip=lerpVector(trace.prevTip,trace.tip,tFrame);for(const sphere of spheres){const result=pointSegmentDistanceSquared(sphere.center,base,tip),radius=sphere.radius+.035;if(result.distanceSquared<=radius*radius){const point=Vector3.Lerp(base,tip,result.t),candidate={sphere,point,bladeT:result.t,frameT:tFrame,distanceSquared:result.distanceSquared};if(!best||candidate.distanceSquared<best.distanceSquared)best=candidate}}if(best)break}return best}
function intersectsSword(a,b,dt){const steps=Math.max(sampleCount(a),sampleCount(b));for(let i=0;i<=steps;i++){const t=i/steps,a0=lerpVector(a.prevBase,a.base,t),a1=lerpVector(a.prevTip,a.tip,t),b0=lerpVector(b.prevBase,b.base,t),b1=lerpVector(b.prevTip,b.tip,t),closest=segmentSegmentDistanceSquared(a0,a1,b0,b1);if(closest.distanceSquared<.0081)return{...closest,frameT:t}}return null}
function stopWeaponAtBarrier(attacker,sword,velocity,hit,dt){const motion=velocity.lengthSquared()>1e-7?velocity.normalizeToNew():sword.tip.subtract(sword.base).normalize(),pushNormal=Vector3.Dot(motion,hit.normal)>0?hit.normal.scale(-1):hit.normal.clone(),remaining=Vector3.Distance(sword.prevTip,sword.tip)*(1-hit.frameT),penetration=clamp(.018+remaining*.82,.018,.18);if(attacker.applyWeaponContact)attacker.applyWeaponContact({normal:pushNormal,penetration,bladeT:hit.bladeT});else{const correction=pushNormal.scale(penetration),handShare=.22+(1-hit.bladeT)*.32;attacker.rightHand.position.addInPlace(correction.scale(handShare));attacker.sword.base.addInPlace(correction.scale(handShare));attacker.sword.tip.addInPlace(correction);attacker.bones.handR.setAbsolutePosition(attacker.rightHand.position)}attacker.applyWeaponImpulse(pushNormal.scale(1.2+clamp(velocity.length()/8,0,1)*1.8));return pushNormal}
export class CombatSystem{
 constructor(onEvent=()=>{}){this.onEvent=onEvent;this.cooldowns=new Map()}
 key(type,a,b){return`${type}:${a.id}:${b.id}`}
 canContact(type,a,b,now,cooldown){const key=this.key(type,a,b),previous=this.cooldowns.get(key)||-Infinity;if(now-previous<cooldown)return false;this.cooldowns.set(key,now);return true}
 resolveShieldBody(owner,defender,now){const hit=shieldBodyContact(owner.getShieldTrace(),defender);if(!hit)return false;let separation=defender.position.subtract(owner.position);separation.y=0;if(separation.lengthSquared()<1e-6)separation=hit.normal.clone();separation.normalize();const correction=clamp(hit.penetration*.42+.006,.008,.075);translateShield(owner,separation.scale(-correction*.82));owner.applyShieldContact?.({normal:separation.scale(-1),penetration:correction*.7});owner.leftHand.velocity.addInPlace(separation.scale(-correction*15));owner.position.addInPlace(separation.scale(-correction*.34));defender.position.addInPlace(separation.scale(correction*.28));owner.velocity.scaleInPlace(.76);defender.velocity.scaleInPlace(.8);owner.stability=Math.max(0,owner.stability-correction*48);defender.applyBodyImpulse(separation.scale(correction*20));if(this.canContact('shield-body',owner,defender,now,.11))this.onEvent({type:'block',attacker:owner,defender,point:hit.point,normal:hit.normal,intensity:clamp(hit.penetration/.22,.15,.72),speed:0});return true}
 resolveShieldShield(a,b,now){const A=a.getShieldTrace(),B=b.getShieldTrace(),delta=B.center.subtract(A.center),distance=delta.length(),minimum=(A.radius+B.radius)*.78;if(distance<=1e-5||distance>=minimum)return false;const normal=delta.scale(1/distance),penetration=minimum-distance,correction=clamp(penetration*.34,.006,.06);translateShield(a,normal.scale(-correction));translateShield(b,normal.scale(correction));a.applyShieldContact?.({normal:normal.scale(-1),penetration:correction});b.applyShieldContact?.({normal,penetration:correction});a.leftHand.velocity.addInPlace(normal.scale(-correction*13));b.leftHand.velocity.addInPlace(normal.scale(correction*13));if(this.canContact('shield-shield',a,b,now,.13))this.onEvent({type:'clash',a,b,point:Vector3.Lerp(A.center,B.center,.5),intensity:clamp(penetration/.25,.15,.7)});return true}
 resolvePair(a,b,dt,now){if(a.dead||b.dead)return;this.resolveShieldBody(a,b,now);this.resolveShieldBody(b,a,now);this.resolveShieldShield(a,b,now);const swordA=a.getSwordTrace(),swordB=b.getSwordTrace(),velocityA=swordVelocity(swordA,dt),velocityB=swordVelocity(swordB,dt),relative=velocityA.subtract(velocityB),clash=intersectsSword(swordA,swordB,dt);if(clash){const intensity=clamp(relative.length()/10,.12,1),normalA=velocityA.lengthSquared()>1e-5?velocityA.normalizeToNew().scale(-1):a.swordDirection.position.scale(-1),normalB=velocityB.lengthSquared()>1e-5?velocityB.normalizeToNew().scale(-1):b.swordDirection.position.scale(-1);a.applyWeaponContact?.({normal:normalA,penetration:.025+intensity*.05,bladeT:clash.s});b.applyWeaponContact?.({normal:normalB,penetration:.025+intensity*.05,bladeT:clash.t});a.applyWeaponImpulse(normalA.scale(.9+intensity*1.6));b.applyWeaponImpulse(normalB.scale(.9+intensity*1.6));if(this.canContact('clash',a,b,now,.16))this.onEvent({type:'clash',a,b,point:clash.pointA,intensity});return}this.resolveAttack(a,b,swordA,velocityA,dt,now);this.resolveAttack(b,a,swordB,velocityB,dt,now)}
 resolveAttack(attacker,defender,sword,velocity,dt,now){if(attacker.dead||defender.dead)return;const speed=velocity.length(),shieldHit=intersectsShield(sword,defender.getShieldTrace(),dt);if(shieldHit){const pushNormal=stopWeaponAtBarrier(attacker,sword,velocity,shieldHit,dt),incidence=Math.abs(Vector3.Dot(velocity.lengthSquared()>1e-5?velocity.normalizeToNew():sword.tip.subtract(sword.base).normalize(),shieldHit.normal)),intensity=clamp((Math.max(speed,.8)/9)*(.55+incidence*.45),.10,1);defender.applyShieldImpulse(pushNormal.scale(-1.4*intensity));defender.applyShieldContact?.({normal:pushNormal.scale(-1),penetration:.015+intensity*.035});if(this.canContact('shield',attacker,defender,now,.13))this.onEvent({type:'block',attacker,defender,point:shieldHit.point,normal:shieldHit.normal,intensity,speed});return}if(speed<.45)return;const bodyHit=intersectsBody(sword,defender,dt);if(!bodyHit)return;const tipFactor=Math.max(0,bladeClosestFactor(bodyHit.point,sword.base,sword.tip)),damage=weaponDamage(speed,tipFactor,bodyHit.sphere.multiplier),direction=velocity.lengthSquared()>1e-5?velocity.normalizeToNew():sword.tip.subtract(sword.base).normalize();if(damage<=0){if(this.canContact('graze',attacker,defender,now,.08))this.onEvent({type:'graze',attacker,defender,point:bodyHit.point,intensity:clamp(speed/5,.1,.5),speed});return}if(!this.canContact('body',attacker,defender,now,.24))return;const impulse=direction.scale(4.6+damage*.13),applied=defender.takeDamage(damage,impulse);attacker.applyWeaponImpulse(direction.scale(-(1.1+applied*.025)));this.onEvent({type:'hit',attacker,defender,point:bodyHit.point,bodyPart:bodyHit.sphere.name,damage:applied,intensity:clamp(applied/28,.2,1),speed})}
 reset(){this.cooldowns.clear()}
}
