import { Quaternion, Vector3 } from '@babylonjs/core';
import { clamp } from './core.js';
import { ConstraintArm, vec3 } from './constraint-model.js';

const AXIS_Y=new Vector3(0,1,0),AXIS_Z=new Vector3(0,0,1);
function basis(yaw){return{forward:new Vector3(Math.sin(yaw),0,Math.cos(yaw)),right:new Vector3(Math.cos(yaw),0,-Math.sin(yaw))}}
function quatAxisTo(axis,direction){const dir=direction.normalizeToNew(),dot=clamp(Vector3.Dot(axis,dir),-1,1);if(dot>.999999)return Quaternion.Identity();if(dot<-.999999)return Quaternion.RotationAxis(new Vector3(1,0,0),Math.PI);const cross=Vector3.Cross(axis,dir);if(cross.lengthSquared()<1e-8)return Quaternion.Identity();cross.normalize();return Quaternion.RotationAxis(cross,Math.acos(dot))}
function setSegment(mesh,a,b,axis=AXIS_Y){const delta=b.subtract(a),length=Math.max(.001,delta.length());mesh.position.copyFrom(a.add(b).scale(.5));mesh.rotationQuaternion=quatAxisTo(axis,delta);if(axis===AXIS_Y)mesh.scaling.set(1,length,1);else mesh.scaling.set(1,1,length)}
function toWorld(local,origin,b){return origin.add(b.right.scale(local.x)).add(new Vector3(0,local.y,0)).add(b.forward.scale(local.z))}
function toLocal(world,b){return vec3(Vector3.Dot(world,b.right),world.y,Vector3.Dot(world,b.forward))}
const PLAYER_GUARD={hand:vec3(.17,-.19,.43),tip:vec3(.28,.43,1.25),shieldHand:vec3(-.17,-.16,.37),shieldCenter:vec3(-.23,-.12,.43)};

class PhysicalUpperBody{
 constructor(game){this.game=game;this.player=game.player;this.weapon=new ConstraintArm({upper:.34,lower:.33,tool:1.04,handed:1,restHand:PLAYER_GUARD.hand,restTool:vec3(.10,.58,.80)});this.shield=new ConstraintArm({upper:.33,lower:.32,tool:.075,handed:-1,restHand:PLAYER_GUARD.shieldHand,restTool:vec3(-.18,.05,.98)});this.prevSwordBase=null;this.prevSwordTip=null;this.prevShieldCenter=null;this.prevShieldNormal=null;this.lastGesture={x:0,y:0};this.breathPhase=Math.random()*Math.PI*2;this.reset();this.patchImpulses()}
 reset(){this.weapon.reset(vec3());this.shield.reset(vec3());this.prevSwordBase=this.prevSwordTip=this.prevShieldCenter=this.prevShieldNormal=null;this.lastGesture={x:0,y:0}}
 patchImpulses(){const p=this.player,oldWeapon=p.applyWeaponImpulse.bind(p),oldShield=p.applyShieldImpulse.bind(p);p.applyWeaponImpulse=impulse=>{oldWeapon(impulse);const b=basis(p.upperYaw),l=toLocal(impulse,b);this.weapon.impulse(vec3(l.x,l.y,l.z),.040)};p.applyShieldImpulse=impulse=>{oldShield(impulse);const b=basis(p.upperYaw),l=toLocal(impulse,b);this.shield.impulse(vec3(l.x,l.y,l.z),.034)};p.applyWeaponContact=({normal,penetration=.04,bladeT=.8})=>{const b=basis(p.upperYaw),n=toLocal(normal,b),pose=this.weapon.contact(vec3(n.x,n.y,n.z),penetration,bladeT),shoulder=p.bones.shoulderR.getAbsolutePosition();this.applyWeaponPose(pose,shoulder,b,1/120)};p.applyShieldContact=({normal,penetration=.03})=>{const b=basis(p.upperYaw),n=toLocal(normal,b),pose=this.shield.contact(vec3(n.x,n.y,n.z),penetration,.7),shoulder=p.bones.shoulderL.getAbsolutePosition();this.applyShieldPose(pose,shoulder,b,1/120)}}
 drive(control,dt){const p=this.player,b=basis(p.upperYaw),shoulderR=p.bones.shoulderR.getAbsolutePosition(),shoulderL=p.bones.shoulderL.getAbsolutePosition(),gy=control.gestureYawRate??control.lookYawRate??0,gp=control.gesturePitchRate??control.lookPitchRate??0,gestureEnergy=clamp(Math.hypot(gy,gp)/10.5,0,1),deltaX=gy-this.lastGesture.x,deltaY=gp-this.lastGesture.y;this.lastGesture={x:gy,y:gp};const snap=clamp(Math.hypot(deltaX,deltaY)/6.4,0,1);this.breathPhase+=dt*(1.7+gestureEnergy*.8);const breath=Math.sin(this.breathPhase),moving=clamp(control.moveMagnitude||0,0,1),aimPitch=clamp(control.lookPitch||0,-.68,.72),height=aimPitch*1.05;
  // The viewing angle moves the entire combat workspace. Looking down genuinely lowers the sword
  // and shield toward thigh/knee level; looking up creates high guard / overhead cover.
  const guardHand=vec3(PLAYER_GUARD.hand.x,clamp(PLAYER_GUARD.hand.y+height*.52+breath*.006-moving*.012,-.58,.28),PLAYER_GUARD.hand.z-moving*.018);
  const guardTip=vec3(PLAYER_GUARD.tip.x+breath*.008,clamp(PLAYER_GUARD.tip.y+height*.92+breath*.012,-.72,1.10),PLAYER_GUARD.tip.z-(Math.max(0,-aimPitch)*.20));
  const drive=vec3(-gy*(.78+.48*snap),gp*(1.06+.58*snap),gestureEnergy*(1.15+.65*snap));
  const weaponPose=this.weapon.step({shoulder:vec3(),guardHand,guardTip,drive,brace:.72-gestureEnergy*.28,dt,iterations:9});
  let threat=vec3(),danger=0;const enemy=this.game.enemy;if(enemy&&!enemy.dead){const trace=enemy.getSwordTrace(),rel=trace.tip.subtract(p.bones.chest.getAbsolutePosition()),dist=rel.length();danger=clamp((trace.speed-1.7)/6,0,1)*clamp((3.0-dist)/1.5,0,1);threat=vec3(-Vector3.Dot(rel,b.right)*danger*2.2,(rel.y-.2)*danger*1.35,danger*1.45)}
  const shieldUserY=height*.78,shieldDrive=vec3(threat.x-gy*.10,threat.y+gp*.20,threat.z),shieldGuardHand=vec3(PLAYER_GUARD.shieldHand.x,clamp(PLAYER_GUARD.shieldHand.y+shieldUserY+breath*.004,-.58,.46),PLAYER_GUARD.shieldHand.z),shieldGuardCenter=vec3(PLAYER_GUARD.shieldCenter.x,clamp(PLAYER_GUARD.shieldCenter.y+shieldUserY+breath*.005,-.62,.62),PLAYER_GUARD.shieldCenter.z+danger*.035-Math.abs(aimPitch)*.03);
  const shieldPose=this.shield.step({shoulder:vec3(),guardHand:shieldGuardHand,guardTip:shieldGuardCenter,drive:shieldDrive,brace:.88-danger*.08,dt,iterations:10});
  this.applyWeaponPose(weaponPose,shoulderR,b,dt);this.applyShieldPose(shieldPose,shoulderL,b,dt);if(gestureEnergy>.12){p.impactLeanVelocity.addInPlace(b.right.scale(-deltaX*.0017));p.impactLeanVelocity.y+=-deltaY*.0008;p.stability=Math.max(0,p.stability-gestureEnergy*dt*1.8)}}
 applyWeaponPose(pose,shoulder,b,dt){const w=this.player,elbow=toWorld(pose.elbow,shoulder,b),hand=toWorld(pose.hand,shoulder,b),tip=toWorld(pose.tip,shoulder,b);w.bones.elbowR.setAbsolutePosition(elbow);w.bones.handR.setAbsolutePosition(hand);w.rightHand.position.copyFrom(hand);setSegment(w.meshes.upperArmR,shoulder,elbow);setSegment(w.meshes.forearmR,elbow,hand);const dir=tip.subtract(hand).normalize(),lastBase=this.prevSwordBase?.clone()??hand.clone(),lastTip=this.prevSwordTip?.clone()??tip.clone();w.sword.prevBase.copyFrom(lastBase);w.sword.prevTip.copyFrom(lastTip);w.sword.base.copyFrom(hand);w.sword.tip.copyFrom(tip);this.prevSwordBase=hand.clone();this.prevSwordTip=tip.clone();w.swordDirection.position.copyFrom(dir);w.sword.speed=tip.subtract(lastTip).scale(1/Math.max(dt,1/240)).length();const baseSpeed=hand.subtract(lastBase).scale(1/Math.max(dt,1/240)),tipSpeed=tip.subtract(lastTip).scale(1/Math.max(dt,1/240));w.sword.angularSpeed=tipSpeed.subtract(baseSpeed).length()/w.sword.length;setSegment(w.meshes.blade,hand.add(dir.scale(.10)),tip,AXIS_Z);setSegment(w.meshes.grip,hand.subtract(dir.scale(.18)),hand,AXIS_Y);w.meshes.guard.position.copyFrom(hand.add(dir.scale(.015)));w.meshes.guard.rotationQuaternion=quatAxisTo(AXIS_Z,dir);const roll=clamp((pose.tip.x-pose.hand.x)*-.55+(pose.tip.y-pose.hand.y)*.32,-.85,.85),q=Quaternion.RotationAxis(dir,roll);w.meshes.blade.rotationQuaternion=q.multiply(w.meshes.blade.rotationQuaternion);w.meshes.guard.rotationQuaternion=q.multiply(w.meshes.guard.rotationQuaternion)}
 applyShieldPose(pose,shoulder,b,dt){const w=this.player,elbow=toWorld(pose.elbow,shoulder,b),hand=toWorld(pose.hand,shoulder,b),center=toWorld(pose.tip,shoulder,b);w.bones.elbowL.setAbsolutePosition(elbow);w.bones.handL.setAbsolutePosition(hand);w.leftHand.position.copyFrom(hand);setSegment(w.meshes.upperArmL,shoulder,elbow);setSegment(w.meshes.forearmL,elbow,hand);const normal=b.forward.scale(.88).add(b.right.scale(.14)).add(new Vector3(0,clamp((center.y-shoulder.y)*-.12,-.18,.12),0)).normalize(),lastCenter=this.prevShieldCenter?.clone()??center.clone(),lastNormal=this.prevShieldNormal?.clone()??normal.clone();w.shield.prevCenter.copyFrom(lastCenter);w.shield.prevNormal.copyFrom(lastNormal);w.shield.center.copyFrom(center);w.shield.normal.copyFrom(normal);this.prevShieldCenter=center.clone();this.prevShieldNormal=normal.clone();w.shieldNormal.position.copyFrom(normal);const rot=quatAxisTo(AXIS_Y,normal);w.meshes.shield.position.copyFrom(center);w.meshes.shield.rotationQuaternion=rot;w.meshes.shieldRim.position.copyFrom(center.add(normal.scale(.045)));w.meshes.shieldRim.rotationQuaternion=rot;w.meshes.shieldBoss.position.copyFrom(center.add(normal.scale(.075)))}
}
export function installConstraintCombat(game){const body=new PhysicalUpperBody(game),originalUpdate=game.update.bind(game),originalRestart=game.restart?.bind(game),originalHandle=game.handleCombatEvent.bind(game);let hitStop=0;const originalPlayerUpdate=game.player.update.bind(game.player);game.player.update=(dt,control,snap=false)=>{originalPlayerUpdate(dt,control,snap);if(snap)body.reset();else body.drive(control,dt)};game.update=(dt,now)=>{if(hitStop>0){hitStop-=dt;return}originalUpdate(dt,now)};game.handleCombatEvent=event=>{if(event.type==='hit')hitStop=Math.max(hitStop,.032+(event.intensity||0)*.018);else if(event.type==='clash')hitStop=Math.max(hitStop,.018+(event.intensity||0)*.012);else if(event.type==='block')hitStop=Math.max(hitStop,.014+(event.intensity||0)*.010);originalHandle(event)};if(originalRestart)game.restart=(...args)=>{body.reset();hitStop=0;return originalRestart(...args)};return body}
