import { bindPointerGesture } from '../../../shared/mobile-runtime.js';
import { clamp } from './core.js';

export class DuelInput {
  constructor(root, storageNamespace) {
    this.root=root;this.storageNamespace=storageNamespace;this.leftZone=root.querySelector('#move-zone');this.rightZone=root.querySelector('#look-zone');this.base=root.querySelector('#joystick-base');this.knob=root.querySelector('#joystick-knob');this.movePointer=null;this.lookPointer=null;this.moveOrigin={x:0,y:0};this.lookLast={x:0,y:0};this.move={x:0,y:0};this.lookAccum={x:0,y:0};this.keys=new Set();this.sensitivity=Number(localStorage.getItem(`${storageNamespace}:sensitivity`)||1);this.cleanup=[];this.bind();
  }
  bind(){this.cleanup.push(bindPointerGesture(this.leftZone,{onStart:e=>this.startMove(e),onMove:e=>this.updateMove(e),onEnd:e=>this.endMove(e),onCancel:e=>this.endMove(e)}));this.cleanup.push(bindPointerGesture(this.rightZone,{onStart:e=>this.startLook(e),onMove:e=>this.updateLook(e),onEnd:e=>this.endLook(e),onCancel:e=>this.endLook(e)}));this.onKeyDown=e=>this.keys.add(e.code);this.onKeyUp=e=>this.keys.delete(e.code);window.addEventListener('keydown',this.onKeyDown);window.addEventListener('keyup',this.onKeyUp)}
  startMove(event){if(this.movePointer!==null)return;event.preventDefault();this.movePointer=event.pointerId;this.moveOrigin.x=event.clientX;this.moveOrigin.y=event.clientY;this.base.classList.add('active');this.base.style.transform=`translate3d(${event.clientX}px, ${event.clientY}px, 0)`;this.updateMove(event)}
  updateMove(event){if(event.pointerId!==this.movePointer)return;event.preventDefault();const dx=event.clientX-this.moveOrigin.x,dy=event.clientY-this.moveOrigin.y,radius=Math.min(62,Math.max(48,window.innerHeight*.14)),length=Math.hypot(dx,dy),scale=length>radius?radius/length:1,px=dx*scale,py=dy*scale,nx=px/radius,ny=-py/radius,magnitude=Math.hypot(nx,ny),dead=.12,filtered=magnitude<dead?0:(magnitude-dead)/(1-dead),n=magnitude>1e-5?filtered/magnitude:0;this.move.x=nx*n;this.move.y=ny*n;this.knob.style.transform=`translate3d(${px}px, ${py}px, 0)`}
  endMove(event){if(event.pointerId!==this.movePointer)return;event.preventDefault();this.movePointer=null;this.move.x=0;this.move.y=0;this.knob.style.transform='translate3d(0,0,0)';this.base.classList.remove('active')}
  startLook(event){if(this.lookPointer!==null)return;event.preventDefault();this.lookPointer=event.pointerId;this.lookLast.x=event.clientX;this.lookLast.y=event.clientY;this.rightZone.classList.add('engaged')}
  updateLook(event){if(event.pointerId!==this.lookPointer)return;event.preventDefault();const dx=event.clientX-this.lookLast.x,dy=event.clientY-this.lookLast.y;this.lookLast.x=event.clientX;this.lookLast.y=event.clientY;this.lookAccum.x+=dx;this.lookAccum.y+=dy}
  endLook(event){if(event.pointerId!==this.lookPointer)return;event.preventDefault();this.lookPointer=null;this.rightZone.classList.remove('engaged')}
  getMove(){let x=this.move.x,y=this.move.y;if(this.keys.has('KeyA')||this.keys.has('ArrowLeft'))x-=1;if(this.keys.has('KeyD')||this.keys.has('ArrowRight'))x+=1;if(this.keys.has('KeyW')||this.keys.has('ArrowUp'))y+=1;if(this.keys.has('KeyS')||this.keys.has('ArrowDown'))y-=1;const l=Math.hypot(x,y);if(l>1){x/=l;y/=l}return{x,y,magnitude:Math.min(1,Math.hypot(x,y))}}
  consumeLook(dt){const dx=this.lookAccum.x,dy=this.lookAccum.y;this.lookAccum.x=0;this.lookAccum.y=0;const safeDt=Math.max(1/240,dt);const rawYaw=dx*.00518*this.sensitivity,rawPitch=dy*.00473*this.sensitivity;const gestureYawRate=clamp(rawYaw/safeDt,-15,15),gesturePitchRate=clamp(rawPitch/safeDt,-14,14);const energy=clamp((Math.hypot(gestureYawRate,gesturePitchRate)-2.2)/8.5,0,1);const cameraShare=1-energy*.50;const yaw=rawYaw*cameraShare,pitch=rawPitch*cameraShare;return{yaw,pitch,yawRate:clamp(yaw/safeDt,-11,11),pitchRate:clamp(pitch/safeDt,-10,10),gestureYawRate,gesturePitchRate,gestureEnergy:energy}}
  setSensitivity(value){this.sensitivity=clamp(Number(value)||1,.45,2.2);localStorage.setItem(`${this.storageNamespace}:sensitivity`,String(this.sensitivity))}
  resetPointers(){this.movePointer=null;this.lookPointer=null;this.move.x=0;this.move.y=0;this.lookAccum.x=0;this.lookAccum.y=0;this.knob.style.transform='translate3d(0,0,0)';this.base.classList.remove('active');this.rightZone.classList.remove('engaged')}
  dispose(){for(const cleanup of this.cleanup)cleanup?.();window.removeEventListener('keydown',this.onKeyDown);window.removeEventListener('keyup',this.onKeyUp);this.keys.clear()}
}
