export class InputController {
  constructor(root, settings){this.root=root;this.settings=settings;this.moveX=0;this.moveY=0;this.jump=false;this.flyY=0;this.breaking=false;this.use=false;this.attack=false;this.crouch=false;this.touchCrouch=false;this.lastJumpTap=0;this.pointerMap=new Map();this.keys=new Set();this.lookPointer=null;this.joyPointer=null;this.lookLast=null;this.onLook=()=>{};this.onHotbar=()=>{};this.bind();}
  bind(){
    const canvas=this.root.querySelector('#game-canvas'),joy=this.root.querySelector('#joystick'),knob=this.root.querySelector('#joystick-knob');
    const resetJoy=()=>{this.moveX=this.moveY=0;this.joyPointer=null;knob.style.transform='translate(-50%,-50%)';};
    joy.addEventListener('pointerdown',e=>{e.preventDefault();this.joyPointer=e.pointerId;joy.setPointerCapture(e.pointerId);this.updateJoy(e,joy,knob);});
    joy.addEventListener('pointermove',e=>{if(e.pointerId===this.joyPointer){e.preventDefault();this.updateJoy(e,joy,knob);}});joy.addEventListener('pointerup',resetJoy);joy.addEventListener('pointercancel',resetJoy);
    canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'){if(document.pointerLockElement!==canvas)canvas.requestPointerLock?.();if(e.button===0)this.breaking=true;if(e.button===2)this.use=true;return;}e.preventDefault();if(this.lookPointer===null){this.lookPointer=e.pointerId;this.lookLast={x:e.clientX,y:e.clientY,time:performance.now(),moved:0,holding:false};canvas.setPointerCapture(e.pointerId);}});
    canvas.addEventListener('pointermove',e=>{if(e.pointerType==='mouse')return;if(e.pointerId!==this.lookPointer||!this.lookLast)return;e.preventDefault();const dx=e.clientX-this.lookLast.x,dy=e.clientY-this.lookLast.y;this.lookLast.x=e.clientX;this.lookLast.y=e.clientY;this.lookLast.moved+=Math.abs(dx)+Math.abs(dy);this.onLook(dx,dy);});
    const endLook=e=>{if(e.pointerId!==this.lookPointer)return;if(this.lookLast?.holding)this.breaking=false;else if(this.lookLast&&this.lookLast.moved<12&&performance.now()-this.lookLast.time<260)this.use=true;this.lookPointer=null;this.lookLast=null;};canvas.addEventListener('pointerup',endLook);canvas.addEventListener('pointercancel',endLook);canvas.addEventListener('contextmenu',e=>e.preventDefault());
    document.addEventListener('mousemove',e=>{if(document.pointerLockElement===canvas)this.onLook(e.movementX,e.movementY);});
    document.addEventListener('mousedown',e=>{if(document.pointerLockElement===canvas){if(e.button===0)this.breaking=true;if(e.button===2)this.use=true;}});document.addEventListener('mouseup',e=>{if(e.button===0)this.breaking=false;});
    document.addEventListener('keydown',e=>{this.keys.add(e.code);if(e.code==='Space'){this.jump=true;e.preventDefault();}if(e.code==='KeyF')this.root.dispatchEvent(new CustomEvent('toggleflight'));if(e.code==='KeyE')this.root.dispatchEvent(new CustomEvent('openinventory'));if(e.code==='Escape')this.root.dispatchEvent(new CustomEvent('pausegame'));if(/^Digit[1-9]$/.test(e.code))this.onHotbar(Number(e.code.slice(-1))-1);});
    document.addEventListener('keyup',e=>this.keys.delete(e.code));document.addEventListener('wheel',e=>this.onHotbar(e.deltaY>0?1:-1,true),{passive:true});
    this.button('#jump-btn',()=>{const now=performance.now();if(now-this.lastJumpTap<300)this.root.dispatchEvent(new CustomEvent('toggleflight'));else this.jump=true;this.lastJumpTap=now;});this.holdButton('#break-btn',v=>this.breaking=v);this.button('#use-btn',()=>this.use=true);this.holdButton('#crouch-btn',v=>{this.touchCrouch=v;this.root.dispatchEvent(new CustomEvent('crouch',{detail:v}));});
    this.button('#inventory-btn',()=>this.root.dispatchEvent(new CustomEvent('openinventory')));this.button('#pause-btn',()=>this.root.dispatchEvent(new CustomEvent('pausegame')));
  }
  updateJoy(e,joy,knob){const r=joy.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,max=r.width*.34,len=Math.hypot(dx,dy),s=len>max?max/len:1;this.moveX=dx*s/max;this.moveY=dy*s/max;knob.style.transform=`translate(calc(-50% + ${dx*s}px),calc(-50% + ${dy*s}px))`;}
  button(sel,fn){const el=this.root.querySelector(sel);el?.addEventListener('pointerdown',e=>{e.preventDefault();fn();navigator.vibrate?.(this.settings.vibration?8:0);});}
  holdButton(sel,fn){const el=this.root.querySelector(sel);if(!el)return;el.addEventListener('pointerdown',e=>{e.preventDefault();el.setPointerCapture(e.pointerId);fn(true);});for(const type of ['pointerup','pointercancel','lostpointercapture'])el.addEventListener(type,()=>fn(false));}
  update(){if(this.lookLast&&!this.lookLast.holding&&this.lookLast.moved<12&&performance.now()-this.lookLast.time>320){this.lookLast.holding=true;this.breaking=true;}const l=(this.keys.has('KeyA')?-1:0)+(this.keys.has('KeyD')?1:0),f=(this.keys.has('KeyW')?1:0)+(this.keys.has('KeyS')?-1:0);if(l||f){this.moveX=l;this.moveY=f;}else if(this.joyPointer===null){this.moveX=0;this.moveY=0;}this.crouch=this.touchCrouch||this.keys.has('ShiftLeft')||this.keys.has('ShiftRight');this.flyY=(this.keys.has('Space')?1:0)+(this.keys.has('ShiftLeft')||this.keys.has('ShiftRight')?-1:0);}
  consumeUse(){const v=this.use;this.use=false;return v;}
}
