const DB='pocket-works-kryazh-v1',STORE='worlds';
const makeId=()=>globalThis.crypto?.randomUUID?.()||`kryazh-${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;
function open(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:'id'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
export async function listWorlds(){const db=await open();return new Promise((resolve,reject)=>{const r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>resolve(r.result.sort((a,b)=>(b.updated||0)-(a.updated||0)));r.onerror=()=>reject(r.error);});}
export async function loadWorld(id){const db=await open();return new Promise((resolve,reject)=>{const r=db.transaction(STORE).objectStore(STORE).get(id);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error);});}
export async function saveWorld(record){const db=await open();record.updated=Date.now();record.revision=(record.revision||0)+1;return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(structuredClone(record));tx.oncomplete=()=>resolve(record);tx.onerror=()=>reject(tx.error);});}
export async function deleteWorld(id){const db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}
export async function duplicateWorld(id){const w=await loadWorld(id);if(!w)throw new Error('World not found');w.id=makeId();w.name=`${w.name} Copy`;w.created=Date.now();w.updated=Date.now();w.revision=0;return saveWorld(w);}
export function exportWorld(record){const blob=new Blob([JSON.stringify({format:'kryazh-world',version:1,world:record})],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${record.name.replace(/[^a-z0-9-_]+/gi,'_')}.kryazh.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
export async function importWorld(file){const data=JSON.parse(await file.text());if(data?.format!=='kryazh-world'||!data.world)throw new Error('Not a КРЯЖ world file');data.world.id=makeId();data.world.name=`${data.world.name||'Imported World'} Imported`;data.world.revision=0;return saveWorld(data.world);}
