import { VoxelEngine, SIZE, BLOCKS } from './engine.js';
const $=id=>document.getElementById(id), E=new VoxelEngine($('world'));
const U={shell:$('gameShell'),loading:$('loadingScreen'),loadText:$('loadingText'),loadBar:$('loadingBar'),bad:$('unsupported'),title:$('titleScreen'),cont:$('continueButton'),contMeta:$('continueMeta'),newWorld:$('newWorldButton'),titleSettings:$('titleSettingsButton'),hud:$('hud'),pause:$('pauseButton'),seed:$('worldSeedLabel'),fps:$('fpsLabel'),coords:$('coordsLabel'),cross:$('crosshair'),target:$('targetLabel'),toast:$('toast'),joy:$('joystick'),knob:$('joystickKnob'),sneak:$('sneakButton'),jump:$('jumpButton'),mine:$('breakButton'),mineRing:$('breakProgress'),place:$('placeButton'),hand:$('hand'),invButton:$('inventoryButton'),hotbar:$('hotbar'),inv:$('inventoryPanel'),invClose:$('inventoryClose'),invGrid:$('inventoryGrid'),pausePanel:$('pausePanel'),pauseSeed:$('pauseSeed'),resume:$('resumeButton'),save:$('saveButton'),time:$('timeButton'),timeMeta:$('timeButtonMeta'),pauseSettings:$('pauseSettingsButton'),respawn:$('respawnButton'),exit:$('exitButton'),settings:$('settingsPanel'),settingsClose:$('settingsClose'),sens:$('sensitivitySetting'),quality:$('renderSetting'),sound:$('soundSetting'),haptic:$('hapticSetting'),left:$('leftHandSetting'),reset:$('resetWorldButton'),confirm:$('confirmPanel'),confirmYes:$('confirmDelete'),confirmNo:$('cancelDelete'),water:$('waterVignette')};
const SAVE='pocket-works:plast:world-v1', OPT='pocket-works:plast:settings-v1', TAU=Math.PI*2;
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}}, baseOpt={sensitivity:1,quality:1,sound:true,haptic:true,left:false};
let opt={...baseOpt,...read(OPT,{})}, saved=read(SAVE,null), mode='boot', spawn=[48.5,15,48.5], hot=[1,2,3,4,6,8,10],slot=0,target=null,breakOn=false,breakValue=0,breakKey='',confirmKind='',menuAngle=0,last=performance.now(),fpsTime=last,frames=0,saveDelay=-1,toastTimer=0,audio=null;
const P={pos:[48.5,15,48.5],vel:[0,0,0],yaw:.7,pitch:-.12,ground:false,water:false,crouch:false};
const input={x:0,y:0,keys:new Set(),joy:null,look:null,center:[0,0]};
function buzz(v){if(opt.haptic&&navigator.vibrate)navigator.vibrate(v)}
function tone(type='tap'){if(!opt.sound)return;let AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;if(!audio)audio=new AC();audio.resume?.();let map={tap:[420,.04,.02],step:[90,.035,.018],mine:[68,.11,.045],place:[130,.07,.04],deny:[80,.11,.03],jump:[180,.08,.03],save:[520,.09,.03]},p=map[type]||map.tap,o=audio.createOscillator(),g=audio.createGain();o.type=type==='mine'?'sawtooth':type==='jump'?'triangle':'square';o.frequency.value=p[0];g.gain.setValueAtTime(p[2],audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+p[1]);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+p[1]);}
function toast(t){U.toast.textContent=t;U.toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>U.toast.classList.remove('show'),1000)}
function applyOpt(){U.shell.classList.toggle('left-handed',opt.left);U.sens.querySelector('i').textContent=['НИЗКАЯ','СРЕДНЯЯ','ВЫСОКАЯ'][opt.sensitivity];U.quality.querySelector('i').textContent=['ЭКОНОМ','ВЫСОКОЕ','УЛЬТРА'][opt.quality];U.sound.querySelector('i').textContent=opt.sound?'ВКЛ':'ВЫКЛ';U.haptic.querySelector('i').textContent=opt.haptic?'ВКЛ':'ВЫКЛ';U.left.querySelector('i').textContent=opt.left?'ВКЛ':'ВЫКЛ';localStorage.setItem(OPT,JSON.stringify(opt));}
function icon(id){let b=BLOCKS[id];return `<i class="block-icon" style="--block-side:${b.color};--block-top:${b.top};--block-light:${b.light};--block-dark:${b.dark}"></i>`}
function buildBars(){U.hotbar.innerHTML='';hot.forEach((id,i)=>{let b=document.createElement('button');b.className='hotbar-slot'+(i===slot?' selected':'');b.innerHTML=icon(id)+`<small>${i+1}</small>`;b.onclick=()=>select(i);U.hotbar.append(b)});U.invGrid.innerHTML='';BLOCKS.filter(b=>b.id&&b.id!==5).forEach(b=>{let x=document.createElement('button');x.className='inventory-item'+(hot[slot]===b.id?' selected':'');x.innerHTML=icon(b.id)+`<span>${b.name}</span>`;x.onclick=()=>{hot[slot]=b.id;buildBars();closeInv();toast(b.name);tone();saveDelay=.2};U.invGrid.append(x)})}
function select(i){slot=(i+7)%7;buildBars();toast(BLOCKS[hot[slot]].name);tone();saveDelay=.2}
function updateContinue(){U.cont.disabled=!saved;U.contMeta.textContent=saved?`${String(saved.seed%1e6).padStart(6,'0')} · сохранённый мир`:'сохранённого мира пока нет'}
function saveWorld(show=false){if(!E.seed)return;try{saved={version:1,seed:E.seed,mods:[...E.mods],player:{pos:P.pos,yaw:P.yaw,pitch:P.pitch},hot,slot,day:stateDay,stateTime:Date.now()};localStorage.setItem(SAVE,JSON.stringify(saved));updateContinue();if(show){toast('МИР СОХРАНЁН');tone('save');buzz(18)}}catch{toast('НЕ ХВАТИЛО МЕСТА ДЛЯ СОХРАНЕНИЯ')}}
function progress(v,t){U.loading.hidden=false;U.loadBar.style.width=`${v*100}%`;U.loadText.textContent=t}
async function makeWorld(seed,mods=[]){U.title.hidden=true;U.hud.hidden=true;spawn=await E.generate(seed,mods,progress);U.loading.hidden=true;U.seed.textContent=`МИР ${String(E.seed%1e6).padStart(6,'0')}`;U.pauseSeed.textContent=`SEED ${E.seed}`;}
async function newWorld(){hidePanels();let a=new Uint32Array(1);crypto.getRandomValues(a);await makeWorld(a[0],[]);hot=[1,2,3,4,6,8,10];slot=0;P.pos=[...spawn];P.vel=[0,0,0];P.yaw=.7;P.pitch=-.12;stateDay=.18;buildBars();saveWorld();play()}
let stateDay=saved?.day??.18;
function play(){hidePanels();mode='play';U.title.hidden=true;U.hud.hidden=false;last=performance.now();tone()}
function continueWorld(){if(!saved)return;let p=saved.player||{};P.pos=Array.isArray(p.pos)&&p.pos.length===3?p.pos.map(Number):[...spawn];P.yaw=Number.isFinite(p.yaw)?p.yaw:.7;P.pitch=Number.isFinite(p.pitch)?p.pitch:-.12;P.vel=[0,0,0];hot=Array.isArray(saved.hot)&&saved.hot.length===7?saved.hot:[1,2,3,4,6,8,10];slot=Number.isInteger(saved.slot)?Math.max(0,Math.min(6,saved.slot)):0;if(collide(...P.pos))P.pos=[...spawn];buildBars();play()}
function title(){mode='menu';breakOn=false;resetBreak();hidePanels();U.hud.hidden=true;U.title.hidden=false;updateContinue()}
function pause(){if(mode!=='play')return;mode='pause';breakOn=false;resetBreak();U.pausePanel.hidden=false;document.exitPointerLock?.();saveWorld()}
function resume(){hidePanels();mode='play';U.hud.hidden=false;last=performance.now()}
function hidePanels(){U.inv.hidden=U.pausePanel.hidden=U.settings.hidden=U.confirm.hidden=true}
function openInv(){if(mode!=='play')return;mode='inv';U.inv.hidden=false;buildBars()}
function closeInv(){U.inv.hidden=true;if(mode==='inv')mode='play'}
let settingsReturn='menu';function openSettings(from=mode){settingsReturn=from;if(from==='play')mode='settings';U.settings.hidden=false;applyOpt()}
function closeSettings(){U.settings.hidden=true;if(settingsReturn==='pause'){mode='pause';U.pausePanel.hidden=false}else if(settingsReturn==='play')mode='play';else title()}
function ask(kind){confirmKind=kind;U.confirm.querySelector('h2').textContent=kind==='new'?'Создать новый мир?':'Удалить мир?';U.confirm.querySelector('p').textContent=kind==='new'?'Текущий мир будет заменён новым процедурным ландшафтом.':'Рельеф, постройки и позиция исчезнут без возможности восстановления.';U.confirmYes.textContent=kind==='new'?'СОЗДАТЬ НОВЫЙ':'УДАЛИТЬ';U.confirm.hidden=false}
async function confirm(){U.confirm.hidden=true;if(confirmKind==='new')await newWorld();else{localStorage.removeItem(SAVE);saved=null;updateContinue();title();toast('МИР УДАЛЁН')}confirmKind=''}
function solid(id){return id!==0&&id!==5}
function collide(x,y,z){let h=P.crouch?1.28:1.62,half=P.crouch?.28:.3;for(let X=Math.floor(x-half);X<=Math.floor(x+half);X++)for(let Y=Math.floor(y-h);Y<=Math.floor(y+.16);Y++)for(let Z=Math.floor(z-half);Z<=Math.floor(z+half);Z++)if(solid(E.get(X,Y,Z)))return true;return false}
function moveAxis(a,n){let steps=Math.max(1,Math.ceil(Math.abs(n)/.16)),d=n/steps;for(let i=0;i<steps;i++){let p=[...P.pos];p[a]+=d;if(!collide(...p))P.pos[a]=p[a];else{P.vel[a]=0;break}}}
let stepClock=0;function physics(dt){let k=input.keys,x=input.x+(k.has('KeyD')?1:0)-(k.has('KeyA')?1:0),y=input.y+(k.has('KeyW')?1:0)-(k.has('KeyS')?1:0),m=Math.hypot(x,y);if(m>1){x/=m;y/=m}let speed=P.crouch?1.7:m>.82||k.has('ShiftLeft')?5.1:3.55,s=Math.sin(P.yaw),c=Math.cos(P.yaw),dx=(x*c+y*s)*speed,dz=(-x*s+y*c)*speed,a=P.ground?13:P.water?5:4;P.vel[0]+=(dx-P.vel[0])*Math.min(1,a*dt);P.vel[2]+=(dz-P.vel[2])*Math.min(1,a*dt);let eye=E.get(Math.floor(P.pos[0]),Math.floor(P.pos[1]),Math.floor(P.pos[2])),body=E.get(Math.floor(P.pos[0]),Math.floor(P.pos[1]-1),Math.floor(P.pos[2]));P.water=eye===5;U.water.classList.toggle('active',P.water);if(eye===5||body===5){P.vel[1]+=(-2-P.vel[1])*Math.min(1,dt*2.2);if(k.has('Space'))P.vel[1]+=11*dt}else P.vel[1]-=21.5*dt;moveAxis(0,P.vel[0]*dt);moveAxis(2,P.vel[2]*dt);moveAxis(1,P.vel[1]*dt);P.ground=collide(P.pos[0],P.pos[1]-.07,P.pos[2]);if(P.ground&&P.vel[1]<0)P.vel[1]=0;P.pos[0]=Math.max(1.2,Math.min(SIZE.x-1.2,P.pos[0]));P.pos[2]=Math.max(1.2,Math.min(SIZE.z-1.2,P.pos[2]));if(P.pos[1]<-3)respawn();if(P.ground&&m>.1&&Math.hypot(P.vel[0],P.vel[2])>1){stepClock-=dt*Math.hypot(P.vel[0],P.vel[2]);if(stepClock<0){stepClock=1.55;tone('step')}}}
function jump(){if(mode!=='play')return;let water=E.get(Math.floor(P.pos[0]),Math.floor(P.pos[1]-1),Math.floor(P.pos[2]))===5;if(P.ground){P.vel[1]=7.3;P.ground=false;tone('jump');buzz(16)}else if(water)P.vel[1]=4.2}
function respawn(){P.pos=[...spawn];P.vel=[0,0,0];P.pitch=-.08;toast('ВОЗРОЖДЕНИЕ');saveDelay=.2}
function targetUpdate(){target=E.ray(P.pos,P.yaw,P.pitch);if(!target){U.target.hidden=true;if(breakOn)resetBreak();return}U.target.hidden=false;U.target.querySelector('b').textContent=BLOCKS[target.id].name;U.target.querySelector('span').textContent=`${target.distance.toFixed(1)} м`}
function resetBreak(){breakValue=0;breakKey='';U.mineRing.style.setProperty('--progress','0deg');U.cross.classList.remove('breaking');U.mine.classList.remove('active')}
function mining(dt){if(!breakOn||!target){if(breakValue)resetBreak();return}let k=`${target.x},${target.y},${target.z}`;if(k!==breakKey){breakKey=k;breakValue=0}breakValue+=dt/Math.max(.08,BLOCKS[target.id].hardness);U.mineRing.style.setProperty('--progress',`${Math.min(360,breakValue*360)}deg`);U.cross.classList.add('breaking');U.mine.classList.add('active');if(breakValue>=1){E.set(target.x,target.y,target.z,0);tone('mine');buzz([20,16,30]);swing('swing');target=null;resetBreak();saveDelay=.5}}
function swing(c){U.hand.classList.remove('swing','place-swing');void U.hand.offsetWidth;U.hand.classList.add(c)}
function place(){if(mode!=='play'||!target)return;let id=hot[slot],x=target.x+target.normal[0],y=target.y+target.normal[1],z=target.z+target.normal[2],old=E.get(x,y,z);if(!E.inside(x,y,z)||y<1||old&&old!==5)return deny('МЕСТО ЗАНЯТО');E.raw(x,y,z,id);if(collide(...P.pos)){E.raw(x,y,z,old);return deny('БЛОК ПЕРЕСЕКАЕТ ИГРОКА')}E.raw(x,y,z,old);E.set(x,y,z,id);tone('place');buzz(22);swing('place-swing');saveDelay=.4}
function deny(t){toast(t);tone('deny');buzz([10,15,10])}
function look(dx,dy,touch){let f=[.0016,.00225,.0032][opt.sensitivity]*(touch?1.25:1);P.yaw=(P.yaw+dx*f)%TAU;P.pitch=Math.max(-1.47,Math.min(1.47,P.pitch-dy*f))}
function bind(){addEventListener('resize',()=>E.resize([.55,.75,.95][opt.quality]));document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='play')pause();if(document.hidden)saveWorld()});addEventListener('beforeunload',()=>saveWorld());U.cont.onclick=continueWorld;U.newWorld.onclick=()=>saved?ask('new'):newWorld();U.titleSettings.onclick=()=>openSettings('menu');U.pause.onclick=pause;U.resume.onclick=resume;U.save.onclick=()=>saveWorld(true);U.time.onclick=()=>{stateDay=(stateDay+.5)%1;U.timeMeta.textContent=Math.sin(stateDay*TAU)>0?'день':'ночь';saveDelay=.2};U.pauseSettings.onclick=()=>{U.pausePanel.hidden=true;openSettings('pause')};U.respawn.onclick=()=>{respawn();resume()};U.exit.onclick=()=>{saveWorld();title()};U.invButton.onclick=openInv;U.invClose.onclick=closeInv;U.settingsClose.onclick=closeSettings;U.reset.onclick=()=>ask('delete');U.confirmYes.onclick=confirm;U.confirmNo.onclick=()=>{U.confirm.hidden=true;confirmKind=''};
U.sens.onclick=()=>{opt.sensitivity=(opt.sensitivity+1)%3;applyOpt();tone()};U.quality.onclick=()=>{opt.quality=(opt.quality+1)%3;applyOpt();tone()};U.sound.onclick=()=>{opt.sound=!opt.sound;applyOpt();if(opt.sound)tone()};U.haptic.onclick=()=>{opt.haptic=!opt.haptic;applyOpt();buzz(18)};U.left.onclick=()=>{opt.left=!opt.left;applyOpt();buzz(18)};U.jump.onpointerdown=e=>{e.preventDefault();jump()};U.place.onpointerdown=e=>{e.preventDefault();place()};U.mine.onpointerdown=e=>{e.preventDefault();breakOn=true;U.mine.setPointerCapture?.(e.pointerId)};let stop=()=>{breakOn=false;resetBreak()};U.mine.onpointerup=U.mine.onpointercancel=U.mine.onlostpointercapture=stop;U.sneak.onclick=()=>{P.crouch=!P.crouch;U.sneak.classList.toggle('active',P.crouch);buzz(12)};
U.joy.onpointerdown=e=>{if(mode!=='play')return;let r=U.joy.getBoundingClientRect();input.joy=e.pointerId;input.center=[r.left+r.width/2,r.top+r.height/2];U.joy.setPointerCapture(e.pointerId);joy(e)};U.joy.onpointermove=e=>{if(e.pointerId===input.joy)joy(e)};U.joy.onpointerup=U.joy.onpointercancel=e=>{if(e.pointerId!==input.joy)return;input.joy=null;input.x=input.y=0;U.knob.style.transform='translate(0,0)'};
E.canvas.onpointerdown=e=>{if(mode!=='play'||e.pointerType==='mouse'||e.clientX<innerWidth*.28)return;input.look={id:e.pointerId,x:e.clientX,y:e.clientY};E.canvas.setPointerCapture(e.pointerId)};E.canvas.onpointermove=e=>{if(!input.look||e.pointerId!==input.look.id)return;look(e.clientX-input.look.x,e.clientY-input.look.y,true);input.look.x=e.clientX;input.look.y=e.clientY};E.canvas.onpointerup=E.canvas.onpointercancel=e=>{if(input.look?.id===e.pointerId)input.look=null};E.canvas.onclick=e=>{if(mode==='play'&&e.pointerType!=='touch')E.canvas.requestPointerLock?.()};document.onmousemove=e=>{if(document.pointerLockElement===E.canvas&&mode==='play')look(e.movementX,e.movementY,false)};document.onmousedown=e=>{if(document.pointerLockElement!==E.canvas||mode!=='play')return;if(e.button===0)breakOn=true;if(e.button===2)place()};document.onmouseup=e=>{if(e.button===0){breakOn=false;resetBreak()}};document.oncontextmenu=e=>e.preventDefault();E.canvas.onwheel=e=>{if(mode==='play'){e.preventDefault();select(slot+Math.sign(e.deltaY))}};
document.onkeydown=e=>{input.keys.add(e.code);if(e.code==='Space'){e.preventDefault();jump()}if(e.code==='KeyE'){e.preventDefault();mode==='play'?openInv():closeInv()}if(e.code==='Escape'){if(mode==='play')pause();else if(mode==='pause')resume();else if(mode==='inv')closeInv();else if(mode==='settings')closeSettings()}if(/^Digit[1-7]$/.test(e.code))select(+e.code.at(-1)-1)};document.onkeyup=e=>input.keys.delete(e.code)}
function joy(e){let dx=e.clientX-input.center[0],dy=e.clientY-input.center[1],m=Math.hypot(dx,dy),r=38;if(m>r){dx=dx/m*r;dy=dy/m*r}input.x=dx/r;input.y=-dy/r;U.knob.style.transform=`translate(${dx}px,${dy}px)`}
function loop(now){let dt=Math.min(.05,Math.max(0,(now-last)/1000));last=now;if(mode==='play'){physics(dt);targetUpdate();mining(dt);stateDay=(stateDay+dt/780)%1;U.coords.textContent=`${Math.floor(P.pos[0])} · ${Math.floor(P.pos[1]-1.6)} · ${Math.floor(P.pos[2])}`;frames++;if(now-fpsTime>700){U.fps.textContent=`${Math.round(frames*1000/(now-fpsTime))} FPS`;frames=0;fpsTime=now}saveDelay-=dt;if(saveDelay<=0&&saveDelay>-10){saveDelay=-999;saveWorld()}}let cam=P.pos,yaw=P.yaw,pitch=P.pitch;if(mode==='menu'||mode==='boot'){menuAngle+=dt*.09;cam=[spawn[0]+Math.sin(menuAngle)*18,Math.min(SIZE.y-2,spawn[1]+8),spawn[2]+Math.cos(menuAngle)*18];let dx=spawn[0]-cam[0],dy=spawn[1]+1.5-cam[1],dz=spawn[2]-cam[2];yaw=Math.atan2(dx,dz);pitch=Math.atan2(dy,Math.hypot(dx,dz))}E.render(cam,yaw,pitch,target,breakValue,stateDay,P.water,now/1000,[.55,.75,.95][opt.quality]);requestAnimationFrame(loop)}
async function boot(){applyOpt();buildBars();bind();try{if(!E.init()){U.loading.hidden=true;U.bad.hidden=false;return}await makeWorld(saved?.seed??(crypto.getRandomValues(new Uint32Array(1))[0]),saved?.mods||[]);updateContinue();title();last=performance.now();requestAnimationFrame(loop)}catch(e){console.error(e);U.loading.hidden=true;U.bad.hidden=false;U.bad.querySelector('p').textContent=`ПЛАСТ не запустился: ${e.message}`}}
boot();
