import { installMobileRuntime } from '../../shared/mobile-runtime.js';
import { createVersionedStore } from '../../shared/capabilities/storage.js';
import { createWorkshopMode } from '../../shared/workshop-mode.js';
import { watchConnectivity } from '../../shared/pwa-utils.js';
import { AXES, BILLS, FACTIONS, createCampaign, describeEnding, evaluateBill, getCurrentDossier, isCampaignOver, resolveVote, scoreCampaign, toggleClause, validateCampaign } from './logic.js';

installMobileRuntime();
const NS='pocket-works:quorum';
const store=createVersionedStore({namespace:NS,version:1,defaults:{campaign:null,sound:true,bestScore:0,completedRuns:0,runArchive:[]},validate:v=>Boolean(v&&typeof v==='object'&&!Array.isArray(v))});
const $=id=>document.querySelector(`#${id}`);
const el={start:$('start-screen'),game:$('game-screen'),end:$('end-screen'),startNew:$('start-new'),resume:$('continue-campaign'),restart:$('restart-campaign'),rulesOpen:$('rules-open'),archiveOpen:$('archive-open'),gameArchive:$('game-archive-open'),endArchive:$('end-archive-open'),sound:$('sound-toggle'),rules:$('rules-dialog'),archive:$('archive-dialog'),result:$('result-dialog'),round:$('round-value'),legitimacy:$('legitimacy-value'),legitimacyBar:$('legitimacy-bar'),stability:$('stability-value'),stabilityBar:$('stability-bar'),votes:$('vote-value'),majority:$('majority-status'),needed:$('votes-needed'),needle:$('majority-needle'),seats:$('seat-layer'),legend:$('faction-legend'),billCode:$('bill-code'),billTitle:$('bill-title'),billSummary:$('bill-summary'),billCore:$('bill-core'),zone:$('amendment-zone'),dock:$('drag-dock'),attached:$('attached-list'),slot:$('slot-count'),integrity:$('integrity-value'),integrityBar:$('integrity-bar'),tension:$('tension-value'),tensionBar:$('tension-bar'),tray:$('clause-tray'),forecast:$('forecast-delta'),ratify:$('ratify-button'),ratifyVotes:$('ratify-votes'),resultSeal:$('result-seal'),resultCode:$('result-code'),resultTitle:$('result-title'),resultCopy:$('result-copy'),resultVotes:$('result-votes'),resultIntegrity:$('result-integrity'),resultLegitimacy:$('result-legitimacy'),resultStability:$('result-stability'),resultFactions:$('result-factions'),next:$('next-session'),archiveSummary:$('archive-summary'),archiveList:$('archive-list'),endGrade:$('end-grade'),endTitle:$('end-title'),endCopy:$('end-copy'),endScore:$('end-score'),endPassed:$('end-passed'),endLegitimacy:$('end-legitimacy'),endStability:$('end-stability'),endBest:$('end-best'),toast:$('toast')};
let view='start',audio=null,toastTimer=0,restartUntil=0,lastVote=null;
const seatNodes=[];
const campaign=()=>{const value=store.get('campaign');return validateCampaign(value)?value:null};
const save=value=>store.set('campaign',value);
const delta=value=>value>0?`+${value}`:String(value);

function show(name){view=name;[['start',el.start],['game',el.game],['end',el.end]].forEach(([key,node])=>{node.hidden=key!==name;node.classList.toggle('is-active',key===name)});window.scrollTo({top:0,behavior:'auto'})}
function toast(text){clearTimeout(toastTimer);el.toast.textContent=text;el.toast.classList.add('is-visible');toastTimer=setTimeout(()=>el.toast.classList.remove('is-visible'),2200)}
function vibrate(pattern=8){try{navigator.vibrate?.(pattern)}catch{}}
function context(){if(!store.get('sound',true))return null;const C=window.AudioContext||window.webkitAudioContext;if(!C)return null;if(!audio)audio=new C();if(audio.state==='suspended')audio.resume().catch(()=>{});return audio}
function sound(kind='tick'){const c=context();if(!c)return;const p={tick:[340,.035,'triangle',.035],paper:[210,.06,'sine',.045],vote:[145,.09,'square',.04],pass:[420,.18,'triangle',.055],fail:[110,.2,'sawtooth',.045]}[kind]||[300,.05,'sine',.035],now=c.currentTime,o=c.createOscillator(),g=c.createGain();o.type=p[2];o.frequency.setValueAtTime(p[0],now);if(kind==='pass')o.frequency.exponentialRampToValueAtTime(680,now+p[1]);if(kind==='fail')o.frequency.exponentialRampToValueAtTime(72,now+p[1]);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(p[3],now+.012);g.gain.exponentialRampToValueAtTime(.0001,now+p[1]);o.connect(g).connect(c.destination);o.start(now);o.stop(now+p[1]+.02)}
function renderSound(){const on=store.get('sound',true);el.sound.setAttribute('aria-pressed',String(on));el.sound.title=on?'Выключить звук':'Включить звук'}

function seatLayout(){const out=[];[{count:12,radius:68},{count:14,radius:88},{count:16,radius:108},{count:18,radius:128}].forEach((row,rowIndex)=>{for(let i=0;i<row.count;i++){const ratio=i/(row.count-1),angle=(200+ratio*140)*Math.PI/180;out.push({x:180+Math.cos(angle)*row.radius,y:190+Math.sin(angle)*row.radius,row:rowIndex})}});return out.sort((a,b)=>a.x-b.x||a.row-b.row)}
function buildChamber(){const layout=seatLayout(),factions=FACTIONS.flatMap(f=>Array.from({length:f.seats},()=>f));layout.forEach((pos,index)=>{const f=factions[index],circle=document.createElementNS('http://www.w3.org/2000/svg','circle');circle.setAttribute('cx',pos.x);circle.setAttribute('cy',pos.y);circle.setAttribute('r',pos.row<2?5.6:5.1);circle.setAttribute('class','seat is-no');circle.style.fill=f.color;circle.style.stroke=f.color;circle.dataset.faction=f.id;circle.dataset.index=index;el.seats.append(circle);seatNodes.push(circle)})}
function renderChamber(result){let cursor=0;result.factions.forEach(f=>{for(let i=0;i<f.seats;i++){const seat=seatNodes[cursor++],yes=i<f.yes;seat.classList.toggle('is-yes',yes);seat.classList.toggle('is-no',!yes)}});const angle=-58+Math.min(1,result.votes/60)*116;el.needle.style.transform=`rotate(${angle}deg)`;el.legend.innerHTML=result.factions.map(f=>`<div class="faction-item" style="--faction-color:${f.color}"><strong>${f.short}</strong><span>${f.yes} / ${f.seats}</span></div>`).join('')}
function renderCore(bill){el.billCore.innerHTML=AXES.map(axis=>({...axis,value:bill.core[axis.id]||0})).filter(a=>Math.abs(a.value)>=.22).sort((a,b)=>Math.abs(b.value)-Math.abs(a.value)).map(a=>`<span class="axis-mark ${a.value<0?'is-negative':''}"><b>${a.glyph}</b> ${a.label} <i>${a.value>0?'↑':'↓'}${Math.round(Math.abs(a.value)*10)}</i></span>`).join('')}
function short(ids){return ids.map(id=>FACTIONS.find(f=>f.id===id)?.short).filter(Boolean).join(' · ')}
function renderAttached(result){el.slot.textContent=`${result.selected.length} / 3`;el.attached.innerHTML=result.selected.length?result.selected.map(c=>`<div class="attached-clause"><i></i><strong>${c.title}</strong><button type="button" data-remove-clause="${c.id}" aria-label="Снять поправку ${c.title}" data-native-press>×</button></div>`).join(''):'<p class="empty-amendments" id="empty-amendments">Перетащи сюда поправку или нажми на неё</p>';el.attached.querySelectorAll('[data-remove-clause]').forEach(button=>button.addEventListener('click',()=>changeClause(button.dataset.removeClause)))}

function bindCard(card,id){let pointer=null,startX=0,startY=0,dragging=false;const clear=()=>{card.classList.remove('is-dragging');card.style.removeProperty('--drag-x');card.style.removeProperty('--drag-y');el.zone.classList.remove('is-target');el.dock.classList.remove('is-active');el.dock.hidden=true;pointer=null;dragging=false};card.addEventListener('click',()=>{if(card.dataset.suppressClick!=='true')changeClause(id)});card.addEventListener('pointerdown',event=>{if(event.button!==0&&event.pointerType!=='touch')return;pointer=event.pointerId;startX=event.clientX;startY=event.clientY;card.setPointerCapture(pointer)});card.addEventListener('pointermove',event=>{if(event.pointerId!==pointer)return;const dx=event.clientX-startX,dy=event.clientY-startY;if(!dragging&&Math.hypot(dx,dy)>9){dragging=true;card.classList.add('is-dragging');el.zone.classList.add('is-target');el.dock.hidden=false;el.dock.classList.add('is-active');sound('paper')}if(dragging){card.style.setProperty('--drag-x',`${dx}px`);card.style.setProperty('--drag-y',`${dy}px`)}});const finish=event=>{if(event.pointerId!==pointer)return;if(dragging){const inside=rect=>event.clientX>=rect.left&&event.clientX<=rect.right&&event.clientY>=rect.top&&event.clientY<=rect.bottom,accepted=inside(el.zone.getBoundingClientRect())||inside(el.dock.getBoundingClientRect());card.dataset.suppressClick='true';accepted?addClause(id):toast('Поправка вернулась в комитет');setTimeout(()=>card.dataset.suppressClick='false',0)}if(card.hasPointerCapture(pointer))card.releasePointerCapture(pointer);clear()};card.addEventListener('pointerup',finish);card.addEventListener('pointercancel',finish);card.addEventListener('lostpointercapture',clear)}
function renderClauses(result){const selected=new Set(result.selected.map(c=>c.id));el.tray.innerHTML=result.dossier.clauses.map((c,index)=>`<button class="clause-card ${selected.has(c.id)?'is-selected':''}" type="button" data-clause-id="${c.id}" data-index="0${index+1}" aria-pressed="${selected.has(c.id)}" data-gesture-surface><h3>${c.title}</h3><p>${c.note}</p><div class="clause-meta"><span class="clause-cost">−${c.cost}% смысла</span><span class="clause-allies">За: ${short(c.appeals)||'без любимчиков'}</span></div></button>`).join('');el.tray.querySelectorAll('.clause-card').forEach(card=>bindCard(card,card.dataset.clauseId))}
function renderGame(c){const dossier=getCurrentDossier(c),result=evaluateBill(c);if(!dossier||!result){renderEnd(c);return}el.round.textContent=`${c.round+1} / ${c.dossiers.length}`;el.legitimacy.textContent=c.legitimacy;el.legitimacyBar.style.width=`${c.legitimacy}%`;el.stability.textContent=c.stability;el.stabilityBar.style.width=`${c.stability}%`;el.votes.textContent=result.votes;el.needed.textContent=Math.max(0,31-result.votes);el.majority.dataset.state=result.passed?'yes':'no';el.majority.querySelector('strong').textContent=result.passed?'Большинство собрано':'Нет большинства';el.majority.querySelector('small').innerHTML=result.passed?`запас <b>${result.votes-30}</b>`:`нужно ещё <b>${31-result.votes}</b>`;el.billCode.textContent=dossier.bill.code;el.billTitle.textContent=dossier.bill.title;el.billSummary.textContent=dossier.bill.summary;renderCore(dossier.bill);renderAttached(result);el.integrity.textContent=`${result.integrity}%`;el.integrityBar.style.width=`${result.integrity}%`;el.tension.textContent=result.tension<35?'низкое':result.tension<62?'среднее':'высокое';el.tensionBar.style.width=`${result.tension}%`;el.forecast.textContent=`Мандат ${delta(result.legitimacyDelta)} · Устойчивость ${delta(result.stabilityDelta)}`;el.ratifyVotes.textContent=`${result.votes} голосов`;renderChamber(result);renderClauses(result)}
function updateStart(c){const active=c&&!isCampaignOver(c);el.resume.hidden=!active;el.startNew.querySelector('span').textContent=active?'Начать новую республику':'Открыть первую сессию'}
function renderEnd(c){if(!c)return;const ending=describeEnding(c);el.endGrade.textContent=ending.grade;el.endTitle.textContent=ending.title;el.endCopy.textContent=ending.text;el.endScore.textContent=ending.score.toLocaleString('ru-RU');el.endPassed.textContent=`${c.passed} / ${c.dossiers.length}`;el.endLegitimacy.textContent=c.legitimacy;el.endStability.textContent=c.stability;el.endBest.textContent=Math.max(store.get('bestScore',0),ending.score).toLocaleString('ru-RU');show('end')}
function render(){const c=campaign();updateStart(c);renderSound();if(view==='game'){if(!c)show('start');else if(isCampaignOver(c))renderEnd(c);else{show('game');renderGame(c)}}else if(view==='end'){c&&isCampaignOver(c)?renderEnd(c):show('start')}else show('start')}

function archiveRun(c){if(!c||!isCampaignOver(c))return;const existing=store.get('runArchive',[]);if(existing.some(run=>run.seed===c.seed))return;const ending=describeEnding(c);store.patch({bestScore:Math.max(store.get('bestScore',0),ending.score),completedRuns:store.get('completedRuns',0)+1,runArchive:[{seed:c.seed,score:ending.score,grade:ending.grade,passed:c.passed,legitimacy:c.legitimacy,stability:c.stability,finishedAt:c.finishedAt},...existing].slice(0,8)})}
function start(force=false){const current=campaign(),active=current&&!isCampaignOver(current),now=Date.now();if(active&&!force&&now>restartUntil){restartUntil=now+3500;el.startNew.querySelector('span').textContent='Подтвердить новую республику';toast('Текущая кампания будет стёрта. Нажми ещё раз для подтверждения.');return}restartUntil=0;save(createCampaign(Date.now()));view='game';sound('paper');vibrate(10);render()}
function addClause(id){const c=campaign();if(!c)return;if(c.selectedClauseIds.includes(id)){toast('Эта поправка уже в тексте');return}if(c.selectedClauseIds.length>=3){toast('В тексте уже три поправки. Политический Франкенштейн и так дышит.');vibrate([8,35,8]);return}save(toggleClause(c,id));sound('paper');vibrate(7);renderGame(campaign())}
function changeClause(id){const c=campaign();if(!c)return;const selected=c.selectedClauseIds.includes(id);if(!selected&&c.selectedClauseIds.length>=3){toast('Лимит — три поправки. Иначе от закона останется только номер.');vibrate([8,35,8]);return}save(toggleClause(c,id));sound(selected?'tick':'paper');vibrate(6);renderGame(campaign())}
function populateResult(result,next){el.resultSeal.textContent=result.passed?'ПРИНЯТО':'ОТКЛОНЕНО';el.resultSeal.classList.toggle('is-failed',!result.passed);el.resultCode.textContent=`${result.dossier.bill.code} · ИТОГ`;el.resultTitle.textContent=result.passed?'Закон прошёл палату':'Большинство не собралось';el.resultCopy.textContent=!result.passed?`До кворума не хватило ${31-result.votes} голосов. Оппозиция уже печатает плакаты.`:result.integrity<50?'Формально закон принят. Неформально из исходной идеи вынули почти всё, кроме скрепки и номера проекта.':result.votes>=40?'Широкая коалиция сработала: закон узнаваем, запас голосов приличный.':'Тонкое большинство удержалось. Несколько кресел уже делают вид, что голосовали случайно.';el.resultVotes.textContent=result.votes;el.resultIntegrity.textContent=`${result.integrity}%`;el.resultLegitimacy.textContent=delta(result.legitimacyDelta);el.resultStability.textContent=delta(result.stabilityDelta);el.resultFactions.innerHTML=result.factions.map(f=>`<div class="result-faction" style="--faction-color:${f.color}"><i></i><span>${f.name}</span><strong>${f.yes} / ${f.seats}</strong></div>`).join('');el.next.textContent=isCampaignOver(next)?'Итоги кампании':'Следующая сессия'}
function ratify(){const c=campaign();if(!c||isCampaignOver(c))return;const result=evaluateBill(c);lastVote=result;sound('vote');vibrate([12,45,12]);const next=resolveVote(c);save(next);if(isCampaignOver(next))archiveRun(next);populateResult(result,next);setTimeout(()=>{sound(result.passed?'pass':'fail');vibrate(result.passed?[16,40,22]:[30,60,30])},170);if(!el.result.open)el.result.showModal()}
function continueResult(){if(el.result.open)el.result.close();const c=campaign();if(c&&isCampaignOver(c)){view='end';renderEnd(c)}else{view='game';render()}}
function renderArchive(){const c=campaign(),history=c?.history||[];el.archiveSummary.innerHTML=`<div><span>Сессий</span><strong>${history.length}</strong></div><div><span>Принято</span><strong>${history.filter(x=>x.passed).length}</strong></div><div><span>Лучший счёт</span><strong>${store.get('bestScore',0).toLocaleString('ru-RU')}</strong></div>`;el.archiveList.innerHTML=history.length?history.map((entry,index)=>{const bill=BILLS.find(b=>b.id===entry.billId);return `<article class="archive-entry"><span class="entry-number">${String(index+1).padStart(2,'0')}</span><div><h3>${bill?.title||entry.billId}</h3><p>${entry.selectedClauseIds.length} поправки · целостность ${entry.integrity}% · напряжение ${entry.tension}</p></div><div class="entry-result"><strong>${entry.votes} / 60</strong><span>${entry.passed?'принято':'отклонено'}</span></div></article>`}).join(''):'<p class="archive-empty">Пока здесь только чистая бумага. Проведи первое голосование.</p>'}
function openArchive(){renderArchive();if(!el.archive.open)el.archive.showModal()}

buildChamber();render();
el.startNew.addEventListener('click',()=>start(false));el.restart.addEventListener('click',()=>start(true));el.resume.addEventListener('click',()=>{view='game';sound('paper');render()});el.ratify.addEventListener('click',ratify);el.next.addEventListener('click',continueResult);el.rulesOpen.addEventListener('click',()=>el.rules.showModal());[el.archiveOpen,el.gameArchive,el.endArchive].forEach(button=>button.addEventListener('click',openArchive));el.sound.addEventListener('click',()=>{const next=!store.get('sound',true);store.set('sound',next);renderSound();if(next)sound('tick')});document.querySelectorAll('[data-dialog-close]').forEach(button=>button.addEventListener('click',()=>{const dialog=button.closest('dialog');if(dialog.open)dialog.close()}));document.querySelectorAll('dialog').forEach(dialog=>dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close()}));el.result.addEventListener('close',()=>{if(!lastVote)return;lastVote=null;const c=campaign();if(c&&isCampaignOver(c)){view='end';renderEnd(c)}else if(view==='game')render()});window.addEventListener('appdatareset',()=>{view='start';restartUntil=0;lastVote=null;render();toast('Данные КВОРУМА очищены')});window.addEventListener('pagehide',()=>{const c=campaign();if(c)save(c)});document.addEventListener('visibilitychange',()=>{if(document.hidden&&audio?.state==='running')audio.suspend().catch(()=>{})});
createWorkshopMode({appName:'КВОРУМ',version:'1.0.0',cachePrefix:'quorum-',storageNamespace:NS,onReset(){store.reset();window.dispatchEvent(new CustomEvent('appdatareset'))}});
watchConnectivity(online=>{document.documentElement.dataset.network=online?'online':'offline'});
