export type EnemyKind='crawler'|'runner'|'brute'|'boss';
export type ModuleKind='gun'|'saw'|'shield'|'mortar'|'magnet'|'engine';
export type Phase='menu'|'running'|'levelup'|'paused'|'won'|'lost';
export interface InputState{moveX:number;moveZ:number;rigTarget:number}
export interface ModuleState{kind:ModuleKind;level:number;slot:number;cooldown:number}
export interface EnemyState{id:number;kind:EnemyKind;x:number;z:number;vx:number;vz:number;hp:number;maxHp:number;radius:number;mass:number;speed:number;damage:number;attackCooldown:number}
export interface ProjectileState{kind:'bullet'|'mortar';x:number;z:number;vx:number;vz:number;ttl:number;damage:number;radius:number;slot:number;targetX?:number;targetZ?:number}
export interface PickupState{x:number;z:number;vx:number;vz:number;value:number}
export type GameEvent={type:'shot';x:number;z:number;slot:number;weapon:'gun'|'mortar'}|{type:'hit';x:number;z:number;strength:number}|{type:'saw';x:number;z:number;slot:number}|{type:'shield';x:number;z:number;slot:number}|{type:'death';x:number;z:number;kind:EnemyKind}|{type:'hurt';amount:number}|{type:'blast';x:number;z:number;radius:number}|{type:'level'}|{type:'boss'}|{type:'victory'}|{type:'defeat'};
export interface GameState{version:1;phase:Phase;time:number;playerX:number;playerZ:number;playerVX:number;playerVZ:number;hp:number;maxHp:number;xp:number;nextXp:number;level:number;kills:number;rigRotation:number;modules:ModuleState[];enemies:EnemyState[];projectiles:ProjectileState[];pickups:PickupState[];spawnTimer:number;bossSpawned:boolean;pendingUpgrades:number;nextEnemyId:number;rng:number;events:GameEvent[]}
export interface UpgradeChoice{id:string;title:string;detail:string;kind:ModuleKind|'repair'|'chassis'}
export const RUN_DURATION=300,BOSS_TIME=240,ARENA_RADIUS=27,MAX_ENEMIES=170;
const TAU=Math.PI*2,SLOT=TAU/6,CELL=3.25;
const grid=new Map<number,number[]>();
const weights:Record<ModuleKind,number>={gun:1,saw:1.6,shield:2.2,mortar:2.6,magnet:1.8,engine:1.3};
const slots:Record<ModuleKind,number>={gun:0,mortar:1,shield:2,magnet:3,saw:4,engine:5};
const labels:Record<ModuleKind,string>={gun:'Пулемёт',saw:'Цепная пила',shield:'Тяжёлый щит',mortar:'Миномёт',magnet:'Электромагнит',engine:'Привод рига'};
function rnd(s:GameState){s.rng=(Math.imul(s.rng,1664525)+1013904223)>>>0;return s.rng/4294967296}
function wrap(a:number){a%=TAU;if(a>Math.PI)a-=TAU;if(a<-Math.PI)a+=TAU;return a}
function nearAngle(a:number,b:number){return Math.abs(wrap(a-b))}
function clamp2(x:number,z:number,max=1):[number,number]{const n=Math.hypot(x,z);return n>max?[x/n*max,z/n*max]:[x,z]}
function moduleAt(s:GameState,k:ModuleKind){return s.modules.find(m=>m.kind===k)}
function point(s:GameState,m:ModuleState,r=2){const a=s.rigRotation+m.slot*SLOT;return{x:s.playerX+Math.cos(a)*r,z:s.playerZ+Math.sin(a)*r,a}}
function spec(k:EnemyKind,t:number){const q=1+Math.min(1.05,t/420);if(k==='runner')return{hp:18*q,radius:.42,mass:.65,speed:3.55,damage:4.5};if(k==='brute')return{hp:78*q,radius:.8,mass:2.8,speed:1.35,damage:9};if(k==='boss')return{hp:1150,radius:1.65,mass:9,speed:1.05,damage:15};return{hp:31*q,radius:.55,mass:1,speed:2.05,damage:5.5}}
export function createGame(seed=0x51a7e):GameState{return{version:1,phase:'menu',time:0,playerX:0,playerZ:0,playerVX:0,playerVZ:0,hp:100,maxHp:100,xp:0,nextXp:9,level:1,kills:0,rigRotation:0,modules:[{kind:'gun',level:1,slot:0,cooldown:.05},{kind:'shield',level:1,slot:2,cooldown:0},{kind:'saw',level:1,slot:4,cooldown:0}],enemies:[],projectiles:[],pickups:[],spawnTimer:.6,bossSpawned:false,pendingUpgrades:0,nextEnemyId:1,rng:seed>>>0||1,events:[]}}
export function startGame(s:GameState){if(s.phase==='menu'||s.phase==='paused')s.phase='running'}
function spawn(s:GameState,forced?:EnemyKind){if(s.enemies.length>=MAX_ENEMIES)return;let kind=forced;if(!kind){const p=Math.min(1,s.time/RUN_DURATION),r=rnd(s),brute=Math.max(0,(s.time-55)/720),runner=.06+p*.24;kind=r<brute?'brute':r<brute+runner?'runner':'crawler'}const v=spec(kind,s.time),a=rnd(s)*TAU,d=21+rnd(s)*5;s.enemies.push({id:s.nextEnemyId++,kind,x:s.playerX+Math.cos(a)*d,z:s.playerZ+Math.sin(a)*d,vx:0,vz:0,hp:v.hp,maxHp:v.hp,radius:v.radius,mass:v.mass,speed:v.speed,damage:v.damage,attackCooldown:.45+rnd(s)*.55})}
function nearest(s:GameState,x:number,z:number,range:number,angle?:number):EnemyState|null{let best:EnemyState|null=null,b2=range*range;for(const e of s.enemies){const dx=e.x-x,dz=e.z-z,d2=dx*dx+dz*dz;if(d2>=b2)continue;if(angle!==undefined&&nearAngle(Math.atan2(dz,dx),angle)>1.25)continue;b2=d2;best=e}return best??(angle===undefined?null:nearest(s,x,z,range))}
function damage(e:EnemyState,d:number,ix=0,iz=0){e.hp-=d;e.vx+=ix/Math.max(.55,e.mass);e.vz+=iz/Math.max(.55,e.mass)}
function updateModules(s:GameState,dt:number){for(const m of s.modules){m.cooldown=Math.max(0,m.cooldown-dt);const p=point(s,m);
if(m.kind==='gun'&&m.cooldown<=0){const e=nearest(s,p.x,p.z,10.2+m.level*.7,p.a);if(e){const dx=e.x-p.x,dz=e.z-p.z,n=Math.hypot(dx,dz)||1,sp=16;s.projectiles.push({kind:'bullet',x:p.x,z:p.z,vx:dx/n*sp,vz:dz/n*sp,ttl:.82,damage:9+m.level*3.2,radius:.16,slot:m.slot});m.cooldown=Math.max(.11,.3-(m.level-1)*.035);s.events.push({type:'shot',x:p.x,z:p.z,slot:m.slot,weapon:'gun'})}}
else if(m.kind==='saw'){let touch=false;for(const e of s.enemies){const dx=e.x-p.x,dz=e.z-p.z,n=Math.hypot(dx,dz);if(n<e.radius+.95+m.level*.08){damage(e,(23+m.level*7)*dt,dx/(n||1)*10*dt,dz/(n||1)*10*dt);touch=true}}if(touch&&m.cooldown<=0){m.cooldown=.11;s.events.push({type:'saw',x:p.x,z:p.z,slot:m.slot})}}
else if(m.kind==='shield'){let touch=false;for(const e of s.enemies){const dx=e.x-p.x,dz=e.z-p.z,n=Math.hypot(dx,dz);if(n<e.radius+1.05+m.level*.05){e.vx+=dx/(n||1)*(8+m.level)/e.mass;e.vz+=dz/(n||1)*(8+m.level)/e.mass;touch=true}}if(touch&&m.cooldown<=0){m.cooldown=.16;s.events.push({type:'shield',x:p.x,z:p.z,slot:m.slot})}}
else if(m.kind==='magnet'){const r=5+m.level*.7;for(const e of s.enemies){const dx=p.x-e.x,dz=p.z-e.z,n=Math.hypot(dx,dz);if(n>.5&&n<r){const f=(1-n/r)*(3.8+m.level)*dt/e.mass;e.vx+=dx/n*f;e.vz+=dz/n*f}}}
else if(m.kind==='mortar'&&m.cooldown<=0){const e=nearest(s,p.x,p.z,13);if(e){const flight=.78;s.projectiles.push({kind:'mortar',x:p.x,z:p.z,vx:(e.x-p.x)/flight,vz:(e.z-p.z)/flight,ttl:flight,damage:30+m.level*10,radius:2.25+m.level*.2,slot:m.slot,targetX:e.x,targetZ:e.z});m.cooldown=Math.max(.72,1.85-(m.level-1)*.16);s.events.push({type:'shot',x:p.x,z:p.z,slot:m.slot,weapon:'mortar'})}}}}
function projectiles(s:GameState,dt:number){for(let i=s.projectiles.length-1;i>=0;i--){const p=s.projectiles[i];p.x+=p.vx*dt;p.z+=p.vz*dt;p.ttl-=dt;if(p.kind==='mortar'&&p.ttl<=0){const x=p.targetX??p.x,z=p.targetZ??p.z;for(const e of s.enemies){const dx=e.x-x,dz=e.z-z,n=Math.hypot(dx,dz);if(n<p.radius+e.radius){const f=1-Math.min(1,n/p.radius);damage(e,p.damage*(.45+f*.55),dx/(n||1)*8*f,dz/(n||1)*8*f)}}s.events.push({type:'blast',x,z,radius:p.radius});s.projectiles.splice(i,1);continue}if(p.kind==='bullet'){let hit=false;for(const e of s.enemies){const dx=e.x-p.x,dz=e.z-p.z;if(dx*dx+dz*dz<(e.radius+p.radius)**2){const n=Math.hypot(p.vx,p.vz)||1;damage(e,p.damage,p.vx/n*3,p.vz/n*3);s.events.push({type:'hit',x:p.x,z:p.z,strength:1});hit=true;break}}if(hit||p.ttl<=0)s.projectiles.splice(i,1)}else if(p.ttl<=0)s.projectiles.splice(i,1)}}
function rebuild(s:GameState){grid.clear();for(let i=0;i<s.enemies.length;i++){const e=s.enemies[i],x=Math.floor(e.x/CELL)+64,z=Math.floor(e.z/CELL)+64,k=x*256+z;const b=grid.get(k);if(b)b.push(i);else grid.set(k,[i])}}
function shieldFactor(s:GameState,e:EnemyState){const a=Math.atan2(e.z-s.playerZ,e.x-s.playerX);let f=1;for(const m of s.modules)if(m.kind==='shield'&&nearAngle(a,s.rigRotation+m.slot*SLOT)<.72)f=Math.min(f,.26-Math.min(.09,(m.level-1)*.022));return f}
function enemies(s:GameState,dt:number){rebuild(s);for(let i=0;i<s.enemies.length;i++){const e=s.enemies[i];e.attackCooldown-=dt;const tx=s.playerX-e.x,tz=s.playerZ-e.z,n=Math.hypot(tx,tz)||1,gx=Math.floor(e.x/CELL)+64,gz=Math.floor(e.z/CELL)+64;let sx=0,sz=0;for(let ox=-1;ox<=1;ox++)for(let oz=-1;oz<=1;oz++){const b=grid.get((gx+ox)*256+gz+oz);if(!b)continue;for(const j of b){if(j===i)continue;const o=s.enemies[j],dx=e.x-o.x,dz=e.z-o.z,d2=dx*dx+dz*dz,w=e.radius+o.radius+.08;if(d2>.001&&d2<w*w){const d=Math.sqrt(d2),f=(w-d)/w;sx+=dx/d*f;sz+=dz/d*f}}}const response=e.kind==='runner'?8:e.kind==='boss'?2.1:4.5;e.vx+=(tx/n*e.speed-e.vx)*Math.min(1,response*dt);e.vz+=(tz/n*e.speed-e.vz)*Math.min(1,response*dt);e.vx+=sx*5*dt/e.mass;e.vz+=sz*5*dt/e.mass;e.x+=e.vx*dt;e.z+=e.vz*dt;const contact=e.radius+.66;if(n<contact){const nx=tx/n,nz=tz/n;e.x-=nx*(contact-n)*.6;e.z-=nz*(contact-n)*.6;if(e.attackCooldown<=0){const hit=e.damage*shieldFactor(s,e);s.hp-=hit;s.events.push({type:'hurt',amount:hit});e.attackCooldown=e.kind==='boss'?.85:1.05;e.vx-=nx*3/e.mass;e.vz-=nz*3/e.mass}}}}
function deaths(s:GameState){for(let i=s.enemies.length-1;i>=0;i--){const e=s.enemies[i];if(e.hp>0)continue;s.kills++;s.events.push({type:'death',x:e.x,z:e.z,kind:e.kind});const total=e.kind==='boss'?30:e.kind==='brute'?4:e.kind==='runner'?2:1,pieces=e.kind==='boss'?8:e.kind==='brute'?2:1;for(let q=0;q<pieces;q++){const a=rnd(s)*TAU,sp=.35+rnd(s)*1.2;s.pickups.push({x:e.x,z:e.z,vx:Math.cos(a)*sp,vz:Math.sin(a)*sp,value:Math.max(1,Math.ceil(total/pieces))})}if(e.kind==='boss'){s.phase='won';s.events.push({type:'victory'})}s.enemies.splice(i,1)}}
function pickups(s:GameState,dt:number){const m=moduleAt(s,'magnet'),collect=1.8+(m?.level??0)*.55,pull=4.7+(m?.level??0)*1.25;for(let i=s.pickups.length-1;i>=0;i--){const p=s.pickups[i],dx=s.playerX-p.x,dz=s.playerZ-p.z,n=Math.hypot(dx,dz)||1;if(n<pull){const f=(1-n/pull)*(14+(m?.level??0)*2.4);p.vx+=dx/n*f*dt;p.vz+=dz/n*f*dt}p.x+=p.vx*dt;p.z+=p.vz*dt;p.vx*=Math.pow(.06,dt);p.vz*=Math.pow(.06,dt);if(n<collect){s.xp+=p.value;s.pickups.splice(i,1)}}while(s.xp>=s.nextXp){s.xp-=s.nextXp;s.level++;s.nextXp=Math.floor(s.nextXp*1.22+3);s.pendingUpgrades++;s.phase='levelup';s.events.push({type:'level'})}}
function director(s:GameState,dt:number){if(!s.bossSpawned&&s.time>=BOSS_TIME){s.bossSpawned=true;spawn(s,'boss');s.events.push({type:'boss'})}s.spawnTimer-=dt;if(s.spawnTimer>0||s.enemies.length>=MAX_ENEMIES)return;const p=Math.min(1,s.time/RUN_DURATION),count=1+(rnd(s)<p*.58?1:0)+(rnd(s)<p*.2?1:0);for(let i=0;i<count;i++)spawn(s);s.spawnTimer=Math.max(.24,.92-p*.57)*(.86+rnd(s)*.3)}
export function rigWeight(s:GameState){return s.modules.reduce((a,m)=>a+weights[m.kind]*(1+(m.level-1)*.12),0)}
export function stepGame(s:GameState,input:InputState,dt:number){if(s.phase!=='running')return;dt=Math.min(.05,Math.max(0,dt));s.events=[];s.time+=dt;const motor=moduleAt(s,'engine'),speed=5.15+(motor?.level??0)*.48,[mx,mz]=clamp2(input.moveX,input.moveZ),a=Math.min(1,10.5*dt);s.playerVX+=(mx*speed-s.playerVX)*a;s.playerVZ+=(mz*speed-s.playerVZ)*a;s.playerX+=s.playerVX*dt;s.playerZ+=s.playerVZ*dt;const lim=ARENA_RADIUS-2,n=Math.hypot(s.playerX,s.playerZ);if(n>lim){s.playerX=s.playerX/n*lim;s.playerZ=s.playerZ/n*lim}const turn=(5+(motor?.level??0)*.42)/(1+Math.max(0,rigWeight(s)-4.8)*.05),d=wrap(input.rigTarget-s.rigRotation);s.rigRotation=wrap(s.rigRotation+Math.sign(d)*Math.min(Math.abs(d),turn*dt));director(s,dt);updateModules(s,dt);projectiles(s,dt);enemies(s,dt);deaths(s);if(s.phase!=='running')return;pickups(s,dt);if(s.hp<=0){s.hp=0;s.phase='lost';s.events.push({type:'defeat'})}}
function candidate(s:GameState,k:ModuleKind):UpgradeChoice{const m=moduleAt(s,k);const detail:Record<ModuleKind,string>={gun:'Скорострельность, урон и импульс.',saw:'Контактный урон и рабочий радиус.',shield:'Шире сектор и сильнее отталкивание.',mortar:'Мощнее взрыв и быстрее перезарядка.',magnet:'Сильнее тяга и больше радиус сбора.',engine:'Быстрее мех и разворот тяжёлого рига.'};return{id:(m?'level-':'add-')+k,title:m?`${labels[k]} · ур. ${m.level+1}`:labels[k],detail:detail[k],kind:k}}
export function getUpgradeChoices(s:GameState):UpgradeChoice[]{const a:UpgradeChoice[]=[];for(const k of ['gun','saw','shield','mortar','magnet','engine'] as ModuleKind[]){const m=moduleAt(s,k);if(!m||m.level<5)a.push(candidate(s,k))}a.push({id:'repair',title:'Полевой ремонт',detail:'Восстановить 34 прочности.',kind:'repair'},{id:'chassis',title:'Усиленное шасси',detail:'+18 к максимуму и текущей прочности.',kind:'chassis'});for(let i=a.length-1;i>0;i--){const j=Math.floor(rnd(s)*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a.slice(0,3)}
export function applyUpgrade(s:GameState,c:UpgradeChoice){if(c.kind==='repair')s.hp=Math.min(s.maxHp,s.hp+34);else if(c.kind==='chassis'){s.maxHp+=18;s.hp=Math.min(s.maxHp,s.hp+18)}else{const m=moduleAt(s,c.kind);if(m)m.level=Math.min(5,m.level+1);else{const used=new Set(s.modules.map(x=>x.slot));let slot=slots[c.kind];if(used.has(slot))slot=[0,1,2,3,4,5].find(x=>!used.has(x))??slot;s.modules.push({kind:c.kind,level:1,slot,cooldown:.05});s.modules.sort((a,b)=>a.slot-b.slot)}}s.pendingUpgrades=Math.max(0,s.pendingUpgrades-1);s.phase=s.pendingUpgrades?'levelup':'running'}
export function pauseGame(s:GameState){if(s.phase==='running')s.phase='paused'}
export function resumeGame(s:GameState){if(s.phase==='paused')s.phase='running'}
export function serializeGame(s:GameState){return JSON.stringify({...s,events:[]})}
export function restoreGame(raw:string|null):GameState|null{if(!raw)return null;try{const p=JSON.parse(raw) as Partial<GameState>;if(p.version!==1||!Array.isArray(p.modules)||!Array.isArray(p.enemies)||!Array.isArray(p.projectiles)||!Array.isArray(p.pickups)||typeof p.hp!=='number'||typeof p.playerX!=='number'||typeof p.rng!=='number')return null;const s=p as GameState;s.events=[];if(s.phase==='paused')s.phase='running';return s}catch{return null}}
