const te = new TextEncoder();

export function downloadBlob(blob, filename) {
  const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);
}
export function downloadText(text, filename, type='text/plain;charset=utf-8') { downloadBlob(new Blob([text],{type}),filename); }
export const safeName = name => String(name||'model').trim().replace(/[^a-zA-Z0-9а-яА-ЯёЁіІїЇєЄ_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,80)||'model';

export function exportBinarySTL(meshes, name='model') {
  const visible=meshes.filter(m=>m.visible!==false&&m.indices.length);const tris=visible.reduce((n,m)=>n+m.indices.length/3,0);const buffer=new ArrayBuffer(84+tris*50);const view=new DataView(buffer);const header=te.encode(`FORMA ${name}`.slice(0,80));new Uint8Array(buffer,0,header.length).set(header);view.setUint32(80,tris,true);let off=84;
  for(const m of visible)for(let i=0;i<m.indices.length;i+=3){const ia=m.indices[i]*3,ib=m.indices[i+1]*3,ic=m.indices[i+2]*3;const n=faceNormal(m.positions,ia,ib,ic);for(const v of n){view.setFloat32(off,v,true);off+=4;}for(const idx of [ia,ib,ic])for(let k=0;k<3;k++){view.setFloat32(off,m.positions[idx+k],true);off+=4;}view.setUint16(off,0,true);off+=2;}
  return new Blob([buffer],{type:'model/stl'});
}

export function exportOBJ(meshes, name='model') {
  const visible=meshes.filter(m=>m.visible!==false&&m.indices.length);let obj=`# Generated by FORMA\nmtllib ${safeName(name)}.mtl\n`;let mtl='# Generated by FORMA\n';let offset=1;
  visible.forEach((m,mi)=>{obj+=`\no ${clean(m.name)}\nusemtl material_${mi}\n`;for(let i=0;i<m.positions.length;i+=3)obj+=`v ${fmt(m.positions[i])} ${fmt(m.positions[i+1])} ${fmt(m.positions[i+2])}\n`;for(let i=0;i<m.normals.length;i+=3)obj+=`vn ${fmt(m.normals[i])} ${fmt(m.normals[i+1])} ${fmt(m.normals[i+2])}\n`;for(let i=0;i<m.indices.length;i+=3){const a=m.indices[i]+offset,b=m.indices[i+1]+offset,c=m.indices[i+2]+offset;obj+=`f ${a}//${a} ${b}//${b} ${c}//${c}\n`;}const rgb=hexRgb(m.color);mtl+=`\nnewmtl material_${mi}\nKd ${rgb.map(fmt).join(' ')}\nKa 0.08 0.08 0.08\nKs 0.12 0.12 0.12\nNs 24\nd 1\n`;offset+=m.positions.length/3;});
  return {obj:new Blob([obj],{type:'text/plain'}),mtl:new Blob([mtl],{type:'text/plain'})};
}

export function export3MF(meshes, name='model') {
  const visible=meshes.filter(m=>m.visible!==false&&m.indices.length);const colors=visible.map(m=>normalizeHex(m.color));let xml=`<?xml version="1.0" encoding="UTF-8"?>\n<model unit="millimeter" xml:lang="ru-RU" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">\n<metadata name="Title">${escapeXml(name)}</metadata>\n<resources>\n<basematerials id="1">`;
  colors.forEach((c,i)=>xml+=`<base name="${escapeXml(visible[i].name)}" displaycolor="${c.toUpperCase()}FF"/>`);xml+='</basematerials>';
  visible.forEach((m,mi)=>{xml+=`<object id="${mi+2}" type="model" name="${escapeXml(m.name)}"><mesh><vertices>`;for(let i=0;i<m.positions.length;i+=3)xml+=`<vertex x="${fmt(m.positions[i])}" y="${fmt(m.positions[i+1])}" z="${fmt(m.positions[i+2])}"/>`;xml+='</vertices><triangles>';for(let i=0;i<m.indices.length;i+=3)xml+=`<triangle v1="${m.indices[i]}" v2="${m.indices[i+1]}" v3="${m.indices[i+2]}" pid="1" p1="${mi}"/>`;xml+='</triangles></mesh></object>';});
  xml+='</resources><build>';visible.forEach((_,i)=>xml+=`<item objectid="${i+2}"/>`);xml+='</build></model>';
  const contentTypes=`<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/></Types>`;
  const rels=`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Target="/3D/3dmodel.model" Id="rel0" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/></Relationships>`;
  return new Blob([makeZip({'[Content_Types].xml':te.encode(contentTypes),'_rels/.rels':te.encode(rels),'3D/3dmodel.model':te.encode(xml)})],{type:'model/3mf'});
}

export function exportGLB(meshes, name='model') {
  const visible=meshes.filter(m=>m.visible!==false&&m.indices.length);const chunks=[];let byteLength=0;const bufferViews=[],accessors=[],materials=[],gltfMeshes=[],nodes=[];
  const pushData=(typed,target)=>{const bytes=new Uint8Array(typed.buffer,typed.byteOffset,typed.byteLength);const pad=(4-(byteLength%4))%4;if(pad){chunks.push(new Uint8Array(pad));byteLength+=pad;}const offset=byteLength;const copy=new Uint8Array(bytes.length);copy.set(bytes);chunks.push(copy);byteLength+=copy.length;const id=bufferViews.length;bufferViews.push({buffer:0,byteOffset:offset,byteLength:copy.length,target});return id;};
  visible.forEach((m,mi)=>{const posView=pushData(m.positions,34962),normView=pushData(m.normals,34962);const use16=m.positions.length/3<=65535;const idx=use16?new Uint16Array(m.indices):m.indices;const idxView=pushData(idx,34963);const pAcc=accessors.length;accessors.push({bufferView:posView,componentType:5126,count:m.positions.length/3,type:'VEC3',min:m.bounds.min,max:m.bounds.max});const nAcc=accessors.length;accessors.push({bufferView:normView,componentType:5126,count:m.normals.length/3,type:'VEC3'});const iAcc=accessors.length;accessors.push({bufferView:idxView,componentType:use16?5123:5125,count:idx.length,type:'SCALAR'});const rgb=hexRgb(m.color);materials.push({name:m.name,pbrMetallicRoughness:{baseColorFactor:[...rgb,1],metallicFactor:0,roughnessFactor:.72},doubleSided:false});gltfMeshes.push({name:m.name,primitives:[{attributes:{POSITION:pAcc,NORMAL:nAcc},indices:iAcc,material:mi}]});nodes.push({name:m.name,mesh:mi});});
  const totalPad=(4-(byteLength%4))%4;if(totalPad){chunks.push(new Uint8Array(totalPad));byteLength+=totalPad;}const bin=new Uint8Array(byteLength);let cursor=0;for(const c of chunks){bin.set(c,cursor);cursor+=c.length;}
  const gltf={asset:{version:'2.0',generator:'FORMA'},scene:0,scenes:[{name,nodes:nodes.map((_,i)=>i)}],nodes,meshes:gltfMeshes,materials,buffers:[{byteLength}],bufferViews,accessors};let json=te.encode(JSON.stringify(gltf));const jsonPad=(4-json.length%4)%4;const paddedJson=new Uint8Array(json.length+jsonPad);paddedJson.set(json);paddedJson.fill(0x20,json.length);const total=12+8+paddedJson.length+8+bin.length;const out=new ArrayBuffer(total),view=new DataView(out);view.setUint32(0,0x46546c67,true);view.setUint32(4,2,true);view.setUint32(8,total,true);view.setUint32(12,paddedJson.length,true);view.setUint32(16,0x4E4F534A,true);new Uint8Array(out,20,paddedJson.length).set(paddedJson);let o=20+paddedJson.length;view.setUint32(o,bin.length,true);view.setUint32(o+4,0x004E4942,true);new Uint8Array(out,o+8,bin.length).set(bin);return new Blob([out],{type:'model/gltf-binary'});
}

function makeZip(files){const entries=[];let offset=0;const locals=[];for(const [name,data] of Object.entries(files)){const nameBytes=te.encode(name),crc=crc32(data);const local=new Uint8Array(30+nameBytes.length+data.length);const v=new DataView(local.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0,true);v.setUint16(8,0,true);v.setUint16(10,0,true);v.setUint16(12,0,true);v.setUint32(14,crc,true);v.setUint32(18,data.length,true);v.setUint32(22,data.length,true);v.setUint16(26,nameBytes.length,true);v.setUint16(28,0,true);local.set(nameBytes,30);local.set(data,30+nameBytes.length);locals.push(local);entries.push({nameBytes,crc,size:data.length,offset});offset+=local.length;}
  const centrals=[];let centralSize=0;for(const e of entries){const c=new Uint8Array(46+e.nameBytes.length);const v=new DataView(c.buffer);v.setUint32(0,0x02014b50,true);v.setUint16(4,20,true);v.setUint16(6,20,true);v.setUint16(8,0,true);v.setUint16(10,0,true);v.setUint16(12,0,true);v.setUint16(14,0,true);v.setUint32(16,e.crc,true);v.setUint32(20,e.size,true);v.setUint32(24,e.size,true);v.setUint16(28,e.nameBytes.length,true);v.setUint16(30,0,true);v.setUint16(32,0,true);v.setUint16(34,0,true);v.setUint16(36,0,true);v.setUint32(38,0,true);v.setUint32(42,e.offset,true);c.set(e.nameBytes,46);centrals.push(c);centralSize+=c.length;}
  const end=new Uint8Array(22);const ev=new DataView(end.buffer);ev.setUint32(0,0x06054b50,true);ev.setUint16(4,0,true);ev.setUint16(6,0,true);ev.setUint16(8,entries.length,true);ev.setUint16(10,entries.length,true);ev.setUint32(12,centralSize,true);ev.setUint32(16,offset,true);ev.setUint16(20,0,true);const out=new Uint8Array(offset+centralSize+22);let p=0;for(const x of locals){out.set(x,p);p+=x.length;}for(const x of centrals){out.set(x,p);p+=x.length;}out.set(end,p);return out;}

const CRC_TABLE=(()=>{const t=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;t[n]=c>>>0;}return t;})();
function crc32(data){let c=0xffffffff;for(const b of data)c=CRC_TABLE[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0;}
function faceNormal(p,ia,ib,ic){const ux=p[ib]-p[ia],uy=p[ib+1]-p[ia+1],uz=p[ib+2]-p[ia+2],vx=p[ic]-p[ia],vy=p[ic+1]-p[ia+1],vz=p[ic+2]-p[ia+2];const n=[uy*vz-uz*vy,uz*vx-ux*vz,ux*vy-uy*vx],l=Math.hypot(...n)||1;return n.map(v=>v/l);}
function clean(s){return String(s||'part').replace(/[\r\n]+/g,' ').slice(0,80)}
function fmt(n){return Number(n).toFixed(5).replace(/\.?0+$/,'')||'0'}
function hexRgb(hex){const n=parseInt(normalizeHex(hex).slice(1),16);return[((n>>16)&255)/255,((n>>8)&255)/255,(n&255)/255]}
function normalizeHex(c){return /^#[0-9a-f]{6}$/i.test(c)?c.toLowerCase():'#cccccc'}
function escapeXml(s){return String(s).replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]))}
