import { installMobileRuntime } from '../../shared/mobile-runtime.js';
installMobileRuntime();

const W=240,H=352,LANES=[208,262,316],MAX_DAY=5,MAX_KEEP=9;
const KEY='pocket-works:pyad:save';
const $=id=>document.getElementById(id);
const canvas=$('world'),g=canvas.getContext('2d',{alpha:false});
g.imageSmoothingEnabled=false;
const els={day:$('dayTag'),keep:$('keepTag'),food:$('foodCount'),wood:$('woodCount'),actions:$('actionsCount'),actionsName:$('actionsName'),context:$('contextNote'),legend:$('worldLegend'),dayTools:$('dayTools'),nightTools:$('nightTools'),nightBtn:$('nightBtn'),enemy:$('enemyCount'),banner:$('bannerStatus'),toast:$('sceneToast'),overlay:$('overlay'),panelKicker:$('panelKicker'),panelTitle:$('panelTitle'),panelText:$('panelText'),panelLedger:$('panelLedger'),panelButtons:$('panelButtons')};
const P={sky:'#4f7792',skyHigh:'#31577c',blue:'#253d55',lapis:'#345c79',cloud:'#e3d4ac',gold:'#e1b864',sun:'#f4d686',hills:'#738760',forest:'#3b6048',forestDark:'#254936',leaf:'#5d8051',grass:'#6d8d5a',grassLight:'#86a46b',grassDark:'#4c714d',dirt:'#b7a278',dirtLight:'#cfb68a',stone:'#cdbd95',stoneShade:'#9a997b',stoneDark:'#657782',roof:'#a75f42',roofLight:'#cf8950',red:'#a6433b',redLight:'#db6a4d',banner:'#3f6381',wood:'#7d5137',woodLight:'#bb8352',outline:'#243c38',water:'#56849a',waterLight:'#83b6b5',skin:'#eac49b',steel:'#b5bcaa',armor:'#737f80',shadow:'#314533',fire:'#f2ae4a',white:'#f7e8bf'};
let audio=null,anim=0,lastTime=0,savingClock=0,toastTimer=0,overlayMode='intro';
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const fresh=()=>({mode:'intro',pauseFrom:null,day:1,keep:9,food:6,wood:5,actions:3,lane:1,bannerLane:1,bannerCooldown:0,defenders:[{militia:1,bows:0,wall:0},{militia:1,bows:1,wall:0},{militia:1,bows:0,wall:0}],fire:[0,0,0],melee:[0,0,0],enemies:[],waveElapsed:0,spawnIndex:0,kills:0,score:0,sound:true,best:0});
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
function readSave(){try{const obj=JSON.parse(localStorage.getItem(KEY));if(!obj||!['intro','day','night','paused','won','lost'].includes(obj.mode)||!Array.isArray(obj.defenders)||obj.defenders.length!==3)return null;const base=fresh();base.day=clamp(Number(obj.day)||1,1,5);base.mode=obj.mode;base.pauseFrom=['day','night'].includes(obj.pauseFrom)?obj.pauseFrom:'day';base.keep=clamp(Number(obj.keep)||0,0,9);base.food=clamp(Number(obj.food)||0,0,999);base.wood=clamp(Number(obj.wood)||0,0,999);base.actions=clamp(Number(obj.actions)||0,0,3);base.lane=clamp(Number(obj.lane)||0,0,2);base.bannerLane=clamp(Number(obj.bannerLane)||0,0,2);base.bannerCooldown=clamp(Number(obj.bannerCooldown)||0,0,2);base.defenders=obj.defenders.map(d=>({militia:clamp(Number(d.militia)||0,0,4),bows:clamp(Number(d.bows)||0,0,3),wall:clamp(Number(d.wall)||0,0,2)}));base.fire=Array.isArray(obj.fire)?obj.fire.slice(0,3).map(x=>clamp(Number(x)||0,0,3)):[0,0,0];base.melee=Array.isArray(obj.melee)?obj.melee.slice(0,3).map(x=>clamp(Number(x)||0,0,3)):[0,0,0];base.enemies=Array.isArray(obj.enemies)?obj.enemies.slice(0,50).filter(e=>e&&Number.isFinite(e.x)&&Number.isFinite(e.hp)&&[0,1,2].includes(e.lane)&&['scout','raider','ram'].includes(e.type)).map(e=>({...e,x:clamp(e.x,20,245),hp:clamp(e.hp,.1,12),attack:clamp(Number(e.attack)||0,0,3)})):[];base.waveElapsed=clamp(Number(obj.waveElapsed)||0,0,300);base.spawnIndex=clamp(Number(obj.spawnIndex)||0,0,100);base.kills=clamp(Number(obj.kills)||0,0,1000);base.score=clamp(Number(obj.score)||0,0,99999);base.sound=obj.sound!==false;base.best=clamp(Number(obj.best)||0,0,99999);if(base.mode==='paused'&&!['day','night'].includes(base.pauseFrom))base.pauseFrom='day';return base}catch{return null}}
let state=readSave()||fresh();
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}}
function sfx(type){if(!state.sound)return;try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;if(!audio)audio=new Audio();if(audio.state==='suspended')audio.resume().catch(()=>{});const now=audio.currentTime;const osc=audio.createOscillator(),gain=audio.createGain();const f={tap:340,build:240,bow:760,hit:160,gate:90,win:520,fail:120}[type]||360;osc.type=type==='gate'?'sawtooth':type==='win'?'sine':'triangle';osc.frequency.setValueAtTime(f,now);osc.frequency.exponentialRampToValueAtTime(Math.max(60,f*(type==='bow'?.66:1.27)),now+.085);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(type==='gate'?.045:.025,now+.012);gain.gain.exponentialRampToValueAtTime(.0001,now+.14);osc.connect(gain);gain.connect(audio.destination);osc.start(now);osc.stop(now+.16)}catch{}}
const bump=(message,sound)=>{els.context.textContent=message;if(sound)sfx(sound)};
function toast(text){els.toast.textContent=text;els.toast.classList.add('show');toastTimer=2.15}
function showOverlay(kind){overlayMode=kind;els.overlay.hidden=false;const p=els.panelButtons;p.replaceChildren();function button(text,fn,primary=false){const b=document.createElement('button');b.textContent=text;b.type='button';if(primary)b.className='primary';b.setAttribute('data-native-press','');b.addEventListener('click',fn);p.append(b)}
 if(kind==='intro'){els.panelKicker.textContent='ANNO DOMINI MCCXLVIII';els.panelTitle.textContent='Пядь земли';els.panelText.textContent='Крошечное королевство, в котором помещается целая война. Продержись пять ночей.';els.panelLedger.textContent='ДНЁМ: три приказа, припасы и укрепления. НОЧЬЮ: переноси знамя между тремя дорогами.';button('ПРИНЯТЬ КОРОНУ',start,true)}
 if(kind==='pause'){els.panelKicker.textContent='ЛЕТОПИСЬ КРЕПОСТИ';els.panelTitle.textContent='Совет у ворот';els.panelText.textContent=`Ночь ${state.day} из 5 · Ворота ${state.keep} / 9 · Побеждено ${state.kills}`;els.panelLedger.textContent='Дороги ведут к одному замку. Сохраняй лучников до поздних ночей и усиливай самые опасные направления знаменем.';button('ВЕРНУТЬСЯ К ОБОРОНЕ',resume,true);button(state.sound?'ЗВУК: ВКЛЮЧЁН':'ЗВУК: ВЫКЛЮЧЕН',()=>{state.sound=!state.sound;save();showOverlay('pause')});button('НАЧАТЬ ЗАНОВО',()=>showOverlay('confirm'))}
 if(kind==='confirm'){els.panelKicker.textContent='ULTIMUM CONSILIUM';els.panelTitle.textContent='Сжечь летопись?';els.panelText.textContent='Текущая осада будет потеряна. Рекорд останется в памяти королевства.';els.panelLedger.textContent='Эту кампанию нельзя будет вернуть.';button('ДА, НОВОЕ КОРОЛЕВСТВО',start,true);button('НЕТ, ПРОДОЛЖИТЬ',()=>showOverlay('pause'))}
 if(kind==='won'||kind==='lost'){const won=kind==='won';els.panelKicker.textContent=won?'FINIS · GLORIA':'FINIS · RUINA';els.panelTitle.textContent=won?'Пять ночей':'Пали ворота';els.panelText.textContent=won?'Пока мир спал, ваша пядь земли стала королевством. Хронист поставил точку.':'Башни молчат. Дороги ведут в пепел, но маленькие королевства умеют начинаться заново.';els.panelLedger.textContent=`СЧЁТ ${state.score} · РЕКОРД ${state.best} · УНИЧТОЖЕНО ${state.kills} · ВОРОТА ${state.keep}/9`;button('НАЧАТЬ НОВУЮ ЛЕТОПИСЬ',start,true);button(state.sound?'ЗВУК: ВКЛЮЧЁН':'ЗВУК: ВЫКЛЮЧЕН',()=>{state.sound=!state.sound;save();showOverlay(kind)})}
}
function hideOverlay(){els.overlay.hidden=true}
function start(){const best=state.best,sound=state.sound;state=fresh();state.best=best;state.sound=sound;state.mode='day';hideOverlay();bump('Выбери дорогу и отдай до трёх приказов.','build');toast('ДЕНЬ ПЕРВЫЙ');updateUI();save()}
function pause(){if(state.mode!=='day'&&state.mode!=='night')return;state.pauseFrom=state.mode;state.mode='paused';save();showOverlay('pause');updateUI()}
function resume(){state.mode=state.pauseFrom==='night'?'night':'day';state.pauseFrom=null;hideOverlay();updateUI();save()}
function finish(won){state.mode=won?'won':'lost';state.score+=won?state.keep*20+120:0;state.best=Math.max(state.best,state.score);save();sfx(won?'win':'fail');showOverlay(won?'won':'lost');updateUI()}
const actionDefs={harvest:{food:0,wood:0},wood:{food:0,wood:0},militia:{food:2,wood:1},archer:{food:3,wood:3},wall:{food:0,wood:4},repair:{food:0,wood:3}};
function action(type){if(state.mode!=='day')return;const price=actionDefs[type];if(!price)return;if(state.actions<=0){bump('Приказы закончились — начинай ночь.','tap');return}const d=state.defenders[state.lane];if(type==='militia'&&d.militia>=4)return bump('На этой дороге уже четыре копья.','tap');if(type==='archer'&&d.bows>=3)return bump('Лучников на этой дороге достаточно.','tap');if(type==='wall'&&d.wall>=2)return bump('Частокол здесь уже укреплён.','tap');if(type==='repair'&&state.keep>=MAX_KEEP)return bump('Крепость уже цела.','tap');if(state.food<price.food||state.wood<price.wood)return bump('Недостаточно припасов. Нужны жатва или лес.','tap');state.food-=price.food;state.wood-=price.wood;state.actions--;const label=['северной дороге','главном тракте','южной дороге'][state.lane];if(type==='harvest'){state.food+=5;bump('Крестьяне собрали пять мер зерна.','build')}if(type==='wood'){state.wood+=4;bump('Лесорубы заготовили четыре бревна.','build')}if(type==='militia'){d.militia++;bump(`Копейщик выставлен на ${label}.`,'build')}if(type==='archer'){d.bows++;bump(`Лучник занял позицию на ${label}.`,'build')}if(type==='wall'){d.wall++;bump(`Частокол возведён на ${label}.`,'build')}if(type==='repair'){state.keep=Math.min(MAX_KEEP,state.keep+2);bump('Каменщики укрепили ворота.','build')}state.score+=type==='harvest'||type==='wood'?1:3;updateUI();save()}
function selectLane(lane){lane=Number(lane);if(!Number.isInteger(lane)||lane<0||lane>2)return;if(state.mode!=='day'&&state.mode!=='night')return;if(state.mode==='night'&&lane!==state.bannerLane&&state.bannerCooldown>0){bump('Знамя в пути — ещё мгновение.','tap');return}state.lane=lane;if(state.mode==='night'&&state.bannerLane!==lane){state.bannerLane=lane;state.bannerCooldown=1.2;bump(`Королевское знамя: ${['север','тракт','юг'][lane]}!`,'build')}else if(state.mode==='day')bump(`Выбран ${['северный путь','главный тракт','южный путь'][lane]}.`,'tap');updateUI();save()}
function getWave(day){const wave=[];const amount=day*2+2;for(let i=0;i<amount;i++){const lane=(i*2+day+(i%5===0?1:0))%3;const type=day>=3&&i%5===0?'ram':day>=2&&(i%3===0||day>=4&&i%2===0)?'raider':'scout';wave.push({lane,type,t:1.2+i*Math.max(1.6,2.85-day*.18)})}return wave}
function beginNight(){if(state.mode!=='day')return;state.mode='night';state.waveElapsed=0;state.spawnIndex=0;state.enemies=[];state.fire=[.4,.5,.4];state.melee=[.2,.3,.2];state.bannerLane=state.lane;state.bannerCooldown=0;els.context.textContent='Переноси знамя: выбранная дорога бьёт сильнее.';toast(`НОЧЬ ${state.day} · НАБЕГ`);sfx('gate');updateUI();save()}
function nextDay(){if(state.day>=MAX_DAY){finish(true);return}state.day++;state.mode='day';state.actions=3;state.food+=2;state.wood+=1;state.bannerCooldown=0;state.enemies=[];state.waveElapsed=0;state.spawnIndex=0;toast(`ДЕНЬ ${state.day} · РАССВЕТ`);bump('Уцелевшие принесли 2 зерна и 1 дерево.','build');updateUI();save()}
function hitEnemy(e,damage,x,y){e.hp-=damage;if(!reduced)for(let k=0;k<3;k++)particles.push({x:x+(k-1)*2,y:y-(k%2)*2,life:.4,vel:(k-1)*14});if(e.hp<=0){e.dead=true;state.kills++;state.score+=e.type==='ram'?14:e.type==='raider'?8:5;sfx('hit')}}
let particles=[],arrows=[];
function update(dt){anim+=dt;if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0)els.toast.classList.remove('show')}for(const p of particles){p.life-=dt;p.x+=p.vel*dt;p.y-=10*dt}particles=particles.filter(p=>p.life>0);for(const a of arrows){a.life-=dt;a.x+=(a.tx-a.x)*Math.min(1,dt*12);a.y+=(a.ty-a.y)*Math.min(1,dt*12)}arrows=arrows.filter(a=>a.life>0);
 if(state.mode!=='night')return;state.waveElapsed+=dt;state.bannerCooldown=Math.max(0,state.bannerCooldown-dt);const wave=getWave(state.day);while(state.spawnIndex<wave.length&&wave[state.spawnIndex].t<=state.waveElapsed){const def=wave[state.spawnIndex++],hp=def.type==='ram'?8:def.type==='raider'?4:2;state.enemies.push({lane:def.lane,type:def.type,x:244,hp,attack:0});}
 for(let lane=0;lane<3;lane++){const d=state.defenders[lane],on=state.bannerLane===lane;const present=state.enemies.filter(e=>e.lane===lane&&!e.dead).sort((a,b)=>a.x-b.x);state.fire[lane]-=dt;state.melee[lane]-=dt;
 if(d.bows>0&&present.length&&present[0].x<230&&state.fire[lane]<=0){const e=present[0];hitEnemy(e,d.bows*(on?1.45:1),e.x,LANES[lane]-6);arrows.push({x:80,y:LANES[lane]-15,tx:e.x,ty:LANES[lane]-6,life:.18});state.fire[lane]=Math.max(.5,1.37-.09*d.bows);if(lane===state.lane||Math.random()<.27)sfx('bow')}
 if(d.militia>0&&present.length&&present[0].x<=122&&state.melee[lane]<=0){hitEnemy(present[0],d.militia*(on?1.22:.8),present[0].x,LANES[lane]-5);state.melee[lane]=1.02}
 }
 for(const e of state.enemies){if(e.dead)continue;const d=state.defenders[e.lane],speed=e.type==='ram'?7:e.type==='raider'?11:15;const blockMilitia=d.militia>0&&e.x<=123,blockWall=d.wall>0&&e.x<=60;const stopped=blockMilitia||blockWall;if(!stopped)e.x-=speed*dt;e.attack=Math.max(0,e.attack-dt);if(stopped&&e.attack<=0){e.attack=e.type==='ram'?1.1:1.7;if(blockMilitia){d.militia=Math.max(0,d.militia-(e.type==='ram'?2:1));particles.push({x:113,y:LANES[e.lane]-3,life:.5,vel:3});bump('Передние ряды дрогнули!','hit')}else{d.wall=Math.max(0,d.wall-(e.type==='ram'?2:1));bump('Частокол повреждён!','gate')} }if(e.x<36){e.dead=true;const damage=e.type==='ram'?3:e.type==='raider'?2:1;state.keep=Math.max(0,state.keep-damage);toast(`ВОРОТА −${damage}`);sfx('gate');if(state.keep===0){state.enemies=[];finish(false);return}}}
 state.enemies=state.enemies.filter(e=>!e.dead);if(state.waveElapsed>wave[wave.length-1].t+1.2&&state.enemies.length===0){nextDay();return}updateHUD();savingClock+=dt;if(savingClock>3){savingClock=0;save()}}
function updateHUD(){els.day.textContent=state.mode==='night'?`ЛЕТО 1248 · НОЧЬ ${roman(state.day)}`:`ЛЕТО 1248 · ДЕНЬ ${roman(state.day)}`;els.keep.textContent=`ЗАМОК ${state.keep} / 9`;els.food.textContent=state.food;els.wood.textContent=state.wood;els.actions.textContent=state.mode==='night'?state.kills:state.actions;els.actionsName.textContent=state.mode==='night'?'ПОВЕРЖЕНО':'ПРИКАЗЫ';els.enemy.textContent=`${state.enemies.length} на дорогах · ${getWave(state.day).length-state.spawnIndex} в пути`;els.banner.textContent=state.bannerCooldown>0?`ЗНАМЯ ${state.bannerCooldown.toFixed(1)} c`:'ЗНАМЯ ГОТОВО';window.__PYAD_QA__={mode:state.mode,day:state.day,keep:state.keep,food:state.food,wood:state.wood,actions:state.actions,lanes:state.defenders.map(d=>({...d})),enemies:state.enemies.length,kills:state.kills,score:state.score,bannerLane:state.bannerLane}}
function roman(n){return ['I','II','III','IV','V'][n-1]||String(n)}
function updateUI(){updateHUD();const daytime=state.mode==='day';els.dayTools.hidden=!daytime;els.nightTools.hidden=state.mode!=='night';els.nightBtn.hidden=!daytime;els.nightBtn.disabled=!daytime;els.nightBtn.innerHTML=`НАЧАТЬ НОЧЬ ${roman(state.day)} <span>→</span>`;els.legend.textContent=state.mode==='night'?'Враги идут с востока · держи знамя на угрозе':'Коснись дороги, чтобы разместить защиту';document.querySelectorAll('[data-lane]').forEach(b=>{b.classList.toggle('is-selected',Number(b.dataset.lane)===(state.mode==='night'?state.bannerLane:state.lane));b.setAttribute('aria-pressed',String(Number(b.dataset.lane)===(state.mode==='night'?state.bannerLane:state.lane)))});document.querySelectorAll('[data-action]').forEach(b=>{const type=b.dataset.action;const price=actionDefs[type],d=state.defenders[state.lane];b.disabled=!daytime||state.actions===0||state.food<price.food||state.wood<price.wood||(type==='militia'&&d.militia>=4)||(type==='archer'&&d.bows>=3)||(type==='wall'&&d.wall>=2)||(type==='repair'&&state.keep>=MAX_KEEP)})}
// Only exact integer pixel placements, no gradients, blur, canvas text or smooth vector shapes in the world.
const rect=(x,y,w,h,c)=>{g.fillStyle=c;g.fillRect(Math.round(x),Math.round(y),Math.max(1,Math.round(w)),Math.max(1,Math.round(h)))};
const hash=(x,y,s=5)=>{let z=(x*374761393+y*668265263+s*2246822519)|0;z=(z^(z>>>13))*1274126177;return ((z^(z>>>16))>>>0)/4294967296};
function stairs(x,y,steps,c){steps.forEach((n,i)=>rect(x-i*2,y+i*2,n,2,c))}
function sun(x,y){rect(x-5,y-5,12,12,P.sun);rect(x-7,y-2,16,6,P.sun);rect(x-2,y-8,6,18,P.sun);for(let d=0;d<8;d++){const xx=[-11,9,-9,7,-3,-3,8,-9][d],yy=[0,0,-8,9,-11,10,-8,8][d];rect(x+xx,y+yy,4,3,P.gold)}rect(x-2,y-1,1,2,P.wood);rect(x+3,y-1,1,2,P.wood);rect(x,y+4,3,1,P.wood)}
function cloud(x,y){rect(x,y,21,5,P.cloud);rect(x+5,y-4,11,5,P.cloud);rect(x+12,y-7,7,3,P.white);rect(x+1,y+5,27,2,'#abbcb0')}
function tree(x,y,s=1){const k=s===1?1:1.5;rect(x-2*k,y,4*k,12*k,P.wood);rect(x-8*k,y-8*k,16*k,9*k,P.forestDark);rect(x-6*k,y-13*k,13*k,9*k,P.forest);rect(x-3*k,y-18*k,7*k,8*k,P.leaf);rect(x-7*k,y-3*k,4*k,3*k,P.leaf);rect(x+2*k,y-12*k,3*k,3*k,P.grassLight)}
function flowers(x,y,col=P.sun){rect(x,y,1,3,P.forestDark);rect(x-2,y,5,1,col);rect(x,y-2,1,5,col)}
function wallBrick(x,y,w,h){rect(x,y,w,h,P.stoneDark);rect(x+2,y+2,w-4,h-3,P.stone);for(let i=0;i<Math.floor(h/8);i++){const yy=y+4+i*8;for(let xx=x+3+(i%2)*6;xx<x+w-4;xx+=12){rect(xx,yy,6,1,P.stoneShade);rect(xx+6,yy-3,1,3,P.stoneShade)}}}
function castle(){// Large silhouette is the unique focal landmark.
 rect(7,146,90,35,P.shadow);rect(17,104,73,72,P.stoneDark);wallBrick(18,112,71,62);rect(31,91,51,26,P.stone);rect(35,79,43,14,P.stoneDark);wallBrick(36,83,41,35);rect(43,75,27,9,P.stone);rect(38,68,6,10,P.stone);rect(51,68,6,10,P.stone);rect(64,68,6,10,P.stone);
 // tiled copper-pink roof and tower turrets
 rect(25,83,14,24,P.stoneDark);rect(27,64,10,20,P.stone);rect(24,65,16,3,P.roof);rect(26,60,12,5,P.roof);rect(29,55,6,5,P.roofLight);rect(79,86,13,29,P.stoneDark);rect(81,66,10,23,P.stone);rect(78,68,16,3,P.roof);rect(80,63,12,5,P.roof);rect(83,58,6,5,P.roofLight);
 for(let i=0;i<11;i++)rect(17+i*7,106+(i%2),5,5,P.stone);rect(27,94,3,8,P.blue);rect(71,95,3,8,P.blue);rect(51,105,5,13,P.blue);rect(25,131,7,13,P.blue);rect(76,130,7,13,P.blue);
 rect(43,150,21,30,P.outline);rect(46,155,15,25,P.wood);rect(50,159,7,21,P.outline);rect(52,162,2,16,P.stoneShade);rect(49,152,9,4,P.stoneShade);rect(20,152,2,12,P.wood);rect(82,152,2,12,P.wood);
 for(let i=0;i<8;i++)rect(16+i*9,170,4,3,P.stoneShade);
 rect(56,48,2,30,P.wood);rect(58,49,27,16,P.red);rect(58,65,20,4,P.redLight);rect(68,52,5,10,P.gold);rect(66,55,9,4,P.gold);rect(73,56,2,4,P.white);
 // torches and health-sensitive doorway
 for(const xx of [38,68]){rect(xx,159,3,8,P.wood);rect(xx-1,154+Math.round(Math.sin(anim*8+xx)),5,6,P.fire);rect(xx,152,3,4,P.sun)}if(state.keep<6){rect(54,168,2,8,P.outline);rect(56,172,3,1,P.outline)}if(state.keep<3){rect(45,176,5,4,P.outline);rect(58,160,3,6,P.outline)}
}
function house(x,y,scale=1){const w=20*scale,h=17*scale;rect(x-2*scale,y-4*scale,w+4*scale,4*scale,P.outline);rect(x,y-2*scale,w,h+2*scale,P.stoneShade);rect(x+2*scale,y,w-4*scale,h-3*scale,P.stone);rect(x-3*scale,y-4*scale,26*scale,3*scale,P.roof);rect(x,y-10*scale,20*scale,6*scale,P.roof);rect(x+3*scale,y-14*scale,14*scale,4*scale,P.roofLight);rect(x+6*scale,y+5*scale,6*scale,12*scale,P.wood);rect(x+7*scale,y+6*scale,4*scale,10*scale,P.outline);rect(x+14*scale,y+3*scale,4*scale,4*scale,P.blue);rect(x+15*scale,y+4*scale,2*scale,2*scale,P.waterLight)}
function church(x,y){rect(x,y,27,29,P.stoneShade);rect(x+2,y+2,23,25,P.stone);rect(x-3,y-8,33,7,P.roof);rect(x+2,y-13,23,6,P.roofLight);rect(x+13,y-25,7,19,P.stoneShade);rect(x+14,y-30,5,6,P.stone);rect(x+16,y-35,1,7,P.wood);rect(x+13,y-33,7,1,P.wood);rect(x+9,y+10,7,19,P.outline);rect(x+10,y+11,5,18,P.wood);rect(x+20,y+5,4,7,P.blue)}
function river(){for(let y=140;y<169;y+=2){let wiggle=Math.sin(y*.23)*5;rect(0,y,240,2,(y%4===0)?P.water:P.waterLight);for(let j=0;j<8;j++){let x=(((j*43+y*17)%247)+wiggle)|0;rect(x,y,4+(j%3),1,P.waterLight)}}rect(110,145,34,11,P.stoneDark);rect(111,143,32,9,P.stoneShade);rect(113,143,29,4,P.stone);for(let x=114;x<142;x+=6)rect(x,142,3,2,P.white);rect(117,155,4,4,P.water);rect(134,155,4,4,P.water)}
function field(x,y){rect(x,y,52,20,P.dirtLight);for(let i=0;i<7;i++){rect(x+2,y+i*3,48,1,i%2?P.gold:'#b99857');for(let j=0;j<8;j++){const xx=x+4+j*6,yy=y+i*3-2;rect(xx,yy,2,3,P.gold);if(hash(xx,yy)>.6)rect(xx-1,yy,4,1,P.sun)}}rect(x,y+19,52,2,P.wood)}
function mill(x,y){house(x,y);rect(x+1,y-4,2,20,P.outline);const cx=x-5,cy=y+9;rect(cx-1,cy-13,3,27,P.wood);rect(cx-13,cy-1,27,3,P.wood);rect(cx-9,cy-9,19,3,P.wood);rect(cx-9,cy+7,19,3,P.wood);rect(cx-4,cy-3,9,8,P.woodLight);rect(cx-2,cy-1,5,4,P.outline)}
function backdrop(){rect(0,0,W,H,P.grass);rect(0,0,W,91,P.sky);rect(0,0,W,31,P.skyHigh);sun(194,32);cloud(103,26);cloud(17,34);cloud(215,56);rect(0,83,240,4,P.hills);for(let i=0;i<17;i++){const x=i*16-5,h=16+(i%5)*7;rect(x,89-h,17,h,P.hills);rect(x+2,89-h,9,2,P.leaf)}rect(0,95,240,46,P.forest);for(let i=0;i<20;i++)tree(i*14-6+(i%4)*2,144,(i%4===0)?1.4:1);river();rect(0,170,240,182,P.grass);for(let i=0;i<240;i+=9){for(let j=170;j<352;j+=9){const h=hash(i,j);if(h>.78)rect(i+(h*5|0),j+(h*8|0),3,2,P.grassLight);else if(h<.16)rect(i+1,j+2,4,2,P.grassDark)}}
 field(116,173);house(188,132);house(153,120);mill(221,127);church(102,117);
 // Bottom trails and fence posts. The dark separators keep the three tactical lanes legible.
 for(let lane=0;lane<3;lane++){const y=LANES[lane];rect(31,y-9,209,21,P.grassDark);rect(31,y-6,209,15,P.dirt);rect(31,y-2,209,5,P.dirtLight);for(let x=34;x<238;x+=15){rect(x+(lane%2)*4,y-6,7,1,P.stoneShade);rect(x+3,y+7,8,1,'#a5936d')}rect(31,y-11,209,2,P.leaf);rect(31,y+10,209,2,P.forestDark)}
 // Trees and props define roads, not generic sprinkled noise.
 for(let lane=0;lane<3;lane++){const y=LANES[lane];for(let j=0;j<5;j++){const x=38+j*45+(lane%2)*12;const t=y+21;if(t<352)tree(x,t,1)}}for(let i=0;i<7;i++){const x=5+(i*37)%240,y=187+(i%3)*54;if(y<348)flowers(x,y,i%2?P.gold:P.white)}
 // miniature river side, farm cart and wandering cow
 rect(3,183,34,5,P.stoneShade);rect(5,188,33,3,P.stone);rect(12,171,4,17,P.wood);rect(19,179,3,9,P.wood);rect(24,175,4,13,P.wood);rect(12,173,16,3,P.woodLight);
 castle();
 // Border: genuine chunky pixels rather than vector calligraphy.
 rect(0,0,240,5,P.wood);rect(0,0,240,2,P.gold);rect(0,5,5,347,P.wood);rect(235,5,5,347,P.wood);rect(0,348,240,4,P.wood);rect(0,349,240,1,P.gold);for(let i=8;i<232;i+=16){rect(i,3,6,2,P.red);rect(i+6,2,3,2,P.sun)}for(let y=14;y<348;y+=23){rect(1,y,3,6,P.gold);rect(236,y+9,3,5,P.gold)}
}
function drawWall(lane){const d=state.defenders[lane];if(d.wall===0)return;const y=LANES[lane];for(let i=0;i<d.wall;i++){const x=53-i*8;rect(x,y-16,6,26,P.wood);rect(x+1,y-16,4,23,P.woodLight);rect(x,y-20,6,5,P.wood);rect(x-1,y-4,8,2,P.outline);rect(x-1,y+5,8,2,P.outline)}}
function sprite(x,y,kind,t=0,flip=false){x=Math.round(x);y=Math.round(y);const step=Math.floor(t*5)%2;const hostile=kind==='scout'||kind==='raider'||kind==='ram';const cloth=kind==='archer'?P.banner:kind==='militia'?P.stone:kind==='peasant'?P.gold:kind==='scout'?P.redLight:kind==='raider'?P.red:P.wood;
 const h=kind==='ram'?17:13,w=kind==='ram'?13:8;rect(x-1,y+1,w+2,2,'#3f5944');rect(x+2,y-10,4,4,kind==='peasant'?P.skin:P.steel);rect(x+1,y-11,6,2,kind==='peasant'?P.wood:hostile?P.outline:P.armor);rect(x+2,y-6,5,6,cloth);rect(x+3,y-5,1,3,kind==='militia'?P.red:kind==='archer'?P.sun:P.stoneDark);rect(x+1,y-5,2,5,kind==='peasant'?P.skin:P.armor);rect(x+7,y-5,2,4,P.skin);rect(x+2,y,2,4,P.wood);rect(x+5,y,2,4,P.wood);rect(x+step,y+3,3,1,P.outline);rect(x+5-step,y+3,3,1,P.outline);
 if(kind==='militia'){rect(x+7,y-16,1,18,P.outline);rect(x+6,y-19,3,4,P.steel);rect(x-1,y-4,3,5,P.blue)}if(kind==='archer'){rect(x+8,y-8,1,9,P.woodLight);rect(x+9,y-9,1,2,P.woodLight);rect(x+9,y-1,1,2,P.woodLight);rect(x+6,y-7,2,5,P.wood)}if(kind==='scout'){rect(x+1,y-12,4,2,P.outline);rect(x-2,y-3,3,5,P.red)}if(kind==='raider'){rect(x,y-12,8,2,P.outline);rect(x+8,y-13,2,12,P.steel);rect(x-3,y-5,4,7,P.red)}if(kind==='ram'){rect(x-3,y-9,17,7,P.wood);rect(x-2,y-11,13,2,P.outline);rect(x-2,y-2,4,4,P.outline);rect(x+11,y-2,4,4,P.outline);rect(x+4,y-15,4,5,P.red);rect(x+7,y-13,4,5,P.outline)}if(kind==='peasant'){rect(x+1,y-12,7,2,P.wood);rect(x-1,y-6,2,6,P.skin)}
}
function banner(lane,t){const y=LANES[lane];const bx=140;rect(bx-4,y+6,12,2,P.outline);rect(bx,y-31,2,37,P.wood);rect(bx-1,y-31,4,3,P.sun);rect(bx+2,y-29,19,11,P.banner);rect(bx+17,y-23,7+(Math.sin(t*7)>0?1:0),5,P.banner);rect(bx+6,y-26,8,1,P.gold);rect(bx+9,y-27,2,8,P.gold);rect(bx+6,y-24,8,2,P.gold);rect(bx+2,y-29,2,12,P.stoneDark)}
function drawScene(){backdrop();if(state.mode==='night'||state.mode==='paused'&&state.pauseFrom==='night'){rect(5,5,230,343,'rgba(23,38,61,.24)');for(let i=0;i<14;i++){const x=16+(i*39)%212,y=25+(i*17)%92;rect(x,y,1,1,P.sun)}rect(40,165,3,6,P.fire);rect(71,166,2,5,P.fire)}
 const t=reduced?0:anim;const viewLane=state.mode==='night'?state.bannerLane:state.lane;const y=LANES[viewLane];rect(36,y-11,199,1,P.gold);rect(36,y+11,199,1,P.gold);for(let lane=0;lane<3;lane++){drawWall(lane);const d=state.defenders[lane],yy=LANES[lane];for(let k=0;k<d.bows;k++)sprite(73+k*10,yy-3,'archer',t+k/5);for(let k=0;k<d.militia;k++)sprite(103+k*9,yy+2,'militia',t+k/6);if(state.mode!=='night'&&d.militia===0&&d.bows===0&&d.wall===0){rect(113,yy-2,7,2,P.stoneDark)}}
 // Tiny workers and pennant movement make even the untouched diorama alive.
 if(state.mode!=='night'){sprite(173+(Math.sin(t*.8)*6|0),181,'peasant',t);sprite(202-(Math.sin(t*.5)*5|0),183,'peasant',t);rect(173,177,3,1,P.sun)}
 state.enemies.forEach(e=>{sprite(e.x,LANES[e.lane],e.type,t,true);const max=e.type==='ram'?8:e.type==='raider'?4:2;rect(e.x,LANES[e.lane]-23,12,2,P.outline);rect(e.x,LANES[e.lane]-23,12*Math.max(0,e.hp/max),2,P.redLight)});
 banner(viewLane,t);for(const a of arrows){rect(a.x,a.y,5,1,P.outline);rect(a.x+4,a.y-1,2,3,P.stone)}for(const p of particles){rect(p.x,p.y,2,2,p.life>.24?P.redLight:P.gold)}
 // Informative pixel legend within the miniature, never faux dynamic statistics.
 for(let i=0;i<3;i++){const yy=LANES[i];rect(8,yy-10,21,18,P.wood);rect(10,yy-8,17,14,P.stone);rect(10,yy-8,17,3,i===viewLane?P.gold:P.stoneShade);rect(12,yy-2,12,2,i===viewLane?P.red:P.blue);for(let k=0;k<state.defenders[i].militia;k++)rect(12+k*3,yy+2,2,2,P.armor);for(let k=0;k<state.defenders[i].bows;k++)rect(12+k*3,yy-5,2,2,P.banner)}
}
function render(){g.imageSmoothingEnabled=false;drawScene()}
function frame(now){const dt=Math.min(.05,Math.max(0,(now-lastTime)/1000||0));lastTime=now;if(!document.hidden){update(dt);render()}requestAnimationFrame(frame)}
function canvasClick(ev){if(state.mode!=='day'&&state.mode!=='night')return;const r=canvas.getBoundingClientRect(),x=(ev.clientX-r.left)/r.width*W,y=(ev.clientY-r.top)/r.height*H;if(x<0||x>W||y<0||y>H)return;if(y<185){bump('Ворота держатся. Укрепляй дороги ниже.','tap');return}let lane=0;for(let i=1;i<3;i++)if(Math.abs(y-LANES[i])<Math.abs(y-LANES[lane]))lane=i;selectLane(lane)}
canvas.addEventListener('pointerup',canvasClick);
document.querySelectorAll('[data-lane]').forEach(b=>b.addEventListener('click',()=>selectLane(b.dataset.lane)));
document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>action(b.dataset.action)));
$('nightBtn').addEventListener('click',beginNight);$('menuBtn').addEventListener('click',()=>{if(state.mode==='intro'||state.mode==='won'||state.mode==='lost')showOverlay(state.mode==='intro'?'intro':state.mode);else if(state.mode==='paused')showOverlay('pause');else pause()});
window.addEventListener('pagehide',save);document.addEventListener('visibilitychange',()=>{if(document.hidden){save();if(audio&&audio.state==='running')audio.suspend().catch(()=>{})}else{lastTime=performance.now()}});
window.addEventListener('keydown',e=>{if(['1','2','3'].includes(e.key)){if(state.mode==='day'||state.mode==='night')selectLane(Number(e.key)-1)}if(e.key==='Escape'){if(state.mode==='paused')resume();else pause()}});
if(state.mode==='paused'){showOverlay('pause')}else if(state.mode==='intro'){showOverlay('intro')}else if(state.mode==='won'||state.mode==='lost'){showOverlay(state.mode)}else{hideOverlay();bump(state.mode==='night'?'Продолжай держать оборону.':'Выбирай дорогу и усиливай гарнизоны.')}updateUI();requestAnimationFrame(frame);