const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const canvas=$('#canvas'), ctx=canvas.getContext('2d',{alpha:false});
const COLS=54, ROWS=78, N=COLS*ROWS, SAVE_KEY='pocket-works:nomos-lab:state';
const COLORS=['#a6422f','#2e6f68','#a6792e','#785d87','#6d763d','#b0613f','#34617b','#845342','#49705a','#6c557a','#bb7b2e','#4d7270'];
const PREFIX=['Ар','Вел','Сар','Кер','Тир','Мор','Эл','Дар','Нор','Тал','Кас','Рин','Остр','Зар','Бел','Хар'];
const SUFFIX=['ания','ор','ия','ат','ское царство','ская лига','ир','ана','ия','град','ская земля','он'];
let W=1,H=1,dpr=1,cellW=1,cellH=1,last=0,acc=0,playing=false,speed=1,mode='political',tool='inspect',painting=false,sound=true,audio=null,toastTimer=null;
let state;
function makeArray(v=0){return Array(N).fill(v)}
function noise(x,y,seed){let n=Math.sin(x*12.9898+y*78.233+seed*37.719)*43758.5453;return n-Math.floor(n)}
function smoothField(seed,scale=8){const a=makeArray();for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++){let v=0,w=0;for(let oy=-1;oy<=1;oy++)for(let ox=-1;ox<=1;ox++){const px=(x+ox*scale)/scale,py=(y+oy*scale)/scale;const wt=ox===0&&oy===0?4:1;v+=noise(Math.floor(px),Math.floor(py),seed)*wt;w+=wt}a[y*COLS+x]=v/w}return a}
function blankState(){return{year:1,preset:'river',seed:Math.floor(Math.random()*1e9),terrain:makeArray(),fertility:makeArray(),ore:makeArray(),owner:makeArray(-1),culture:makeArray(-1),unrest:makeArray(),population:makeArray(),factions:[],laws:{centralization:52,exchange:48,violence:42,memory:58},events:[],epochs:[],nextFaction:0,seenIntro:false}}
function idx(x,y){return y*COLS+x} function xy(i){return[i%COLS,Math.floor(i/COLS)]} function inside(x,y){return x>=0&&y>=0&&x<COLS&&y<ROWS}
function neighbors(i){const[x,y]=xy(i),r=[];for(const[dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]])if(inside(x+dx,y+dy))r.push(idx(x+dx,y+dy));return r}
function land(i){return state.terrain[i]>.36}
function nameFaction(){return PREFIX[(state.nextFaction*5+state.seed)%PREFIX.length]+SUFFIX[(state.nextFaction*7+Math.floor(state.seed/9))%SUFFIX.length]}
function newFaction(cell,parent=-1){const id=state.nextFaction++,color=COLORS[id%COLORS.length];const f={id,name:nameFaction(),color,born:state.year,capital:cell,wealth:18+Math.random()*12,cohesion:75,trade:0,parent,alive:true};state.factions[id]=f;state.owner[cell]=id;state.culture[cell]=id;state.population[cell]=16+Math.random()*12;event(`${f.name} возникает как новый политический очаг.`,color);return f}
function generate(preset='river'){
  const oldIntro=state?.seenIntro||false;state=blankState();state.preset=preset;state.seenIntro=oldIntro;const elev=smoothField(state.seed,9),wet=smoothField(state.seed+11,7),mineral=smoothField(state.seed+29,6);
  for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++){const i=idx(x,y),edge=Math.min(x/(COLS*.35),(COLS-1-x)/(COLS*.35),y/(ROWS*.28),(ROWS-1-y)/(ROWS*.28));let e=elev[i]*.72+Math.max(0,Math.min(1,edge))*.36;if(preset==='archipelago')e-=.12+noise(x/4,y/4,state.seed+4)*.1;if(preset==='river')e+=Math.sin(y*.18+x*.07)*.035;if(preset==='powder')e+=.07;state.terrain[i]=e;state.fertility[i]=Math.max(0,Math.min(1,wet[i]*1.25-(e>.72?.28:0)));state.ore[i]=Math.max(0,Math.min(1,mineral[i]*1.1+(e>.62?.22:0)));state.population[i]=0}
  if(preset==='river'){for(let y=0;y<ROWS;y++){const x=Math.round(COLS*.48+Math.sin(y*.12)*5);for(let dx=-1;dx<=1;dx++){const i=idx(Math.max(0,Math.min(COLS-1,x+dx)),y);state.terrain[i]=dx===0?.18:.31;state.fertility[i]=1}}}
  const count=preset==='blank'?0:preset==='powder'?9:preset==='archipelago'?6:5;for(let k=0;k<count;k++){let best=-1,bv=-1;for(let tries=0;tries<500;tries++){const i=Math.floor(Math.random()*N);if(!land(i)||state.owner[i]>=0)continue;const[x,y]=xy(i);const spacing=state.factions.some(f=>f&&Math.hypot(x-xy(f.capital)[0],y-xy(f.capital)[1])<10);const v=state.fertility[i]+state.ore[i]*.35+(spacing?-2:0);if(v>bv){bv=v;best=i}}if(best>=0)newFaction(best)}
  state.epochs=[];captureEpoch('Начало летописи');syncControls();save();render();event(preset==='blank'?'Пустой мир ждёт твоих очагов.':'Первые общества закрепились на карте.','#a6422f')
}
function event(text,color='#a6422f'){state.events.unshift({year:state.year,text,color});state.events=state.events.slice(0,80);$('#ticker').textContent=text;$('.ticker i').style.borderColor=color}
function cellsOf(id){const a=[];for(let i=0;i<N;i++)if(state.owner[i]===id)a.push(i);return a}
function stats(id){const cells=cellsOf(id),f=state.factions[id];let pop=0,u=0,food=0,ore=0;for(const i of cells){pop+=state.population[i];u+=state.unrest[i];food+=state.fertility[i];ore+=state.ore[i]}return{cells,pop,unrest:cells.length?u/cells.length:0,food,ore,wealth:f?.wealth||0}}
function step(){state.year++;const law=state.laws;const alive=state.factions.filter(f=>f?.alive);
  for(const f of alive){const s=stats(f.id);if(!s.cells.length){f.alive=false;continue}const income=s.food*.055+s.ore*.035+s.pop*.002+(law.exchange/100)*Math.sqrt(s.cells.length)*.08;f.wealth=Math.max(0,f.wealth+income-.02*s.cells.length);f.cohesion=Math.max(0,Math.min(100,88-s.unrest*52-(s.cells.length/24)*(law.centralization/100)*12+(law.memory/100)*10));f.trade=(law.exchange/100)*Math.sqrt(s.cells.length)*2;
    for(const i of s.cells){const cap=6+state.fertility[i]*34+state.ore[i]*8;state.population[i]=Math.max(.2,Math.min(cap,state.population[i]*(1.006+state.fertility[i]*.008)));const[x,y]=xy(i),[cx,cy]=xy(f.capital),dist=Math.hypot(x-cx,y-cy);state.unrest[i]=Math.max(0,Math.min(1,state.unrest[i]*.96+dist/220*(law.centralization/100)+(state.culture[i]!==f.id?.022:0)-law.memory/100*.009))}
  }
  const attempts=Math.max(1,Math.floor(alive.length*(.7+speed*.25)));for(let a=0;a<attempts;a++){const f=alive[Math.floor(Math.random()*alive.length)];if(!f?.alive)continue;const s=stats(f.id);if(!s.cells.length)continue;const from=s.cells[Math.floor(Math.random()*s.cells.length)],targets=neighbors(from).filter(i=>land(i)&&state.owner[i]!==f.id);if(!targets.length)continue;const t=targets[Math.floor(Math.random()*targets.length)],other=state.owner[t];const mountain=state.terrain[t]>.76?.55:1;const resource=.45+state.fertility[t]*.7+state.ore[t]*.35;if(other<0){if(Math.random()<(.028+law.centralization/2200)*mountain*resource){state.owner[t]=f.id;state.culture[t]=Math.random()<.2?f.id:state.culture[from];state.population[t]=Math.max(1,state.population[from]*.15);f.wealth-=.3}}else{const o=state.factions[other];if(!o?.alive)continue;const aggression=law.violence/100,tradePeace=law.exchange/100;const attack=.002+aggression*.018-tradePeace*.009;if(Math.random()<attack*mountain){const os=stats(other);const power=(f.wealth+10)*(f.cohesion/100)*(1+s.cells.length*.012);const defense=(o.wealth+10)*(o.cohesion/100)*(1+os.cells.length*.012);if(Math.random()<power/(power+defense)){state.owner[t]=f.id;state.unrest[t]=Math.min(1,state.unrest[t]+.38);f.wealth-=.5;o.wealth-=.8;if(Math.random()<.12)event(`${f.name} отнимает пограничную землю у ${o.name}.`,f.color)}else f.wealth-=.8}}
  }
  for(const f of alive){const s=stats(f.id);if(!s.cells.length){f.alive=false;event(`${f.name} исчезает с карты.`,f.color);continue}if(s.cells.length>14&&s.unrest>.48&&Math.random()<.012*(1-state.laws.memory/140)){const candidates=s.cells.filter(i=>state.unrest[i]>.45&&i!==f.capital);if(candidates.length>4){const seed=candidates[Math.floor(Math.random()*candidates.length)],nf=newFaction(seed,f.id);const frontier=new Set([seed]);for(let wave=0;wave<3;wave++)for(const i of[...frontier])for(const n of neighbors(i))if(state.owner[n]===f.id&&state.unrest[n]>.35&&Math.random()<.55){state.owner[n]=nf.id;frontier.add(n)}event(`${f.name} раскалывается: возникает ${nf.name}.`,nf.color)}}}
  if(state.year%50===0)captureEpoch(`Рубеж ${state.year}-го года`);if(state.year%5===0)save();if(state.year%10===0&&Math.random()<.35){const biggest=state.factions.filter(f=>f?.alive).map(f=>[f,stats(f.id)]).sort((a,b)=>b[1].cells.length-a[1].cells.length)[0];if(biggest)event(`${biggest[0].name} — крупнейшая держава мира: ${biggest[1].cells.length} земель.`,biggest[0].color)}updateYear()}
function captureEpoch(title){const snap={year:state.year,title,owner:[...state.owner],culture:[...state.culture],unrest:[...state.unrest],population:[...state.population],factions:JSON.parse(JSON.stringify(state.factions)),nextFaction:state.nextFaction};state.epochs.unshift(snap);state.epochs=state.epochs.slice(0,12)}
function restoreEpoch(n){const e=state.epochs[n];if(!e)return;state.year=e.year;state.owner=[...e.owner];state.culture=[...e.culture];state.unrest=[...e.unrest];state.population=[...e.population];state.factions=JSON.parse(JSON.stringify(e.factions));state.nextFaction=e.nextFaction;playing=false;updatePlay();closeSheets();event(`Летопись восстановлена: год ${state.year}.`);save();render()}
function save(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(state))}catch(e){console.warn(e)}}
function load(){try{const raw=localStorage.getItem(SAVE_KEY);if(raw){state=JSON.parse(raw);return true}}catch(e){}return false}
function colorFor(i){if(!land(i))return state.terrain[i]<.24?'#8ab0b2':'#aac4bf';if(mode==='wealth'){const f=state.owner[i]>=0?state.factions[state.owner[i]]:null;const v=Math.min(1,(state.fertility[i]*.55+state.ore[i]*.25+(f?.wealth||0)/160));return mix('#e2d5ae','#8a642b',v)}if(mode==='unrest')return mix('#e1d4ae','#8e2d27',state.unrest[i]);if(mode==='culture'){const c=state.culture[i];return c>=0?mix(state.factions[c]?.color||'#777','#e4d6b1',.22):'#ddd1ad'}const id=state.owner[i];return id>=0?mix(state.factions[id]?.color||'#777','#e5d7b3',.18):'#ded2b1'}
function mix(a,b,t){const A=parseInt(a.slice(1),16),B=parseInt(b.slice(1),16),r=Math.round(((A>>16)&255)*(1-t)+((B>>16)&255)*t),g=Math.round(((A>>8)&255)*(1-t)+((B>>8)&255)*t),bl=Math.round((A&255)*(1-t)+(B&255)*t);return`rgb(${r},${g},${bl})`}
function resize(){const r=canvas.getBoundingClientRect();dpr=Math.min(2,devicePixelRatio||1);W=Math.max(1,r.width);H=Math.max(1,r.height);canvas.width=Math.floor(W*dpr);canvas.height=Math.floor(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);cellW=W/COLS;cellH=H/ROWS;render()}
function render(){if(!state)return;ctx.fillStyle='#a9c3be';ctx.fillRect(0,0,W,H);for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++){const i=idx(x,y);ctx.fillStyle=colorFor(i);ctx.fillRect(x*cellW,y*cellH,cellW+.5,cellH+.5);if(land(i)&&state.terrain[i]>.76){ctx.fillStyle='#5e55471f';ctx.beginPath();ctx.moveTo(x*cellW,y*cellH+cellH);ctx.lineTo(x*cellW+cellW*.5,y*cellH+1);ctx.lineTo((x+1)*cellW,y*cellH+cellH);ctx.fill()}if(land(i)&&state.ore[i]>.78){ctx.fillStyle='#3b3428aa';ctx.fillRect(x*cellW+cellW*.38,y*cellH+cellH*.38,Math.max(1,cellW*.24),Math.max(1,cellH*.24))}}
  if(mode==='political')for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++){const i=idx(x,y),id=state.owner[i];if(id<0)continue;ctx.strokeStyle='#27231daa';ctx.lineWidth=.75;ctx.beginPath();if(x===0||state.owner[i-1]!==id){ctx.moveTo(x*cellW,y*cellH);ctx.lineTo(x*cellW,(y+1)*cellH)}if(y===0||state.owner[i-COLS]!==id){ctx.moveTo(x*cellW,y*cellH);ctx.lineTo((x+1)*cellW,y*cellH)}if(x===COLS-1||state.owner[i+1]!==id){ctx.moveTo((x+1)*cellW,y*cellH);ctx.lineTo((x+1)*cellW,(y+1)*cellH)}if(y===ROWS-1||state.owner[i+COLS]!==id){ctx.moveTo(x*cellW,(y+1)*cellH);ctx.lineTo((x+1)*cellW,(y+1)*cellH)}ctx.stroke()}
  for(const f of state.factions){if(!f?.alive||state.owner[f.capital]!==f.id)continue;const[x,y]=xy(f.capital),cx=(x+.5)*cellW,cy=(y+.5)*cellH;ctx.fillStyle='#f5ead1';ctx.beginPath();ctx.arc(cx,cy,Math.max(3,cellW*1.25),0,Math.PI*2);ctx.fill();ctx.strokeStyle='#27231d';ctx.lineWidth=1;ctx.stroke();ctx.fillStyle=f.color;ctx.beginPath();ctx.arc(cx,cy,Math.max(1.8,cellW*.62),0,Math.PI*2);ctx.fill()}}
function pointerCell(e){const r=canvas.getBoundingClientRect(),x=Math.floor((e.clientX-r.left)/r.width*COLS),y=Math.floor((e.clientY-r.top)/r.height*ROWS);return inside(x,y)?idx(x,y):-1}
function applyTool(i){if(i<0)return;if(tool==='inspect'){inspect(i);return}const[x,y]=xy(i),radius=tool==='crisis'?3:tool==='mountain'?2:1;for(let oy=-radius;oy<=radius;oy++)for(let ox=-radius;ox<=radius;ox++){if(!inside(x+ox,y+oy)||Math.hypot(ox,oy)>radius+.2)continue;const n=idx(x+ox,y+oy),fall=1-Math.hypot(ox,oy)/(radius+1);if(tool==='grain'&&land(n))state.fertility[n]=Math.min(1,state.fertility[n]+.22*fall);if(tool==='ore'&&land(n))state.ore[n]=Math.min(1,state.ore[n]+.25*fall);if(tool==='mountain'){state.terrain[n]=Math.min(1,state.terrain[n]+.2*fall);if(state.terrain[n]>.82)state.fertility[n]*=.8}if(tool==='crisis'&&land(n)){state.unrest[n]=Math.min(1,state.unrest[n]+.42*fall);state.population[n]*=.92}}
  if(tool==='seed'&&land(i)&&state.owner[i]<0)newFaction(i);if(tool==='crisis')event('В мир внесён искусственный кризис.','#8e2d27');pulse(tool==='crisis'?90:22);save();render()}
function inspect(i){const id=state.owner[i];if(id<0){showToast(land(i)?'Ничейная земля. Здесь можно посеять очаг.':'Вода не удерживает государственные границы.');return}const f=state.factions[id],s=stats(id);$('#iname').textContent=f.name;$('#isigil').style.background=f.color;$('#iage').textContent=`существует ${state.year-f.born+1} лет`;$('#ipop').textContent=Math.round(s.pop);$('#iland').textContent=s.cells.length;$('#iwealth').textContent=Math.round(f.wealth);$('#icohesion').textContent=`${Math.round(f.cohesion)}%`;$('#inote').textContent=s.unrest>.45?'Держава держится на честном слове и инерции.':s.cells.length>35?'Большая система: сильная, дорогая и плохо управляемая.':f.trade>1?'Торговля связывает провинции лучше любой идеологии.':'Молодое государство ищет устойчивую форму.';$('#inspector').classList.add('open');pulse(12)}
function updateYear(){$('#year').textContent=`год ${state.year}`}
function updatePlay(){$('#play').textContent=playing?'Ⅱ':'▶';$('#play').setAttribute('aria-label',playing?'Поставить на паузу':'Запустить симуляцию')}
function syncControls(){updateYear();updatePlay();for(const[k,v]of Object.entries(state.laws)){const el=$('#'+k);if(el){el.value=v;el.nextElementSibling.value=v}}}
function openSheet(id){playing=false;updatePlay();$('#scrim').hidden=false;$$('.sheet').forEach(s=>s.hidden=s.id!==id);if(id==='chronicleSheet')renderChronicle()}
function closeSheets(){$('#scrim').hidden=true;$$('.sheet').forEach(s=>s.hidden=true)}
function renderChronicle(){const alive=state.factions.filter(f=>f?.alive).length,pop=Math.round(state.population.reduce((a,b)=>a+b,0)),landCount=state.owner.filter(x=>x>=0).length;$('#summary').innerHTML=`<div><b>${alive}</b><small>держав</small></div><div><b>${pop}</b><small>людей</small></div><div><b>${landCount}</b><small>земель</small></div>`;$('#epochs').innerHTML=state.epochs.length?state.epochs.map((e,i)=>`<button class="epoch" data-epoch="${i}"><b>год ${e.year}</b><small>${e.title}</small><em>вернуть</em></button>`).join(''):'<div class="empty">Летопись пока пуста.</div>';$$('[data-epoch]').forEach(b=>b.onclick=()=>restoreEpoch(+b.dataset.epoch))}
function showToast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),1800)}
function pulse(ms=20){if(navigator.vibrate)navigator.vibrate(ms);if(!sound)return;try{audio??=new AudioContext();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=ms>50?110:230;g.gain.setValueAtTime(.04,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.08);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.08)}catch(e){}}
function loop(t){const dt=Math.min(100,t-last||0);last=t;if(playing){acc+=dt*speed;while(acc>180){step();acc-=180}render()}requestAnimationFrame(loop)}
canvas.addEventListener('pointerdown',e=>{painting=true;canvas.setPointerCapture(e.pointerId);applyTool(pointerCell(e))});canvas.addEventListener('pointermove',e=>{if(painting&&tool!=='inspect'&&tool!=='seed')applyTool(pointerCell(e))});canvas.addEventListener('pointerup',()=>painting=false);canvas.addEventListener('pointercancel',()=>painting=false);
$$('[data-mode]').forEach(b=>b.onclick=()=>{$$('[data-mode]').forEach(x=>x.classList.remove('on'));b.classList.add('on');mode=b.dataset.mode;render();pulse()});
$$('[data-tool]').forEach(b=>b.onclick=()=>{$$('[data-tool]').forEach(x=>x.classList.remove('on'));b.classList.add('on');tool=b.dataset.tool;$('#inspector').classList.remove('open');$('#hint').classList.toggle('show',tool!=='inspect');pulse()});
$('#closeInspector').onclick=()=>$('#inspector').classList.remove('open');$('#play').onclick=()=>{playing=!playing;updatePlay();pulse(30)};$('#speed').onclick=()=>{speed=speed===1?2:speed===2?4:1;$('#speed b').textContent=`×${speed}`;showToast(`Скорость времени: ×${speed}`);pulse()};$('#laws').onclick=()=>openSheet('lawsSheet');$('#world').onclick=()=>openSheet('worldSheet');$('#chronicle').onclick=()=>openSheet('chronicleSheet');$('#scrim').onclick=closeSheets;$$('[data-close]').forEach(b=>b.onclick=closeSheets);
for(const id of['centralization','exchange','violence','memory']){$('#'+id).oninput=e=>e.target.nextElementSibling.value=e.target.value}
$('#seal').onclick=()=>{for(const id of['centralization','exchange','violence','memory'])state.laws[id]=+$('#'+id).value;event('Новые законы мира вступили в силу.');save();closeSheets();pulse(45)};
$$('[data-preset]').forEach(b=>b.onclick=()=>{generate(b.dataset.preset);closeSheets();pulse(55)});
$('#sound').onclick=()=>{sound=!sound;$('#sound').textContent=sound?'◖':'×';showToast(sound?'Звук включён':'Звук выключен')};
$('#export').onclick=()=>{render();const a=document.createElement('a');a.download=`nomos-year-${state.year}.png`;a.href=canvas.toDataURL('image/png');a.click();showToast('Карта сохранена')};
$('#start').onclick=()=>{state.seenIntro=true;save();$('#onboarding').hidden=true;openSheet('worldSheet');pulse(40)};
document.addEventListener('visibilitychange',()=>{if(document.hidden){playing=false;updatePlay();save()}});window.addEventListener('resize',resize);
if(!load())generate('river');else{syncControls();event(state.events?.[0]?.text||'Сохранённый мир восстановлен.',state.events?.[0]?.color||'#a6422f')}
if(!state.seenIntro)$('#onboarding').hidden=false;syncControls();resize();requestAnimationFrame(loop);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
