import { DURATION_BANDS, dateKey, durationBandLabel, filterByRange, summarizeCheckIns, summarizeEpisodes } from './core.js';
import { CHECKIN_SCORES, CONTEXTS, EPISODE_SCORES, TECHNIQUES, TYPE_LABELS } from './protocols.js';

const e = (v='') => String(v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const score = v => v == null ? '—' : Number(v).toFixed(Number(v)%1?1:0);
const date = (v,o={day:'2-digit',month:'short'}) => new Intl.DateTimeFormat('ru-RU',o).format(new Date(v));
const localInput = (d=new Date()) => new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);

export function scoreFields(defs){return defs.map(([name,label])=>`<div class="score"><b>${e(label)}</b><div class="scores">${[0,1,2,3,4,5].map(v=>`<label><input type="radio" name="${name}" value="${v}" ${v===3?'checked':''}><span>${v}</span></label>`).join('')}</div></div>`).join('')}
export function timeline(state,limit=Infinity,selected=null){
 const rows=[...state.episodes.map(x=>({kind:'episode',id:x.id,at:x.occurredAt,title:TYPE_LABELS[x.type]||x.type,detail:`${durationBandLabel(x.durationBand)} · контроль ${x.control}/5 · удовольствие ${x.pleasure}/5`})),...state.checkIns.map(x=>({kind:'checkin',id:x.id,at:x.occurredAt,title:'Чек-ин состояния',detail:`проникновение ${x.penetrationDesire}/5 · оральное ${x.oralDesire}/5 · стресс ${x.stress}/5`})),...state.techniqueSessions.map(x=>({kind:'technique',id:x.id,at:x.startedAt,title:TECHNIQUES.find(t=>t.id===x.techniqueId)?.title||x.techniqueId,detail:`циклов ${x.cyclesCompleted} · контроль ${x.control}/5 · тревога ${x.anxiety}/5`}))].sort((a,b)=>new Date(b.at)-new Date(a.at));
 const filtered=selected?rows.filter(x=>dateKey(x.at)===selected):rows;
 if(!filtered.length)return '<div class="empty">Пока пусто. Первая запись нужна не для вывода, а чтобы появилась точка отсчёта.</div>';
 return `<div class="timeline">${filtered.slice(0,limit).map(x=>`<article class="item"><time>${date(x.at)}<br>${date(x.at,{hour:'2-digit',minute:'2-digit'})}</time><div><strong>${e(x.title)}</strong><small>${e(x.detail)}</small></div><button data-delete-kind="${x.kind}" data-delete-id="${e(x.id)}">Удалить</button></article>`).join('')}</div>`;
}
export function today(state){
 const eps=filterByRange(state.episodes,'30d'),checks=filterByRange(state.checkIns,'30d'),es=summarizeEpisodes(eps),cs=summarizeCheckIns(checks);
 let note='Нужно хотя бы три наблюдения, прежде чем спорить с реальностью.';
 if(cs.oralDesire!=null&&cs.penetrationDesire!=null&&cs.oralDesire-cs.penetrationDesire>=1.5)note='Желание в целом не исчезло: интерес к оральному заметно выше интереса к проникновению.';
 else if(es.medianAnxiety>=4)note='Высокое напряжение может быть отдельной мишенью: не меняй сразу пять условий.';
 return `<div class="hero"><p class="eyebrow">${date(new Date(),{weekday:'long',day:'numeric',month:'long'})}</p><h1>Не мерить себя.<br>Замечать закономерности.</h1><p>Данные остаются на устройстве. Точность до секунды необязательна.</p></div>
 <div class="quick"><button data-action="episode"><em>01</em><span><b>Записать эпизод</b><small>контроль, удовольствие, контекст</small></span><b>↗</b></button><button data-action="checkin"><em>02</em><span><b>Чек-ин состояния</b><small>желание, энергия, стресс</small></span><b>↗</b></button><button data-tab="techniques"><em>03</em><span><b>Начать практику</b><small>пошаговый режим без экзамена</small></span><b>↗</b></button></div>
 <section class="section"><div class="sectionhead"><div><p class="eyebrow">ПОСЛЕДНИЕ 30 ДНЕЙ</p><h2>Сводка</h2></div><small>${eps.length+checks.length} записей</small></div><div class="metrics"><div class="metric"><b>${score(es.medianControl)}/5</b><span>контроль</span></div><div class="metric"><b>${score(es.medianPleasure)}/5</b><span>удовольствие</span></div><div class="metric"><b>${score(cs.penetrationDesire)}/5</b><span>желание проникновения</span></div></div><div class="note">${e(note)}</div></section>
 <section class="section"><div class="sectionhead"><h2>Последние записи</h2><button data-tab="journal">Открыть всё</button></div>${timeline(state,5)}</section>`;
}
export function calendar(state,cursor,selected){
 const y=cursor.getFullYear(),m=cursor.getMonth(),first=new Date(y,m,1),offset=(first.getDay()+6)%7,start=new Date(y,m,1-offset),keys=new Set([...state.episodes.map(x=>dateKey(x.occurredAt)),...state.checkIns.map(x=>dateKey(x.occurredAt)),...state.techniqueSessions.map(x=>dateKey(x.startedAt))]);
 let days='';for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const k=dateKey(d);days+=`<button class="${d.getMonth()!==m?'out ':''}${keys.has(k)?'has ':''}${selected===k?'selected':''}" data-date="${k}">${d.getDate()}</button>`}
 return `<div class="calendar"><div class="calhead"><button data-cal="prev">←</button><b>${date(cursor,{month:'long',year:'numeric'})}</b><button data-cal="next">→</button></div><div class="week">${['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map(x=>`<span>${x}</span>`).join('')}</div><div class="days">${days}</div></div>`;
}
export function journal(state,cursor,selected){return `<div class="pagehead"><p class="eyebrow">ХРОНОЛОГИЯ</p><h1>Журнал</h1><p>Нажми выбранный день ещё раз, чтобы снять фильтр.</p></div>${calendar(state,cursor,selected)}${timeline(state,Infinity,selected)}`}
export function techniques(state){return `<div class="pagehead"><p class="eyebrow">ПРАКТИКИ</p><h1>Тренировать контроль,<br>не выбивать рекорд.</h1><p>Один протокол — одна серия. Не меняй одновременно технику, средство и сценарий.</p></div>${TECHNIQUES.map(t=>`<article class="tech"><code>${t.code}</code><div><h2>${e(t.title)}</h2><p>${e(t.summary)}</p><button data-technique="${t.id}">Открыть протокол</button></div></article>`).join('')}<section class="products"><div class="sectionhead"><h2>Средства</h2><button data-action="product">Добавить карточку</button></div>${state.products.length?state.products.map(p=>`<div class="product"><div><b>${e(p.name)}</b><span>${e(p.activeIngredients)} · ${e(p.labelWait)}</span></div><button class="link" data-product-delete="${p.id}">Удалить</button></div>`).join(''):'<div class="empty">Карточек нет. Спрей для горла и средство для пениса — не одно и то же, даже если логотип одинаковый.</div>'}</section>`}
export function exportScreen(markdown){return `<div class="pagehead"><p class="eyebrow">ПЕРЕДАЧА ДАННЫХ</p><h1>Отчёт без археологии.</h1><p>Markdown удобен для чата, JSON сохраняет полную структуру.</p></div><div class="exportbar"><div class="range">${[['7d','7 дней'],['30d','30 дней'],['90d','90 дней'],['all','Всё'],['since-export','С экспорта']].map(([v,l])=>`<label><input type="radio" name="range" value="${v}" ${v==='30d'?'checked':''}><span>${l}</span></label>`).join('')}</div><label class="check"><input type="checkbox" id="include-notes"><span>Включить личные заметки</span></label><button class="solid" data-export="copy">Копировать Markdown</button><button class="outline" data-export="md">Скачать .md</button><button class="outline" data-export="json">Скачать JSON</button></div><textarea class="preview" id="preview" readonly>${e(markdown)}</textarea>`}
export function episodeForm(state){return `<form id="entry-form" data-kind="episode"><label class="field"><span>Когда</span><input type="datetime-local" name="occurredAt" value="${localInput()}" required></label><fieldset><legend>Тип</legend><div class="choices">${Object.entries(TYPE_LABELS).map(([v,l],i)=>`<label><input type="radio" name="type" value="${v}" ${i===0?'checked':''}><span>${l}</span></label>`).join('')}</div></fieldset><fieldset><legend>Примерная длительность проникновения</legend><div class="choices">${DURATION_BANDS.map((b,i)=>`<label><input type="radio" name="durationBand" value="${b.id}" ${i===2?'checked':''}><span>${b.label}</span></label>`).join('')}</div></fieldset>${scoreFields(EPISODE_SCORES)}<fieldset><legend>Контекст</legend><div class="tags">${CONTEXTS.map(([v,l])=>`<label><input type="checkbox" name="context" value="${v}"><span>${l}</span></label>`).join('')}</div></fieldset><label class="field"><span>Техника</span><select name="techniqueId"><option value="">Нет</option>${TECHNIQUES.map(t=>`<option value="${t.id}">${e(t.title)}</option>`).join('')}</select></label><label class="field"><span>Средство</span><select name="productId"><option value="">Нет</option>${state.products.map(p=>`<option value="${p.id}">${e(p.name)}</option>`).join('')}</select></label><label class="field"><span>Заметка</span><textarea name="notes" rows="3"></textarea></label><div class="form-actions"><button class="solid" type="submit">Сохранить эпизод</button></div></form>`}
export function checkinForm(){return `<form id="entry-form" data-kind="checkin"><label class="field"><span>Когда</span><input type="datetime-local" name="occurredAt" value="${localInput()}" required></label>${scoreFields(CHECKIN_SCORES)}<fieldset><legend>Утренняя эрекция</legend><div class="choices">${[['0','Нет'],['1','Частично'],['2','Да']].map(([v,l],i)=>`<label><input type="radio" name="morningErection" value="${v}" ${i===0?'checked':''}><span>${l}</span></label>`).join('')}</div></fieldset><label class="field"><span>Заметка</span><textarea name="notes" rows="3"></textarea></label><div class="form-actions"><button class="solid" type="submit">Сохранить чек-ин</button></div></form>`}
export function productForm(){return `<form id="entry-form" data-kind="product"><div class="warning"><b>Только средство, прямо предназначенное производителем для применения на пенисе.</b><br>Спреи для горла или подавления рвотного рефлекса сюда не подходят.</div><label class="field"><span>Название</span><input name="name" required></label><label class="field"><span>Действующие вещества</span><input name="activeIngredients" required></label><label class="field"><span>Концентрация</span><input name="concentration"></label><label class="field"><span>Доза по инструкции</span><input name="labelDose" required></label><label class="field"><span>Ожидание по инструкции</span><input name="labelWait" required></label><label class="check"><input type="checkbox" name="labelled" required><span>На упаковке прямо указано применение на пенисе</span></label><div class="form-actions"><button class="solid" type="submit">Сохранить карточку</button></div></form>`}
export { e, localInput };
