const CACHE_PREFIX='tempo-',CACHE_NAME='tempo-v1.0.0',APP_VERSION='1.0.0',RELEASE_DATE='2026-08-04',CACHE_PROTOCOL=2;
const RELEASE_NOTES=['Локальный журнал эпизодов и состояния.','Пошаговые stop–start и интервальные практики.','Календарь, сигналы и Markdown/JSON-экспорт.'];
const APP_SHELL=['./','./index.html','./app.config.json','./styles.css','./app.js','./screens.js','./protocols.js','./core.js','./manifest.webmanifest','./icons/icon.svg','../../shared/mobile-runtime.css','../../shared/mobile-runtime.js','../../shared/pwa-utils.js','../../shared/update-manager.css','../../shared/update-manager.js','../../shared/workshop-mode.css','../../shared/workshop-mode.js','../../shared/capabilities/storage.js','../../shared/capabilities/transfer.js','../../shared/capabilities/diagnostics.js'];
const SCOPE_URL=new URL('./',self.registration.scope),BUILD_TOKEN=`${APP_VERSION}-p${CACHE_PROTOCOL}`,SHELL_KEYS=new Map(APP_SHELL.map(x=>{const u=new URL(x,SCOPE_URL);return[u.pathname,u.href]}));
function fresh(input){const u=new URL(input instanceof Request?input.url:input,SCOPE_URL);u.searchParams.set('__pw_build',BUILD_TOKEN);return fetch(u,{cache:'no-store',credentials:'same-origin',redirect:'follow'}).then(r=>{if(!r.ok)throw new Error(`Fresh request failed: ${r.status}`);return r})}
async function precache(){const c=await caches.open(CACHE_NAME);await Promise.all([...new Set(SHELL_KEYS.values())].map(async u=>c.put(u,await fresh(u))))}
async function networkFirst(req,canonical,fallback=canonical){try{const r=await fresh(req),c=await caches.open(CACHE_NAME);await c.put(canonical,r.clone());return r}catch{return(await caches.match(canonical))||(await caches.match(fallback))}}
self.addEventListener('install',e=>e.waitUntil(precache()));
self.addEventListener('message',e=>{if(e.data?.type==='GET_UPDATE_INFO')e.ports?.[0]?.postMessage({version:APP_VERSION,releaseDate:RELEASE_DATE,releaseNotes:RELEASE_NOTES,cacheProtocol:CACHE_PROTOCOL,cacheName:CACHE_NAME});if(e.data?.type==='SKIP_WAITING')self.skipWaiting()});
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith(CACHE_PREFIX)&&k!==CACHE_NAME).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;const u=new URL(e.request.url);if(u.origin!==self.location.origin)return;if(e.request.mode==='navigate'){e.respondWith(networkFirst(e.request,SCOPE_URL.href,SCOPE_URL.href));return}const canonical=SHELL_KEYS.get(u.pathname);if(canonical)e.respondWith(networkFirst(e.request,canonical,SCOPE_URL.href))});
