import { installMobileRuntime } from '../../shared/mobile-runtime.js';
import { createVersionedStore } from '../../shared/capabilities/storage.js';
import { createWorkshopMode } from '../../shared/workshop-mode.js';
import { watchConnectivity } from '../../shared/pwa-utils.js';
import {
  VERSION, BATTLE_COUNT, FIELDS, ORDINARIES, MOTTOS, CATALOGS,
  createCampaign, hydrateCampaign, prepareBattle, recordBattle, applyOffer,
  doctrineLayers, doctrineName, createBattleState, stepBattle, summarizeBattle
} from './engine.js';
import { HERALDIC_SCHOOLS, heraldicIdentity, schoolForDoctrine, liveryForDoctrine } from './heraldry.js';

installMobileRuntime();
const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
const store = createVersionedStore({
  namespace:'pocket-works:blazon', version:VERSION,
  defaults:{settings:{sound:true},campaign:null,stats:{runs:0,victories:0}}
});
let settings=store.get('settings');
let campaign=hydrateCampaign(store.get('campaign'));
let stats=store.get('stats');
let setup={field:null,ordinary:null};
let battleState=null,battleSummary=null,battleRunning=false,paused=false,speed=1,lastFrame=0,accumulator=0,lastEventCount=0,audio=null,flashTimer=0;
const screens={menu:$('#menuScreen'),doctrine:$('#doctrineScreen'),battle:$('#battleScreen')};
const dialogs={setup:$('#setupDialog'),rules:$('#rulesDialog'),result:$('#resultDialog'),reward:$('#rewardDialog'),ending:$('#endingDialog')};
const canvas=$('#battleCanvas');
const ctx=canvas.getContext('2d');

const livingStyle=document.createElement('link');livingStyle.rel='stylesheet';livingStyle.href='./living-battle.css?v=4.0.0';document.head.append(livingStyle);
const footer=$('.menu-screen footer');if(footer)footer.textContent='v4.0 · living battle · каждый воин существует отдельно';
const battleFooter=$('.battle-footer span');if(battleFooter)battleFooter.textContent='Отряд задаёт намерение. Каждый воин сам занимает место, вступает в схватку и отступает.';

function persist(){store.patch({settings,campaign,stats});}
function showScreen(name){Object.entries(screens).forEach(([key,node])=>node.classList.toggle('is-active',key===name));}
function openDialog(dialog){if(!dialog.open)dialog.showModal();}
function closeDialog(dialog){if(dialog.open)dialog.close();}
function fmtTime(value){const sec=Math.max(0,Math.floor(value));return`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;}
function roman(number){return['I','II','III','IV','V','VI'][number-1]||number;}
function vibrate(value){try{navigator.vibrate?.(value);}catch{}}
function sound(type){if(!settings.sound)return;try{audio||=new AudioContext();if(audio.state==='suspended')audio.resume();const map={tap:[220,.04],seal:[150,.1],horn:[95,.35],win:[180,.45],lose:[90,.4],impact:[72,.05]};const[f,d]=map[type]||map.tap;const o=audio.createOscillator(),g=audio.createGain();o.type=type==='horn'?'sawtooth':'triangle';o.frequency.setValueAtTime(f,audio.currentTime);if(type==='win')o.frequency.exponentialRampToValueAtTime(f*2.2,audio.currentTime+d);g.gain.setValueAtTime(.0001,audio.currentTime);g.gain.exponentialRampToValueAtTime(.045,audio.currentTime+.008);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d+.03);}catch{}}

function ordinaryMarkup(id,fill,clip){const common=`fill="${fill}" clip-path="url(#${clip})" class="ordinary"`;if(id==='pale')return`<rect x="45" y="30" width="30" height="146" ${common}/>`;if(id==='fess')return`<rect x="14" y="79" width="92" height="31" ${common}/>`;if(id==='bend')return`<path d="M-5 48 18 26 126 146 104 169Z" ${common}/>`;if(id==='chevron')return`<path d="M22 134 60 86 99 134" fill="none" stroke="${fill}" stroke-width="22" stroke-linejoin="miter" clip-path="url(#${clip})" class="ordinary"/>`;return'';}
function useCharge(id,placement,color,outline,className){if(!id||!placement)return'';const flip=placement.flip?-1:1,rotate=placement.rotate||0,anchorX=placement.flip?placement.x+120*placement.scale:placement.x;return`<g class="${className}" style="color:${color};--detail:${outline};--charge-outline:${outline}" transform="translate(${anchorX} ${placement.y}) rotate(${rotate}) scale(${placement.scale*flip} ${placement.scale})"><use href="#charge-${id}"></use></g>`;}
function schoolOrnament(identity,compact){if(compact)return'';const{school,palette}=identity;if(school.id==='imperial')return`<path class="mantle mantle-imperial" d="M22 34C5 59 7 121 18 160L39 133L60 177L81 133L102 160C113 121 115 59 98 34L78 52L60 25L42 52Z"/><path class="mantle-lining" d="M30 45C18 73 21 119 28 141L44 119L60 158L76 119L92 141C99 119 102 73 90 45L73 59L60 39L47 59Z"/>`;if(school.id==='civic')return`<g class="civic-wreath" style="color:${palette.accent}"><path d="M18 151C5 116 8 80 28 51M102 151c13-35 10-71-10-100"/><path d="m20 130-14-10m18-7-16-8m21-9-16-6m75 40 14-10m-18-7 16-8m-21-9 16-6"/></g><path class="mural-crown" d="M35 29V15h10v8h10v-8h10v8h10v-8h10v14Z"/>`;if(school.id==='knightly')return`<path class="mantle mantle-knightly" d="M25 39C8 67 10 128 24 159L42 128L60 170L78 128L96 159C110 128 112 67 95 39L77 55L60 31L43 55Z"/><path class="mantle-lining" d="M34 50C24 79 27 117 32 136L46 114L60 151L74 114L88 136C93 117 96 79 86 50L70 62L60 45L50 62Z"/>`;return`<path class="mantle mantle-northern" d="M29 34C15 62 16 120 25 160L43 133L60 179L77 133L95 160C104 120 105 62 91 34L76 51L60 27L44 51Z"/><path class="fur-edge" d="M30 42c6 4 10-5 16 0 6 5 9-6 15 0 6 5 10-5 16 0 6 5 9-5 14 0"/>`;}
function commandMarkup(doctrine,identity){const{palette,school}=identity;if(doctrine.command==='crown')return useCharge('crown',{x:39,y:school.id==='civic'?18:3,scale:.35},palette.metal,palette.ink,'external-mark command-crown');if(doctrine.command==='helmet')return`${useCharge('helmet',{x:38,y:2,scale:.37},'#8e8b82',palette.ink,'external-mark command-helmet')}<path class="crest-plume" style="fill:${palette.accent}" d="M52 9C61-8 80-5 86 8C73 4 65 10 59 22Z"/>`;if(doctrine.command==='chain')return`<ellipse class="achievement-chain" cx="60" cy="106" rx="49" ry="62" style="stroke:${palette.metal}"/>`;return'';}
function achievementMarkup(doctrine,id='coat',compact=false){const identity=heraldicIdentity(doctrine),{palette,shield,composition,school}=identity,clip=`${id}-clip`,gradient=`${id}-field`;const main=doctrine.main?useCharge(doctrine.main,composition.main,palette.main,palette.ink,'charge-main'):'';const secondary=doctrine.secondary?composition.secondary.map(p=>useCharge(doctrine.secondary,p,palette.accent,palette.metal,'charge-secondary')).join(''):'';const motto=doctrine.motto?(MOTTOS[doctrine.motto]?.name||''):'—';return`<svg class="achievement achievement-${school.id}" data-school="${school.id}" viewBox="0 0 120 190" role="img" aria-label="${doctrineName(doctrine)}"><defs><clipPath id="${clip}"><path d="${shield.path}"/></clipPath><linearGradient id="${gradient}" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${palette.field}"/><stop offset=".5" stop-color="${palette.field}"/><stop offset="1" stop-color="${palette.ink}" stop-opacity=".28"/></linearGradient><pattern id="${id}-grain" width="7" height="7" patternUnits="userSpaceOnUse"><path d="M0 1h7M2 0v7" stroke="rgba(255,255,255,.055)" stroke-width=".45"/></pattern></defs>${schoolOrnament(identity,compact)}${compact?'':commandMarkup(doctrine,identity)}<path class="achievement-shadow" d="${shield.path}" transform="translate(0 2)"/><path class="achievement-shield" fill="url(#${gradient})" d="${shield.path}"/><path class="achievement-grain" fill="url(#${id}-grain)" d="${shield.path}"/>${ordinaryMarkup(doctrine.ordinary,palette.metal,clip)}<path class="ordinary-highlight" d="${shield.path}" clip-path="url(#${clip})"/><path class="achievement-inner" d="${shield.inner}"/>${main}${secondary}<path class="achievement-edge" d="${shield.path}" style="stroke:${palette.metal}"/>${compact?'':`<path class="motto-scroll" style="fill:${palette.metal};stroke:${palette.ink}" d="M11 158C31 153 89 153 109 158L101 181C81 176 39 176 19 181Z"/><text class="motto-copy" x="60" y="171" text-anchor="middle">${motto}</text>`}</svg>`;}
function layerLabel(slot){return{field:'Поле',ordinary:'Строй',main:'Ратники',secondary:'Лучники',command:'Командование',motto:'Девиз'}[slot];}
function renderLedger(node,doctrine){node.innerHTML=doctrineLayers(doctrine).map(({slot,definition})=>`<div class="layer-row${definition?'':' is-empty'}"><span>${layerLabel(slot)}</span><div><strong>${definition?.name||'Не начертано'}</strong><small>${definition?.summary||'Этот слой откроется после следующего боя.'}</small></div></div>`).join('');}
function renderMenu(){$('#soundButton').textContent=`Звук: ${settings.sound?'вкл':'выкл'}`;$('#continueButton').hidden=!campaign||campaign.completed;if(campaign&&!campaign.completed)$('#continueCaption').textContent=`Битва ${campaign.battleIndex+1} из ${BATTLE_COUNT}`;const d=campaign?.doctrine||{field:'gules',ordinary:'bend',main:'lion',secondary:'eagle',command:'helmet',motto:'breach'};$('#menuHeraldry').innerHTML=achievementMarkup(d,'menu',true);}
function renderDoctrine(){campaign=prepareBattle(campaign);persist();const ps=HERALDIC_SCHOOLS[schoolForDoctrine(campaign.doctrine)],es=HERALDIC_SCHOOLS[schoolForDoctrine(campaign.currentEnemy)];$('#battleIndexLabel').textContent=`БИТВА ${roman(campaign.battleIndex+1)} ИЗ ${roman(BATTLE_COUNT)}`;$('#integrityMarks').textContent=`${'◆'.repeat(campaign.integrity)}${'◇'.repeat(3-campaign.integrity)}`;$('#playerDoctrineName').textContent=doctrineName(campaign.doctrine);$('#enemyDoctrineName').textContent=doctrineName(campaign.currentEnemy);$('#playerSchoolName').textContent=ps.name;$('#enemySchoolName').textContent=es.name;$('#playerAchievement').innerHTML=achievementMarkup(campaign.doctrine,'player');$('#enemyAchievement').innerHTML=achievementMarkup(campaign.currentEnemy,'enemy');renderLedger($('#playerLedger'),campaign.doctrine);renderLedger($('#enemyLedger'),campaign.currentEnemy);}
function renderSetup(){$('#fieldChoices').innerHTML=Object.values(FIELDS).map(item=>{const l=liveryForDoctrine({field:item.id,ordinary:setup.ordinary||'pale'});return`<button class="doctrine-choice${setup.field===item.id?' is-selected':''}" data-field="${item.id}"><i class="tincture-swatch" style="--field:${l.primary};--metal:${l.metal};--accent:${l.accent}"></i><strong>${item.name}</strong><span>${item.summary}</span></button>`;}).join('');$('#ordinaryChoices').innerHTML=Object.values(ORDINARIES).map(item=>{const school=HERALDIC_SCHOOLS[schoolForDoctrine({ordinary:item.id})];return`<button class="doctrine-choice${setup.ordinary===item.id?' is-selected':''}" data-ordinary-choice="${item.id}"><i class="ordinary-preview" data-ordinary="${item.id}" data-school="${school.id}"></i><em>${school.short}</em><strong>${item.name}</strong><span>${item.summary}</span></button>`;}).join('');$('#sealSetupButton').disabled=!(setup.field&&setup.ordinary);$$('[data-field]').forEach(b=>b.addEventListener('click',()=>{setup.field=b.dataset.field;sound('tap');renderSetup();}));$$('[data-ordinary-choice]').forEach(b=>b.addEventListener('click',()=>{setup.ordinary=b.dataset.ordinaryChoice;sound('tap');renderSetup();}));}
function startNewSetup(){setup={field:null,ordinary:null};renderSetup();openDialog(dialogs.setup);}
function sealSetup(){if(!setup.field||!setup.ordinary)return;campaign=createCampaign(setup.field,setup.ordinary,Date.now());stats.runs++;persist();closeDialog(dialogs.setup);renderDoctrine();showScreen('doctrine');sound('seal');vibrate(15);}
function continueCampaign(){if(!campaign)return;if(campaign.phase==='reward'&&campaign.offers?.length){renderRewards();openDialog(dialogs.reward);}else if(campaign.phase==='ending'){renderEnding();openDialog(dialogs.ending);}else{renderDoctrine();showScreen('doctrine');}}

function startBattle(replay=false){if(!replay){campaign=prepareBattle(campaign);persist();}battleState=createBattleState(campaign.doctrine,campaign.currentEnemy,campaign.currentSeed);battleSummary=null;battleRunning=true;paused=false;speed=1;accumulator=0;lastEventCount=0;$$('.speed-controls button').forEach(b=>b.classList.toggle('is-active',b.dataset.speed==='1'));$('#hudPlayerShield').innerHTML=achievementMarkup(campaign.doctrine,'hud-player',true);$('#hudEnemyShield').innerHTML=achievementMarkup(campaign.currentEnemy,'hud-enemy',true);showScreen('battle');sound('horn');requestAnimationFrame(()=>{resizeCanvas();lastFrame=performance.now();requestAnimationFrame(frame);});}
function resizeCanvas(){const rect=canvas.getBoundingClientRect(),dpr=Math.min(2,devicePixelRatio||1);canvas.width=Math.max(1,Math.floor(rect.width*dpr));canvas.height=Math.max(1,Math.floor(rect.height*dpr));ctx.setTransform(dpr*rect.width/1000,0,0,dpr*rect.height/600,0,0);}
function frame(now){if(!battleRunning)return;const elapsed=Math.min(.08,(now-lastFrame)/1000);lastFrame=now;if(!paused){accumulator+=elapsed*speed;while(accumulator>=.05&&battleState.status==='running'){stepBattle(battleState,.05);accumulator-=.05;}}drawBattle();updateBattleHud();if(battleState.events.length>lastEventCount){const event=battleState.events.at(-1);lastEventCount=battleState.events.length;if(event.rule!=='deployment')flashRule(event.text);}if(battleState.status==='finished'){battleRunning=false;battleSummary=summarizeBattle(battleState);setTimeout(showResult,500);return;}requestAnimationFrame(frame);}
function flashRule(text){const node=$('#ruleFlash');node.textContent=text;node.classList.add('is-visible');clearTimeout(flashTimer);flashTimer=setTimeout(()=>node.classList.remove('is-visible'),1250);}
function updateBattleHud(){$('#battleClock').textContent=fmtTime(battleState.time);$('#playerFormation').textContent=`${4-battleState.player.brokenCount} / 4`;$('#enemyFormation').textContent=`${4-battleState.enemy.brokenCount} / 4`;}

function drawField(){const w=1000,h=600;const sky=ctx.createLinearGradient(0,0,0,h);sky.addColorStop(0,'#71816a');sky.addColorStop(.24,'#5a6b51');sky.addColorStop(1,'#2a382d');ctx.fillStyle=sky;ctx.fillRect(-20,-20,w+40,h+40);ctx.fillStyle='rgba(28,38,27,.28)';ctx.beginPath();ctx.moveTo(-20,108);ctx.bezierCurveTo(170,50,340,120,500,74);ctx.bezierCurveTo(690,20,830,116,1020,58);ctx.lineTo(1020,-20);ctx.lineTo(-20,-20);ctx.fill();ctx.fillStyle='rgba(190,172,119,.08)';ctx.beginPath();ctx.ellipse(500,320,125,295,0,0,Math.PI*2);ctx.fill();for(let y=80;y<580;y+=62){ctx.strokeStyle='rgba(225,209,161,.075)';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(-20,y);ctx.bezierCurveTo(250,y-18,720,y+16,1020,y-5);ctx.stroke();}for(let i=0;i<70;i++){const x=(i*137)%1000,y=95+((i*83)%490);ctx.strokeStyle=i%3?'rgba(21,34,22,.28)':'rgba(220,199,137,.14)';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+((i%5)-2)*1.8,y-4-(i%4));ctx.stroke();}}
function drawTinyEmblem(id,x,y,size,color){ctx.save();ctx.translate(x,y);ctx.fillStyle=color;ctx.strokeStyle=color;ctx.lineWidth=Math.max(1,size*.12);if(id==='lion'){ctx.beginPath();ctx.arc(0,0,size*.27,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(-size*.2,size*.15);ctx.lineTo(-size*.42,size*.42);ctx.moveTo(size*.18,size*.15);ctx.lineTo(size*.42,size*.4);ctx.stroke();}else if(id==='boar'){ctx.beginPath();ctx.ellipse(0,0,size*.38,size*.24,0,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(size*.28,-size*.05);ctx.lineTo(size*.48,-size*.18);ctx.lineTo(size*.37,size*.08);ctx.fill();}else if(id==='tower'){ctx.fillRect(-size*.32,-size*.3,size*.64,size*.65);for(let i=-1;i<=1;i++)ctx.fillRect(i*size*.23-size*.08,-size*.45,size*.16,size*.18);}else if(id==='stag'){ctx.beginPath();ctx.arc(0,size*.05,size*.2,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(-size*.12,-size*.12);ctx.lineTo(-size*.32,-size*.43);ctx.moveTo(size*.12,-size*.12);ctx.lineTo(size*.32,-size*.43);ctx.stroke();}else if(id==='eagle'){ctx.beginPath();ctx.moveTo(0,size*.3);ctx.lineTo(-size*.46,-size*.25);ctx.lineTo(-size*.08,-size*.08);ctx.lineTo(0,-size*.38);ctx.lineTo(size*.08,-size*.08);ctx.lineTo(size*.46,-size*.25);ctx.closePath();ctx.fill();}else if(id==='rose'){for(let i=0;i<5;i++){ctx.save();ctx.rotate(i*Math.PI*2/5);ctx.beginPath();ctx.ellipse(0,-size*.24,size*.15,size*.28,0,0,Math.PI*2);ctx.fill();ctx.restore();}}else if(id==='key'){ctx.beginPath();ctx.arc(-size*.18,-size*.16,size*.16,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(-size*.05,-size*.04);ctx.lineTo(size*.35,size*.36);ctx.moveTo(size*.2,size*.2);ctx.lineTo(size*.34,size*.07);ctx.stroke();}else if(id==='sun'){ctx.beginPath();ctx.arc(0,0,size*.24,0,Math.PI*2);ctx.fill();for(let i=0;i<8;i++){ctx.save();ctx.rotate(i*Math.PI/4);ctx.beginPath();ctx.moveTo(0,-size*.32);ctx.lineTo(0,-size*.5);ctx.stroke();ctx.restore();}}ctx.restore();}
function drawBanner(army,doctrine){const l=liveryForDoctrine(doctrine),dir=army.side==='player'?1:-1,wave=Math.sin(battleState.time*2.3+army.banner.y*.01)*4;ctx.save();ctx.translate(army.banner.x,army.banner.y);ctx.strokeStyle='#5b3b1b';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(0,48);ctx.lineTo(0,-62);ctx.stroke();ctx.fillStyle=l.primary;ctx.beginPath();ctx.moveTo(0,-57);ctx.quadraticCurveTo(dir*29,-63+wave,dir*67,-47);ctx.lineTo(dir*61,-5);ctx.quadraticCurveTo(dir*30,-20-wave*.4,0,-15);ctx.closePath();ctx.fill();ctx.strokeStyle=l.metal;ctx.lineWidth=3;ctx.stroke();ctx.fillStyle=l.metal;if(doctrine.ordinary==='pale')ctx.fillRect(dir*27,-55,dir*14,43);else if(doctrine.ordinary==='fess')ctx.fillRect(Math.min(dir*62,0),-39,62,11);else if(doctrine.ordinary==='bend'){ctx.save();ctx.translate(dir*32,-32);ctx.rotate(-dir*.55);ctx.fillRect(-5,-30,10,60);ctx.restore();}else{ctx.strokeStyle=l.metal;ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(dir*13,-18);ctx.lineTo(dir*32,-42);ctx.lineTo(dir*51,-18);ctx.stroke();}drawTinyEmblem(doctrine.main,dir*32,-33,22,l.emblem);ctx.fillStyle='rgba(0,0,0,.24)';ctx.fillRect(-30,50,60,8);ctx.restore();if(army.banner.capture>0){ctx.fillStyle=l.metal;ctx.fillRect(army.banner.x-27,army.banner.y+62,54*(army.banner.capture/3),5);}}
function warriorList(){const list=[];for(const army of[battleState.player,battleState.enemy])for(const squad of[...army.archers,...army.infantry])for(const member of squad.members)list.push({army,squad,member});return list;}
function drawFallen(member,squad,doctrine){if(member.fallenAt===null)return;const l=liveryForDoctrine(doctrine),dir=member.side==='player'?1:-1,fade=Math.max(.28,1-(battleState.time-member.fallenAt)/18);ctx.save();ctx.globalAlpha=fade;ctx.translate(member.x,member.y);ctx.rotate(dir*Math.PI*.43);ctx.fillStyle='rgba(0,0,0,.22)';ctx.beginPath();ctx.ellipse(0,5,11,4,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=l.primary;ctx.fillRect(-7,-3,14,7);ctx.fillStyle=l.metal;ctx.fillRect(1,-5,8,7);ctx.restore();}
function drawWarrior(member,squad,doctrine){if(member.state==='fallen')return;const l=liveryForDoctrine(doctrine),dir=member.facing||(member.side==='player'?1:-1),moving=Math.hypot(member.vx,member.vy),bob=moving>.8?Math.sin(member.phase)*1.35:0,lean=Math.max(-.16,Math.min(.16,member.vy*.012));ctx.save();ctx.translate(member.x,member.y+bob);ctx.rotate(lean);ctx.scale(dir,1);ctx.globalAlpha=.42+.58*member.morale;ctx.fillStyle='rgba(0,0,0,.27)';ctx.beginPath();ctx.ellipse(0,10,8.5,3.7,0,0,Math.PI*2);ctx.fill();if(moving>5){ctx.strokeStyle='rgba(214,197,145,.14)';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(-dir*6,10);ctx.lineTo(-dir*(10+moving*.12),11);ctx.stroke();}ctx.fillStyle=member.hitFlash>0?'#fff4d2':l.primary;ctx.beginPath();ctx.moveTo(-4,-6);ctx.lineTo(5,-6);ctx.lineTo(6,8);ctx.lineTo(-5,8);ctx.closePath();ctx.fill();ctx.fillStyle=l.accent;ctx.fillRect(-4,-6,9,3);ctx.fillStyle='#c79f73';ctx.beginPath();ctx.arc(0,-10,4.2,0,Math.PI*2);ctx.fill();ctx.fillStyle=squad.index%2?l.metal:l.accent;ctx.beginPath();ctx.arc(0,-11,4.6,Math.PI,Math.PI*2);ctx.fill();if(member.type==='infantry'){const attack=member.state==='fighting'?-.55:0;ctx.save();ctx.rotate(attack);ctx.strokeStyle='#51402c';ctx.lineWidth=1.8;ctx.beginPath();ctx.moveTo(-2,-1);ctx.lineTo(14,-14);ctx.stroke();ctx.restore();ctx.fillStyle=l.metal;ctx.beginPath();ctx.moveTo(1,-5);ctx.quadraticCurveTo(11,-3,9,9);ctx.lineTo(2,8);ctx.closePath();ctx.fill();ctx.strokeStyle=l.ink;ctx.lineWidth=.75;ctx.stroke();drawTinyEmblem(doctrine.main,5,2,4.8,l.emblem);}else{ctx.fillStyle=l.accent;ctx.beginPath();ctx.arc(0,-10,5,Math.PI,Math.PI*2);ctx.fill();ctx.strokeStyle='#4b3722';ctx.lineWidth=1.6;ctx.beginPath();ctx.arc(3,-1,7.4,-Math.PI/2,Math.PI/2);ctx.stroke();ctx.beginPath();ctx.moveTo(3,-8.4);ctx.lineTo(3,6.4);ctx.stroke();ctx.strokeStyle=l.metal;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(-5,4);ctx.lineTo(-9,-5);ctx.stroke();drawTinyEmblem(doctrine.secondary,-2,3,4.5,l.metal);}if(squad.leader&&member.index===0){ctx.fillStyle=l.metal;ctx.beginPath();ctx.moveTo(-4,-15);ctx.lineTo(0,-23);ctx.lineTo(4,-15);ctx.fill();}if(member.state==='rout'){ctx.strokeStyle='rgba(244,231,192,.8)';ctx.setLineDash([2,3]);ctx.beginPath();ctx.arc(0,0,12,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);}ctx.restore();}
function drawArrow(arrow){const p=1-Math.max(0,arrow.life)/arrow.duration,x=arrow.x1+(arrow.x2-arrow.x1)*p,y=arrow.y1+(arrow.y2-arrow.y1)*p-Math.sin(p*Math.PI)*28;const p0=Math.max(0,p-.08),x0=arrow.x1+(arrow.x2-arrow.x1)*p0,y0=arrow.y1+(arrow.y2-arrow.y1)*p0-Math.sin(p0*Math.PI)*28;ctx.save();ctx.strokeStyle='#e2cf99';ctx.lineWidth=1.4;ctx.beginPath();ctx.moveTo(x0,y0);ctx.lineTo(x,y);ctx.stroke();ctx.restore();}
function drawEffects(){for(const e of battleState.effects){ctx.save();ctx.globalAlpha=Math.min(1,e.life*4);if(e.type==='hit'||e.type==='arrow-hit'){ctx.translate(e.x,e.y);ctx.strokeStyle=e.type==='arrow-hit'?'#ead39c':'#fff0bd';ctx.lineWidth=1.5;for(let i=0;i<4;i++){ctx.rotate(Math.PI/2);ctx.beginPath();ctx.moveTo(3,0);ctx.lineTo(8+e.life*8,0);ctx.stroke();}}else{ctx.fillStyle='rgba(212,191,136,.18)';ctx.beginPath();ctx.arc(e.x,e.y,12*(1.3-e.life),0,Math.PI*2);ctx.fill();}ctx.restore();}}
function drawSquadIntent(squad,doctrine){if(squad.broken||squad.type==='archer')return;const l=liveryForDoctrine(doctrine);ctx.save();ctx.globalAlpha=.13;ctx.strokeStyle=l.metal;ctx.setLineDash([3,5]);ctx.lineWidth=1;ctx.beginPath();ctx.arc(squad.formX,squad.formY,22,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.restore();}
function drawBattle(){const shake=battleState.impact*4,angle=battleState.time*31.7;ctx.clearRect(0,0,1000,600);ctx.save();ctx.translate(Math.sin(angle)*shake,Math.cos(angle*.77)*shake*.55);drawField();for(const army of[battleState.player,battleState.enemy])drawBanner(army,army.doctrine);for(const army of[battleState.player,battleState.enemy])for(const squad of army.infantry)drawSquadIntent(squad,army.doctrine);const units=warriorList();for(const unit of units.filter(u=>u.member.state==='fallen').sort((a,b)=>a.member.y-b.member.y))drawFallen(unit.member,unit.squad,unit.army.doctrine);for(const arrow of battleState.arrows)drawArrow(arrow);for(const unit of units.filter(u=>u.member.state!=='fallen').sort((a,b)=>a.member.y-b.member.y))drawWarrior(unit.member,unit.squad,unit.army.doctrine);drawEffects();ctx.restore();}

function showResult(){const won=battleSummary.winner==='player';$('#resultEyebrow').textContent=`БИТВА ${roman(campaign.battleIndex+1)} ЗАВЕРШЕНА`;$('#resultTitle').textContent=won?'Вражеское знамя обрушено':'Твой строй разрушен';$('#resultMeasures').innerHTML=`<div><span>Время</span><b>${fmtTime(battleSummary.duration)}</b></div><div><span>Твои воины</span><b>${battleSummary.playerRemaining}/48</b></div><div><span>Вражеские</span><b>${battleSummary.enemyRemaining}/48</b></div><div><span>Итог</span><b>${won?'Победа':'Поражение'}</b></div>`;$('#decisiveEvents').innerHTML=(battleSummary.decisive.length?battleSummary.decisive:[{time:0,text:'Бой решён общим движением строя.'}]).map(e=>`<article><time>${fmtTime(e.time)} · ${e.side==='player'?'ТВОИ':e.side==='enemy'?'ВРАГ':'ПОЛЕ'}</time><span>${e.text}</span></article>`).join('');$('#continueResultButton').querySelector('small').textContent=campaign.battleIndex===BATTLE_COUNT-1?'Завершить поход':'Изменить доктрину';openDialog(dialogs.result);sound(won?'win':'lose');vibrate(won?[20,40,20]:80);}
function continueAfterResult(){campaign=recordBattle(campaign,battleSummary);if(battleSummary.winner==='player')stats.victories++;persist();closeDialog(dialogs.result);if(campaign.completed){renderEnding();openDialog(dialogs.ending);return;}renderRewards();openDialog(dialogs.reward);}
function rewardHeading(slot){return{main:['ГЛАВНАЯ ФИГУРА','Как будут действовать ратники?'],secondary:['ВТОРИЧНАЯ ФИГУРА','Как лучники свяжутся со строем?'],command:['ВНЕШНИЙ ЭЛЕМЕНТ','Кто задаёт высший порядок?'],motto:['ДЕВИЗ','Какое правило один раз превысит остальные?'],revision:['ПЕРЕСМОТР УСТАВА','Что изменить перед последним полем?']}[slot]||['НОВЫЙ СЛОЙ','Как изменится армия?'];}
function principleCopy(p){return{pressure:'Создаёт последовательное давление, но делает замысел заметнее.',adaptation:'Лучше реагирует на бой, но чаще прерывает начатое.',cohesion:'Связывает части армии, рискуя сделать их слишком зависимыми.',reserve:'Сохраняет решение до кризиса, ослабляя ранний этап.',breach:'Превращает разрыв в глубокий успех, но открывает прорвавшихся.',recovery:'Возвращает потерянную организацию ценой темпа.'}[p]||'Меняет решение отрядов, а не их характеристики.';}
function rewardPreview(offer,index){return achievementMarkup({...campaign.doctrine,[offer.slot]:offer.id},`reward-${campaign.battleIndex}-${index}`,true);}
function renderRewards(){const offers=campaign.offers||[],first=offers[0],[eyebrow,title]=rewardHeading(first?.revision?'revision':first?.slot);$('#rewardEyebrow').textContent=eyebrow;$('#rewardTitle').textContent=title;$('#rewardGrid').innerHTML=offers.map((offer,index)=>`<button class="reward-card" data-offer="${index}"><div class="reward-card-preview">${rewardPreview(offer,index)}</div><div class="reward-card-copy"><em>${offer.revision?`Заменит: ${CATALOGS[offer.slot][offer.replaces]?.name}`:layerLabel(offer.slot)}</em><strong>${offer.definition.name}</strong><p>${offer.definition.summary}</p><small>${offer.definition.detail||principleCopy(offer.definition.principle)}</small></div></button>`).join('');$$('.reward-card').forEach(b=>b.addEventListener('click',()=>chooseReward(Number(b.dataset.offer))));}
function chooseReward(index){const offer=campaign.offers[index];campaign=applyOffer(campaign,offer);persist();closeDialog(dialogs.reward);renderDoctrine();showScreen('doctrine');sound('seal');vibrate(18);}
function renderEnding(){const won=campaign.integrity>0;$('#endingAchievement').innerHTML=achievementMarkup(campaign.doctrine,'ending');$('#endingTitle').textContent=won?`Доктрина выиграла ${campaign.victories} из ${BATTLE_COUNT}`:'Знамя рода не пережило поход';$('#endingCopy').textContent=`Сохранено целостности: ${campaign.integrity} из 3. Победы: ${campaign.victories}. Геральдическая школа: ${HERALDIC_SCHOOLS[schoolForDoctrine(campaign.doctrine)].name}.`;}
function leaveBattle(){battleRunning=false;paused=false;showScreen('doctrine');renderDoctrine();}

$('#newButton').addEventListener('click',startNewSetup);$('#continueButton').addEventListener('click',continueCampaign);$('#sealSetupButton').addEventListener('click',sealSetup);$('#rulesButton').addEventListener('click',()=>openDialog(dialogs.rules));$('#codexButton').addEventListener('click',()=>openDialog(dialogs.rules));$('#doctrineMenuButton').addEventListener('click',()=>{showScreen('menu');renderMenu();});$('#startBattleButton').addEventListener('click',()=>startBattle(false));$('#leaveBattleButton').addEventListener('click',leaveBattle);$('#pauseSimulationButton').addEventListener('click',()=>{paused=!paused;$('#pauseSimulationButton').textContent=paused?'Продолжить':'Пауза';});$('#replayButton').addEventListener('click',()=>{closeDialog(dialogs.result);startBattle(true);});$('#continueResultButton').addEventListener('click',continueAfterResult);$('#endingMenuButton').addEventListener('click',()=>{closeDialog(dialogs.ending);campaign=null;persist();renderMenu();showScreen('menu');});$('#endingRestartButton').addEventListener('click',()=>{closeDialog(dialogs.ending);startNewSetup();});$('#soundButton').addEventListener('click',()=>{settings.sound=!settings.sound;persist();renderMenu();sound('tap');});$$('[data-close-dialog]').forEach(b=>b.addEventListener('click',()=>closeDialog(b.closest('dialog'))));$$('[data-speed]').forEach(b=>b.addEventListener('click',()=>{speed=Number(b.dataset.speed);$$('[data-speed]').forEach(other=>other.classList.toggle('is-active',other===b));sound('tap');}));window.addEventListener('resize',()=>{if(screens.battle.classList.contains('is-active'))resizeCanvas();});window.addEventListener('pagehide',persist);document.addEventListener('visibilitychange',()=>{if(document.hidden)persist();});
createWorkshopMode({appName:'БЛАЗОН: Доктрина',version:'4.0.0',cachePrefix:'blazon-',storageNamespace:'pocket-works:blazon',onReset(){store.reset();campaign=null;settings=store.get('settings');stats=store.get('stats');renderMenu();showScreen('menu');}});watchConnectivity(online=>document.documentElement.dataset.network=online?'online':'offline');if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});renderMenu();showScreen('menu');
