(()=>{
const $=s=>document.querySelector(s),founders={lion:['Лев','Два ближайших отряда совместно уничтожают одну цель.'],boar:['Вепрь','Первый отряд использует пролом и идёт в глубину.'],tower:['Башня','Удержанная позиция становится точкой повторного сбора.'],stag:['Олень','Уступающий отряд отходит к союзнику и возвращается вместе с ним.']},schools={imperial:['Имперская','Осевая симметрия и властная центральная фигура.'],civic:['Городская','Строгая геометрия и повторяющийся ритм.'],knightly:['Рыцарская','Крупная фигура и турнирный наклон.'],northern:['Северная','Узкий щит, пустоты и суровая вертикаль.']},evolved=new Set(['lion-bifurcated','lion-crowned','lion-regardant','boar-armed','boar-coupled','boar-blooded','tower-gate','tower-triple','tower-burning','stag-courant','stag-crowned','stag-regardant']);
globalThis.__blazonFounder=null;globalThis.__blazonSchool=null;
const css=document.createElement('link');css.rel='stylesheet';css.href='./armorial-progression.css?v=5.0.0';document.head.append(css);
function setup(){const dialog=$('#setupDialog'),seal=$('#sealSetupButton');if(!dialog||!seal)return;dialog.querySelector('h2').textContent='Задай поле, строй, основателя и школу';if(!$('#mainChoices')){const s=document.createElement('section');s.innerHTML='<h3>Основатель · инстинкт ратников с первого боя</h3><div class="choice-grid founder-grid" id="mainChoices"></div>';seal.before(s)}if(!$('#schoolChoices')){const s=document.createElement('section');s.innerHTML='<h3>Школа · только облик, не механика</h3><div class="choice-grid school-grid" id="schoolChoices"></div>';seal.before(s)}const h=$('#ordinaryChoices')?.previousElementSibling;if(h)h.textContent='Ординарий · геометрия строя';seal.querySelector('span').textContent='Скрепить первый устав';seal.querySelector('small').textContent='Все четыре решения обязательны'}
function founderCards(){const root=$('#mainChoices');if(!root)return;const key=globalThis.__blazonFounder||'-';if(root.dataset.key===key&&root.children.length===4)return;root.dataset.key=key;root.innerHTML=Object.entries(founders).map(([id,[name,copy]])=>`<button type="button" class="doctrine-choice founder-choice${key===id?' is-selected':''}" data-v5-founder="${id}"><i class="founder-mark"><svg viewBox="0 0 120 120"><use href="#charge-${id}"></use></svg></i><strong>${name}</strong><span>${copy}</span></button>`).join('')}
function schoolCards(){const root=$('#schoolChoices');if(!root)return;const key=globalThis.__blazonSchool||'-';if(root.dataset.key===key&&root.children.length===4)return;root.dataset.key=key;root.innerHTML=Object.entries(schools).map(([id,[name,copy]])=>`<button type="button" class="doctrine-choice school-choice${key===id?' is-selected':''}" data-v5-school="${id}"><i class="school-shield school-shield-${id}"></i><strong>${name}</strong><span>${copy}</span></button>`).join('')}
function seal(){const b=$('#sealSetupButton');if(b)b.disabled=!($('.field-grid .is-selected')&&$('.ordinary-grid .is-selected')&&globalThis.__blazonFounder&&globalThis.__blazonSchool)}
function symbols(){const defs=$('.symbol-library defs');if(!defs||$('#charge-lion-crowned'))return;const g=document.createElementNS('http://www.w3.org/2000/svg','g');g.innerHTML=`<symbol id="charge-lion-bifurcated" viewBox="0 0 120 120"><use href="#charge-lion"/><path d="M43 48C20 42 8 29 12 10c12 5 23 13 28 26" fill="none" stroke="currentColor" stroke-width="7"/></symbol><symbol id="charge-lion-crowned" viewBox="0 0 120 120"><use href="#charge-lion"/><path d="m70 16 7-12 8 9 9-9 5 14-6 8H76Z" fill="currentColor"/></symbol><symbol id="charge-lion-regardant" viewBox="0 0 120 120"><g transform="translate(120) scale(-1 1)"><use href="#charge-lion"/></g></symbol><symbol id="charge-boar-armed" viewBox="0 0 120 120"><use href="#charge-boar"/><path d="M95 64c10 8 18 6 23-3-2 15-13 23-27 17" fill="none" stroke="currentColor" stroke-width="6"/></symbol><symbol id="charge-boar-coupled" viewBox="0 0 120 120"><g transform="translate(-9 8) scale(.82)"><use href="#charge-boar"/></g><g transform="translate(53 40) scale(.48)"><use href="#charge-boar"/></g></symbol><symbol id="charge-boar-blooded" viewBox="0 0 120 120"><use href="#charge-boar"/><path d="M42 29 69 96M57 22l25 62" stroke="var(--detail,#1c1814)" stroke-width="6"/></symbol><symbol id="charge-tower-gate" viewBox="0 0 120 120"><use href="#charge-tower"/><path d="M47 107V76c0-17 26-17 26 0v31" fill="none" stroke="var(--detail,#1c1814)" stroke-width="8"/></symbol><symbol id="charge-tower-triple" viewBox="0 0 120 120"><g transform="translate(2 42) scale(.48)"><use href="#charge-tower"/></g><g transform="translate(34 5) scale(.48)"><use href="#charge-tower"/></g><g transform="translate(66 42) scale(.48)"><use href="#charge-tower"/></g></symbol><symbol id="charge-tower-burning" viewBox="0 0 120 120"><use href="#charge-tower"/><path d="M30 36c-11-17 5-24 1-35 16 10 18 21 11 35m21-3C53 16 69 10 67 0c16 12 16 23 8 36m18 0C82 20 98 14 95 3c17 12 16 24 8 35" fill="currentColor"/></symbol><symbol id="charge-stag-courant" viewBox="0 0 120 120"><g transform="translate(0 8) rotate(-7 60 60)"><use href="#charge-stag"/></g><path d="M18 104h34m9 7h42" stroke="currentColor" stroke-width="5"/></symbol><symbol id="charge-stag-crowned" viewBox="0 0 120 120"><use href="#charge-stag"/><path d="m76 37 6-12 8 8 8-9 5 14-6 7H82Z" fill="currentColor"/></symbol><symbol id="charge-stag-regardant" viewBox="0 0 120 120"><g transform="translate(120) scale(-1 1)"><use href="#charge-stag"/></g></symbol>`;while(g.firstChild)defs.append(g.firstChild)}
function decorate(){for(const svg of document.querySelectorAll('svg.achievement')){const id=svg.querySelector('.charge-main use')?.getAttribute('href')?.replace('#charge-',''),done=evolved.has(id);svg.classList.toggle('is-evolved',done);for(const n of svg.querySelectorAll('.mantle,.mantle-lining,.civic-wreath,.mural-crown,.fur-edge'))n.style.display=done?'':'none';const motto=svg.querySelector('.motto-copy');if(motto?.textContent.trim()==='—'){motto.style.display='none';svg.querySelector('.motto-scroll')?.style.setProperty('display','none')}}if($('#rewardGrid svg.is-evolved')){$('#rewardEyebrow').textContent='ЭВОЛЮЦИЯ ФИГУРЫ';$('#rewardTitle').textContent='Во что превратится основатель рода?'}}
let observer,pending=false;function watch(){observer?.observe(document.body,{childList:true,subtree:true})}function sync(){if(pending)return;pending=true;queueMicrotask(()=>{pending=false;observer?.disconnect();setup();founderCards();schoolCards();seal();decorate();watch()})}
symbols();sync();observer=new MutationObserver(sync);watch();
document.addEventListener('click',e=>{const f=e.target.closest('[data-v5-founder]'),s=e.target.closest('[data-v5-school]');if(f){globalThis.__blazonFounder=f.dataset.v5Founder;founderCards();seal()}if(s){globalThis.__blazonSchool=s.dataset.v5School;schoolCards();seal()}if(e.target.closest('#newButton')){globalThis.__blazonFounder=null;globalThis.__blazonSchool=null;sync()}if(e.target.closest('#sealSetupButton')&&(!globalThis.__blazonFounder||!globalThis.__blazonSchool)){e.preventDefault();e.stopImmediatePropagation();seal()}if(e.target.closest('[data-field],[data-ordinary-choice]'))queueMicrotask(seal)},true);
const footer=$('.menu-screen footer');if(footer)footer.textContent='v5.0 · armorial progression · растущий герб';
})();
