(()=>{
  const founders=[
    {id:'lion',name:'Лев',copy:'Два ближайших отряда совместно уничтожают одну цель.'},
    {id:'boar',name:'Вепрь',copy:'Первый отряд использует физический пролом и идёт в глубину.'},
    {id:'tower',name:'Башня',copy:'Удержанная позиция становится точкой повторного сбора.'},
    {id:'stag',name:'Олень',copy:'Уступающий отряд отходит к союзнику и возвращается вместе с ним.'}
  ];
  const schools=[
    {id:'imperial',name:'Имперская',copy:'Осевая симметрия и властная центральная фигура.'},
    {id:'civic',name:'Городская',copy:'Строгая геометрия и ритм повторяющихся знаков.'},
    {id:'knightly',name:'Рыцарская',copy:'Крупная фигура и турнирный наклон.'},
    {id:'northern',name:'Северная',copy:'Узкий щит, пустоты и суровая вертикаль.'}
  ];
  const evolutionIds=new Set(['lion-bifurcated','lion-crowned','lion-regardant','boar-armed','boar-coupled','boar-blooded','tower-gate','tower-triple','tower-burning','stag-courant','stag-crowned','stag-regardant']);
  globalThis.__blazonFounder=null;globalThis.__blazonSchool=null;
  const $=selector=>document.querySelector(selector);
  const link=document.createElement('link');link.rel='stylesheet';link.href='./armorial-progression.css?v=5.0.0';document.head.append(link);
  function replaceSymbol(id,markup){const node=document.getElementById(`charge-${id}`);if(node)node.innerHTML=markup;}
  function installSymbols(){
    replaceSymbol('lion','<path d="M66 15c10-10 25-8 31 2l15 2-10 10 8 10-14 7-12-4-8 18 16 12-8 14-15-12-5 13 13 23H57L46 86l-8 25H21l6-31-12-9 10-12 13 7 8-18-8-13 8-12 12 8 8-16Z" fill="currentColor"/><path d="M47 47c-18 1-31-9-34-27 17 0 30 6 38 20-19 9-28 23-25 42" fill="none" stroke="currentColor" stroke-width="8" stroke-linecap="round"/><circle cx="88" cy="27" r="3.5" fill="var(--detail,#1c1814)"/>');
    replaceSymbol('boar','<path d="M12 66 24 39l24-18 37 3 20 18 3 26-20 25-39 9-29-13-8-23Zm76-20 23-8-7 16 12 7-20 8-8-23Z" fill="currentColor"/><path d="M31 39 17 17l27 12M35 94l-6 19m55-22 8 19" fill="none" stroke="currentColor" stroke-width="8"/><circle cx="82" cy="45" r="4" fill="var(--detail,#1c1814)"/>');
    replaceSymbol('stag','<path d="M19 75c9-18 25-27 43-25l15 2 10-15 12 5-7 19c7 10 6 23-1 34H75l-5-18-18 1-6 31H28l7-34H19Z" fill="currentColor"/><path d="M82 42c-4-15 1-28 13-39M86 31 73 17m17 7 15-12M93 47c5-14 12-23 24-29M42 77 25 102m50-25 14 29" fill="none" stroke="currentColor" stroke-width="7" stroke-linecap="round"/><circle cx="89" cy="49" r="3" fill="var(--detail,#1c1814)"/>');
    replaceSymbol('eagle','<path d="M57 38C43 21 25 13 4 15l15 12-16 5 20 10-16 9 25 8-13 12 31 5 10-29-3-9Zm6 0c14-17 32-25 53-23l-15 12 16 5-20 10 16 9-25 8 13 12-31 5-10-29 3-9Z" fill="currentColor"/><path d="M49 39c-5 14-2 32 6 45l-15 25 20-9 20 9-15-25c8-13 11-31 6-45L60 28 49 39Z" fill="currentColor"/><circle cx="72" cy="28" r="3" fill="var(--detail,#1c1814)"/>');
    const defs=document.querySelector('.symbol-library defs');if(!defs||document.getElementById('charge-lion-crowned'))return;
    const holder=document.createElementNS('http://www.w3.org/2000/svg','g');holder.innerHTML=`<symbol id="charge-lion-bifurcated" viewBox="0 0 120 120"><use href="#charge-lion"/><path d="M43 48C20 42 8 29 12 10c12 5 23 13 28 26" fill="none" stroke="currentColor" stroke-width="7"/></symbol><symbol id="charge-lion-crowned" viewBox="0 0 120 120"><use href="#charge-lion"/><path d="m70 16 7-12 8 9 9-9 5 14-6 8H76Z" fill="currentColor"/></symbol><symbol id="charge-lion-regardant" viewBox="0 0 120 120"><g transform="translate(120 0) scale(-1 1)"><use href="#charge-lion"/></g></symbol><symbol id="charge-boar-armed" viewBox="0 0 120 120"><use href="#charge-boar"/><path d="M95 64c10 8 18 6 23-3-2 15-13 23-27 17" fill="none" stroke="currentColor" stroke-width="6"/></symbol><symbol id="charge-boar-coupled" viewBox="0 0 120 120"><g transform="translate(-9 8) scale(.82)"><use href="#charge-boar"/></g><g transform="translate(53 40) scale(.48)"><use href="#charge-boar"/></g></symbol><symbol id="charge-boar-blooded" viewBox="0 0 120 120"><use href="#charge-boar"/><path d="M42 29 69 96M57 22l25 62" stroke="var(--detail,#1c1814)" stroke-width="6" opacity=".72"/></symbol><symbol id="charge-tower-gate" viewBox="0 0 120 120"><use href="#charge-tower"/><path d="M47 107V76c0-17 26-17 26 0v31" fill="none" stroke="var(--detail,#1c1814)" stroke-width="8"/></symbol><symbol id="charge-tower-triple" viewBox="0 0 120 120"><g transform="translate(2 42) scale(.48)"><use href="#charge-tower"/></g><g transform="translate(34 5) scale(.48)"><use href="#charge-tower"/></g><g transform="translate(66 42) scale(.48)"><use href="#charge-tower"/></g></symbol><symbol id="charge-tower-burning" viewBox="0 0 120 120"><use href="#charge-tower"/><path d="M30 36c-11-17 5-24 1-35 16 10 18 21 11 35m21-3C53 16 69 10 67 0c16 12 16 23 8 36m18 0C82 20 98 14 95 3c17 12 16 24 8 35" fill="currentColor"/></symbol><symbol id="charge-stag-courant" viewBox="0 0 120 120"><g transform="translate(0 8) rotate(-7 60 60)"><use href="#charge-stag"/></g><path d="M18 104h34m9 7h42" stroke="currentColor" stroke-width="5" opacity=".55"/></symbol><symbol id="charge-stag-crowned" viewBox="0 0 120 120"><use href="#charge-stag"/><path d="m76 37 6-12 8 8 8-9 5 14-6 7H82Z" fill="currentColor"/></symbol><symbol id="charge-stag-regardant" viewBox="0 0 120 120"><g transform="translate(120 0) scale(-1 1)"><use href="#charge-stag"/></g></symbol>`;while(holder.firstChild)defs.append(holder.firstChild);
  }
  function installSetup(){const dialog=$('#setupDialog'),seal=$('#sealSetupButton');if(!dialog||!seal)return;const header=dialog.querySelector('h2');if(header)header.textContent='Задай поле, строй, основателя и школу';if(!$('#mainChoices')){const section=document.createElement('section');section.innerHTML='<h3>Основатель · инстинкт ратников с первого боя</h3><div class="choice-grid founder-grid" id="mainChoices"></div>';seal.before(section);}if(!$('#schoolChoices')){const section=document.createElement('section');section.innerHTML='<h3>Школа · только облик, не механика</h3><div class="choice-grid school-grid" id="schoolChoices"></div>';seal.before(section);}const ordinaryTitle=$('#ordinaryChoices')?.previousElementSibling;if(ordinaryTitle)ordinaryTitle.textContent='Ординарий · геометрия строя';seal.querySelector('span').textContent='Скрепить первый устав';seal.querySelector('small').textContent='Все четыре решения обязательны';}
  function renderFounders(){const root=$('#mainChoices');if(!root)return;root.innerHTML=founders.map(item=>`<button type="button" class="doctrine-choice founder-choice${globalThis.__blazonFounder===item.id?' is-selected':''}" data-v5-founder="${item.id}"><i class="founder-mark"><svg viewBox="0 0 120 120"><use href="#charge-${item.id}"></use></svg></i><strong>${item.name}</strong><span>${item.copy}</span></button>`).join('');}
  function renderSchools(){const root=$('#schoolChoices');if(!root)return;root.innerHTML=schools.map(item=>`<button type="button" class="doctrine-choice school-choice${globalThis.__blazonSchool===item.id?' is-selected':''}" data-v5-school="${item.id}"><i class="school-shield school-shield-${item.id}"></i><strong>${item.name}</strong><span>${item.copy}</span></button>`).join('');}
  function syncSeal(){const button=$('#sealSetupButton');if(button)button.disabled=!($('.field-grid .is-selected')&&$('.ordinary-grid .is-selected')&&globalThis.__blazonFounder&&globalThis.__blazonSchool);}
  function decorateAchievements(root=document){for(const svg of root.querySelectorAll?.('svg.achievement')||[]){const href=svg.querySelector('.charge-main use')?.getAttribute('href')?.replace('#charge-','')||'';const evolved=evolutionIds.has(href);svg.classList.toggle('is-evolved',evolved);for(const ornament of svg.querySelectorAll('.mantle,.mantle-lining,.civic-wreath,.mural-crown,.fur-edge'))ornament.style.display=evolved?'':'none';const motto=svg.querySelector('.motto-copy');if(motto&&motto.textContent.trim()==='—'){motto.style.display='none';svg.querySelector('.motto-scroll')?.style.setProperty('display','none');}}const evolvedReward=$('#rewardGrid svg.achievement.is-evolved');if(evolvedReward){if($('#rewardEyebrow'))$('#rewardEyebrow').textContent='ЭВОЛЮЦИЯ ФИГУРЫ';if($('#rewardTitle'))$('#rewardTitle').textContent='Во что превратится основатель рода?';}}
  installSymbols();installSetup();renderFounders();renderSchools();syncSeal();decorateAchievements();
  document.addEventListener('click',event=>{const founder=event.target.closest('[data-v5-founder]'),school=event.target.closest('[data-v5-school]');if(founder){globalThis.__blazonFounder=founder.dataset.v5Founder;renderFounders();syncSeal();}if(school){globalThis.__blazonSchool=school.dataset.v5School;renderSchools();syncSeal();}if(event.target.closest('#newButton')){globalThis.__blazonFounder=null;globalThis.__blazonSchool=null;queueMicrotask(()=>{installSetup();renderFounders();renderSchools();syncSeal();});}if(event.target.closest('#sealSetupButton')&&(!globalThis.__blazonFounder||!globalThis.__blazonSchool)){event.preventDefault();event.stopImmediatePropagation();syncSeal();}if(event.target.closest('[data-field],[data-ordinary-choice]'))queueMicrotask(syncSeal);},true);
  const observer=new MutationObserver(()=>{installSetup();renderFounders();renderSchools();syncSeal();decorateAchievements();});observer.observe(document.body,{childList:true,subtree:true});
  const footer=$('.menu-screen footer');if(footer)footer.textContent='v5.0 · armorial progression · растущий герб';
})();
